### ISSUE TITLE
Build the TensorFlow Backend With Custom TensorFlow Failed. 

### ISSUE THREAD

**Issue by liangyanfeng** [triton-inference-server/server#2558] opened 2021-02-25 06:58 UTC
Build tensorflow backend failed in nvcr.io/nvidia/tensorflow:20.12-tf1-py3 docker.
command: 
root@db597b92d0c1:/opt/tensorflow# ./nvbuild.sh

INFO: Found 2 targets...
ERROR: /opt/tensorflow/tensorflow-source/tensorflow/compiler/xla/service/cpu/BUILD:622:1: C++ compilation of rule '//tensorflow/compiler/xla/service/cpu:runtime_matmul' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a8fc6d0749b4f3c43761726a36e8ec4c/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/usr/local/nvm/versions/node/v15.2.1/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin:/opt/tensorrt/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3.8 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=0 \
    TF_CONFIGURE_IOS=0 \
    TF_CUBLAS_VERSION=11 \
    TF_CUDA_COMPUTE_CAPABILITIES=5.2,6.0,6.1,7.0,7.5,8.0,8.6 \
    TF_CUDA_PATHS=/usr,/usr/local/cuda \
    TF_CUDA_VERSION=11.1 \
    TF_CUDNN_VERSION=8 \
    TF_ENABLE_XLA=1 \
    TF_NCCL_VERSION=2 \
    TF_NEED_CUDA=1 \
    TF_NEED_TENSORRT=1 \
    TF_TENSORRT_VERSION=7 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_matmul/runtime_matmul.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_matmul/runtime_matmul.pic.o' -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL -DTENSORFLOW_USE_MKLDNN_CONTRACTION_KERNEL -iquote . -iquote bazel-out/k8-opt/genfiles -iquote bazel-out/k8-opt/bin -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -iquote external/mkl_dnn -iquote bazel-out/k8-opt/genfiles/external/mkl_dnn -iquote bazel-out/k8-opt/bin/external/mkl_dnn -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/mkl_dnn/include -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/include -isystem bazel-out/k8-opt/bin/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/common -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/cpu -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/gemm -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/cpu/gemm -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/gemm -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/xbyak '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w '-march=sandybridge' '-mtune=broadwell' -Wno-sign-compare '-std=c++14' '-D_GLIBCXX_USE_CXX11_ABI=0' -DEIGEN_AVOID_STL_ARRAY -c tensorflow/compiler/xla/service/cpu/runtime_matmul.cc -o bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_matmul/runtime_matmul.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
INFO: Elapsed time: 305.031s, Critical Path: 77.47s
INFO: 998 processes: 998 local.
FAILED: Build did NOT complete successfully
cp: cannot stat 'bazel-bin/tensorflow/libtensorflow_cc.so.?': No such file or directory
root@db597b92d0c1:/opt/tensorflow# exit
exit

**Comment by tanmayv25** [comment] 2021-02-25 19:13
Your system probably is going out of the memory. You can work around this by adding these  bazel build options.
https://docs.bazel.build/versions/master/user-manual.html#flag--local_{ram,cpu}_resources

You can find the `nvbuildopts` script in /opt/tensorflow directory alongside `nvbuild.sh`.
Just add the following two options: `--local_ram_resources=HOST_RAM*.5 --local_cpu_resources=HOST_CPUS*.5` and give it a try.

**Comment by liangyanfeng** [comment] 2021-02-26 07:14
Thanks, tanmayv25;
I add "--local_ram_resources=HOST_RAM*.5 --local_cpu_resources=HOST_CPUS*.5" {ram,cpu}_resources in nvbuildopts script. But I see following errors: (HOST_RAM = 16G, HOST_CPUS = 8)

ERROR: /root/.cache/bazel/_bazel_root/a8fc6d0749b4f3c43761726a36e8ec4c/external/llvm-project/llvm/BUILD:4324:1: C++ compilation of rule '@llvm-project//llvm:x86_code_gen' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a8fc6d0749b4f3c43761726a36e8ec4c/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/usr/local/nvm/versions/node/v15.2.1/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin:/opt/tensorrt/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3.8 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=0 \
    TF_CONFIGURE_IOS=0 \
    TF_ENABLE_XLA=1 \
    TF_NEED_CUDA=1 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/llvm-project/llvm/_objs/x86_code_gen/X86ISelLowering.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/llvm-project/llvm/_objs/x86_code_gen/X86ISelLowering.pic.o' -DLLVM_ENABLE_STATS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DLLVM_BUILD_GLOBAL_ISEL -iquote external/llvm-project -iquote bazel-out/k8-opt/genfiles/external/llvm-project -iquote bazel-out/k8-opt/bin/external/llvm-project -iquote external/zlib -iquote bazel-out/k8-opt/genfiles/external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -isystem external/llvm-project/llvm/include -isystem bazel-out/k8-opt/genfiles/external/llvm-project/llvm/include -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/include -isystem external/zlib/zlib/include -isystem bazel-out/k8-opt/genfiles/external/zlib/zlib/include -isystem bazel-out/k8-opt/bin/external/zlib/zlib/include -isystem external/llvm-project/llvm/include/llvm/IR -isystem bazel-out/k8-opt/genfiles/external/llvm-project/llvm/include/llvm/IR -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/include/llvm/IR -isystem external/llvm-project/llvm/lib/Transforms/InstCombine -isystem bazel-out/k8-opt/genfiles/external/llvm-project/llvm/lib/Transforms/InstCombine -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/lib/Transforms/InstCombine -isystem external/llvm-project/llvm/lib/Target/X86 -isystem bazel-out/k8-opt/genfiles/external/llvm-project/llvm/lib/Target/X86 -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/lib/Target/X86 '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w '-march=sandybridge' '-mtune=broadwell' -Wno-sign-compare '-std=c++14' '-D_GLIBCXX_USE_CXX11_ABI=0' -Iexternal/llvm-project/llvm/lib/Target/X86 -c external/llvm-project/llvm/lib/Target/X86/X86ISelLowering.cpp -o bazel-out/k8-opt/bin/external/llvm-project/llvm/_objs/x86_code_gen/X86ISelLowering.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[10,878 / 13,557] checking cached actions
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /root/.cache/bazel/_bazel_root/a8fc6d0749b4f3c43761726a36e8ec4c/java_pid7330.hprof ...
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.ArrayList.<init>(Unknown Source)
	at com.google.devtools.build.skyframe.ReverseDepsUtility.maybeDelayReverseDepOp(ReverseDepsUtility.java:70)
	at com.google.devtools.build.skyframe.ReverseDepsUtility.removeReverseDep(ReverseDepsUtility.java:166)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.removeReverseDep(InMemoryNodeEntry.java:466)
	at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DeletingNodeVisitor$1.run(InvalidatingNodeVisitor.java:302)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 1776.619s, Critical Path: 140.25s
INFO: 1012 processes: 1012 local.
FAILED: Build did NOT complete successfully
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.ArrayList.<init>(Unknown Source)
KERNEL_TEST_RETURN=0
	at com.google.devtools.build.skyframe.ReverseDepsUtility.maybeDelayReverseDepOp(ReverseDepsUtility.java:70)
	at com.google.devtools.build.skyframe.ReverseDepsUtility.removeReverseDep(ReverseDepsUtility.java:166)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.removeReverseDep(InMemoryNodeEntry.java:466)
	at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DeletingNodeVisitor$1.run(InvalidatingNodeVisitor.java:302)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.ArrayList.<init>(Unknown Source)
	at com.google.devtools.build.skyframe.ReverseDepsUtility.maybeDelayReverseDepOp(ReverseDepsUtility.java:70)
	at com.google.devtools.build.skyframe.ReverseDepsUtility.removeReverseDep(ReverseDepsUtility.java:166)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.removeReverseDep(InMemoryNodeEntry.java:466)
	at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DeletingNodeVisitor$1.run(InvalidatingNodeVisitor.java:302)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Java heap space

FAILED: Build did NOT complete successfully
cp: cannot stat 'bazel-bin/tensorflow/libtensorflow_cc.so.?': No such file or directory

**Comment by liangyanfeng** [comment] 2021-02-26 07:51
Can TensorFlow Backend be compiled on the host (HOST_RAM = 16G, HOST_CPUS = 8) ?

**Comment by tanmayv25** [comment] 2021-02-26 18:44
This discussion should be helpful.
https://github.com/tensorflow/tensorflow/issues/30047

The issue is with compilation of tensorflow framework and not Triton TensorFlow backend, hence closing the issue. Re-open if you have any questions.

**Closed by tanmayv25** 2021-02-26 18:44 UTC
