### ISSUE TITLE
Triton21.05 has problem when load model from Minio

### ISSUE THREAD

**Issue by CPFelix** [triton-inference-server/server#3287] opened 2021-08-27 07:33 UTC
**Description**
1.Model without config.pbtxt on Minio can't be load successfully.The same problem with #3135
2.When I config the config.pbtxt for model on Minio,I can load it successfully.But then I find can't infer from client, and error is 'tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses'.
I then load model from local, use the same clint with doing nothing else and infer successfully, so inconceivable!
And has to say, I used 20.03 and 20.10 before,and did't happend such errors.

**Triton Information**
21.05.

Are you using the Triton container or did you build it yourself?
container.

**To Reproduce**

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
1.Can load model without config.pbtxt from Minio.
2.Can infer successfully when load models from Minio.

**Comment by dyastremsky** [comment] 2021-08-30 20:33
Thanks for reporting. I've filed a bug for #3135.

Can you please provide information for reproducing the behavior for the inference issue? The run command, config.pbxt file, and logs would be helpful. Whatever you can provide.

**Comment by CPFelix** [comment] 2021-08-31 09:19
@dyastremsky Thanks for reply!
run command:
"
sudo docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -e AWS_ACCESS_KEY_ID=minioadmin -e AWS_SECRET_ACCESS_KEY=88888888 -e AWS_REGION="us-east-1" -v/home/chenpengfei/server-2.10.0/docs/examples/plugins:/plugins --env LD_PRELOAD=/plugins/liblayerplugin.so nvcr.io/nvidia/tritonserver:21.05-py3 tritonserver  --model-repository=s3://xxx.xxx.xxx.xxx:9000/models/model_repository --strict-model-config=false -log-verbose=1
"
config.pbxt:
"
name: "yolov4"
platform: "tensorrt_plan"
max_batch_size : 8
input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3,608,608]
  }
]
output [
  {
    name: "prob"
    data_type: TYPE_FP32
    dims: [7001,1,1]
  }
]
"
And I use the opencode here: https://github.com/isarsoft/yolov4-triton-tensorrt

**Comment by dyastremsky** [comment] 2021-08-31 15:44
My pleasure, and thank you! Filing a bug. We'll investigate.

**Comment by CoderHam** [comment] 2022-02-16 21:24
@CPFelix the issue "Model without config.pbtxt on Minio can't be load successfully" was resolved by https://github.com/triton-inference-server/server/pull/3704.

We test models that can be loaded from Minio and inferred. The error `tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses` seems to be caused by the server either being down or the request being sent to an incorrect port. Can you share the model, config and reproductions steps?

I would also suggest attempting the same using the latest release i.e. 22.02.

**Comment by CoderHam** [comment] 2022-02-24 16:38
@CPFelix closing due to inactivity. Will re-open if needed.

**Closed by CoderHam** 2022-02-24 16:38 UTC
Labels: investigating
