### ISSUE TITLE
infrence of torch script model much slower with triton than python environment

### ISSUE THREAD

**Issue by yjegssl** [triton-inference-server/server#2836] opened 2021-05-10 11:13 UTC
**Description**
I convert models in an open source OCR project  with torch.jit.trace() and put it on triton to do inference, but the inference speed much slower than I just run the traced model in python environment

**Triton Information**
What version of Triton are you using?
21.04 py3
Are you using the Triton container or did you build it yourself?
container
**To Reproduce**
Steps to reproduce the behavior.
`pip install easyocr`
`
import easyocr
import torch
reader = easyocr.Reader(['ch_sim','en'],quantize=False,gpu=False)
imgH=640
imgW=352
max_length = 36
batch_size = 8
image = torch.ones([1,3,imgH, imgW])
image = torch.autograd.Variable(image).cuda()
img = torch.ones([batch_zie, 1, 64, 256]).cuda()
text = torch.ones([1,int(max_length+1)]).cuda()

detector = reader.detector.cuda()
scripted_detector = torch.jit.trace(detector, image)
scripted_detector.save('scripted_detector.pt')
recognizer = reader.recognizer.cuda()
scripted_recognizer = torch.jit.trace(recognizer,(img, text))
scripted_recognizer.save('scripted_recognizer.pt')
`
'
name: "detector"
platform: "pytorch_libtorch"
max_batch_size: 1
input[
{
name: "input_0"
data_type: TYPE_FP32
dims: [3,352,640]
}
]

output[
{
name: "output_0"
data_type: TYPE_FP32
dims: [-1, -1]
},
{
name: "output_1"
data_type: TYPE_FP32
dims: [-1, -1]
}
]
instance_group [
{
count: 1
kind: KIND_GPU
gpus: [0]
}
]

'
`name: "detector"
platform: "pytorch_libtorch"
max_batch_size: 1
input[
{
name: "input_0"
data_type: TYPE_FP32
dims: [3,352,640]
}
]

output[
{
name: "output_0"
data_type: TYPE_FP32
dims: [-1, -1]
},
{
name: "output_1"
data_type: TYPE_FP32
dims: [-1, -1]
}
]
instance_group [
{
count: 1
kind: KIND_GPU
gpus: [0]
}
]

'
name: "detector"
platform: "pytorch_libtorch"
max_batch_size: 1
input[
{
name: "input_0"
data_type: TYPE_FP32
dims: [3,352,640]
}
]

output[
{
name: "output_0"
data_type: TYPE_FP32
dims: [-1, -1]
},
{
name: "output_1"
data_type: TYPE_FP32
dims: [-1, -1]
}
]
instance_group [
{
count: 1
kind: KIND_GPU
gpus: [0]
}
]

'
`name: "recognizer"
platform: "pytorch_libtorch"
max_batch_size: 1
input[
{
name: "input_0"
data_type: TYPE_FP32
dims: [1,64,256]
},
name: "input_1"
data_type: TYPE_INT64
dims: [1,37]
]

output[
{
name: "output_0"
data_type: TYPE_FP32
dims: [-1, -1]
},
]
instance_group [
{
count: 1
kind: KIND_GPU
gpus: [0]
}
]
`
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
vgg based cnn 
rcnn
**Expected behavior**
inference time similar or faster than just using easyOCR project with python, gpu

**Comment by CoderHam** [comment] 2021-05-10 15:02
@yjegssl thanks for opening the ticket. Please share performance numbers so that we can understand to what extend the model is slower. 
1. Which version of pytorch did you use for running the inference in the python environment?
2. Did you try running the model in LibTorch (C API) directly?
3. What was your GPU utilization both with and without Triton?

**Comment by yjegssl** [comment] 2021-05-11 03:04
the original project, process a 640*339 rgb image: 

detector inference time: 0.1275s
recognizer inference total time: 0.0948s
gpu memory usage: 1983M(triton use 367 M when no models are loaded)

traced model on triton, process the same image:
detector inference time:0.8537s
recognizer inference total time:0.2309s(here I pad input to the same size)
gpu memory usage:1605M

traced model inference in python environment:
detector inference time:0.5361s
recognizer inference total time:0.3365s (pad to the same size)
gpu memory usage:1323M (set model to cpu, not clear why it has gpu usage)

1.torch version: 1.8.1+cu102
2.not yet, and not clear how
3.as showed above

**Comment by yjegssl** [comment] 2021-05-13 10:45
I am using triton client 20.09 docker image
the perf_client output:
Avg request latency:14381 usec (overhead 27 usec + queue 17 usec + compute input 689 usec + compute infer 4059 usec + compute output 9589 usec)

**Comment by CoderHam** [comment] 2021-05-13 18:56
20.09 is over 6 months old. Do you mind trying with a new version? There was a recent [fix](https://github.com/triton-inference-server/pytorch_backend/pull/12) that should have solve some performance issues.

**Comment by yjegssl** [comment] 2021-05-14 02:16
I will have a try next week
and why the compute output latency so high even higher than compute infer?
what does that mean?

**Comment by yjegssl** [comment] 2021-05-24 15:24
I 've tried 21.04 client, the performance does not increase much.

**Comment by CoderHam** [comment] 2021-05-24 17:54
> and why the compute output latency so high even higher than compute infer?

There was a [bug](https://github.com/triton-inference-server/pytorch_backend/pull/22) in the way the timestamp was being collected due to missing synchronization in the pytorch backend. 

Can you share the perf numbers generated by  21.04/21.05 using perf_analzyer? Also can you share the arguments you used?

**Comment by DayDayupupupup** [comment] 2021-06-03 07:13
I have a similar issue with **python backend**
**Description**
I deploy a python backend model with a piece of image processing code, but the inference speed of triton was much slower than run the same code in python environment.  I set timestamp in model.py's execute() function,
it spends 214ms, but in python environment, the same code only spend 48ms.

Another issue, using perf_analyzer tool, latency is 300+ms,  is it normal that the latency is much greater than the execute() function‘s internal time?

**Triton Information**
21.05 py3
Are you using the Triton container or did you build it yourself?
container

**Comment by Tabrizian** [comment] 2021-06-03 14:44
@DayDayupupupup Can you open a separate ticket and put all the details (your model, Triton version, ...) so that we can investigate.

**Comment by DayDayupupupup** [comment] 2021-06-04 03:54
@Tabrizian I created  a new issue here:[#2958](https://github.com/triton-inference-server/server/issues/2958)

**Comment by CoderHam** [comment] 2021-06-07 14:18
@yjegssl the slowdown might be caused by TorchScript. You can refer to the pytorch documentation for the same. 

Your numbers for the traced model inference in python environment indicated that the numbers were recording after setting the model to CPU. Could you share the numbers when using the GPU?

Comparing the pytorch python model to the torchscript model does not guarantee the slowdown is from Triton's side. At the very least you should be running the torchscript model using the python API. But to truly compare apples to apples you want to compare:
TorchScript Model performance uisng PyTorch C++ API with Triton's C++ implementation in the PyTorch Backend. The only difference in this case would be the overhead for the additional network overhead and the input and output marshalling.

**Comment by CoderHam** [comment] 2021-07-08 21:27
Closing due to inactivity.

**Comment by CoderHam** [comment] 2021-09-09 19:14
@koval not sure why you believe the PyTorch version is 1.9.0. the [Framework Support Matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) clearly mentions 1.10.0a0+ecc3718
for the PyTorch version in 21.07.

That being said, we will look into the perf issue you described here. Since we confirmed the issue is seen in the PyTorch container as well, I am confident the issue is not Triton specific and rather originates in PyTorch.

**Comment by koval** [comment] 2021-09-09 19:41
@CoderHam  The way I understood Framework Support Matrix is rows are container images (Triton Inference Server in our case) and columns - container image versions (21.07 in our case). The cell at the intersection of our row and column contains:

```
2.12.0 including
TensorRT 8.0.1.6
PyTorch 1.9.0a0+c3d40fd
TensorFlow 1.15.5
TensorFlow 2.5.0
ONNX Runtime 1.8.0
DCGM 2.2.3
```

**Comment by koval** [comment] 2021-09-20 15:14
@CoderHam Some more information to help investigate the issue. The model where we observe slowness is based on EfficientNet architecture and has automatic mixed precision enabled. I wrote a small script which loads pretrained EfficientNet model and measures inference speed:

```python
import sys
import time

from efficientnet_pytorch import EfficientNet
import torch


def call_once(model, autocast_enabled):
    tensor = torch.rand(1, 3, 224, 224, device="cuda:0")
    with torch.jit.optimized_execution(False):
        with torch.no_grad():
            with torch.cuda.amp.autocast(enabled=autocast_enabled):
                [t.cpu().numpy() for t in model(tensor)]
                torch.cuda.synchronize()


def main():
    if len(sys.argv) != 3:
        print("usage: perf.py (autocast|noautocast) <n>")
        return

    autocast_enabled = sys.argv[1] == 'autocast'
    n = int(sys.argv[2])

    model = EfficientNet.from_name('efficientnet-b2').cuda()

    # First few inferences might be slow due to JIT
    print("Warming up model")
    for i in range(5):
        call_once(model, autocast_enabled)

    print("Measuring latency")
    start = time.monotonic()

    for i in range(n):
        call_once(model, autocast_enabled)

    end = time.monotonic()
    print("Avg time per forward (ms):", (end - start) * 1000 / n)


if __name__ == '__main__':
    main()
```

The script uses open-source EfficientNet PyTorch implementation from `efficientnet_pytorch` Python package. The latest version of it can be installed with `pip install efficientnet_pytorch==0.7.1` command.

I ran the above script in `nvcr.io/nvidia/pytorch:21.07-py3` container. First without APM:

```
$ python perf.py noautocast 100
Warming up model
Measuring latency
Avg time per forward (ms): 18.974962929996764
```

And then with AMP enabled:

```
$ python perf.py autocast 100
Warming up model
Measuring latency
Avg time per forward (ms): 225.7623102000025
```

So the reason of slowness seems to be AMP.

**Comment by koval** [comment] 2021-09-24 13:39
A follow-up to the comment above. It seems like I tracked down the sequence of PyTorch operations from EfficientNet model which have abnormal latency with AMP enabled in Nvidia Pytorch container image. This is ZeroPad2d followed by Conv2d. Here is a little script to reproduce the issue:

```python
import sys
import time

import torch
from torch.nn import functional as F


def call_once(weight, autocast_enabled):
    tensor = torch.rand(1, 1248, 7, 7, device="cuda:0")

    with torch.jit.optimized_execution(False):
        with torch.no_grad():
            with torch.cuda.amp.autocast(enabled=autocast_enabled):
                tensor = F.pad(tensor, (2, 2, 2, 2), 'constant')
                res = F.conv2d(tensor, weight, stride=(1, 1), groups=1248)
                [t.cpu().numpy() for t in res]
                torch.cuda.synchronize()


def measure_latency(n, weight, autocast_enabled):
    # First few calls might be slow due to JIT
    for i in range(5):
        call_once(weight, autocast_enabled)

    print(f"Measuring latency with autocast_enabled={autocast_enabled}")
    start = time.monotonic()

    for i in range(n):
        call_once(weight, autocast_enabled)

    end = time.monotonic()
    print("Avg time per zeropad2d + conv2d (ms):", (end - start) * 1000 / n)
    print()


def main():
    if len(sys.argv) != 2:
        print("usage: perf_conv2d.py <n>")
        return

    n = int(sys.argv[1])
    weight = torch.rand(1248, 1, 5, 5, device="cuda:0")

    measure_latency(n, weight, autocast_enabled=False)
    measure_latency(n, weight, autocast_enabled=True)


if __name__ == '__main__':
    main()
```

When I run this script in `nvcr.io/nvidia/pytorch:21.07-py3` I get:

```
$ python3 perf_conv2d.py 1000
Measuring latency with autocast_enabled=False
Avg time per zeropad2d + conv2d (ms): 0.22013764100847766

Measuring latency with autocast_enabled=True
Avg time per zeropad2d + conv2d (ms): 28.747077540989267
```

At the same time if run the script in `nvcr.io/nvidia/tritonserver:21.07-py3` image with manually installed any of official PyTorch 1.9/1.10/1.11 versions, I'm getting roughly those numbers:

```
$ python3 perf_conv2d.py 1000
Measuring latency with autocast_enabled=False
Avg time per zeropad2d + conv2d (ms): 0.22207251699001063

Measuring latency with autocast_enabled=True
Avg time per zeropad2d + conv2d (ms): 0.19390030999784358
```

So zeropad2d + conv2d in Nvidia's PyTorch image with AMP enabled is ~29ms vs normal sub-millisecond latency in official PyTorch versions.

@CoderHam  @Tabrizian I tried to narrow the issue down as much as I can. If you have any questions please let me know. I understand this looks like an issue in Nvidia's PyTorch build, not in Triton itself. I cannot find where to open an issue for Nvidia PyTorch docker image. So I would appreciate if you could connect me with or reach out to people who can help resolve it. I really like the product you are working on, Triton, but this issue is a blocker for adoption of any recent Triton versions for us.

**Comment by jamt9000** [comment] 2021-09-24 14:54
@koval could this be caused by the padding hacks used to emulate TensorFlow-style convolution padding? https://github.com/lukemelas/EfficientNet-PyTorch/blob/7e8b0d312162f335785fb5dcfa1df29a75a1783a/efficientnet_pytorch/utils.py#L216

Does it still happen with the timm [EfficientNet implementation](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/efficientnet.py) which uses standard pytorch convolution?

**Comment by Tabrizian** [comment] 2021-09-24 18:54
@koval Thanks for the detailed investigation. What is the GPU version used for generating the numbers that you shared above? Also, were you able to generate the PyTorch upstream numbers out of the Triton container as well?

**Comment by koval** [comment] 2021-09-24 19:10
@Tabrizian All my investigation was done on NVIDIA T4 GPU in g4dn.xlarge AWS instance. The numbers for the official PyTorch releases come from `nvcr.io/nvidia/tritonserver:21.07-py3` container where I installed PyTorch via pip (both stable 1.9 version and nightly 1.10 and 1.11 versions).

**Comment by CoderHam** [comment] 2021-09-24 21:27
> A follow-up to the comment above. It seems like I tracked down the sequence of PyTorch operations from EfficientNet model which have abnormal latency with AMP enabled in Nvidia Pytorch container image. This is ZeroPad2d followed by Conv2d. Here is a little script to reproduce the issue:
> 
> ```python
> import sys
> import time
> 
> import torch
> from torch.nn import functional as F
> 
> 
> def call_once(weight, autocast_enabled):
>     tensor = torch.rand(1, 1248, 7, 7, device="cuda:0")
> 
>     with torch.jit.optimized_execution(False):
>         with torch.no_grad():
>             with torch.cuda.amp.autocast(enabled=autocast_enabled):
>                 tensor = F.pad(tensor, (2, 2, 2, 2), 'constant')
>                 res = F.conv2d(tensor, weight, stride=(1, 1), groups=1248)
>                 [t.cpu().numpy() for t in res]
>                 torch.cuda.synchronize()
> 
> 
> def measure_latency(n, weight, autocast_enabled):
>     # First few calls might be slow due to JIT
>     for i in range(5):
>         call_once(weight, autocast_enabled)
> 
>     print(f"Measuring latency with autocast_enabled={autocast_enabled}")
>     start = time.monotonic()
> 
>     for i in range(n):
>         call_once(weight, autocast_enabled)
> 
>     end = time.monotonic()
>     print("Avg time per zeropad2d + conv2d (ms):", (end - start) * 1000 / n)
>     print()
> 
> 
> def main():
>     if len(sys.argv) != 2:
>         print("usage: perf_conv2d.py <n>")
>         return
> 
>     n = int(sys.argv[1])
>     weight = torch.rand(1248, 1, 5, 5, device="cuda:0")
> 
>     measure_latency(n, weight, autocast_enabled=False)
>     measure_latency(n, weight, autocast_enabled=True)
> 
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> When I run this script in `nvcr.io/nvidia/pytorch:21.07-py3` I get:
> 
> ```
> $ python3 perf_conv2d.py 1000
> Measuring latency with autocast_enabled=False
> Avg time per zeropad2d + conv2d (ms): 0.22013764100847766
> 
> Measuring latency with autocast_enabled=True
> Avg time per zeropad2d + conv2d (ms): 28.747077540989267
> ```
> 
> At the same time if run the script in `nvcr.io/nvidia/tritonserver:21.07-py3` image with manually installed any of official PyTorch 1.9/1.10/1.11 versions, I'm getting roughly those numbers:
> 
> ```
> $ python3 perf_conv2d.py 1000
> Measuring latency with autocast_enabled=False
> Avg time per zeropad2d + conv2d (ms): 0.22207251699001063
> 
> Measuring latency with autocast_enabled=True
> Avg time per zeropad2d + conv2d (ms): 0.19390030999784358
> ```
> 
> So zeropad2d + conv2d in Nvidia's PyTorch image with AMP enabled is ~29ms vs normal sub-millisecond latency in official PyTorch versions.
> 
> @CoderHam @Tabrizian I tried to narrow the issue down as much as I can. If you have any questions please let me know. I understand this looks like an issue in Nvidia's PyTorch build, not in Triton itself. I cannot find where to open an issue for Nvidia PyTorch docker image. So I would appreciate if you could connect me with or reach out to people who can help resolve it. I really like the product you are working on, Triton, but this issue is a blocker for adoption of any recent Triton versions for us.

**Comment by CoderHam** [comment] 2021-11-30 23:01
@nieksand can you try with the latest Triton release - 21.11 and see if you are still seeing the perf issues?

**Comment by nieksand** [comment] 2021-12-01 09:15
Sure.  I will try today and update this ticket accordingly.

**Comment by nieksand** [comment] 2021-12-01 13:34
It looks like it is fixed.

Our EfficientNet latency is now comparable to what we saw on Triton 20.07.  

@koval reran his repro script, and performance for 21.11 with autocast enabled looks good:
```
# python3 perf_conv2d.py 1000
Measuring latency with autocast_enabled=False
Avg time per zeropad2d + conv2d (ms): 0.2254070260005392

Measuring latency with autocast_enabled=True
Avg time per zeropad2d + conv2d (ms): 0.22318216899839172
```

We have one EfficientNet based model still showing a 2x latency hit (vs. 10x previously), but this may be a separate issue.  We'll do some profiling and open a fresh ticket if we can narrow down the cause.

Thank you for resolving this!

**Comment by CoderHam** [comment] 2021-12-01 18:47
@nieksand great to hear, Closing this ticket based on your feedback

**Comment by koval** [comment] 2021-12-01 19:36
@CoderHam I have profiled the EfficientNet model which still shows 2x latency hit compared to Triton 20.07. This appears to be due to very slow depthwise conv2d operation on particular tensor and weights shapes with AMP enabled. I wrote a minimal script to reproduce the issue:

```python
import sys
import time

import torch
from torch.nn import functional as F


SLOW_SHAPES = [
    # (tensor shape, weights shape)
    ((1, 1248, 16, 16), (1248, 1, 3, 3)),
    ((1, 2112, 16, 16), (2112, 1, 3, 3)),
]


def call_once(tshape, weight, autocast_enabled):
    tensor = torch.rand(*tshape, device="cuda:0")

    with torch.jit.optimized_execution(False):
        with torch.no_grad():
            with torch.cuda.amp.autocast(enabled=autocast_enabled):
                res = F.conv2d(tensor, weight, stride=(1, 1), groups=weight.shape[0])
                [t.cpu().numpy() for t in res]
                torch.cuda.synchronize()


def measure_latency(n, tshape, weight, autocast_enabled):
    # First few calls might be slow due to JIT
    for i in range(5):
        call_once(tshape, weight, autocast_enabled)

    print(f"\tMeasuring latency with autocast_enabled={autocast_enabled}")
    start = time.monotonic()

    for i in range(n):
        call_once(tshape, weight, autocast_enabled)

    end = time.monotonic()
    print("\tAvg time per conv2d (ms):", (end - start) * 1000 / n)
    print()


def main():
    if len(sys.argv) != 2:
        print("usage: perf_conv2d.py <n>")
        return

    n = int(sys.argv[1])

    for tshape, wshape in SLOW_SHAPES:
        weight = torch.rand(*wshape, device="cuda:0")

        print(f'Tensor shape={tshape}, weights shape={wshape}')
        measure_latency(n, tshape, weight, autocast_enabled=False)
        measure_latency(n, tshape, weight, autocast_enabled=True)
        print()


if __name__ == '__main__':
    main()
```

Running it in `nvcr.io/nvidia/pytorch:21.11-py3` docker image returns following:

```
$ python perf_conv2d.py 100
Tensor shape=(1, 1248, 16, 16), weights shape=(1248, 1, 3, 3)
        Measuring latency with autocast_enabled=False
        Avg time per conv2d (ms): 0.47760577999724774

        Measuring latency with autocast_enabled=True
        Avg time per conv2d (ms): 6.986462770000799


Tensor shape=(1, 2112, 16, 16), weights shape=(2112, 1, 3, 3)
        Measuring latency with autocast_enabled=False
        Avg time per conv2d (ms): 0.6045674399865675

        Measuring latency with autocast_enabled=True
        Avg time per conv2d (ms): 11.641760519996751
```

So an order of magnitude slowdown.

**Comment by CoderHam** [comment] 2021-12-01 20:51
@koval the issue here appears to be PyTorch specific and not Triton specific. Correct me if I am wrong but you see this perf only with the pytorch version from the NGC container and not upstream / public pytorch?

**Comment by koval** [comment] 2021-12-02 11:56
Yes, I see performance regression only in PyTorch version from the NGC container. Public PyTorch (the version which I just tested is `1.11.0.dev20211202+cu113`) works fine:

```
$ python3 perf_conv2d.py 100
Tensor shape=(1, 1248, 16, 16), weights shape=(1248, 1, 3, 3)
	Measuring latency with autocast_enabled=False
	Avg time per conv2d (ms): 0.5426265999994939

	Measuring latency with autocast_enabled=True
	Avg time per conv2d (ms): 0.39972413000214146


Tensor shape=(1, 2112, 16, 16), weights shape=(2112, 1, 3, 3)
	Measuring latency with autocast_enabled=False
	Avg time per conv2d (ms): 0.6689998199999536

	Measuring latency with autocast_enabled=True
	Avg time per conv2d (ms): 0.47524825999971654
```

Is there an issue tracker for Nvidia PyTorch?

**Comment by CoderHam** [comment] 2022-04-06 18:28
@koval can you confirm that this issue is resolved in the new Triton release i.e. 22.03?

**Comment by koval** [comment] 2022-04-11 11:52
@CoderHam I can confirm I don't see the issue in `nvcr.io/nvidia/pytorch:22.03-py3` and `nvcr.io/nvidia/tritonserver:22.03-py3`.

**Closed** 2022-04-11 13:44 UTC
Labels: bug, performance, pytorch ngc
