### ISSUE TITLE
Proper Densenet_onnx Classification Input File Format Error 

### ISSUE THREAD

**Issue by eanmikale** [triton-inference-server/server#4274] opened 2022-04-24 14:13 UTC
**Description**

We are attempting to use curl for inference. 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Here is the curl command: 

curl -v -X POST https://infinite8institute-ne0kw2501y9ifdei.socketxp.com/v2/models/densenet_onnx/infer -H "Authorization: Bearer keyphrase" -d @./test2.json

Here is the command output: 

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 34.122.60.35...
* TCP_NODELAY set
* Connected to infinite8institute-ne0kw2501y9ifdei.socketxp.com (34.122.60.35) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.socketxp.com
*  start date: Mar 30 13:47:47 2022 GMT
*  expire date: Jun 28 13:47:46 2022 GMT
*  subjectAltName: host "infinite8institute-ne0kw2501y9ifdei.socketxp.com" matched cert's "*.socketxp.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> POST /v2/models/densenet_onnx/infer HTTP/1.1
> Host: infinite8institute-ne0kw2501y9ifdei.socketxp.com
> User-Agent: curl/7.58.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTIxNTE0NDMsImlkIjoiaW5maW5pdGU4aW5zdGl0dXRlQGdtYWlsLmNvbSJ9.wM3hEJUIFuJ4aXNqndmSbmoyBYwDKjJkoRT6ho3LMY
> Content-Length: 596
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 596 out of 596 bytes
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 400 Bad Request
< Content-Length: 72
< Content-Type: application/json
< Date: Sun, 24 Apr 2022 13:52:31 GMT
< 
* Connection #0 to host infinite8institute-ne0kw2501y9ifdei.socketxp.com left intact
* {"error":"failed to parse the request JSON buffer: Invalid value. at 0"}

**Triton Information**
What version of Triton are you using?

current master version. 

Are you using the Triton container or did you build it yourself?

Built from source. 

Here is json file: 

POST /v2/models/densenet_onnx/infer HTTP/2
Host: https://infinite8institute-ne0kw2501y9ifdei.socketxp.com
Authorization: Bearer `key phrase`
Content-Type: application/json
Content-Length: 590
{
  "id" : "densenet_onnx",
  "inputs" : [
    {
      "name" : "input0",
      "shape" : [ 2, 2 ],
      "datatype" : "TYPE_FP32",
      "data" : [ 1, 3, 224, 224 ]
    }
  ],
  "outputs" : [
    {
      "name" : "output0",
      "parameters" : { "classification" : 2 }
    }
  ]
}

**Expected behavior**

Classification inference output of top classes.

**Comment by dyastremsky** [comment] 2022-05-23 21:35
The error is saying that the JSON file is invalid, and it looks to be happening outside of Triton. Is the header (POST...) part of your JSON file? That wouldn't pass JSON parsing, since it wouldn't be valid.

**Comment by eanmikale** [comment] 2022-05-24 00:11
This is the main error:     import tritonclient.http as httpclient

ImportError: No module named tritonclient.http



However, I can import using the Python3 interpreter. 



Maybe, we can solve this first and then look at the JSON upload? 






---- On Mon, 23 May 2022 16:36:06 -0500 dyastremsky ***@***.***> wrote ----





The error is saying that the JSON file is invalid, and it looks to be happening outside of Triton. Is the header (POST...) part of your JSON file? That wouldn't pass JSON parsing, since it wouldn't be valid.

**Comment by dyastremsky** [comment] 2022-05-24 00:33
That import looks fine. We use the same line in a lot of the tests in the QA folder.

Maybe there's a path error or an error with how it's run (e.g. Python vs Python3). I can only help with bugs or questions relating to Triton, so if you run into those, let me know.

**Comment by eanmikale** [comment] 2022-05-24 03:25
Sorry, I needed to add the Python backend. This fixed the error. 



However, I am getting hung again on the following output: 



++ curl -s -w '%{http_code}' localhost:8000/v2/health/ready



I cannot find here this code is coming from in the source code. Any assistance is greatly appreciated. 








---- On Mon, 23 May 2022 19:33:55 -0500 dyastremsky ***@***.***> wrote ----





That import looks fine. We use the same line in a lot of the tests in the QA folder.

Maybe there's a path error or an error with how it's run (e.g. Python vs Python3). I can only help with bugs or questions relating to Triton, so if you run into those, let me know.

**Comment by dyastremsky** [comment] 2022-05-24 03:54
I'm not understanding the question. If it's where that's used, there's a bit of documentation for its utility in the quick start guide [here]: (https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md). That command is to test the health of the server.

The documentation would be your greatest resource. It sounds like this ticket no longer relates to the original issue. If so, the best route would be to close it and open a new ticket with the questions that we want to answer. If this is still related to the issue, please let me know what needs answering. As a note, I'm happy to answer questions, but I can't get into the nitty gritty of your program and reproducing it unless there's a bug.

**Comment by eanmikale** [comment] 2022-05-24 05:17
You can close this ticket number. I am now familiar with the correct formatting. Thank you. 







---- On Mon, 23 May 2022 22:54:16 -0500 dyastremsky ***@***.***> wrote ----





I'm not understanding the question. If it's where that's used, there's a bit of documentation for its utility in the quick start guide [here]: (https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md). That command is to test the health of the server.

The documentation would be your greatest resource. It sounds like this ticket no longer relates to the original issue. If so, the best route would be to close it and open a new ticket with the questions that we want to answer. If this is still related to the issue, please let me know what needs answering. As a note, I'm happy to answer questions, but I can't get into the nitty gritty of your program and reproducing it unless there's a bug.

**Comment by dyastremsky** [comment] 2022-05-24 14:15
Wonderful, any time. 👍

**Closed by dyastremsky** 2022-05-24 14:15 UTC
