### ISSUE TITLE
Python backend segfault with detectron2

### ISSUE THREAD

**Issue by bcvanmeurs** [triton-inference-server/server#3074] opened 2021-07-01 09:17 UTC
**Description**
I am trying to get a detectron2 model running in Triton.
In version 21.06 the server hangs on loading the model and displays the following error:

```
triton_python_b[23212]: segfault at 7f51a3e2666d ip 00007f51a29ed7e4 sp 00007ffe0a569868 error 4 in libc-2.31.so[7f51a2884000+178000]

# addr2line -p -a -f -e /usr/lib/x86_64-linux-gnu/libc-2.31.so 178000
0x0000000000178000: __nss_database_lookup at ??:?
```

In version 21.04 this error occured sometimes at inference time, there is no output and the server hangs.
```
I0701 09:00:13.631002 1 infer_request.cc:497] prepared: [0x0x7fb864002d90] request id: 42, model: mag, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7fb864003248] input: INPUT0, type: UINT8, original shape: [7372,4146,3], batch + shape: [7372,4146,3], shape: [7372,4146,3]
override inputs:
inputs:
[0x0x7fb864003248] input: INPUT0, type: UINT8, original shape: [7372,4146,3], batch + shape: [7372,4146,3], shape: [7372,4146,3]
original requested outputs:
requested outputs:
OUTPUT0

I0701 09:00:13.631087 1 python.cc:347] model mag, instance mag_0, executing 1 requests
```
dmesg shows
```
triton_python_b[30191]: segfault at 7faf0dae966d ip 00007faf0c6b07e4 sp 00007ffe2c701488 error 4 in libc-2.31.so[7faf0c547000+178000]
[ 5125.940257] Code: 7f 07 c5 fe 7f 4f 20 c5 fe 7f 54 17 e0 c5 fe 7f 5c 17 c0 c5 f8 77 c3 48 39 f7 0f 87 ab 00 00 00 0f 84 e5 fe ff ff c5 fe 6f 26 <c5> fe 6f 6c 16 e0 c5 fe 6f 74 16 c0 c5 fe 6f 7c 16 a0 c5 7e 6f 44
```
this error occurs when using curl on the http endpoint as well as with go in grpc.
It does not seem to occur when using the python client or the perf_analyzer.
After using the python client once, it works fine with curl/grpc.

**Triton Information**
What version of Triton are you using?
Tried on 21.04 and 21.06

Are you using the Triton container or did you build it yourself?
Using the triton container with custom pip installs.
```
FROM nvcr.io/nvidia/tritonserver:21.04-py3 # or 21.06-py3

RUN apt-get update && apt-get install -y python3-dev
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
RUN python3 -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.8/index.html
RUN python3 -m pip install opencv-contrib-python-headless
```

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

model config:
```
name: "mag"
backend: "python"

input [
  {
    name: "INPUT0"
    data_type: TYPE_UINT8
    dims: [ -1 , -1, 3 ]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ -1, 4 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
```

model.py file: https://gist.github.com/bcvanmeurs/053d4443c9669b74eca742c71eaa4d1d

I can't share our actual model, but I can create a dummy or supply a pretrained one if necessary.

**Expected behavior**
A consistent inference result or a more clear error message at server startup (21.06).

Thanks in advance!

**Comment by jbkyang-nvi** [comment] 2021-07-01 19:49
Thanks for your report. I have created a ticket will look into this

**Comment by Tabrizian** [comment] 2021-07-06 19:39
@bcvanmeurs Can you please share a dummy version of the model so that I can use for reproducing this error?

**Comment by Tabrizian** [comment] 2021-07-06 20:03
Also, I tried your `model.py` file but it looks like `dl_detection` module does not exist. Can you provide a working `model.py` file so that we can further investigate. Thanks.

**Comment by bcvanmeurs** [comment] 2021-07-20 14:04
Hi @Tabrizian, sorry for the late response, somehow I missed the notifications here.

I have uploaded a model with randomised weights here: https://shukmagpilotmodelshare.blob.core.windows.net/random-model/random_model.pth. It is protected with a key, which I'll send over email.

Regarding the model.py it is a working example, but it only runs in the docker when the dependencies are installed. dl_detection is a python module of detectron2. Please let me know if you have more questions.

**Comment by Tabrizian** [comment] 2021-07-21 16:54
Thanks for getting back to us. I can confirm that I have received the email. We'll get back to you as soon as there are any further updates.

**Comment by bcvanmeurs** [comment] 2021-07-29 13:34
Hi @Tabrizian any update on this? Can I help in any way?

**Comment by Tabrizian** [comment] 2021-07-29 15:10
@bcvanmeurs I just tried your model again with all the dependencies installed but still it cannot find `dl_detection` module. Are you sure that it is a module of `detectron2`?

```
root@082e3ce405ad:/opt/tritonserver# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import detectron2
>>> dir(detectron2)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'setup_environment', 'utils']
>>> import dl_detection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dl_detection'
>>>
```

```
+-------+---------+----------------------------------------------------------------------------+                                                                                                                                                                                [0/1819]
| Model | Version | Status                                                                     |
+-------+---------+----------------------------------------------------------------------------+
| mag   | 1       | UNAVAILABLE: Internal: ModuleNotFoundError: No module named 'dl_detection' |
|       |         |                                                                            |
|       |         | At:                                                                        |
|       |         |   /opt/tritonserver/models/mag/1/model.py(1): <module>                     |
|       |         |   <frozen importlib._bootstrap>(219): _call_with_frames_removed            |
|       |         |   <frozen importlib._bootstrap_external>(848): exec_module                 |
|       |         |   <frozen importlib._bootstrap>(686): _load_unlocked                       |
|       |         |   <frozen importlib._bootstrap>(975): _find_and_load_unlocked              |
|       |         |   <frozen importlib._bootstrap>(991): _find_and_load                       |
+-------+---------+----------------------------------------------------------------------------+

I0729 15:04:44.518684 713 tritonserver.cc:1718]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                 |
| server_version                   | 2.11.0                                                                                                                                                                                 |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /opt/tritonserver/models                                                                                                                                                               |
| model_control_mode               | MODE_NONE                                                                                                                                                                              |
| strict_model_config              | 1                                                                                                                                                                                      |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                              |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                               |
| min_supported_compute_capability | 6.0                                                                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by bcvanmeurs** [comment] 2021-07-30 11:17
@Tabrizian my bad, you are completely right.
[dl_detection.zip](https://github.com/triton-inference-server/server/files/6907133/dl_detection.zip)

**Comment by Tabrizian** [comment] 2021-09-07 16:42
@bcvanmeurs Sorry for getting back to you late. The link to the model has expired. Can you please provide an up-to-date link to the '/models/mag/1/random_model.pth' again? Thanks

**Comment by bcvanmeurs** [comment] 2021-09-08 11:14
Hi @Tabrizian please find a new upload here: https://shukmagpilotmodelshare.blob.core.windows.net/model/random_model.pth

**Comment by Tabrizian** [comment] 2021-09-08 17:45
There was a but in 21.06 which has been fixed in 21.07+ versions of Triton I was able to run your model with 21.07 and perf analyzer didn't return any error. However, I encountered another problem in 21.06 which has been fixed in 21.07+.

```
  pixel_mean
  pixel_std
  anchor_generator.cell_anchors.{0, 1, 2, 3, 4}
I0908 17:43:21.235953 535 model_repository_manager.cc:1212] successfully loaded 'mag' version 1
I0908 17:43:21.236099 535 server.cc:504]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0908 17:43:21.236167 535 server.cc:543]
+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| tensorrt    | <built-in>                                                      | {}     |
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| python      | /opt/tritonserver/backends/python/libtriton_python.so           | {}     |
+-------------+-----------------------------------------------------------------+--------+

I0908 17:43:21.236196 535 server.cc:586]
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
| mag   | 1       | READY  |
+-------+---------+--------+

I0908 17:43:21.236291 535 tritonserver.cc:1718]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                 |
| server_version                   | 2.12.0                                                                                                                                                                                 |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /home/itabrizian/Code/triton/server/qa/L0_backend_python/repro-3/models/                                                                                                               |
| model_control_mode               | MODE_NONE                                                                                                                                                                              |
| strict_model_config              | 1                                                                                                                                                                                      |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                              |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                               |
| min_supported_compute_capability | 6.0                                                                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0908 17:43:21.243066 535 grpc_server.cc:4072] Started GRPCInferenceService at 0.0.0.0:8001
I0908 17:43:21.244487 535 http_server.cc:2795] Started HTTPService at 0.0.0.0:8000
I0908 17:43:21.287368 535 sagemaker_server.cc:134] Started Sagemaker HTTPService at 0.0.0.0:8080
I0908 17:43:21.329734 535 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002
```

```
*** Measurement Settings ***
  Batch size: 1
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1

  Client:
    Request count: 131
    Throughput: 26.2 infer/sec
    Avg latency: 38209 usec (standard deviation 2268 usec)
    p50 latency: 37780 usec
    p90 latency: 38029 usec
    p95 latency: 38781 usec
    p99 latency: 52201 usec
    Avg HTTP time: 38142 usec (send/recv 63 usec + response wait 38079 usec)
  Server:
    Inference count: 158
    Execution count: 158
    Successful request count: 158
    Avg request latency: 37804 usec (overhead 2 usec + queue 26 usec + compute input 12 usec + compute infer 37696 usec + compute output 68 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 26.2 infer/sec, latency 38209 usec
```

Can you try Triton 21.07+ to see whether you still see this issue? Thanks

**Comment by Tabrizian** [comment] 2021-09-09 21:59
Or if you can share the curl command that you used which resulted in segfault would be useful for the repro as well.

**Comment by Tabrizian** [comment] 2021-09-22 14:05
Closing the ticket due to in-activity. Feel free to re-open if the issue persists.

**Closed by Tabrizian** 2021-09-22 14:05 UTC
Labels: bug
