### ISSUE TITLE
Unable to access GCS bucket with workload identity mechanism in GKE

### ISSUE THREAD

**Issue by jplu** [triton-inference-server/server#5039] opened 2022-11-07 09:47 UTC
**Description**
Since the version 22.08 it is not possible anymore to get access to the GCS buckets. Triton fails to start with the following error message:
```
I1107 09:25:28.889159 31 server.cc:259] No server context available. Exiting immediately.
error: creating server: Internal - Unable to create GCS client. Check account credentials.
```

**Triton Information**
From Triton 22.08, official build.

**To Reproduce**
Here a minimal K8S manifest in order to be able to easily replicate the behavior:
```
apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: "default"


spec:
  containers:
  - image: nvcr.io/nvidia/tritonserver:22.08-py3
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: <MY_SERVICE_ACCOUNT>
```
Replace `<MY_SERVICE_ACCOUNT>` with the name of the created service account to get access to GCS. Once the pod is deployed, run a shell on the pod with:
```
kubectl exec -it workload-identity-test --namespace default -- /bin/bash
```
Once done run Triton with:
```
tritonserver --model-store=<GCS_BUCKET_ADDRESS>
```
Replace `<GCS_BUCKET_ADDRESS>` with the name of the bucket where the models are stored.

**Expected behavior**
Being able to use the GKE workload identity mechanism.

Thanks in advance.

**Comment by Tabrizian** [comment] 2022-11-08 16:11
@jplu Did the GCS work properly before 22.08 version? Looks like there is an authentication issue. Are the environment variable required for authentication present in the container?

CC @kthui

**Comment by jplu** [comment] 2022-11-08 16:12
Yes they all work from 21.09 to 22.07. I haven't checked if the environment variable was there.

**Comment by Tabrizian** [comment] 2022-11-08 16:42
I have filed a ticket for this issue.

**Comment by jplu** [comment] 2022-12-08 11:03
The issue is still there in the 22.11 version. Here a screenshot of a diff between the result of the `env` command withing a 22.07 (where it works on the right) and the 22.11 (where it doesn't on the left).
![Capture d’écran du 2022-12-08 12-00-23](https://user-images.githubusercontent.com/959590/206430486-b00df2e8-35d2-442f-92f0-bad3d96692ff.png)
I don't see anything suspect.

**Comment by Tabrizian** [comment] 2023-02-06 14:57
The issue has been fixed in the 23.01 release. Can you try it? https://github.com/triton-inference-server/core/pull/152

**Comment by jplu** [comment] 2023-02-07 12:08
@Tabrizian The issue hasn't been fixed (at least for me). It seems that the account declared to be used as a workload identity is not detected at all:

```
error: creating server: Internal - Could not get MetaData for bucket with name <GCS_REPO> : Permanent error in GetBucketMetadata: {
  "error": {
    "code": 401,
    "message": "Anonymous caller does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist).",
    "errors": [
      {
        "message": "Anonymous caller does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist).",
        "domain": "global",
        "reason": "required",
        "locationType": "header",
        "location": "Authorization"
      }
    ]
  }
}
```

My process to test is still the same than what I put in my first message.

**Comment by jplu** [comment] 2023-02-07 13:29
Other precision, when I run in the deployed pod:
```
curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/email
```
I properly get the IAM service account email address listed as the active identity. So it doesn't seems to come from a config error on K8S side.

**Comment by Tabrizian** [comment] 2023-02-07 14:10
Sorry, it looks like we have only resolved the public GCS bucket issues. @kthui Could you please take a look into this?

**Comment by kthui** [comment] 2023-02-09 03:32
Hi @jplu, I am able to reproduce your error exactly by not setting `$ gsutil iam ch allUsers:legacyBucketReader "${BUCKET_URL}"` role for the public bucket ([GCS doc](https://cloud.google.com/storage/docs/access-control/iam-roles#legacy-roles)). I am wondering if that is the case on your side? I will check if we can read from `$ gsutil iam ch allUsers:objectViewer "${BUCKET_URL}"` role instead.

**Comment by jplu** [comment] 2023-02-09 08:35
Hi @kthui! Thanks for clarifying the issue. My bucket is 100% private only me (the ower) and the created workload identity have access to it. So yes that is the case on my side, no `allUsers:legacyBucketReade` attached to the bucket.

**Comment by kthui** [comment] 2023-02-16 02:53
Hi @jplu, I think the reason for the failure is Anonymous credential is used instead of the Compute Engine credential (identity mechanism). I have added a PR that will use the Compute Engine credential when it is available. Once the PR is merged, this issue will be automatically closed, but please feel free to re-open if the PR does not fix your issue.

**Closed** 2023-02-16 02:53 UTC
Labels: bug

**Comment by jplu** [comment] 2023-02-16 12:33
Thanks very much! I will test once the next release will be out, and let you know if it works or not :)

**Comment by Vozf** [comment] 2023-03-29 14:16
It works on 23.03 and it seems all containers from 22.07 to 23.03 are unusable with google cloud

**Comment by jplu** [comment] 2023-04-18 09:59
Sorry for the delay I do confirm that it is perfecly working now with the version 23.03.

Thanks a lot!
