### ISSUE TITLE
Python backend dynamic loading model uses configuration parameters, and loading fails

### ISSUE THREAD

**Issue by zjq1996518** [triton-inference-server/server#4733] opened 2022-08-03 06:30 UTC
**Description**
When using dynamically loaded models via the load model API, the model loading fail.
but when I was cancel config param, the loading success.

**Triton Information**
triton version: 2.21.0

**To Reproduce**
http parameters
```
{
  parameter: {
    config: "{
      "name": "line",
      "backend": "python",
      "default_model_filename": "model.py",
      "max_batch_size": 0,
      "input": [
        {
          "name": "img",
          "data_type": "TYPE_UINT8",
          "dims": [
            -1,
            -1,
            -1
          ]
        },
        {
          "name": "img_url",
          "data_type": "TYPE_STRING",
          "dims": [
            1
          ]
        },
        {
          "name": "need_pad",
          "data_type": "TYPE_BOOL",
          "dims": [
            1
          ]
        },
        {
          "name": "score_thr",
          "data_type": "TYPE_FP32",
          "dims": [
            1
          ]
        },
        {
          "name": "topk",
          "data_type": "TYPE_INT32",
          "dims": [
            1
          ]
        }
      ],
      "output": [
        {
          "name": "confidences",
          "data_type": "TYPE_FP32",
          "dims": [
            -1
          ]
        },
        {
          "name": "lines",
          "data_type": "TYPE_INT32",
          "dims": [
            -1,
            4
          ]
        },
        {
          "name": "centers",
          "data_type": "TYPE_INT32",
          "dims": [
            -1,
            2
          ]
        }
      ],
      "instance_group": [
        {
          "count": 4,
          "kind": "KIND_CPU"
        }
      ],
      "parameters": {
        "key": "EXECUTION_ENV_PATH",
        "value": {
          "string_value": "$$TRITON_MODEL_DIRECTORY/../model-py38-debug.tar.gz"
        }
      }
    }"
  }
}
```
the log show：
```
model_repository_manager.cc:2064] Poll failed for model directory 'line': unexpected platform type '' for line
```

**Expected behavior**
uses configuration parameters loading success.

**Comment by dyastremsky** [comment] 2022-08-03 17:01
Does it run successfully in a newer version of Triton, particularly 2.24.0? We've been making our autocomplete functionality more rigorous these past few months, so this bug may not exist in the latest container.

**Comment by zjq1996518** [comment] 2022-08-04 05:14
> Does it run successfully in a newer version of Triton, particularly 2.24.0? We've been making our autocomplete functionality more rigorous these past few months, so this bug may not exist in the latest container.

Thank you very much for your reply. I will try to use the new version test

**Comment by tanmayv25** [comment] 2022-08-05 00:23
>but when I was cancel config param, the loading success.

@zjq1996518 Can you elaborate more on this?

**Comment by zjq1996518** [comment] 2022-08-05 02:49
> 

@tanmayv25 It means that there are no parameters when calling the API.
```
curl -X POST <host:port>/v2/repository/models/line/load
```
If I use the config parameter:
```
curl -X POST -H 'Content-type':'application/json' -d <config_param> <host:port>/v2/repository/models/line/load 
```
config_param in problem description.
In fact, I use Python requests to call
```python
import requests
# no parameter
requests.post(url)
# use parameter
requests.post(url, json=<config_param>)
```
But there should be no difference between Python and curl.

**Comment by tanmayv25** [comment] 2022-08-05 21:05
Thanks for the clarification. We will take a look and respond.

**Comment by risheek11** [comment] 2023-09-05 14:05
But I did encounter the below error when passing custom execution environment for the python backend in the config.
`Invalid config override: (parameters[0].value): invalid value "EXECUTION_ENV_PATH" for type [type.googleapis.com/inference.ModelParameter](http://type.googleapis.com/inference.ModelParameter)`

**Comment by dyastremsky** [comment] 2023-09-05 19:09
Great job finding the typo. Closing since the original issue was resolved.

Risheek11, as far as your issue, could you please open a new issue following the bug template (including the full reproduction steps). This will help us find what's going on with your config.

**Closed by dyastremsky** 2023-09-05 19:09 UTC
Labels: bug
