### ISSUE TITLE
Server returns broken json requests when using TensorRT model config

### ISSUE THREAD

**Issue by andreabrduque** [triton-inference-server/server#3711] opened 2021-12-17 14:32 UTC
**Description**
I have the following model config

```
name: "ner"
platform: "onnxruntime_onnx"
max_batch_size: 128
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "token_type_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]
output [
  {
    name: "start_logits"
    data_type: TYPE_FP32
    dims: [ -1, 5 ]
  },
  {
    name: "end_logits"
    data_type: TYPE_FP32
    dims: [ -1, 5 ]
  }
]

optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }
    parameters { key: "max_workspace_size_bytes" value: "4073741824" }
    }]
}}

````

It loads fine. When I make requests to it, it returns me a payload broken in the middle such as 

```
{
    "id": "42",
    "model_name": "ner",
    "model_version": "1",
    "outputs": [
        {
            "name": "end_logits",
            "datatype": "FP32",
            "shape": [
                2,
                8,
                5
            ],
            "data": [

```

**Triton Information**
What version of Triton are you using?

Using triton image nvcr.io/nvidia/tritonserver:21.11-py3

**To Reproduce**
Create a model repository with that config. Make a post request to http://localhost:8000/v2/models/ner/infer such as 
````
curl -d '{
    "id" : "42",
    "inputs": [
        {
            "name": "input_ids",
            "shape": [2, 8],
            "datatype":"INT64",
            "data":  [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]

        },
        {
            "name": "token_type_ids",
            "shape": [2,8],
            "datatype":"INT64",
            "data":  [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]
        },
            {
            "name": "attention_mask",
            "shape": [2, 8],
            "datatype":"INT64",
            "data":  [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]
        }

   ],
    "outputs" : [
    {
      "name" : "start_logits"
    },
     {
      "name" : "end_logits"
    }
  ]

}'  -H "Content-Type: application/json" -X POST http://localhost:8000/v2/models/ner/infer
````

**Expected behavior**
The full payload with the correct tensors
The model without TensorRT optimization returns the full payload, with the output tensors as expected. Example:

```
{
   "id":"42",
   "model_name":"ner",
   "model_version":"1",
   "outputs":[
      {
         "name":"end_logits",
         "datatype":"FP32",
         "shape":[
            2,
            8,
            5
         ],
         "data":[
            -9.151423454284668,
            -9.307648658752442,
             ....
            -9.209794044494629,
            -9.336723327636719,
            -9.302064895629883,
            -10.113032341003418,
            -9.484901428222657
         ]
      },
      {
         "name":"start_logits",
         "datatype":"FP32",
         "shape":[
            2,
            8,
            5
         ],
         "data":[
            -8.951006889343262,
            -9.178339004516602,
            ....
            -9.090873718261719,
            -9.383940696716309,
            -9.084102630615235,
            -9.8538236618042,
            -9.339037895202637
         ]
      }
   ]
}
```

**Comment by Tabrizian** [comment] 2021-12-17 16:37
Thanks for filing the issue. Looks like you are using a custom container. Does the same error happen in the official Triton NGC containers too?

**Comment by andreabrduque** [comment] 2021-12-17 16:51
> Thanks for filing the issue. Looks like you are using a custom container. Does the same error happen in the official Triton NGC containers too?

Thanks for the reply. My mistake at writing the issue. I edited  it with the right nvcr container nvcr.io/nvidia/tritonserver:21.11-py3. I did not make a custom container, only pushed to our repository to speed up pulling it from the cloud, since it is such a huge image :)

**Comment by Tabrizian** [comment] 2021-12-20 21:51
This looks like a bug. Can you share your model so that we can look into this?

**Comment by andreabrduque** [comment] 2021-12-21 08:35
Hey Tabrizian, here it is: https://drive.google.com/file/d/1Hm8Q4CnAjpychj3L3c4C4p6pQ517ZLef/view?usp=sharing

**Comment by deadeyegoodwin** [comment] 2022-01-21 18:42
Thanks for sharing the model. We will try to look into this soon.

**Comment by rmccorm4** [comment] 2022-01-26 23:27
Hi @andreabrduque ,

Thanks for sharing the repro.

I took a look at your setup using the latest `21.12-py3` container and was able to reproduce the issue.

**Let me share some of my findings so far:**

1. The entire ONNX model is convertible to TensorRT, so I decided to convert it to a TensorRT engine to see if we could eliminate variables in the ONNXRT-TRT accelerator. Using the standalone TensorRT engine (`platform: "tensorrt_plan"`), I was able to reproduce the error using the same inputs you shared above `[[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]` for every input (inputs were converted to `TYPE_INT32` in the conversion as well for both methods). 

Here's an example of how I converted the model with the similar parameters from your `config.pbtxt` using [Polygraphy](https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy):
```
#!/bin/bash
# (inside tritonserver:21.12-py3 container)
export POLYGRAPHY_AUTOINSTALL_DEPS=1
pip install colored polygraphy --extra-index-url https://pypi.ngc.nvidia.com

polygraphy convert --fp16 --trt-min-shapes input_ids:[1,1] token_type_ids:[1,1] attention_mask:[1,1] --trt-opt-shapes input_ids:[2,8] token_type_ids:[2,8] attention_mask:[2,8] --trt-max-shapes input_ids:[128,8] token_type_ids:[128,8] attention_mask:[128,8] --workspace 4073741824 -o model.plan model.onnx
```

2. Checking the outputs of the TensorRT engine using Polygraphy shows all `nan` outputs for the [1,2,3,4,5,6,7,8] inputs you provided above.

helper script:
```python
# data_loader_bad.py
import numpy as np
inputs = {
    "input_ids": np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]], dtype=np.int32),
    "token_type_ids": np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]], dtype=np.int32),
    "attention_mask": np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]], dtype=np.int32),
}

def load_data():
    yield inputs
```
output:
```
$ polygraphy run model.plan --data-loader-script data_loader_bad.py --trt -vvv
...
[V] Runner input metadata is: {input_ids [dtype=int32, shape=(-1, -1)],
     token_type_ids [dtype=int32, shape=(-1, -1)],
     attention_mask [dtype=int32, shape=(-1, -1)]}
[V] Setting binding: input_ids (index: 0) to shape: (2, 8)
[V] Setting binding: token_type_ids (index: 1) to shape: (2, 8)
[V] Setting binding: attention_mask (index: 2) to shape: (2, 8)
[I] trt-runner-N0-01/26/22-22:52:42    
    ---- Inference Output(s) ----
    {start_logits [dtype=float32, shape=(2, 8, 5)],
     end_logits [dtype=float32, shape=(2, 8, 5)]}
[X] trt-runner-N0-01/26/22-22:52:42     | Inference Time: 2.624 ms | Received outputs:
        OrderedDict([('start_logits', array([[[nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan]],
        
               [[nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan]]], dtype=float32)), ('end_logits', array([[[nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan]],
        
               [[nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan],
                [nan, nan, nan, nan, nan]]], dtype=float32))])
[I] trt-runner-N0-01/26/22-22:52:42     | Completed 1 iteration(s) in 2.624 ms | Average inference time: 2.624 ms.
[V] Successfully ran: ['trt-runner-N0-01/26/22-22:52:42']
[I] PASSED | Command: /usr/local/bin/polygraphy run model.plan --data-loader-script data_loader_bad.py --trt -vvv
```

3. However, if you changed the input values to all ones for example `[1,1,1,1,1,1,1,1]`, we get some good looking outputs in the above example.

And we also get a full response from Triton if you update your `config.pbtxt` as well (shortened output for readability):
```
#!/bin/bash
curl -d '{
    "id" : "42",
    "inputs": [
        {
            "name": "input_ids",
            "shape": [2, 8],
            "datatype":"INT32",
            "data":  [[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1]]        },
        {
            "name": "token_type_ids",
            "shape": [2,8],
            "datatype":"INT32",
            "data":  [[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1]]
        },
            {
            "name": "attention_mask",
            "shape": [2, 8],
            "datatype":"INT32",
            "data":  [[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1]]
        }   ],
    "outputs" : [
    {
      "name" : "start_logits"
    },
     {
      "name" : "end_logits"
    }
  ]}'  -H "Content-Type: application/json" -X POST http://localhost:8000/v2/models/ner_trt/infer
```
```
{"id":"42","model_name":"ner_trt","model_version":"1","outputs":[{"name":"start_logits","datatype":"FP32","shape":[2,8,5],"data":[0.407470703125,...,0.06488037109375]},{"name":"end_logits","datatype":"FP32","shape":[2,8,5],"data":[0.21192237734794618,...,0.23753800988197328]}]}
```

4. Lastly, I can see again using `polygraphy` that running the model using `onnxruntime` hits an error on a `Gather` layer for your given inputs `[1,2,3,4,5,6,7,8],[...]`:
```
# inputs [1,2,3,4,5,6,7,8]
$ polygraphy run --onnxrt model.onnx --data-loader-script data_loader_bad.py
[I] onnxrt-runner-N0-01/26/22-23:23:31  | Activating and starting inference
[I] onnxrt-runner-N0-01/26/22-23:23:31 
    ---- Inference Input(s) ----
    {input_ids [dtype=int64, shape=(2, 8)],
     token_type_ids [dtype=int64, shape=(2, 8)],
     attention_mask [dtype=int64, shape=(2, 8)]}
2022-01-26 23:23:35.257264380 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running Gather node. Name:'Gather_16' Status Message: indices element out of data bounds, idx=2 must be within the inclusive range [-2,1]
```

but `onnxruntime` succeeds for some different inputs:
```
# inputs [1,1,1,1,1,1,1,1]
$ polygraphy run --onnxrt model.onnx --data-loader-script data_loader_good.py
[I] onnxrt-runner-N0-01/26/22-23:24:18  | Activating and starting inference
[I] onnxrt-runner-N0-01/26/22-23:24:18 
    ---- Inference Input(s) ----
    {input_ids [dtype=int64, shape=(2, 8)],
     token_type_ids [dtype=int64, shape=(2, 8)],
     attention_mask [dtype=int64, shape=(2, 8)]}
[I] onnxrt-runner-N0-01/26/22-23:24:18 
    ---- Inference Output(s) ----
    {start_logits [dtype=float32, shape=(2, 8, 5)],
     end_logits [dtype=float32, shape=(2, 8, 5)]}
[I] onnxrt-runner-N0-01/26/22-23:24:18  | Completed 1 iteration(s) in 16.74 ms | Average inference time: 16.74 ms.
[I] PASSED | Command: /usr/local/bin/polygraphy run --onnxrt model.onnx --data-loader-script data_loader_good.py
```

helper script:
```
# data_loader_good.py
import numpy as np
inputs = {
    "input_ids": np.array([[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1]], dtype=np.int32),
    "token_type_ids": np.array([[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1]], dtype=np.int32),
    "attention_mask": np.array([[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1]], dtype=np.int32),
}

def load_data():
    yield inputs
```

---

**@andreabrduque are you able to confirm that your model is working as expected when directly using `onnxruntime` or `TensorRT` ?**

**Comment by CoderHam** [comment] 2022-01-31 21:27
@rmccorm4 can you link the PRs for the fix and close this accordingly

**Comment by andreabrduque** [comment] 2022-02-01 08:05
Thank you all for looking into this. I confirm that model works as expected using onnxruntime. I don't know why TensorRT converts values to NANs, but I haven't tried TensorRT on this model besides altering the configuration of the triton server.

**Closed** 2022-02-01 19:38 UTC
Labels: bug
