### ISSUE TITLE
Can't make more than one request

### ISSUE THREAD

**Issue by katerinafrid** [triton-inference-server/server#5046] opened 2022-11-08 13:21 UTC
I launched a triton server for a QA model and try to test it. For the first request everything works well, I get a response as I expect. But the second request can't be made because of an error 

` 
File "/home/kate/.local/share/virtualenvs/monorepo-DVV9frgJ/lib/python3.8/site-packages/tritonclient/http/__init__.py", line 1486, in infer
    _raise_if_error(response)
  File "/home/kate/.local/share/virtualenvs/monorepo-DVV9frgJ/lib/python3.8/site-packages/tritonclient/http/__init__.py", line 65, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: in ensemble 'qa_ensemble_model', PyTorch execute failure: default_program(24): error: extra text after expected end of number

default_program(28): error: extra text after expected end of number

2 errors detected in the compilation of "default_program".

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_div_add(float* tattention_scores_2, float* tv_, float* aten_add, float* aten_mul) {
{
if (blockIdx.x<1ll ? 1 : 0) {
if ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)<54ll ? 1 : 0) {
if (blockIdx.x<1ll ? 1 : 0) {
        float v = __ldg(tv_ + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
        aten_mul[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v * -3.402823466385289e+38.f;
      }    }  }if ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)<11664ll ? 1 : 0) {
    float v_1 = __ldg(tattention_scores_2 + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
    float v_2 = __ldg(tv_ + 18ll * (((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)) / 3888ll) + ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)) % 18ll);
    aten_add[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v_1 / 8.f + v_2 * -3.402823466385289e+38.f;
  }}
}
`

I use
nvcr.io/nvidia/tritonserver:22.01-py3
cuda 11.6
platform: "pytorch_libtorch"
model was saved with torch '1.11.0a0+bfe5ad2' in nvcr.io/nvidia/pytorch 22.01-py3 environment

**Comment by Tabrizian** [comment] 2022-11-08 16:13
Looks like in issue in the model. Can you try running the model outside Triton and repeat the same exercise?

**Comment by katerinafrid** [comment] 2022-11-09 12:49
The same problem is with another ensemble model in the same model repository. Both models are transformers consisting of 2 parts: a tokenizer and a model itself.

**Comment by Tabrizian** [comment] 2022-11-14 04:51
@katerinafrid Understood, but can you try the same experiment outside the Triton? This would help us understand whether the issue is in Triton or with your model that we need to further investigate.

**Comment by WissamAntoun** [comment] 2022-11-25 23:59
@Tabrizian I also have been facing this exact same issue, with triton 22.04 and 22.10, and converted with pytorch 1.8 , 1.10, 1.11. The model was trained on colab with an A100.

conversion code
```python
import torch
from transformers import BertForSequenceClassification, BertTokenizer

MODEL_PATH = "./1/orig_files/"
tokenizer = BertTokenizer.from_pretrained(MODEL_PATH)
text = ["Test test test test test test"] * 4
input_ids = tokenizer.batch_encode_plus(
    text, return_tensors="pt", max_length=80, padding="max_length"
)

class WrappedModel(torch.nn.Module):
    def __init__(self):
        super(WrappedModel, self).__init__()
        self.model = BertForSequenceClassification.from_pretrained(
            MODEL_PATH, return_dict=False
        ).cuda()

    def forward(self, input_ids, token_type_ids, attention_mask):
        return self.model(
            input_ids=input_ids.cuda(),
            token_type_ids=token_type_ids.cuda(),
            attention_mask=attention_mask.cuda(),
        )

pt_model = WrappedModel().eval()
traced_script_module = torch.jit.trace(
    pt_model,
    (input_ids["input_ids"], input_ids["token_type_ids"], input_ids["attention_mask"]),
)
traced_script_module.save("1/model.pt")

**Comment by Tabrizian** [comment] 2022-12-02 23:13
@WissamAntoun Can you run two inferences on this model when using Python?

**Comment by WissamAntoun** [comment] 2022-12-02 23:19
@Tabrizian using python as in python_backend in Triton or as in a regular "bare metal" python?
I tried later and it works fine.

I also tried all of these following https://discuss.pytorch.org/t/second-forward-call-of-torchscripted-module-breaks-on-cuda/124291/7 and it didn't work
```python
torch._C._jit_override_can_fuse_on_cpu(False)
torch._C._jit_override_can_fuse_on_gpu(False)
torch._C._jit_set_texpr_fuser_enabled(False)
torch._C._jit_set_nvfuser_enabled(False)
```

i also found this relevant issue https://github.com/pytorch/pytorch/issues/62962#issuecomment-1245990087

**Comment by jbkyang-nvi** [comment] 2023-01-28 00:04
Closing this issue due to lack of activity. If this issue needs follow-up, please let us know and we can reopen it for you.

**Comment by WissamAntoun** [comment] 2023-01-30 00:53
@jbkyang-nvi  can we re-open this issue. 

It keeps happening with some of the conversion that i do. It also seems arbitrary. I can't seem figure out what causes the problem. at the first I thought that the issue was the training and saving on the A100. 
But now it's happening on my rtx 3080ti driver 522.30, cuda 11.1, torch 1.11.

**Comment by wellhowtosay** [comment] 2023-04-13 16:31
> 

and you my friend are a true hero

**Comment by wellhowtosay** [comment] 2023-04-13 16:32
> 

and you my friend are a true hero

**Comment by wellhowtosay** [comment] 2023-04-13 16:32
> @jbkyang-nvi can we re-open this issue.
> 
> It keeps happening with some of the conversion that i do. It also seems arbitrary. I can't seem figure out what causes the problem. at the first I thought that the issue was the training and saving on the A100. But now it's happening on my rtx 3080ti driver 522.30, cuda 11.1, torch 1.11.
> 
> i just tried the conversion in nvcr.io/nvidia/pytorch:21.07-py3 and it didn't work.
> 
> Update 1: i was able to reproduce the bug outside triton using the following torch 1.10
> 
> ```python
> pt_model = WrappedModel().eval()
> traced_script_module = torch.jit.trace(
>     pt_model,
>     (input_ids["input_ids"], input_ids["token_type_ids"], input_ids["attention_mask"]),
> )
> traced_script_module.eval()
> traced_script_module.save("1/model.pt")
> 
> f = torch.jit.freeze(traced_script_module)
> f.eval()
> 
> f(input_ids["input_ids"], input_ids["token_type_ids"], input_ids["attention_mask"])
> f(input_ids["input_ids"], input_ids["token_type_ids"], input_ids["attention_mask"])
> ```
> 
> So I'm guessing this isn't a triton bug but a pytorch jit bug, might be similar to [pytorch/pytorch#63923](https://github.com/pytorch/pytorch/issues/63923)
> 
> Update 2: I upgraded to torch 1.13 and i couldn't reproduce the bug outside triton anymore Update 3: I finally solved the issue by disabling the hit executor in the model's config
> 
> ```
> parameters: {
> key: "ENABLE_JIT_EXECUTOR"
>     value: {
>     string_value: "false"
>     }
> }
> ```

and you my friend are a true hero

**Comment by dyastremsky** [comment] 2023-07-06 18:30
Thank you for finding a fix and updating the thread, @WissamAntoun! Closing, as this looks to be solved.

**Closed by dyastremsky** 2023-07-06 18:30 UTC

**Comment by chiehpower** [comment] 2024-11-05 00:39
> Hi all,
> 
> I encountered a similar error that I already used the latest Trtion server (docker image) **NVIDIA Release 24.10 (build 117849258) Triton Server Version 2.51.0**.
> 
> ```
> inference failed: [500] PyTorch execute failure: default_program(18): error: duplicate parameter name
>   void fused_add_add(long long* const_v_, long long* const_v__1, long long* const_v__1, long long* const_v_) {
>                                                                             ^
> 
> default_program(18): error: duplicate parameter name
>   void fused_add_add(long long* const_v_, long long* const_v__1, long long* const_v__1, long long* const_v_) {
>                                                                                                    ^
> 
> 2 errors detected in the compilation of "default_program".
> 
> nvrtc compilation failed: 
> 
> #define NAN __int_as_float(0x7fffffff)
> #define POS_INFINITY __int_as_float(0x7f800000)
> #define NEG_INFINITY __int_as_float(0xff800000)
> 
> 
> template<typename T>
> __device__ T maximum(T a, T b) {
>   return isnan(a) ? a : (a > b ? a : b);
> }
> 
> template<typename T>
> __device__ T minimum(T a, T b) {
>   return isnan(a) ? a : (a < b ? a : b);
> }
> 
> extern "C" __global__
> void fused_add_add(long long* const_v_, long long* const_v__1, long long* const_v__1, long long* const_v_) {
> {
> }
> }
> ```
> 
> However, I got another error below after I added the parameter `key: "ENABLE_JIT_EXECUTOR"` in the config.pbtxt.
> 
> ```
> inference failed: [400] PyTorch execute failure: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
> RuntimeError: vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 4)
> ```
> 
> (The behavior was identical to the previous instance, where the first inference completed successfully. However, an error occurred on the second inference request.)
> 
> Here is a partial log from the Triton container.
> 
> ```
> I1104 09:33:01.553405 1 libtorch.cc:2501] "TRITONBACKEND_Initialize: pytorch"
> I1104 09:33:01.553430 1 libtorch.cc:2511] "Triton TRITONBACKEND API version: 1.19"
> I1104 09:33:01.553437 1 libtorch.cc:2517] "'pytorch' TRITONBACKEND API version: 1.19"
> I1104 09:33:01.558105 1 libtorch.cc:2550] "TRITONBACKEND_ModelInitialize: test_model (version 1)"
> W1104 09:33:01.558709 1 libtorch.cc:329] "skipping model configuration auto-complete for 'test_model': not supported for pytorch backend"
> I1104 09:33:01.559432 1 libtorch.cc:358] "Optimized execution is enabled for model instance 'test_model'"
> I1104 09:33:01.559446 1 libtorch.cc:377] "Cache Cleaning is disabled for model instance 'test_model'"
> I1104 09:33:01.559453 1 libtorch.cc:394] "Inference Mode is enabled for model instance 'test_model'"
> I1104 09:33:01.559460 1 libtorch.cc:413] "cuDNN is enabled for model instance 'test_model'"
> I1104 09:33:01.559480 1 libtorch.cc:490] "Jit executor is disabled for model instance 'test_model'"
> I1104 09:33:01.559601 1 libtorch.cc:2594] "TRITONBACKEND_ModelInstanceInitialize: test_model_0 (GPU device 0)"
> ```
> 
> Is there any idea about it?
> 
> Thank you so much!
> 
> ## Testing Hardware
> * GPU: NVIDIA A2
> * Triton Docker image version: `nvcr.io/nvidia/tritonserver:24.10-py3`

I fixed this issue by adding this parameter.

```
parameters: {
key: "DISABLE_OPTIMIZED_EXECUTION"
    value: {
    string_value: "true"
    }
}
```
