### ISSUE TITLE
Shape mismatch attempting to re-use buffer. {1,16,48,48} != {4,16,48,48}

### ISSUE THREAD

**Issue by tringuyen2** [triton-inference-server/server#5320] opened 2023-02-06 08:46 UTC
**Description**

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by tringuyen2** [comment] 2023-02-06 08:55
Hi,
I'm testing model onnx in triton inference server with batch images:
![Screenshot from 2023-02-06 15-49-55](https://user-images.githubusercontent.com/79447747/216926697-4b66157e-6bce-45b6-bd75-9d25c17d9651.png)
I test in cpu, it seem ok and only warning:
2023-02-06 07:58:34.467968523 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,2,48,48} does not match actual shape of {4,2,48,48} for output score_8
2023-02-06 07:58:34.468562610 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,20,24,24} does not match actual shape of {4,20,24,24} for output kps_16
2023-02-06 07:58:34.468776840 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,20,12,12} does not match actual shape of {4,20,12,12} for output kps_32
2023-02-06 07:58:34.468869978 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,2,12,12} does not match actual shape of {4,2,12,12} for output score_32
2023-02-06 07:58:34.469463412 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,8,48,48} does not match actual shape of {4,8,48,48} for output bbox_8
2023-02-06 07:58:34.469676267 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,2,24,24} does not match actual shape of {4,2,24,24} for output score_16
2023-02-06 07:58:34.469868107 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,8,24,24} does not match actual shape of {4,8,24,24} for output bbox_16
2023-02-06 07:58:34.469957211 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,8,12,12} does not match actual shape of {4,8,12,12} for output bbox_32
2023-02-06 07:58:34.470779652 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,20,48,48} does not match actual shape of {4,20,48,48} for output kps_8


I test in GPU, it's error:
2023-02-06 08:41:40.276174352 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running Conv node. Name:'Conv_105' Status Message: /workspace/onnxruntime/onnxruntime/core/framework/op_kernel.cc:81 virtual OrtValue* onnxruntime::OpKernelContext::OutputMLValue(int, const onnxruntime::TensorShape&) status.IsOK() was false. Shape mismatch attempting to re-use buffer. {1,16,48,48} != {4,16,48,48}. Validate usage of dim_value (values should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.

**Comment by rmccorm4** [comment] 2023-02-06 22:27
Hi @tringuyen2 ,

There appears to be something wrong with this model. It looks like the batch size may not be propagating correctly. Even though the CPU messages are only warnings, I still think they should be fixed, as wrong shapes will have either an error or unexpected behavior at some point later in the pipeline. I don't think this issue is specific to Triton, you can probably reproduce something similar using ONNXRuntime directly in a simple python script or perhaps with [polygraphy](https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy).

**Closed** 2023-02-08 07:47 UTC
