### ISSUE TITLE
Error about layer datatype when load onnx model 

### ISSUE THREAD

**Issue by HoangTienDuc** [triton-inference-server/server#3967] opened 2022-02-22 05:07 UTC
**Description**
Hi, I want to use deepstream triton to get inference from my onnx model. However, at this time, DS-6.0 L4T does not support INT64 datatype. So, to make my program run, i need to change the layer that has datatype INT64 to another datatype (ex: FLOAT32, FLOAT16). 
After changing the layer datatype, the updated model was checked successfully. However the updated model can not be loaded by Triton. Below is my log.
```
E0222 04:41:59.627111 1553 model_repository_manager.cc:1215] failed to load 'detector' version 1: Internal: onnx runtime error 1: Load model from /ws/threatvision/models/detector/1/model.onnx failed:Type Error: Type (tensor(float)) of output arg (detected_classes) of node (squeeze_detected_classes) does not match expected type (tensor(int64)).
ERROR: Triton: failed to load model detector, triton_err_str:Invalid argument, err_msg:load failed for model 'detector': version 1: Internal: onnx runtime error 1: Load model from /ws/threatvision/models/detector/1/model.onnx failed:Type Error: Type (tensor(float)) of output arg (detected_classes) of node (squeeze_detected_classes) does not match expected type (tensor(int64)).;

ERROR: failed to load model: detector, nvinfer error:NVDSINFER_TRITON_ERROR
ERROR: failed to initialize backend while ensuring model:detector ready, nvinfer error:NVDSINFER_TRITON_ERROR
0:00:01.015761414  1553      0xba84b20 ERROR          nvinferserver gstnvinferserver.cpp:362:gst_nvinfer_server_logger:<primary-inference> nvinferserver[UID 5]: Error in createNNBackend() <infer_trtis_context.cpp:248> [UID = 5]: failed to initialize triton backend for model:detector, nvinfer error:NVDSINFER_TRITON_ERROR
I0222 04:41:59.627514 1553 server.cc:234] Waiting for in-flight requests to complete.
I0222 04:41:59.627594 1553 server.cc:249] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
0:00:01.016339843  1553      0xba84b20 ERROR          nvinferserver gstnvinferserver.cpp:362:gst_nvinfer_server_logger:<primary-inference> nvinferserver[UID 5]: Error in initialize() <infer_base_context.cpp:81> [UID = 5]: create nn-backend failed, check config file settings, nvinfer error:NVDSINFER_TRITON_ERROR
0:00:01.016545057  1553      0xba84b20 WARN           nvinferserver gstnvinferserver_impl.cpp:507:start:<primary-inference> error: Failed to initialize InferTrtIsContext
0:00:01.016596481  1553      0xba84b20 WARN           nvinferserver gstnvinferserver_impl.cpp:507:start:<primary-inference> error: Config file path: /ws/threatvision/cfg/dstest_ssd_nopostprocess.txt
0:00:01.017292124  1553      0xba84b20 WARN           nvinferserver gstnvinferserver.cpp:460:gst_nvinfer_server_start:<primary-inference> error: gstnvinferserver_impl start failed
Error: gst-resource-error-quark: Failed to initialize InferTrtIsContext (1): /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinferserver/gstnvinferserver_impl.cpp(507): start (): /GstPipeline:pipeline0/GstNvInferServer:primary-inference:
``` 
**Triton Information**
Deepstream triton 6.0 L4T (provided by nvidia ngc)

**To Reproduce**
```
import onnx_graphsurgeon as gs
import onnx
import numpy as np

model_path = "/ws/model.onnx"

graph = gs.import_onnx(onnx.load(model_path))
for node in graph.nodes:
    if node.name == "squeeze_detected_classes":
        for outp in node.outputs:
            if outp.dtype == np.int64:
                outp.dtype = np.float32

onnx.save(gs.export_onnx(graph), "updated_model.onnx")
model = onnx.load("updated_model.onnx")
print("check update model: ", onnx.checker.check_model(model))
```
onnx model was stored at this [location](https://drive.google.com/drive/folders/17xr7_cQCnMOJhttYEgf8kukWC7iZlWGG)

**Comment by GuanLuo** [comment] 2022-02-22 18:07
Can you try to use the ONNX checker with `check_model(model, full_check=True)`? https://github.com/onnx/onnx/issues/3642

**Comment by HoangTienDuc** [comment] 2022-02-23 01:47
Thank for the useful information

**Comment by GuanLuo** [comment] 2022-02-24 22:58
Closing as the issue is likely due to the model modification, please re-open the issue with updated repro steps if the modified model can be run without Triton but not within Triton.

**Closed by GuanLuo** 2022-02-24 22:58 UTC
