### ISSUE TITLE
Signal 11 received while stress testing

### ISSUE THREAD

**Issue by AndreWanga** [triton-inference-server/server#5328] opened 2023-02-07 13:21 UTC
**Description**
When I do stress test, tritonserver dumped with signal 11

**Triton Information**
tritonserver version: 2.24.0

use the Triton container

**To Reproduce**
1. start triton server with TensorRT model
2. do stress test with 100 users by using grpc
3. wait for servaral minitues
![signal 11](https://user-images.githubusercontent.com/114132971/217255950-b10e1092-61cb-4abc-87bd-5e8af1746a4c.gif)

Simbert(12-layer Bert) NER(4-layer Bert)

**Expected behavior**
Functionlly well during stress test

**Comment by AndreWanga** [comment] 2023-02-08 04:37
@dyastremsky I think I have found the reason of this error. It's because of the auto-config mode. I think in auto-config mode, sometimes the dynamic batch size will beyond the capability of TensorRT model, therefore the tritonserver dumped. So maybe you could verify my theory, if it's true, you could print a warning to tell users NOT to use auto-config mode in product env.

**Comment by dyastremsky** [comment] 2023-02-08 17:21
Thank you for reporting this and providing a theory. If you use log-verbose, you should see the config. Is the dynamic batch size printed beyond the TensorRT model's capability? That should give data to help support/reject the theory.

We could look at this as well, though we'd need reproduction steps to be able to confirm the behavior on our end and to help with the investigation.

CC: @nv-kmcgill53 (Do we do any special handling for TensorRT models when setting dynamic batch size?)

**Comment by nv-kmcgill53** [comment] 2023-02-08 17:41
Absent the logs to see what triton is doing, the logic for auto completing the dynamic batch size is done [here](https://github.com/triton-inference-server/tensorrt_backend/blob/main/src/model_state.cc#L496-L558). Maybe this will help with a quick inspection of the model in use.

**Comment by AndreWanga** [comment] 2023-02-09 13:51
> Absent the logs to see what triton is doing, the logic for auto completing the dynamic batch size is done [here](https://github.com/triton-inference-server/tensorrt_backend/blob/main/src/model_state.cc#L496-L558). Maybe this will help with a quick inspection of the model in use.

Thank for showing me the code, In line 500, I see that "Assuming the first dimension to be batch dimension". Is this reliable? TensorRT model is now explicit defaultlly and I use explicit model too. Maybe here is the reason but  I'm not sure about that. And now I use config.pbtxt to run triton server stably.

**Comment by AndreWanga** [comment] 2023-02-09 13:55
> Thank you for reporting this and providing a theory. If you use log-verbose, you should see the config. Is the dynamic batch size printed beyond the TensorRT model's capability? That should give data to help support/reject the theory.
> 
> We could look at this as well, though we'd need reproduction steps to be able to confirm the behavior on our end and to help with the investigation.
> 
> CC: @nv-kmcgill53 (Do we do any special handling for TensorRT models when setting dynamic batch size?)


<

> Thank you for reporting this and providing a theory. If you use log-verbose, you should see the config. Is the dynamic batch size printed beyond the TensorRT model's capability? That should give data to help support/reject the theory.
> 
> We could look at this as well, though we'd need reproduction steps to be able to confirm the behavior on our end and to help with the investigation.
> 
> CC: @nv-kmcgill53 (Do we do any special handling for TensorRT models when setting dynamic batch size?)

Thanks for dealing with my issue, I've readed the code and reply to your colleague

**Comment by dyastremsky** [comment] 2023-02-21 17:48
That should be reliable, given that it's checked whether batching is supported as well. Can you provide the verbose logs? That's the easiest way to see what's the final config after auto-complete. Otherwise, we'll just be speculating.

**Comment by AndreWanga** [comment] 2023-02-27 15:15
> That should be reliable, given that it's checked whether batching is supported as well. Can you provide the verbose logs? That's the easiest way to see what's the final config after autocomplete. Otherwise, we'll just be speculating.

I'd like to help you, but the log is in product env. I can't copy that. Now I use the config.pbtxt, and it's very stable.

**Comment by dyastremsky** [comment] 2023-02-27 16:10
Okay, great. We can't investigate without logs and/or reproduction steps. Since you solve your issue, I'll close this out. Happy to hear you got it working for you!

**Closed by dyastremsky** 2023-02-27 16:10 UTC
Labels: bug
