### ISSUE TITLE
Redis-Cluster Fails to write keys

### ISSUE THREAD

**Issue by zbloss** [triton-inference-server/server#6724] opened 2023-12-20 15:17 UTC
**Description**

Triton Inference Server fails to write keys sporadically to a redis-cluster. When deploying a redis-cluster with 3 master and 3 slave nodes I've noticed that my triton instance will log the below frequently but not every time.

```bash
│ E1220 14:30:52.961471 64 dynamic_batch_scheduler.cc:686] Failed to insert key [14775872642165677484] into response cache: Failed to insert key: 14775872642165677484. 13615 10.64.4.171:6379                                             │

```

**Triton Information**

I am using Pytriton 0.4.1.

```bash
│ +----------------------------------+------------------------------------------+                                                                                                                                                          │
│ | Option                           | Value                                    |                                                                                                                                                          │
│ +----------------------------------+------------------------------------------+                                                                                                                                                          │
│ | server_id                        | triton                                   |                                                                                                                                                          │
│ | server_version                   | 2.39.0                                   |                                                                                                                                                          │
│ | server_extensions                | classification sequence model_repository |                                                                                                                                                          │
│ |                                  |  model_repository(unload_dependents) sch |                                                                                                                                                          │
│ |                                  | edule_policy model_configuration system_ |                                                                                                                                                          │
│ |                                  | shared_memory cuda_shared_memory binary_ |                                                                                                                                                          │
│ |                                  | tensor_data parameters statistics trace  |                                                                                                                                                          │
│ |                                  | logging                                  |                                                                                                                                                          │
│ | model_repository_path[0]         | /root/.cache/pytriton/workspace_pjucgnk1 |                                                                                                                                                          │
│ | model_control_mode               | MODE_EXPLICIT                            |                                                                                                                                                          │
│ | strict_model_config              | 0                                        |                                                                                                                                                          │
│ | rate_limit                       | OFF                                      |                                                                                                                                                          │
│ | pinned_memory_pool_byte_size     | 268435456                                |                                                                                                                                                          │
│ | min_supported_compute_capability | 6.0                                      |                                                                                                                                                          │
│ | strict_readiness                 | 1                                        |                                                                                                                                                          │
│ | exit_timeout                     | 30                                       |                                                                                                                                                          │
│ | cache_enabled                    | 1                                        |                                                                                                                                                          │
│ +----------------------------------+------------------------------------------+                                                                                                                                                          │
```

**To Reproduce**

Install a redis-cluster using a bitnami chart https://artifacthub.io/packages/helm/bitnami/redis-cluster

`helm install my-redis-cluster bitnamicharts/redis-cluster`

Configure your triton inference server to use the triton [redis_cache](https://github.com/triton-inference-server/redis_cache), then begin sending requests to the inference server.

**Expected behavior**

Keys should write to the redis-cluster master nodes and be read-replicated to the slave nodes.

**Comment by rmccorm4** [comment] 2024-01-08 23:28
Looks like this is a duplicate of https://github.com/triton-inference-server/redis_cache/issues/12 and may be resolved or a known gap in the redis library being used. Please use that issue for further discussion.

**Closed by rmccorm4** 2024-01-08 23:28 UTC
Labels: bug

**Comment by Wenhan-Tan** [comment] 2025-02-18 19:56
Hi @zbloss , did you ever resolve the error?

**Comment by zbloss** [comment] 2025-02-18 19:57
I did not. I packed up my bags and moved over to vllm.

**Comment by Wenhan-Tan** [comment] 2025-02-18 21:09
lol Thanks for sharing though
