### ISSUE TITLE
Support for SwiftStack S3 API

### ISSUE THREAD

**Issue by barelyreal** [triton-inference-server/server#2381] opened 2021-01-05 15:55 UTC
**Is your feature request related to a problem? Please describe.**

I'm unable to connect to a repository located in SwiftStack using the S3 API.  When attempting to start Triton, I get this error:

```
I1218 17:41:51.583433 1 server.cc:277] No server context available. Exiting immediately.
error: creating server: Internal - Could not get MetaData for bucket with name triton-repo
```

I’m able to connect to AWS s3 from Triton and load a model.  I’m also able to connect to SwiftStack using the AWS cli like this:

```
docker run -e "AWS_DEFAULT_REGION=z1-a" \
-e "AWS_ACCESS_KEY_ID=<key id>" \
-e "AWS_SECRET_ACCESS_KEY=<secret>" \
-it amazon/aws-cli --endpoint=https://z1-a.objectstorage.<domainname> s3 ls
```

Looking through the triton server code, it looks like it’s using the official AWS s3 client library, so I’d imagine the environment variables should be used in the same way, but maybe there’s a difference.  Here’s how I’m testing with triton:

```
docker run -e "AWS_DEFAULT_REGION=z1-a" \
-e “AWS_ACCESS_KEY_ID=<key id>" \
-e “AWS_SECRET_ACCESS_KEY=<secret>" \
--rm -p8000:8000 -p8001:8001 -p8002:8002 nvcr.io/nvidia/tritonserver:20.11-py3 tritonserver \
--model-repository=s3://z1-a.objectstorage.<domainname>:443/triton-repo/triton1 \
--strict-model-config=false --log-verbose=1
```

**Describe the solution you'd like**

I would like to be able to load models from a repository located in SwiftStack using the S3 API. :)

**Describe alternatives you've considered**

As a workaround I'm currently loading models from AWS, which works but is slower.

**Additional context**

**Comment by deadeyegoodwin** [comment] 2021-01-26 00:35
Thanks for the enhancement request. We will place it on our roadmap.

**Comment by CoderHam** [comment] 2021-03-09 23:40
Can you confirm the endpoint url is the same? 
We recently added verbose logging for S3 errors that can help you diagnose the issue. Can you try a build with #2557 please follow the docker based build instructions from [build.md](https://github.com/triton-inference-server/server/blob/master/docs/build.md)? 
Additionally as a simple test can you use aws cli / boto3 inside the Triton container to confirm the credentials and endpoints are correct?

**Comment by CoderHam** [comment] 2021-03-24 18:52
@barelyreal can you share your email addresses with me so I can share the latest master build for you to test on?
It contains verbose logging for S3 Storage and could help you understand the cause of the issue better.

**Comment by msalehiNV** [comment] 2021-04-07 20:21
tchihaya@liveperson.com and gbonev@liveperson.com

**Comment by CoderHam** [comment] 2021-04-13 20:10
@barelyreal did you get a chance to test the docker image? I am waiting on you to share the verbose log errors you see to be able to triage this issue.

**Comment by barelyreal** [comment] 2021-04-20 21:56
@gblp has been working on this and should have an answer soon

**Comment by gblp** [comment] 2021-04-21 20:42
@CoderHam This is what we get now:
```
I0421 20:36:26.747315 1 server.cc:230] No server context available. Exiting immediately.
error: creating server: Internal - Could not get MetaData for bucket with name models due to exception: , error message: No response body. with address : 192.168.26.217
```

**Comment by gblp** [comment] 2021-04-21 20:44
@CoderHam This is what we get now:
```
I0421 20:36:26.747315 1 server.cc:230] No server context available. Exiting immediately.
error: creating server: Internal - Could not get MetaData for bucket with name models due to exception: , error message: No response body. with address : XXX.XXX.XXX.XXX
```
I replaced the IP address of our SwiftStack endpoint with XXX.XXX.XXX.XXX for security

**Comment by CoderHam** [comment] 2021-04-26 12:35
@gblp thanks for getting back to us. From the looks of the error message it appears the issue is that the error is related to the Triton being unable to access the Swiftstack bucket with the credentials specified.  
Inside the Triton container can you use aws-cli to test if the credentials are set correctly?

**Comment by arunraman** [comment] 2021-05-04 23:53
I had no problem running this 

`docker run -e AWS_ACCESS_KEY_ID=<AWS_KEY_ID> -e AWS_SECRET_ACCESS_KEY=<AWS_SECRET_KEY> AWS_DEFAULT_REGION=<Region> --gpus device=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 nvcr.io/nvidia/tritonserver:20.12-py3 tritonserver --model-repository=s3://model_bucket/ --model-control-mode=poll --repository-poll-secs=5 --log-verbose=true --exit-on-error=false --strict-model-config=false`

Are the double quotes on the environment variable an issue?

**Comment by arunraman** [comment] 2021-05-18 19:21
We have found the issue on the incompatibility between the AWS S3 and SwiftStack S3 api. @CoderHam is working on a fix for this.

**Comment by CoderHam** [comment] 2021-05-18 19:39
@barelyreal the issue will be fixed by https://github.com/triton-inference-server/server/pull/2879 and https://github.com/triton-inference-server/server/pull/2880

**Closed** 2021-05-18 20:27 UTC
Labels: enhancement
