### ISSUE TITLE
cudashm.get_contents_as_numpy always using gpu 0

### ISSUE THREAD

**Issue by FamousDirector** [triton-inference-server/server#1915] opened 2020-08-20 20:27 UTC
**Description**
While running my code I check `nvidia-smi` and there were too many allocated spaces on GPU:0. I have narrowed it down to my return statement that uses `cudashm.get_contents_as_numpy()`. Even when I declare `cudashm.create_shared_memory_region()` and `triton_client.register_cuda_shared_memory()` to id not 0, it still ends up on the card.

**Triton Information**
I am using the 20.06 Triton container (v2)

**To Reproduce**
Use a GPU system with more than one GPU. Run a Triton client with grpc and cuda shared memory. Set the ouput to be allocated to a gpu that is not id=0. Watch `nvidia-smi` to see the memory be allocated for the output on GPU 0.

**Expected behavior**
I would expect the memory to be allocated on the card specified by `cudashm.create_shared_memory_region()` and `triton_client.register_cuda_shared_memory()`

**Comment by CoderHam** [comment] 2020-08-21 00:39
`cudashm.get_contents_as_numpy()` does not allocate memory on the GPU. It simply performs a D2H copy and for the data in the cuda shared memory and returns it as a numpy array. 
If it does occupy memory on GPU0 that would be caused by `cudashm.create_shared_memory_region()` creating the cuda shared memory region on GPU0 and I agree that would be a bug [We do call cudaSetDevice so this would be unexpected behaviour]. 

I can run some experiments to verify the same. In the meanwhile can you share a minimal repro of the client code you used to produce the same? Are you sure the memory being used on GPU0 is due to the cuda shared memory and not the model itself?

**Comment by FamousDirector** [comment] 2020-08-31 11:47
@CoderHam any update on this? As a side note, I am using an ensemble model, if that matters.

**Comment by CoderHam** [comment] 2020-09-04 05:35
I did observed an increased in GPU memory consumption when using the cuda shared memory python library but my observations were different.

I modified [simple_http_cudashm_client.py](https://github.com/triton-inference-server/server/blob/master/src/clients/python/examples/simple_http_cudashm_client.py) to not perform inference but only create and use the cuda shared memory regions. 

Below is the recorded GPU consumption (bytes)  for a simple model that runs on CPU. As you can see there is indeed a bug but not with  `cudashm.get_contents_as_numpy` it appears to be with `cudashm.create_shared_memory_region`. Infact 307MB (exactly) additional GPU memory is consumed when the 1st CUDA shared memory region is created. 
Creating multiple regions does not impact the size of this increase of GPU memory. It is always the same even for larger cuda shared memory regions. 

```
GPU used Before (all) create_shared_memory_region: 1654194176
GPU used After (1st) create_shared_memory_region: 1976107008
GPU used After (all) create_shared_memory_region: 1976107008
GPU used After set_shared_memory_region: 1976107008
GPU used After 1st cudashm.get_contents_as_numpy: 1976107008
GPU used After 2nd cudashm.get_contents_as_numpy: 1976107008
GPU used After destroy all cudashm: 1974009856 
```

**Comment by CoderHam** [comment] 2020-09-04 05:59
In comparison repeating the same with the C++ library shows a similar increase when calling `CreateCUDAIPCHandle` but of only 2MB:
Used GPU Memory Before CreateCUDAIPCHandle: 2025979904
Used GPU Memory after CreateCUDAIPCHandle : 2028077056
Used GPU Memory after SetSharedMemory: 2028077056
Used GPU Memory after cudaFree: 2025979904

I am looking into what is causing this increase and why it is so much larger in the case of python when both use `CreateCUDAIPCHandle` in their underlying APIs.

**Comment by FamousDirector** [comment] 2020-09-04 11:40
@CoderHam Thank you for investigating this. It is bizarre that they are Does/would a GRPC behave differently? Could you also look at the effects of calling an ensemble model with CUDA shared memory. 

I am also using a Tesla T4 if that matters. Please let me know how I can contribute to this investigation.

**Comment by CoderHam** [comment] 2020-09-10 00:01
The increase appears to be independent of the protocol. I am working on fixing this unexpected increase. It is likely going to solve it for all scenarios.

**Comment by FamousDirector** [comment] 2020-09-10 17:49
This issue is quite critical to us. If there is a fix, would it be possible to see this included in a 20.08.1 release?

**Comment by CoderHam** [comment] 2020-09-10 18:04
Still working on zeroing into the cause. It is specific to the python cuda shared memory client library inside Triton and not the server. The two immediate solutions would be to:
- Use the C++ client library
- Build your own version of the CUDA shared memory library that does not cause this 300MB increase in GPU memory.

We are working on getting these changes into 20.09. We do not intend on having a 20.08.1 release but @deadeyegoodwin can confirm.

**Comment by CoderHam** [comment] 2020-09-11 20:12
The 300MB or so increase in GPU memory is caused by the CUDA lazy initialization. It happens whenever the cuda context is created. This can be limited to some extend using [cudaDeviceSetLimit()](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g05956f16eaa47ef3a4efee84563ccb7d)
Before the call to the function that creates the CUDA IPC handle, there is no other call so the context gets initialized only when this call is made. As a correction to the earlier statement about C++ native, this is need both for the python + shared library and the C++ native implementation. 

Since this is not actionable I am closing the ticket. You can look into alternate workarounds if this is a limiting factor. 
PS: The CUDA context is created by the first runtime call for the target device -- internally, you'll see a driver call to cuDevicePrimaryCtxRetain.  That call will allocate the 300MB (approx).  This allocation will hit every device targeted when the respective device is used.

**Closed by CoderHam** 2020-09-11 20:12 UTC
