### ISSUE TITLE
Model with dynamic shapes and TensorRT optimization outputs nonsense

### ISSUE THREAD

**Issue by mg515** [triton-inference-server/server#2231] opened 2020-11-06 14:14 UTC
**Description**
We use a detector model (RetinaFace) with dynamic batch as well as dynamic height, width and output size. Originally, it's a PyTorch model, which we converted to ONNX via `torch.onnx.export`, where we specify `dynamic_axes`.
[Link to the RetinaFace PyTorch implementation.](https://github.com/biubug6/Pytorch_Retinaface)

When we deploy the ONNX model and not use TensorRT optimization option, everything works as expected and output is correctly interpretable for different input image dimensions. E.g. With the input dimension of `[1, 3, 1920, 1920]`  output variable `loc` would be `[1, 151200, 4]`, which is expected.

However, upon trying to use the TensorRT optimization, we always get the same outputs, which don't make any sense. E.g. for output variable `loc`, we would get an output shape of `[1,6,4]`. The output also always has the same shape, no matter the input dimensions (output shape depends on height and width). Upon checking the tritonserver docker logs, there is no relevant warnings or errors.

**Triton Information**
Triton images from 20.08 to 20.10, they all suffer from the same issue.

Are you using the Triton container or did you build it yourself?
Triton container.

**To Reproduce**
Download the ONNX model here - [gdrive link](https://drive.google.com/file/d/1L_i78-o4CcUGfSZgJKn2sqfN85CDypQg/view?usp=sharing)

Triton configuration to go with the model:
```
name: "retina"
platform: "onnxruntime_onnx"
default_model_filename: "retina_dynamic.onnx"
max_batch_size: 2
input {
  name: "input"
  data_type: TYPE_FP32
  dims: 3
  dims: -1
  dims: -1
}
output {
  name: "landms"
  data_type: TYPE_FP32
  dims: -1
  dims: 10
}
output {
  name: "loc"
  data_type: TYPE_FP32
  dims: -1
  dims: 4
}
output {
  name: "conf"
  data_type: TYPE_FP32
  dims: -1
  dims: 2
}
optimization {
  execution_accelerators {gpu_execution_accelerator : [{name : "tensorrt"}]}
}
model_warmup {
  name: "warmup_retina"
  batch_size: 2
  inputs {
    key: "input"
    value {
      data_type: TYPE_FP32
      dims: 3
      dims:  1920
      dims: 1920
      random_data: true
    }
  }
}
```

**Expected behavior**
When using TensorRT optimization, the output of warmup sample is going to be `[1,6,4]` for variable `loc`, which is **incorrect**.
Without optimization, the output of warmup sample is going to be `[1,151200,4]` for variable `loc`, which is **correct.**

**Other**
Some things we tried:
* variation of optimization parameters (`max_cached_engines`, `minimum_segment_size`, `max_workspace_size_bytes`)
* variation of `torch.onnx.export` parameters (`opset version`, `dynamic folding`)
* fixed batch size
* Triton versions from `20.08` to `20.10`. Last one has a different CUDA dependency too.
* **Fixed height and width dimensions, works both with/without tensorrt optimization correctly.**

**Comment by philipp-schmidt** [comment] 2020-11-26 00:28
I can confirm that there are weird effects when using TensorRT models with dynamic shapes. I am currently experiencing results "leaking" through into other requests, as if they would overwrite each others memory on the server. I am still investigating, but this behavior could be linked to the issue you describe. The issues are directly linked to using the explicit batch mode of TensorRT, which is what onnx does under the hood as well to enable dynamic shapes:

`builder->createNetworkV2(1U << static_cast<int32_t>(NetworkDefinitionCreationFlag::kEXPLICIT_BATCH));`

**Comment by mg515** [comment] 2020-11-26 15:06
Thank you @philipp-schmidt for replying here.

I tested the same setup described in my first post, only this time using Triton version 20.11, the latest one. The problem is partially gone, as inference now works properly, as in giving expected result.
However, inference of one batch now takes very long time (20-40 seconds). I think it has something to do with the fact that dynamic shape in this case can have a lot of different values and Triton somehow has to allocate memory and adjust the graph smartly. Hopefully it gets resolved with the future updates though.:)

**Comment by philipp-schmidt** [comment] 2020-11-26 15:53
Hi, I'm in the middle of finishing a project so I can't dive any deeper into this issue right now, but I wanted to let you know that I reverted to using triton version 19.10, where I am experiencing no errors regarding dynamic shape in tensorRT whatsoever.
I believe that [some of the optimizations of version 20.02](https://github.com/triton-inference-server/server/releases/tag/v1.11.0) introduced some major bugs regarding dynamic shapes and max_batch_size. Currently I am under time pressure to get a  product polished up, so reverting to 19.10 (anything before 20.02 should be fine actually) is the best option for me. I will however get in touch with our nvidia guys here and try to pinpoint where the problems are so I can get onto a more recent triton version asap. I'm gonna reference this issue here so you'll get notified.

**Comment by philipp-schmidt** [comment] 2020-11-26 15:56
Oh and just to make it clear: I never had issues with getting wrong shapes reported by triton, but I'm supposedly getting race conditions on the server side because results of different clients (100+) overwrite each other. I'm not yet sure how this is linked to your issue but they might be related on first glance.

**Comment by deadeyegoodwin** [comment] 2021-01-26 01:03
We have recently fixed a race condition in triton that may relate to your issue. Can you retry with latest Triton. Closing, reopen when you report your findings.

**Closed by deadeyegoodwin** 2021-01-26 01:03 UTC

**Comment by philipp-schmidt** [comment] 2021-01-26 01:57
Thanks @deadeyegoodwin and your team.
If this fixes the issue I was having it just saved me a lot of time debugging, very much appreciated.

**Comment by hande6688** [comment] 2021-12-17 10:05
@philipp-schmidt @mg515 I also use the above retinaface as a Triton for onnx。

name: "retinaface_model"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input0"
    data_type: TYPE_FP32
    format: FORMAT_NONE
    dims: [1,3,640,640]
    is_shape_tensor: false
    allow_ragged_batch: false
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1,16800,16]
    label_filename: ""
    is_shape_tensor: false
  }
]

I don't know how to use the output to draw the detection box, do you know？
