### ISSUE TITLE
Decoupled Models Hang Unexpectedly with No Clear Error Message

### ISSUE THREAD

**Issue by BasharMahasen** [triton-inference-server/server#5951] opened 2023-06-15 04:23 UTC
**Description**
We use Triton decoupled models to avoid the blocking mechanism of default Python models and enable processing more requests by the same instance. We send around 100 frame/s to a decoupled model. Serving works for a few minutes with no issue, then suddenly, it hangs and gets into a deadlock. Once that happens, restarting the client does not help as the server does not accept any more requests. The only way is to restart Triton.

There is no error message from the server /client side. The issue happens randomly, but it does every time.
would you please advise how to troubleshoot this issue, and what configurations for the client (GRPC streaming) or the server side we need to look at?

I attached a sample of the code snippet as well as the verbose logs for your kind review.
[config.txt](https://github.com/triton-inference-server/server/files/11752793/config.txt)
[decoupled_client (1).txt](https://github.com/triton-inference-server/server/files/11752899/decoupled_client.1.txt)
[model.txt](https://github.com/triton-inference-server/server/files/11752795/model.txt)
[triton_verbos_log.zip](https://github.com/triton-inference-server/server/files/11753247/triton_verbos_log.zip)

Regards
Bashar

**Triton Information**
What version of Triton are you using?
23.05-py3

Are you using the Triton container or did you build it yourself?
based on the 23.05-py3 container.

**To Reproduce**
Sample code attached.
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
An error message which indicates what went wrong and why the model became irresponsive.

**Comment by kthui** [comment] 2023-06-20 22:36
Hi @BasharMahasen, could you re-upload the [triton_verbos_log.zip](https://github.com/triton-inference-server/server/files/11753247/triton_verbos_log.zip), maybe without compression? I was not able to decompress the file.

Regarding the Python decoupled model hang issue, would you be able to provide a minimal reproduction? Similar in complexity to our [decoupled examples](https://github.com/triton-inference-server/python_backend/blob/main/examples/decoupled/repeat_model.py).

**Comment by AlexXi19** [comment] 2023-06-21 01:14
I'm running into the same issue. The code would hang on `.send` after continuously sending requests. I've try to add a timeout to the send function but had no success. One thing I found was that other models were still usable. But the inference for the model in question would hang indefinitely.

**Comment by kthui** [comment] 2023-06-22 01:20
Thanks for reporting the issue @AlexXi19 @davidxhive @plakhwara. It would be helpful if you could provide a minimal reproduction for the hang issue, for us to investigate further.

**Comment by AlexXi19** [comment] 2023-06-22 21:41
Thanks for responding. I will try to provide a minimal reproduction.

**Comment by AlexXi19** [comment] 2023-08-15 23:23
Sorry for the late reply, this has been fixed by updating the triton version.

**Comment by krishung5** [comment] 2023-08-21 21:35
Closing due to inactivity. Please let us know if you would like to reopen the issue for follow-up.

**Closed by krishung5** 2023-08-21 21:35 UTC
