### ISSUE TITLE
Output Buffer not being free after request

### ISSUE THREAD

**Issue by Thytu** [triton-inference-server/server#6261] opened 2023-09-01 13:26 UTC
**Description**
Hello 👋,

There is 90% that the issue comes from my side or that I miss something but I would love to have your take on it.

In my understanding triton [allocates a buffer](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/inference_protocols.html#:~:text=When%20Triton%20produces%20an%20output%20tensor%2C%20it%20needs%20a%20memory%20buffer%20into%20which%20it%20can%20store%20the%20contents%20of%20that%20tensor.%20Triton%20defers%20the%20allocation%20of%20these%20output%20buffers%20by%20invoking%20callback%20functions%20in%20your%20application) for the output that should be freed once the request ends.

Using a single ONNX model it appears that this buffer might not be freed. Is that something we should do manually? if so, how?

**Triton Information**

I use a docker image based on `nvcr.io/nvidia/tritonserver:22.12-py3`

**To Reproduce**
I created a basic git repo to help you reproduce this behavior, you can find it [here](https://github.com/gladiaio/triton-inference-memory-allocation).
Its README explains every steps needed to reproduce the issue.

**Expected behavior**

I would expect the buffer to be freed once the request ends, or at least after a certain amount of time.

**Comment by jsoto-gladia** [comment] 2023-09-01 13:42
@jsoto-gladia

**Comment by kthui** [comment] 2023-09-02 01:08
@tanmayv25 Do you know if the memory growth on ONNX model is a known issue?

**Comment by Thytu** [comment] 2023-09-05 07:42
> @tanmayv25 Do you know if the memory growth on ONNX model is a known issue?

I'm not sure it's about ONNX. I could replace the onnx model with a python one to check whether it's related.
Also, I so [this note](https://github.com/triton-inference-server/server/releases/tag/v2.37.0#:~:text=a%20root%20cause.-,Some%20systems,-which%20implement%20malloc) in the latest release, may also be related (idk if it is, just giving more data)

**Comment by dyastremsky** [comment] 2023-10-26 00:07
Can you try a more recent version of Triton and see if this issue still exists? The code has changed significantly since 22.12, and there may have been fixes applied. Also, I notice you said that your version is based on 22.12. Please use the official container (e.g. 23.09) to see if the issue exists there without any modifications.

**Comment by oandreeva-nv** [comment] 2023-11-01 22:11
Hi @Thytu , I was trying to run a reproducer, but I am facing some issues. First, requirements seem to be incomplete, I was able to succeed with updating them as follows:
requirements.txt:
```                                                                                                                      
requests==2.31.0
onnx
tritonclient[all]
torch==2.0.1
torchaudio==2.0.2
```
requirements-server.txt:
```
pyannote-core==5.0.0
pyannote-database==5.0.1
pyannote-metrics==3.2
pyannote-pipeline==3.0.1
git+https://github.com/pyannote/pyannote-audio.git@develop
```
Could you please confirm that these are correct?

Next, after running `bash scripts/run.sh`, I am failing with the following:
```

============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[+] Building 0.2s (10/10) FINISHED                                                                                                                                                                                                                                          
 => [triton-server-pyannote internal] load build definition from Dockerfile                                                                                                                                                                                            0.0s
 => => transferring dockerfile: 516B                                                                                                                                                                                                                                   0.0s
 => [triton-server-pyannote internal] load .dockerignore                                                                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                        0.0s
 => [triton-server-pyannote internal] load metadata for nvcr.io/nvidia/tritonserver:23.08-py3                                                                                                                                                                          0.0s
 => [triton-server-pyannote 1/5] FROM nvcr.io/nvidia/tritonserver:23.08-py3                                                                                                                                                                                            0.0s
 => [triton-server-pyannote internal] load build context                                                                                                                                                                                                               0.0s
 => => transferring context: 112B                                                                                                                                                                                                                                      0.0s
 => CACHED [triton-server-pyannote 2/5] COPY requirements-server.txt ./                                                                                                                                                                                                0.0s
 => CACHED [triton-server-pyannote 3/5] RUN pip install -r requirements-server.txt                                                                                                                                                                                     0.0s
 => CACHED [triton-server-pyannote 4/5] COPY scripts/entrypoint.sh /scripts/                                                                                                                                                                                           0.0s
 => CACHED [triton-server-pyannote 5/5] WORKDIR /models                                                                                                                                                                                                                0.0s
 => [triton-server-pyannote] exporting to image                                                                                                                                                                                                                        0.0s
 => => exporting layers                                                                                                                                                                                                                                                0.0s
 => => writing image sha256:166e138b75ebed017e51613ab62587f3f10d1653a49ac1c6e039000a9221d653                                                                                                                                                                           0.0s
 => => naming to docker.io/library/docker-triton-server-pyannote                                                                                                                                                                                                       0.0s
[+] Running 2/2
 ✔ Network docker_default                     Created                                                                                                                                                                                                                  0.7s 
 ✔ Container docker-triton-server-pyannote-1  Started                                                                                                                                                                                                                  1.1s 
Traceback (most recent call last):
  File "scripts/calls.py", line 19, in <module>
    audio_for_diari, sr = torchaudio.load("clean-code.mp3")
  File "/home/oandreeva/.local/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 256, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/home/oandreeva/.local/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 30, in _fail_load
    raise RuntimeError("Failed to load audio from {}".format(filepath))
RuntimeError: Failed to load audio from clean-code.mp3
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb98a163b80>
[+] Running 2/2
 ✔ Container docker-triton-server-pyannote-1  Removed                                                                                                                                                                                                                 12.4s 
 ✔ Network docker_default                     Removed                                                                                                                                                                                                                  1.0s 
[+] Building 0.2s (10/10) FINISHED                                                                                                                                                                                                                                          
 => [triton-server-dummy internal] load build definition from Dockerfile                                                                                                                                                                                               0.0s
 => => transferring dockerfile: 516B                                                                                                                                                                                                                                   0.0s
 => [triton-server-dummy internal] load .dockerignore                                                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                        0.0s
 => [triton-server-dummy internal] load metadata for nvcr.io/nvidia/tritonserver:23.08-py3                                                                                                                                                                             0.0s
 => [triton-server-dummy 1/5] FROM nvcr.io/nvidia/tritonserver:23.08-py3                                                                                                                                                                                               0.0s
 => [triton-server-dummy internal] load build context                                                                                                                                                                                                                  0.0s
 => => transferring context: 112B                                                                                                                                                                                                                                      0.0s
 => CACHED [triton-server-dummy 2/5] COPY requirements-server.txt ./                                                                                                                                                                                                   0.0s
 => CACHED [triton-server-dummy 3/5] RUN pip install -r requirements-server.txt                                                                                                                                                                                        0.0s
 => CACHED [triton-server-dummy 4/5] COPY scripts/entrypoint.sh /scripts/                                                                                                                                                                                              0.0s
 => CACHED [triton-server-dummy 5/5] WORKDIR /models                                                                                                                                                                                                                   0.0s
 => [triton-server-dummy] exporting to image                                                                                                                                                                                                                           0.0s
 => => exporting layers                                                                                                                                                                                                                                                0.0s
 => => writing image sha256:5a50ea349a71694f2f684497404b2b35b4f5350a4534aacacb583e31fa927c49                                                                                                                                                                           0.0s
 => => naming to docker.io/library/docker-triton-server-dummy                                                                                                                                                                                                          0.0s
[+] Running 2/2
 ✔ Network docker_default                  Created                                                                                                                                                                                                                     0.6s 
 ✔ Container docker-triton-server-dummy-1  Started                                                                                                                                                                                                                     1.9s 
Traceback (most recent call last):
  File "scripts/calls.py", line 19, in <module>
    audio_for_diari, sr = torchaudio.load("clean-code.mp3")
  File "/home/oandreeva/.local/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 256, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/home/oandreeva/.local/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 30, in _fail_load
    raise RuntimeError("Failed to load audio from {}".format(filepath))
RuntimeError: Failed to load audio from clean-code.mp3
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdcbfd12be0>
```
Could you please help with resolving this?

**Comment by jsoto-gladia** [comment] 2023-11-01 22:13
@mariano-at-gladia

**Comment by tanmayv25** [comment] 2023-11-02 00:00
Hi @jsoto-gladia @Thytu
You can confirm whether the output buffer is being released by running tritonserver with `--log-verbose=1`. The application should emit [this ](https://github.com/triton-inference-server/server/blob/main/src/http_server.cc#L1254-L1269) message for every buffer freed up.

As you are using the http endpoint and transferring the tensor data from the client API, we will use CPU memory for the output buffers. From the logs in reproducer, it seems that you are tracking the GPU memory. The GPU memory in model is usually dynamically allocated in pools and is not released until and unless the model gets unloaded. This is usually done to not incur memory allocation cost when new requests arrive to the backend. Can you try [explicitly loading and unloading the model](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_management.md#model-control-mode-explicit) and monitor the GPU memory usage?

**Comment by jsoto-gladia** [comment] 2023-11-02 07:48
hello
that might be it. We are not unloading the model at any time. So the gpu memory does not get freed

**Comment by krishung5** [comment] 2023-11-13 20:57
Closing issue due to lack of activity. Please re-open the issue if you would like to follow up with this issue.

**Closed by krishung5** 2023-11-13 20:57 UTC
