### ISSUE TITLE
WSL2 CUDA SHM support

### ISSUE THREAD

**Issue by bartengine27** [triton-inference-server/server#4434] opened 2022-05-26 10:48 UTC
Dear,

  Is CUDA shared memory supported on WSL2?

  Starting the Triton Server r22.04 docker and executing the simple_grpc_cudashm_client results in:
`
0 + 1 = 0
0 + 1 = 0
error: incorrect sum
`

The output of simple_grpc_infer_client looks correct:
`
0 + 1 = 1
0 - 1 = -1
1 + 1 = 2
1 - 1 = 0
2 + 1 = 3
...
`

Thanks,
Bart

**Comment by dyastremsky** [comment] 2022-05-26 17:19
Can you please fill out the bug template with full reproduction instructions (including details about which system you're running this on)? That'll provide more insight.

If there was an error using shared memory or similar, Triton would typically have thrown an error. We can take a look at the Triton side of things.

**Comment by bartengine27** [comment] 2022-05-27 09:07
Hi @dyastremsky 

  Thanks for the feedback!

  Bug template was filled out https://github.com/triton-inference-server/server/issues/4436.

Thanks,
Bart

**Comment by dyastremsky** [comment] 2022-05-27 17:30
Thanks, Bart! Closing out this ticket since that one has been filed.

**Closed by dyastremsky** 2022-05-27 17:30 UTC
