### ISSUE TITLE
Different result: ensemble_model vs. ensemble_client

### ISSUE THREAD

**Issue by flyingmrwang** [triton-inference-server/server#2275] opened 2020-11-20 03:38 UTC
**Description**
I am comparing the result of model resnet50_netdef in two ways: 
preprocess_resnet50_ensemble&ensemble_image_client.py vs. resnet50_netdef&image_client.py. 
The difference is too high. 
    0.861093 (162) = BEAGLE
    0.048462 (168) = REDBONE
    0.034542 (166) = WALKER HOUND
vs.
    0.880375 (162) = BEAGLE
    0.039533 (168) = REDBONE
    0.031060 (166) = WALKER HOUND
And for other model who outputs scores, rather than probability, the difference could be as high as 10%. 

**Triton Information**
r20.10 w/ docker

**To Reproduce**
Just run demo in two ways with scale method of INCEPTION (others should work the same)

**Expected behavior**
I guess the difference should comes from image processing part. So difference lower than 1% should be acceptable.
Besides, is there any lossy part in image loading, paring or normalization? And if this difference work as designed or a bug?

@GuanLuo @deadeyegoodwin Please have a look~

**Comment by GuanLuo** [comment] 2020-11-23 18:31
It is hard to tell as the preprocess part is implemented differently in two cases, one in C++ and one in Python. #1938 updated the scale in the C++ preprocessor but not the Python one, so that may be why you are observing the difference.

**Comment by flyingmrwang** [comment] 2020-11-24 02:25
@GuanLuo Just as you mentioned, preprocess in python is outdated and should be modify from 128 to 127.5. After that, the output changed slightly and there are still gap between two results. 
Currently, I just assume that this loss in accuracy is caused by preprocessing part. So I will dump the data in each nodes before input tensor. Does triton provide tools or options to debug? Or at least dump the input tensor

**Comment by GuanLuo** [comment] 2020-12-01 20:14
#2305 fixes the scaling value across our examples, that should eliminate some difference. Another thing to be considered is the rounding difference between transferring the data between models, so checking the output of the preprocessing part may expose the cause. For ensemble, since the preprocessing unit is itself a model, you can send request directly to the preprocessing unit and check on the response. For other example, since the preprocessing part is on the client side, you can check on the value with some changes on the client code.

**Comment by flyingmrwang** [comment] 2020-12-07 03:13
@GuanLuo Finally, I found that the difference is caused by different implementations of image decode and resize. Pillow(PIL) and opencv are used in two cases that I described. For image decoding (or say loading), two packages depends on different libjpeg which have slight difference in output. And for resize with bilinear interpolation, processing within Pillow and opencv are also not identical. So for me who train models with pytorch (Pillow inside), I would prefer Pillow to do preprocess when deploying. So maybe I should study python_backend or migrate preproc to client side.

**Comment by GuanLuo** [comment] 2020-12-07 17:43
Good to hear that you tracked down where the difference came from. Since there is intrinsic to the image processing library, there is nothing much we can do and it doesn't worth the time to make them exactly the same as they are just examples. Closing this ticket.

**Closed by GuanLuo** 2020-12-07 17:43 UTC
