### ISSUE TITLE
 Internal: An input of type 'Tensor?' was detected in the model. Only a single input of type Dict(str, Tensor) or input(s) of type Tensor are surpported

### ISSUE THREAD

**Issue by willamhou** [triton-inference-server/server#5195] opened 2022-12-24 13:45 UTC
Description
When trying to load my Triton model, I get an error saying that an input of type Tensor was detected in the model. The same model loads fine on previous versions of Triton (21.02-py3 and 21.03-py3) so I suspect this is a bug with the newer versions.
Triton Information
nvcr.io/nvidia/tritonserver:22.03-py3

Are you using the Triton container or did you build it yourself?
Using the container

Model Forward Function Like this:

![image](https://user-images.githubusercontent.com/8574759/209438712-1acaa422-e81a-4c63-b2af-09877ac59f99.png)

Model configuration file:

name: "classification"
platform:"pytorch_libtorch"
input [
        {
                name:"input__0"
                data_type: TYPE_INT32
                dims: [-1, -1]
        },
        {
                name: "input__1"
                data_type: TYPE_INT32
                dims: [-1, -1]
        },
        {
                name: "input__2"
                data_type: TYPE_BOOL
                dims: [-1, -1]
        },
        {
                name: "input__3"
                data_type: TYPE_BOOL
                dims: [-1, -1]
        },
        {
                name: "input__4"
                data_type: TYPE_INT32
                dims: [-1, 1]
        },
        {
                name: "input__5"
                data_type: TYPE_INT32
                dims: [-1, 1]
        },
	{
                name: "input__6"
                data_type: TYPE_BOOL
                dims: [1, 1]
        },
        {
                name: "input__7"
                data_type: TYPE_BOOL
                dims: [-1, 1]
        },
        {
                name: "input__8"
                data_type: TYPE_FP16
                dims: [-1, -1, -1]
        }

]
output [
    {
        name: "output__0"
        data_type:  TYPE_FP16
        dims: [-1, -1, -1]
    },
    {
        name: "output__1"
        data_type:  TYPE_FP16
        dims: [-1, -1, -1]
    }
]

I exported this model in TorchScript using scripting.

Expected behavior
The model should load correctly.

**Comment by krishung5** [comment] 2022-12-27 20:49
Hi @willamhou, would you be able to try with the latest release and see if this issue still occurs? We have some changes to Pytorch backend during these months and probably the issue got fixed in the middle. If the issue is not resolved, could you provide the full server log including the error message?

**Comment by dyastremsky** [comment] 2023-01-09 19:51
Closing due to lack of activity. Please let us know if you would like follow-up and we will reopen the ticket.

**Closed by dyastremsky** 2023-01-09 19:51 UTC
