### ISSUE TITLE
cpu memory increase constantly when serving model with triton-inference-server

### ISSUE THREAD

**Issue by luckycallor** [triton-inference-server/server#3033] opened 2021-06-22 09:20 UTC
**Description**
I am serving tensorflow savedmodel with triton-inference-server. While the server recieves requests, the cpu memory used creases constantly. The increasing speed seems related to the number of requests. If you request the server for long time, like several days, the increase is obvious.

**Triton Information**
I was using triton 21.03 from https://ngc.nvidia.com/catalog/containers/nvidia:tritonserver/tags 
and I tried triton 21.05, It seems having the same problem.

Are you using the Triton container or did you build it yourself?
I was using the Triton container from https://ngc.nvidia.com/catalog/containers/nvidia:tritonserver/tags 

**To Reproduce**
just serve a tensorflow savedmodel with triton inference server, and request the server constantly. After several hours, you can observe the cpu memory increases.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

I was using the efficientnet-b0 model. https://github.com/qubvel/efficientnet

**Expected behavior**
I expect the reason is found and the bug is fixed.

**Comment by tinghaoyu** [comment] 2021-06-22 09:40
I am facing the same problem when serving Bert

**Comment by tc-yue** [comment] 2021-06-22 09:43
same problems with me when serving onnx models which converted from transfsormers（hugging-face torch version）

**Comment by Tabrizian** [comment] 2021-06-22 15:01
@luckycallor Can you share the CPU memory increase chart? Some frameworks like tensorflow do not release the memory after the inference requests are complete.

**Comment by luckycallor** [comment] 2021-06-23 07:19
> @luckycallor Can you share the CPU memory increase chart? Some frameworks like tensorflow do not release the memory after the inference requests are complete.
The CPU memory increase chart is as following:
<img width="856" alt="企业微信截图_0b2a63ee-e827-4f6c-bba8-0b86011cca05" src="https://user-images.githubusercontent.com/11307624/123053092-1f193400-d436-11eb-89b8-25cbe97d57e2.png">

If the problem is caused by tensorflow, why there is no such problem when I serving the model with tfserving? @Tabrizian

**Comment by luckycallor** [comment] 2021-06-23 07:22
> @luckycallor Can you share the CPU memory increase chart? Some frameworks like tensorflow do not release the memory after the inference requests are complete.

@Tabrizian The CPU memory increase chart is as following:
<img width="659" alt="企业微信截图_f4fe4d95-fb8f-4de0-815d-474f1341f4b6" src="https://user-images.githubusercontent.com/11307624/123053693-bda59500-d436-11eb-97ba-2a854d88ddc7.png">

If the increase is caused by tensorflow, why there is no such problem when I serving the model with tfserving?

**Comment by luckycallor** [comment] 2021-06-23 07:32
> @luckycallor Can you share the CPU memory increase chart? Some frameworks like tensorflow do not release the memory after the inference requests are complete.

@Tabrizian The CPU memory increase chart in last 24h is as following:
<img width="671" alt="企业微信截图_cc611496-ea91-454e-bebf-47e8045c6d59" src="https://user-images.githubusercontent.com/11307624/123055081-1a557f80-d438-11eb-9baa-eb9efe7b5716.png">

If the increase is caused by tensorflow, why there is no such increase when I serving the model with tfserving?

**Comment by Tabrizian** [comment] 2021-06-23 15:48
Thanks for sharing the memory usage graph. It looks like this ticket needs more investigation. I have filed a bug against the dev team to look into this.

> If the increase is caused by tensorflow, why there is no such increase when I serving the model with tfserving?
What I meant by "not releasing the GPU memory" is that Tensorflow reuses the memory that they have allocated once (at least AFAIK).

**Comment by deadeyegoodwin** [comment] 2021-06-23 16:49
@luckycallor can you share the client script you are using to send requests to the server?

**Comment by luckycallor** [comment] 2021-06-24 07:04
> @luckycallor can you share the client script you are using to send requests to the server. Also can you share the model repository you are using so we can repro exactly. The model repo should include the config.pbtxt and the savedmodel files.

@deadeyegoodwin You can download the model repo and client script from the following google drive link https://drive.google.com/file/d/10u7QwCv0Vkfgvcpi2wTl95-SrvXPpLKS/view?usp=sharing

**Comment by luckycallor** [comment] 2021-06-28 07:17
@deadeyegoodwin @Tabrizian hello, is there any progress on this problem?

**Comment by Tabrizian** [comment] 2021-06-29 15:44
We are working on this. We'll let you know as soon as more information is available.

**Comment by krishung5** [comment] 2021-07-07 00:19
@luckycallor Thank you for sharing the script. Unfortunately, I couldn't reproduce it due to compute capability for GPU. Can you please reproduce the problem using a TF-only model (not including any TF-TRT components) or share the source code for the model so that I can generate the model without version compatibility errors, and further investigate with the latest version of Triton?

**Comment by krishung5** [comment] 2021-07-08 01:03
@luckycallor Hi, I've tried to repro this problem with the client script and model you shared. From the memory usage graph, memory growth was not observed.
[memory_growth_model_b0.log](https://github.com/triton-inference-server/server/files/6780757/memory_growth_model_b0.log)

**Comment by krishung5** [comment] 2021-07-09 22:49
Closing the issue. Feel free to re-open if you are still facing this problem.

**Closed by krishung5** 2021-07-09 22:49 UTC
Labels: bug, investigating

**Comment by luckycallor** [comment] 2021-07-22 02:32
> @luckycallor Hi, I've tried to repro this problem with the client script and model you shared. From the memory usage graph, memory growth was not observed.
> [memory_growth_model_b0.log](https://github.com/triton-inference-server/server/files/6780757/memory_growth_model_b0.log)

hello, from the log I can not tell whether the memory is increasing or not. In our obervatoion, the memory increase is relative to the num of requests. Can you test the memory with more requests and longer time?

**Comment by krishung5** [comment] 2021-07-28 01:19
Hi @luckycallor, the graph was the result of sending requests for 8 hours, and you can see that the memory usage was flat. The graph you shared showed consistent memory usage growth, and that could have been detected even if it was run only for 8 hours. FYI, this is what the graph looks like when memory growth is observed.
[memory_growth_example.txt](https://github.com/triton-inference-server/server/files/6889635/memory_growth_example.txt)

**Comment by wanghaohw** [comment] 2022-04-01 00:44
@luckycallor Hava you solved your problem?I find that sending  inferences with different bath_size  will cause similar problem to GPU memory.When I try a new batch_size, it will increase the GPU memory.
