### ISSUE TITLE
Does model should instantly free memory after unload?

### ISSUE THREAD

**Issue by alxmamaev** [triton-inference-server/server#4764] opened 2022-08-13 09:31 UTC
I tested the model repository protocol, which allows to load and unload models.
I was sequentially called load and unload requests, like:
```
POST v2/repository/models/${MODEL_NAME}/load
POST v2/repository/models/${MODEL_NAME}/unload
POST v2/repository/models/${MODEL_NAME}/load
POST v2/repository/models/${MODEL_NAME}/unload
POST v2/repository/models/${MODEL_NAME}/load
POST v2/repository/models/${MODEL_NAME}/unload
POST v2/repository/models/${MODEL_NAME}/load
POST v2/repository/models/${MODEL_NAME}/unload
```
Every time I loaded and unloaded the same model with the same version. Nothing was changed in the repository at this time.
The model backend was PyTorch, model is loaded on Host memory (CPU Instance)
I guessed that the total used memory would not change after the first load, but actually, that is not true. After every `unload` triton free a few memory, much smaller than was got on `load`, on each `load` triton takes more and more host memory.
So in a log way, it may cause Memory Error. Is that undefined behavior?

**Comment by dyastremsky** [comment] 2022-08-15 20:14
Which version of Triton is this for? We released a fix to the unload memory leak in 22.02 [here](https://github.com/triton-inference-server/server/pull/3868/). If it's an older version, could you try a more recent version of Triton see if this bug still exists?

**Comment by alxmamaev** [comment] 2022-08-15 20:43
@dyastremsky Im not shure about version, because I experimented with different containers versions, I'll check and give you actually information.

**Comment by 27359794** [comment] 2022-08-16 16:23
I've observed a memory leak when using Tensorflow models that follows the pattern you describe. The leak is still present in Triton r22.04 but is fixed in r22.07.

**Comment by dyastremsky** [comment] 2022-08-16 16:34
Thank you for providing additional context, @27359794.

That leak may be an unrelated issue, as it's a different backend. TensorFlow manages memory differently than most backends. You can see more information here, where a TensorFlow leak was investigated by our team: https://github.com/triton-inference-server/server/issues/4528#issuecomment-1171545476. You can generally expect TensorFlow not to release all memory, but it's caching memory allocator will only keep the memory at the "high water mark," so models that are loaded use the current unreleased yet available memory. If you have further questions, feel free to open a ticket with your reproduction instructions and context and we can discuss this further.

**Comment by dyastremsky** [comment] 2022-08-31 20:36
Closing due to inactivity. Let us know if you need follow-up and we can reopen the issue.

**Closed by dyastremsky** 2022-08-31 20:36 UTC
Labels: bug
