### ISSUE TITLE
Is there a way to shut down GPU/CPU memory fall back policy?

### ISSUE THREAD

**Issue by Oldpan** [triton-inference-server/server#2740] opened 2021-04-19 11:26 UTC
**Description**
When I start triton server with `cuda-memory-pool-byte-size` set to xxxx, but the gpu memory is not enough. So triton server will warn "CudaMemoryManager has not been created ，falling back to pinned system memory ",  triton server still start normally with warning. But when requests come the server will issue 'failed to create output buffer in GPU memory' and the request will not be OK. 

Is there a way to change the policy to make triton server shut down when get "CudaMemoryManager has not been created ，falling back to pinned system memory"? rather than start it. Thanks~

**Triton Information**
20.08 
built myself

**Comment by GuanLuo** [comment] 2021-04-19 17:31
We currently don't expose that option as CUDA memory pool is a performance feature, and Triton should work properly without it. The fallback is to make sure that some form of output buffer is available even if the requested memory type can't be satisfied.

So the issue is that the request is not being processed properly, do you mind to provide details regarding that? i.e. backend being used and repro steps.

**Comment by Oldpan** [comment] 2021-04-21 06:29
@GuanLuo Yes, I used custom backend and this is code:

```cpp
TRITONSERVER_Error*
TRITONBACKEND_ModelInstanceExecute(
    TRITONBACKEND_ModelInstance* instance, TRITONBACKEND_Request** requests,
    const uint32_t request_count)
{
...
        void* output_result_buffer;
        TRITONSERVER_MemoryType output_memory_type = TRITONSERVER_MEMORY_GPU;
        int64_t output_memory_type_id = 0;
        GUARDED_RESPOND_IF_ERROR(
            responses, r,
            TRITONBACKEND_OutputBuffer(
                output_result, &output_result_buffer, output_buffer_byte_size, &output_memory_type,
                &output_memory_type_id));
        if ((responses[r] == nullptr) ||
            (output_memory_type != TRITONSERVER_MEMORY_GPU)) {
            LOG_MESSAGE(                                                    
            TRITONSERVER_LOG_ERROR,                                       
            (std::string("failed to create output buffer in GPU memory")                         
                .c_str())); 
            GUARDED_RESPOND_IF_ERROR(
                responses, r,
                TRITONSERVER_ErrorNew(
                    TRITONSERVER_ERROR_UNSUPPORTED,
                    "failed to create output buffer in GPU memory"));
            continue;
        }
...
}
```
When GPU/CPU memory fall back policy is used, a request will  `failed to create output buffer in GPU memory`.

**Comment by GuanLuo** [comment] 2021-04-21 07:24
The fallback is not the reason why you are not getting output buffer on GPU memory. In fact, your backend must be able to handle any memory type returned by the `TRITONBACKEND_OutputBuffer()`, the initial value of `output_memory_type` and `output_memory_type_id` is the value preferred by the backend, the function will try to satisfy the preferred value, but it must return the buffer that the output will be in the response, so it may return any possible memory type and id pair.

Consider the case where the response will be sent via GRPC, where the response reside in system memory, even if the backend requests the output buffer to be in GPU, it doesn't make sense to return a GPU memory because it introduces an extra copy: copy from backend to GPU buffer, and then to CPU buffer in response. Instead it should return the buffer from the response directly, so your backend will then directly copy from backend to CPU buffer in response

**Closed** 2021-04-23 21:40 UTC
