### ISSUE TITLE
Perf_Analyzer always throwing 'std::length_error'

### ISSUE THREAD

**Issue by arnabdas** [triton-inference-server/server#4068] opened 2022-03-17 11:59 UTC
**Description**
We are trying `perf_analyzer` to profile our custom model for TTS with Triton. We are trying with various combinations of the options like the following.

``` bash
perf_client -m nemo_model1 -u $host:$port -i gRPC --concurrency-range 1:4:2
perf_client -m nemo_model1 -u "$host:$port" -i gRPC -v -v --input-data="random" --string-length 61
```
But every time we got the following error:

``` text
name: "nemo_model1"
versions: "1"
platform: "python"
inputs {
  name: "input__0"
  datatype: "BYTES"
  shape: -1
  shape: -1
}
outputs {
  name: "output__0"
  datatype: "INT16"
  shape: -1
  shape: -1
}

config {
  name: "nemo_model1"
  version_policy {
    latest {
      num_versions: 1
    }
  }
  max_batch_size: 128
  input {
    name: "input__0"
    data_type: TYPE_STRING
    dims: -1
  }
  output {
    name: "output__0"
    data_type: TYPE_INT16
    dims: -1
  }
  instance_group {
    name: "nemo_model1_0"
    count: 1
    gpus: 0
    kind: KIND_GPU
  }
  dynamic_batching {
    preferred_batch_size: 128
  }
  optimization {
    input_pinned_memory {
      enable: true
    }
    output_pinned_memory {
      enable: true
    }
  }
  backend: "python"
}

terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)
```

What are we doing wrong in invoking the command.

**Triton Information**
We are currently using `v2.8.0`.

Are you using the Triton container or did you build it yourself?
We have used the container 

``` bash
FROM nvcr.io/nvidia/tritonserver:21.03-py3

ADD models /models

# Setup Python
RUN apt update
RUN apt upgrade -y
RUN apt install -y software-properties-common libfreetype6-dev libsndfile-dev
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install -y python3-dev python3-venv
RUN /usr/bin/python3 -m pip install --upgrade pip

# Install NeMo
RUN pip install torch==1.10.1
ADD NeMo NeMo/
ADD nemo.patch NeMo/
WORKDIR NeMo
RUN patch -p1 < nemo.patch
RUN pip install .[tts]
WORKDIR ../
ENV PYTHONPATH=NeMo
# Copy hardcoded models
RUN mkdir models
COPY default_model/imda-only.txt default_model/imda-en_g2p.pt models/
RUN apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

CMD ["/opt/tritonserver/bin/tritonserver", "--model-repository=/models"]
```

Following is our model configuration file:

``` text
name: "nemo_model1"
backend: "python"
max_batch_size: 128
input {
    name: "input__0"
    data_type: TYPE_STRING
    dims: [-1]
  }
output [
  {
    name: "output__0"
    data_type: TYPE_INT16
    dims: [-1]
  }
]
dynamic_batching {}
instance_group {
      count: 1
      kind: KIND_GPU
  }
```

How to overcome the error with `perf_analyzer`. We are invoking `perf_analyzer` on a Ubuntu 20.04 node. We have installed the required dependencies. However for the following two packages, there were no matching candidate, so we installed the available packages for them.

``` bash
libopencv-dev=3.2.0+dfsg-4ubuntu0.1 \
libopencv-core-dev=3.2.0+dfsg-4ubuntu0.1 \
```

**Comment by dyastremsky** [comment] 2022-03-17 20:40
Could you provide a backtrace and reproduction instructions? Does the model load/infer normally when loaded onto Triton? If so, it may be an issue with the input data. The -z flag to send all zeros for the model often helps; otherwise, you may need to provide mock data.

This seems to be a model-specific issue, not an error originating from perf_analyzer or Triton. I don't know if it's relevant to the way you generated your model, but I see a similar bug discussion here for DeepSpeech: https://discourse.mozilla.org/t/error-when-trying-to-decode-terminate-called-after-throwing-an-instance-of-std-length-error/67967

**Comment by arnabdas** [comment] 2022-03-18 01:35
We are able to get audio output using python `tritonclient.grpc` [client](https://pypi.org/project/tritonclient/). However we are facing issues with the `perf_analyzer`. 

Also how to provide mock input for TTS perf analysis.

**Comment by dyastremsky** [comment] 2022-03-18 01:44
For providing mock input, please take a look here: https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md#input-data

**Comment by jbkyang-nvi** [comment] 2022-03-18 18:43
Also would be helpful if you could provide a backtrace of the dump!

**Comment by arnabdas** [comment] 2022-03-29 12:26
We have tried the following commands to run the `perf_analyzer`.

``` bash
perf_analyzer -m nemo_model1 -u $triton_host:$triton_port -i gRPC --input-data ./nemo_model1_input.json --shape [1, 33]
```

We have tried with the following variations of the `input.json`

```json
{
	"data": 
	[
		{ "input__0": ["Angry people are not always wise."] }
	]
}
```

and

```json
{
	"data": 
	[
		{ "input__0": ["A", "n", "g", "r", "y", " ", "p", "e", "o", "p", "l", "e", " ", "a", "r", "e", " ", "n", "o", "t", " ", "a", "l", "w", "a", "y", "s", " ", "w", "i", "s", "e", "."] }
	]
}
```

In both the cases we immediately got the following error:

``` bash
ubuntu@ip-10-0-0-216:~/code/triton_perf$ perf_analyzer -m nemo_model1 -u $triton_host:$triton_port -i gRPC --input-data ./nemo_model1_input.json --shape [1, 61]
terminate called after throwing an instance of "std::out_of_range"
  what():  basic_string::substr: __pos (which is 4) > this->size() (which is 3)
Aborted (core dumped)
```

Stacktrace of the core dump:

```text
ubuntu@ip-10-0-0-216:~/code/triton_perf$ perf_analyzer -m nemo_model1 -u $triton_host:$triton_port -i gRPC --input-data ./nemo_model1_input.json --shape [1, 61]
terminate called after throwing an instance of "std::out_of_range"
  what():  basic_string::substr: __pos (which is 4) > this->size() (which is 3)
Aborted (core dumped)
ubuntu@ip-10-0-0-216:~/code/triton_perf$ coredumpctl gdb -1
           PID: 3496 (perf_analyzer)
           UID: 1000 (ubuntu)
           GID: 1000 (ubuntu)
        Signal: 6 (ABRT)
     Timestamp: Tue 2022-03-29 10:42:24 UTC (11s ago)
  Command Line: perf_analyzer -m nemo_model1 -u breeze-voice-dev.coderuse.net:8001 -i gRPC --input-data ./nemo_model1_input.json --shape [1, 61]
    Executable: /home/ubuntu/.local/bin/perf_analyzer
 Control Group: /user.slice/user-1000.slice/session-3.scope
          Unit: session-3.scope
         Slice: user-1000.slice
       Session: 3
     Owner UID: 1000 (ubuntu)
       Boot ID: 88e9ae91d6bb4e62a4fd5776d1c3339a
    Machine ID: ec2c390a0f02aa18401e9b3af57fce36
      Hostname: ip-10-0-0-216
       Storage: /var/lib/systemd/coredump/core.perf_analyzer.1000.88e9ae91d6bb4e62a4fd5776d1c3339a.3496.1648550544000000000000.lz4
       Message: Process 3496 (perf_analyzer) of user 1000 dumped core.
                
                Stack trace of thread 3496:
                #0  0x00007fdaa481903b __GI_raise (libc.so.6 + 0x4303b)
                #1  0x00007fdaa47f8859 __GI_abort (libc.so.6 + 0x22859)
                #2  0x00007fdaa4bd0911 n/a (libstdc++.so.6 + 0x9e911)
                #3  0x00007fdaa4bdc38c n/a (libstdc++.so.6 + 0xaa38c)
                #4  0x00007fdaa4bdc3f7 _ZSt9terminatev (libstdc++.so.6 + 0xaa3f7)
                #5  0x00007fdaa4bdc6a9 __cxa_throw (libstdc++.so.6 + 0xaa6a9)
                #6  0x00007fdaa4bd33ab n/a (libstdc++.so.6 + 0xa13ab)
                #7  0x00007fdaa4c77f48 _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6substrEmm (libstdc++.so.6 + 0x145f48)
                #8  0x0000556cb5710c37 n/a (/home/ubuntu/.local/bin/perf_analyzer + 0xc7c37)
                #9  0x00007fdaa47fa0b3 __libc_start_main (libc.so.6 + 0x240b3)
                #10 0x0000556cb5717f0e n/a (/home/ubuntu/.local/bin/perf_analyzer + 0xcef0e)

GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/ubuntu/.local/bin/perf_analyzer...
(No debugging symbols found in /home/ubuntu/.local/bin/perf_analyzer)
[New LWP 3496]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `perf_analyzer -m nemo_model1 -u breeze-voice-dev.coderuse.net:8001 -i gRPC --in".
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

The `perf_analyzer` we got from [client release of Triton server](https://github.com/triton-inference-server/server/releases/tag/v2.8.0).

**Comment by arnabdas** [comment] 2022-03-30 04:37
We tested with specified `shape` input. Currently we are not getting the `core dump` error. But some other error is coming.

```bash
ubuntu@ip-10-0-0-216:~/code/triton_perf$ perf_analyzer -m nemo_model1 -u $triton_host:$triton_port -i gRPC --input-data ./nemo_model1_input.json --shape input__0:1,33
 Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: unexpected shape for input 'input__0' for model 'nemo_model1'. Expected [-1,-1], got [1,1,33]
```

#### nemo_model1_input.json
```json
{
	"data": 
	[
		{ "input__0": ["Angry people are not always wise."] }
	]
}
```

We can not use `-1,-1` for the shape input, as we are getting `error: input shape must be > 0`

**Comment by arnabdas** [comment] 2022-03-30 14:50
Thank you @Tabrizian for your reply.

With the new shape parameter also we are facing issues. We are using the same input file.

```bash
ubuntu@ip-10-0-0-216:~/code/triton_perf$ perf_analyzer -m nemo_model1 -u $triton_host:$triton_port -i gRPC --input-data ./nemo_model1_input.json --shape input__0:33
 Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: GRPC Execute Failed, message: Exception calling application: cannot reshape array of size 1 into shape (1,33)
```

**Comment by GuanLuo** [comment] 2022-03-30 21:41
@tanmayv25 can correct me if I am wrong. The `--shape` should be matching the `dims` in your input model config, so it should just need to be 1 dimension, and perf analyzer will handle the batch dimension for you. And from the `input.json` that you given, your input has only 1 element where the content is a string, so you should try `--shape input__0:1`. You can refer to the [perf analyzer doc](https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md#input-data) for more detail.

**Comment by arnabdas** [comment] 2022-03-31 05:18
Finally `perf_analyzer` worked for both `gRPC` and `HTTP`. We ran with `perf_analyzer -m nemo_model1 -u $triton_host:$triton_port -i gRPC --concurrency-range 1:5 --input-data ./nemo_model1_input.json --shape input__0:1 -v -f ./logs/perf__$(date +"%m_%d_%Y_T%T").csv`.

```bash
Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 5
  Pass [1] throughput: 8 infer/sec. Avg latency: 658760 usec (std 3665 usec)
  Pass [2] throughput: 7.8 infer/sec. Avg latency: 656371 usec (std 3270 usec)
  Pass [3] throughput: 8 infer/sec. Avg latency: 657867 usec (std 2605 usec)
  Client: 
    Request count: 40
    Throughput: 8 infer/sec
    Avg latency: 657867 usec (standard deviation 2605 usec)
    p50 latency: 656533 usec
    p90 latency: 662036 usec
    p95 latency: 662175 usec
    p99 latency: 664057 usec
    Avg gRPC time: 658176 usec (marshal 2 usec + response wait 658173 usec + unmarshal 1 usec)
  Server: 
    Inference count: 45
    Execution count: 18
    Successful request count: 18
    Avg request latency: 655925 usec (overhead 8 usec + queue 208823 usec + compute input 17 usec + compute infer 446566 usec + compute output 511 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 5, throughput: 8 infer/sec, latency 657867 usec
```

Thank you @Tabrizian , @GuanLuo , @dyastremsky

**Comment by GuanLuo** [comment] 2022-03-31 17:18
Glad to hear that. Closing as the issue has been resolved

**Closed by GuanLuo** 2022-03-31 17:18 UTC
Labels: bug
