### ISSUE TITLE
Segmentation fault (core dumped) on ensemble model from Triton (GPU) to Python Backend (CPU)

### ISSUE THREAD

**Issue by ivangtorre** [triton-inference-server/server#2475] opened 2021-02-01 09:49 UTC
**Description**
Error in ensemble model when postprocessing python backend on cpu from tensorrt GPU input
"Segmentation fault (core dumped)"

However, if I send the output from tensorrt to the client, and the resend back to the server it perfectly works. It seems to be something reported in previous issues and not completely solved, at least for tritonserver in jetpack 4.4:

https://github.com/triton-inference-server/python_backend/pull/30

**Triton Information**
triton server 2.6 for jetson.
I have built the last python backend which includes this last PR:

https://github.com/triton-inference-server/python_backend/pull/30

Are you using the Triton container or did you build it yourself?
I built myself .

**To Reproduce**

The config.pbtx
```
name: "ensemblePMG_basque"
platform: "ensemble"
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 1, -1 ]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "preprocess"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "INPUT0"
      }
      output_map {
        key: "FEATURES"
        value: "FEATURES"
      }
    },
    {
      model_name: "BasqueQ10x5"
      model_version: -1
      input_map {
        key: "FEATURES"
        value: "FEATURES"
      }
      output_map {
        key: "LOGITS"
        value: "LOGITS"
      }
    },
    {
      model_name: "greedy"
      model_version: -1
      input_map {
        key: "LOGITS"
        value: "LOGITS"
      }
      output_map {
        key: "OUTPUT0"
        value: "OUTPUT0"
      }
    }
  ]
}
```

Last logs before fail :
```
I0201 09:40:12.665871 14297 infer_request.cc:502] prepared: [0x0x7ee00840f0] request id: 1, model: BasqueQ10x5, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7ee0003968] input: FEATURES, type: FP32, original shape: [1,64,464], batch + shape: [1,64,464], shape: [1,64,464]
override inputs:
inputs:
[0x0x7ee0003968] input: FEATURES, type: FP32, original shape: [1,64,464], batch + shape: [1,64,464], shape: [1,64,464]
original requested outputs:
LOGITS
requested outputs:
LOGITS


I0201 09:40:12.665983 14297 python.cc:926] TRITONBACKEND_ModelInstanceExecute: model instance name preprocess_0 released 1 requests
I0201 09:40:12.666197 14297 plan_backend.cc:2322] Running BasqueQ10x5_0_0_gpu0 with 1 requests
I0201 09:40:12.666463 14297 plan_backend.cc:3207] Optimization profile default [0] is selected for BasqueQ10x5_0_0_gpu0
I0201 09:40:12.666887 14297 plan_backend.cc:2721] Context with profile default [0] is being executed for BasqueQ10x5_0_0_gpu0
I0201 09:40:12.689471 14297 infer_response.cc:139] add response output: output: LOGITS, type: FP32, shape: [1,232,37]
I0201 09:40:12.689572 14297 ensemble_scheduler.cc:509] Internal response allocation: LOGITS, size 34336, addr 0xf00e80000, memory type 2, type id 0
I0201 09:40:13.047937 14297 ensemble_scheduler.cc:524] Internal response release: size 34336, addr 0xf00e80000
I0201 09:40:13.048183 14297 infer_request.cc:502] prepared: [0x0x7f34038470] request id: 1, model: greedy, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f3400eca8] input: LOGITS, type: FP32, original shape: [1,232,37], batch + shape: [1,232,37], shape: [1,232,37]
override inputs:
inputs:
[0x0x7f3400eca8] input: LOGITS, type: FP32, original shape: [1,232,37], batch + shape: [1,232,37], shape: [1,232,37]
original requested outputs:
OUTPUT0
requested outputs:
OUTPUT0

I0201 09:40:13.048582 14297 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x101070090
Segmentation fault (core dumped)
```

**Comment by apekshapriya** [comment] 2021-02-01 10:54
Hey @ivangtorre, can you show me the folder structure of the two models and config for ensemble. 

I am trying to run two models in parallel. I have a config file which has a ensembling pipeline in the same form as you have mentioned above.  I have placed them in the following structure:

models:
         ensemble_model
                config.pbtxt(ensemble config as same as one above)
                model_A
                           1/model.plan
                           1/config.pbtxt
                model_B 
                            1/model.plan
                            1/config.pbtxt
       
I am running the server as below:
docker run --gpus all  --ipc=host  --rm -p8000:8000 -p8001:8001 -p8002:8002 -v models:/models nvcr.io/nvidia/tritonserver:20.11-py3 tritonserver --model-repository=/models --log-verbose=0   --strict-model-config=False

Unfortunately, the above folder structure is not correct and when I run this the server is not able to find model A and model B as given in the config file(models/ensemble_mode/config.pbtxt)

Using the example of your models name, can you give a sample folder structure for same?

Thanks in advance!

**Comment by ivangtorre** [comment] 2021-02-01 11:03
@apekshapriya the structure is as follows:
models/
        greedy/
             config.pbtx
             1/
                   model.py

        BasqueQ10x4/
             config.pbtx
             1/
                   model.plan

        preprocess/
             config.pbtx
             1/
                   model.py

**Comment by apekshapriya** [comment] 2021-02-01 11:30
Thanks @ivangtorre for giving the above folder structure of individual models and their config. 
How do you pass the above config file(not the individual configs but the one you have described in the top) that tells the pipeline of the whole ensembling. I mean where do you place the ensemble config with respect to the above folder structure. 

Apologies for bothering again.

**Comment by ivangtorre** [comment] 2021-02-01 11:33
@apekshapriya  just updated my previous comment. Hope it will be useful to you!

**Comment by apekshapriya** [comment] 2021-02-01 12:21
Thanks a lot @ivangtorre! It is able to load all the models now.

**Comment by Tabrizian** [comment] 2021-02-02 23:26
@ivangtorre Thanks for the report. I was not able to reproduce this issue on Jetson when the inputs are in GPU. Can you provide more details? It would be great if you can upload a zip file containing all the models that can be used to reproduce this issue.

**Comment by ivangtorre** [comment] 2021-02-03 07:20
@Tabrizian I will work in a minimal example and upload it on the following days. Thanks for the support

**Comment by Tabrizian** [comment] 2021-02-09 21:29
There was a PR merged recently to fix a problem in the TensorRT backend that may be probably related to this. Can you try the latest version of `server` repo to see whether it fixes your problem or not?

https://github.com/triton-inference-server/server/pull/2348

**Comment by ivangtorre** [comment] 2021-02-10 13:30
Hi @Tabrizian i will try it again and keep informed in the following days

**Comment by Tabrizian** [comment] 2021-03-16 15:28
Closing. Reopen if you still saw the issue.

**Closed by Tabrizian** 2021-03-16 15:28 UTC
