### ISSUE TITLE
Error in using S3-Compatible Storage [Oracle Cloud Infrastructure (OCI) Object Storage]

### ISSUE THREAD

**Issue by chandrameenamohan** [triton-inference-server/server#2493] opened 2021-02-06 04:24 UTC
**Description**
I am trying to use Oracle OCI Object storage. As it is a S3-Compatible: https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm. I am getting error to use. I think it is may be along with hostname you expect the port number.

**Triton Information**
nvcr.io/nvidia/tensorrtserver:20.10-py3

Are you using the Triton container or did you build it yourself?
I am using the Triton container

**To Reproduce**
Steps to reproduce the behavior.
Start the docker server:

docker run --shm-size=1g --ulimit memlock=-1 -p 8000:8000 -p 8001:8001 -p 8002:8002 -e AWS_ACCESS_KEY_ID=<access-key>-e AWS_SECRET_ACCESS_KEY=<secret-key> -e AWS_REGION=<region-name> --ulimit stack=67108864 -ti nvcr.io/nvidia/tritonserver:20.10-py3

Running triton server
tritonserver --model-repository=s3://mynamespace.compat.objectstorage.us-phoenix-1.oraclecloud.com:/triton-repo

Got this erro:
error: creating server: Internal - Could not get MetaData for bucket with name objectstorage.region-identifier.oraclecloud.com:

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
I expect it to work even when I don't provide the port number as I don't know what is the port number of the endpoint of oci object storage. If you see this example it is not require to provide port number to create the AWS S3 Client: 

`import boto3
  
s3 = boto3.resource(
    's3',
    aws_access_key_id="gQ4+YC530sBa8qZI6WcbUbtH8oar0exampleuniqueID",
    aws_secret_access_key="7fa22331ebe62bf4605dc9a42aaeexampleuniqueID",
    region_name="us-phoenix-1", # Region name here that matches the endpoint
    endpoint_url="https://mynamespace.compat.objectstorage.us-phoenix-1.oraclecloud.com" # Include your namespace in the URL
)
  
for bucket in s3.buckets.all():
    print bucket.name`

You can find this example here:https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm

UPDATE: I tried it with '443' port number but still go the same error;

**Comment by CoderHam** [comment] 2021-02-08 19:59
@chandrameenamohan You should not get the same error i.e. 
```
error: creating server: Internal - Could not get MetaData for bucket with name objectstorage.region-identifier.oraclecloud.com:
````

When you specify the s3 repo as (note that the port is specified)
tritonserver --model-repository=s3://mynamespace.compat.objectstorage.us-phoenix-1.oraclecloud.com:443/triton-repo

Additionally when using non-AWS hosted s3 repos i.e. whenever a host is specified, we do require the port to be specified as well since each provider need not use the AWS S3 default of 443. This is enforced by the regex as well which is why you see the error stated above. The error would be different when the port is specified. 

I would double check to ensure the port is correct and share the error with the port specified.

**Comment by CoderHam** [comment] 2021-02-10 21:04
@chandrameenamohan any update on the same?

**Comment by chandrameenamohan** [comment] 2021-02-11 16:31
@CoderHam Thanks for the reply. I tried with the port:443 but it did not work for me. I got the error: "creating server: Internal - Could not get MetaData for bucket with triton-repo". 
OCI does not explicitly tell if there is another port number hence I do not know if other than 443 there exist another one. 

As I mentioned above example of python code. If you see it works for me find for non-aws S3 provider. I don't need to provide port number there. Can we have solution which inspire from the python code. I use aws boto library.

**Comment by CoderHam** [comment] 2021-02-22 18:03
@chandrameenamohan I have not been able to get access to the Oracle S3 but it looks like the issue could be not passing the AWS credentials to Triton correctly. Could you confirm you are setting the environment variables correctly?
https://github.com/triton-inference-server/server/blob/master/docs/model_repository.md#s3
You must either use `aws config` or set the environment variables correctly.

**Comment by CoderHam** [comment] 2021-02-22 19:34
@chandrameenamohan can you also confirm that the boto3 python example you shared was run inside the container or outside the triton container?

**Comment by chandrameenamohan** [comment] 2021-02-23 00:50
I had similar issue when I was trying to use the MLFlow Tracking Server: https://www.mlflow.org/docs/latest/tracking.html#artifact-stores.  I was using [Oracle Object Storage](https://docs.oracle.com/en-us/iaas/Content/Object/Concepts/objectstorageoverview.htm) (S3-compatible). I wanted to Oracle Object Storage for Artifact store. I have needed to follow the same environment settings as triton server. The MLFlow asks for one more environment variable: "To store artifacts in a custom endpoint, set the MLFLOW_S3_ENDPOINT_URL to your endpoint’s URL". It works fine for MLFlow.
 
How does triton figure out the custom s3 endpoint if it is not provided explicitly? Because endpoint for AmazonS3 does not work here. 

I run the the boto3 python code outside and inside the container; it works fine for me; Pasting my code again here:

```
import boto3

s3 = boto3.resource(
's3',
aws_access_key_id="gQ4+YC530sBa8qZI6WcbUbtH8oar0exampleuniqueID",
aws_secret_access_key="7fa22331ebe62bf4605dc9a42aaeexampleuniqueID",
region_name="us-phoenix-1", # Region name here that matches the endpoint
endpoint_url="https://mynamespace.compat.objectstorage.us-phoenix-1.oraclecloud.com" # Include your namespace in the URL
)

# Print out the bucket names
for bucket in s3.buckets.all():
    print(bucket.name)
```

**Comment by CoderHam** [comment] 2021-02-23 01:50
The endpoint url is extracted from the s3 model repository path. For example if the path is specified as 
```
tritonserver --model-repository=s3://mynamespace.compat.objectstorage.us-phoenix-1.oraclecloud.com:443/demo-bucket
```
then the endpoint is `mynamespace.compat.objectstorage.us-phoenix-1.oraclecloud.com:443`

https://github.com/triton-inference-server/server/blob/master/docs/model_repository.md#s3
> For a local or private instance of S3, the prefix s3:// must be followed by the host and port (separated by a semicolon) and subsequently the bucket path.

While MLflow may ask for an additional env variable we extract the same from the environment variable.

**Comment by chandrameenamohan** [comment] 2021-02-23 07:25
I have provided the correct credentials and still got the same error. I tested to check what error I get if I provide wrong credentials. I got the same error again. I think this error message needs to be more specific to the problem. As it gives same error if I provide even wrong region or wrong endpoint name (ex: ax3dvjxgkemg.compat.objectstorage.us-ashburn-1.oraclebadal.com:443) 

Is there any code we try to verify if tritonserver is able to connect to object storage? There is this one - https://github.com/triton-inference-server/server/blob/b6224aeced03f554dd9040e769e53a9da276be32/qa/L0_storage_S3/test.sh but if there is any simple and small script to verify.

**Comment by CoderHam** [comment] 2021-02-23 18:34
Yes, I agree the error messages from the server should be more descriptive. I will work on fixing the same. Can you run the test you were with boto3 directly with [aws-cli](https://aws.amazon.com/cli/) instead?

**Comment by chandrameenamohan** [comment] 2021-02-24 14:24
I installed the cli in nvidia triton server 20.10 docker image. I created .aws/config and .aws/credential files. I tried with aws-cli and it worked for me :).
I ran this command:
`aws --endpoint-url https://namespace.compat.objectstorage.us-ashburn-1.oraclecloud.com s3api get-object --bucket model-bucket --key dir/config.pbtxt config.pbtxt`

I did not require to provide any port number here. 

Is there option in triton-server to run some script which can download the models from respective cloud? If it is not there then good to have as you may not be able to add support for every cloud services but this could help many.

**Comment by CoderHam** [comment] 2021-02-24 20:09
I added some verbose error reporting for s3 which can help you zero in on the issue: https://github.com/triton-inference-server/server/pull/2557 you can apply the patch from here and confirm. Additionally 20.10 is old now and I would recommend moving up to the latest release.  
You can follow the build instructions from [here](https://github.com/triton-inference-server/server/blob/master/docs/build.md).

Since I do not have access to an Oracle S3 storage I would appreciate your help in triaging the issue.

**Comment by chandrameenamohan** [comment] 2021-02-26 09:38
Sure. I will check and let you know.

**Comment by CoderHam** [comment] 2021-03-05 20:59
@chandrameenamohan were you able to run Triton with the S3 patch?

**Comment by chandrameenamohan** [comment] 2021-03-07 06:37
Hey,

I tried to build the image with the new patch but I was getting error to build the docker image. I did not get the time to debug the error. Is there a way you build the image and I will download it and use it to verify.

**Comment by CoderHam** [comment] 2021-03-08 06:04
I do not have a way of sharing the image for you. Is there a reason for building the image on macOS? Our build process and instructions is clearly detailed [here](https://github.com/triton-inference-server/server/blob/master/docs/build.md). If you wish to build on an unsupported platform there are some instructions for that in the document as well.

However I recommend the docker build process as it would the quickest way to get a working Triton version for x86-64 Ubuntu 20.4

**Comment by chandrameenamohan** [comment] 2021-03-18 07:25
I am also not getting time to build this image. I can do it as your change include in next version. Is it available in 21.02 version?

**Comment by CoderHam** [comment] 2021-03-24 18:51
@chandrameenamohan can you share your email addresses with me so I can share the latest master build for you to test on?
It contains verbose logging for S3 Storage and could help you understand the cause of the issue better.

**Comment by chandrameenamohan** [comment] 2021-03-25 02:34
sure. chandrameenamohan@gmail.com

**Comment by CoderHam** [comment] 2021-04-13 19:34
@chandrameenamohan did you get a chance to test the docker image? I am waiting on you to share the verbose log errors you see to be able to triage this issue.

**Comment by CoderHam** [comment] 2021-04-20 21:45
@chandrameenamohan thanks for getting back to us. We look forward to hearing back from you so we can proceed with resolving any potential issues with OCI S3 support.

**Comment by kommons** [comment] 2021-05-04 07:08
@chandrameenamohan Any updates?

**Comment by chandrameenamohan** [comment] 2021-05-04 12:06
Will be able to check and provide in next week.

**Comment by CoderHam** [comment] 2021-05-18 20:26
We have a couple fixes (#2879 and #2880) that should solve your issue. Feel free to try a build out these patches and get back to us with your feedback. 
Closing this ticket. Please let us know if you still face the problem.

**Closed by CoderHam** 2021-05-18 20:26 UTC

**Comment by chandrameenamohan** [comment] 2021-05-19 06:21
Which version they are will be available?

**Comment by CoderHam** [comment] 2021-05-19 14:54
You can also rebuild from source. The NGC image for 21.06 should have this fix.

**Comment by okyspace** [comment] 2021-07-13 09:13
@CoderHam , how do we trigger triton to give the more specific S3 related error like what you mentioned above?
