### ISSUE TITLE
HTTP Triton client is giving gevent error when called concurrently, greenlet.error: cannot switch to a different thread

### ISSUE THREAD

**Issue by AntonioTannoury** [triton-inference-server/server#6650] opened 2023-11-30 15:03 UTC
**Description**
I created an HTTP triton client for a sequence classification model. I works great when calling it normally without concurrent requests. But when using concurrence library to call the client many times concurrently, a greenlet error pops, "**_greenlet.error: cannot switch to a different thread (which happens to have exited)_**".

**Triton Information**
22.05 docker container

**To Reproduce**
The is the script of the client:
```
class TritonTopicClassificationClient:
      def __init__(self, config: TritonRequestConfig):
          self.triton_client = httpclient.InferenceServerClient(url="0.0.0.0:8000", concurrency=32)
          self.config = config.__dict__

    def infer(self, input, request_id = str(uuid.uuid4()), batchsize=64):
        if isinstance(input, str):
            input = [input]
        elif isinstance(input, np.ndarray):
            input = list(input)
        elif isinstance(input, list):
            pass
        else:
            raise (
                InferenceServerException(
                    f"Data format not supported, expected sting or list/numpy_array of strings, got {type(input)}"
                )
            )
        results = []
        for i in tqdm(range(0, len(input), batchsize)):
            inputs = []
            outputs = []

            batch = np.array([input[i : i + batchsize]], dtype=np.object_)
            inputs.append(
                httpclient.InferInput("INPUT_TEXT", list(batch.shape), "BYTES")
            )
            inputs[0].set_data_from_numpy(batch)

            outputs.append(
                httpclient.InferRequestedOutput("JSON_OUTPUT", binary_data=False)
            )
            batch_results = self.triton_client.async_infer(
                inputs=inputs,
                outputs=outputs,
                request_id=request_id,
                **self.config,
            )
            batch_results_outputs = batch_results.get_result().get_response()["outputs"][0]["data"]
            batch_response = [json.loads(i) for i in batch_results_outputs]
            results += batch_response

        return results

```
**Concurrent requests code**

```
import concurrent.futures
from tritoninference import TritonTopicClassificationClient, TritonRequestConfig

config = TritonRequestConfig(
    model_name="topic_pipeline", model_version="1"
)
topic_client = TritonTopicClassificationClient(config=config)

def ask_question(question):
    emb_resp = topic_client.infer(question)
    return emb_resp

questions = ["What is the meaning of life?", "How does photosynthesis work?", "Tell me a joke."]*3

# Using ThreadPoolExecutor to run functions concurrently
with concurrent.futures.ThreadPoolExecutor() as executor:
    for question in questions:
        future = executor.submit(ask_question, question)
```

**Expected behavior**
I expect the client to work concurrently since async_infer was used with concurrency=32 which is higher than the number of requests send concurrently (9 requests)

**Comment by kthui** [comment] 2023-11-30 22:46
Hi @AntonioTannoury, the HTTP Python client is not thread safe. See https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/http/_client.py#L100-L106

You will have to initialize one client per thread for it to be used in multi-threaded environment. For example, with a concurrency of 32, the client should be initialized 32 times.

Alternatively, the [gRPC Python client](https://github.com/triton-inference-server/client/tree/main#grpc-options) is thread safe, or you may try the [HTTP AsyncIO Python client](https://github.com/triton-inference-server/client/tree/main#python-asyncio-support-beta) which does not use threads.

**Comment by AntonioTannoury** [comment] 2023-12-01 12:19
Hello @kthui, thanks for the note on the HTTP client, and it's working fine when I initalize the client every time i call the infer method. 
All good

**Comment by krishung5** [comment] 2024-02-09 01:38
Closing as the issue is resolved.

**Closed by krishung5** 2024-02-09 01:38 UTC
Labels: question

**Comment by Getvalue-automotive** [comment] 2025-01-29 13:35
@kthui https://pythoner.space/questions/python-end-all-threadpoolexecutor-tasks-if-a-single-one-encounters-an-error
