### ISSUE TITLE
image_client.py example is broken for multiple classification outputs

### ISSUE THREAD

**Issue by rgov** [triton-inference-server/server#4310] opened 2022-04-29 15:07 UTC
I am running Triton via the NGC container version 22.04 (which I take to be 2.21.0) and the Python `tritonclient` module version 2.21.0 on Python 3.9.12. I am using the `densenet_onnx` example model from the 2.20.0 tag of this repository.

When I run the command in the Quick Start tutorial, I get an error:

```
$ python image_client.py -m densenet_onnx -c 3 -s INCEPTION ./mug.jpg
Request 1, batch size 1
Traceback (most recent call last):
  File "image_client.py", line 475, in <module>
    postprocess(response, output_name, FLAGS.batch_size, max_batch_size > 0)
  File "image_client.py", line 191, in postprocess
    raise Exception("expected {} results, got {}".format(
Exception: expected 1 results, got 3
```

This is affected by the `-c 3` argument; if I pass `-c 1` then the error goes away.

The assertion checks for one output per input, but in this case for the `densenet_onnx` classification model there are multiple outputs (the top N classifications).

Removing the assertion works fine:

```
Request 1, batch size 1
    13.915170 (504) = COFFEE MUG
    12.018229 (968) = CUP
    9.839116 (967) = ESPRESSO
PASS
```

**Comment by rmccorm4** [comment] 2022-05-03 22:36
Hi @rgov ,

The C++ image_client example (the one mentioned in the quickstart) should work, just tested it:
```
root@RMCCORMICK:/workspace/# image_client -m densenet_onnx -c 10 -s INCEPTION ./mug.jpg
Request 0, batch size 1
Image './mug.jpg':
    15.349614 (504) = COFFEE MUG
    13.227508 (968) = CUP
    10.424984 (505) = COFFEEPOT
    10.369593 (967) = ESPRESSO
    10.053366 (725) = PITCHER
    9.669193 (899) = WATER JUG
    9.096707 (849) = TEAPOT
    8.861099 (901) = WHISKEY JUG
    8.656436 (647) = MEASURING CUP
    8.589909 (438) = BEAKER
```

Looks like there's a bug in the `image_client.py` though. The issue is that the `densenet_onnx` model has a fixed batch size, so specifying a batch size on the CLI doesn't make sense and the shapes being compared get mixed up. If you try the `inception_graphdef` model instead, the python image_client.py should work as expected.

I'll take a look at fixing the example to account for fixed batch size.

**Comment by rmccorm4** [comment] 2022-05-04 17:55
Hi @rgov , this should be fixed on `main` branch now as of PR above. Thanks for reporting.

**Closed** 2022-05-04 17:55 UTC
Labels: bug
