### ISSUE TITLE
protobuf version issue

### ISSUE THREAD

**Issue by roychou121** [triton-inference-server/server#3601] opened 2021-11-23 05:07 UTC
build the triton server cmd :
```
./build.py --no-container-build --cmake-dir=/home/roy/Documents/triton_2170/server/build --build-dir=/home/roy/Documents/triton_2170/roy --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --backend=ensemble
```

When I finished building triton server (without Docker), I got the following error while executing the tritonserver.

`[libprotobuf FATAL /home/roy/Documents/triton/roy/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/stubs/common.cc:86] This program was compiled against version 3.7.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.8.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/workspaces/dcgm-rel_dcgm_2_0-postmerge/_out/build/Linux-amd64-release/common/protobuf/dcgm.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.7.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.8.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/workspaces/dcgm-rel_dcgm_2_0-postmerge/_out/build/Linux-amd64-release/common/protobuf/dcgm.pb.cc".)
Aborted (core dumped)
`

**Comment by GuanLuo** [comment] 2021-11-29 18:49
The issue is that Triton is building against a specific protobuf version (see [CMakeLists.txt](https://github.com/triton-inference-server/third_party/blob/main/CMakeLists.txt#L147-L175)) and it usually links the static version of the built protobuf to resolve protobuf symbols at compile time. When you have previously installed protobuf, it links with the installed version (which only comes with protobuf shared library) and causes version mismatch at runtime.

The quick solution will be building Triton in docker container so the installed protobuf on host machine will not interfere the build, or you will have to configure CMake so it first discovers the protobuf compiled along with Triton build

**Comment by Tabrizian** [comment] 2021-12-13 22:26
Closing due to in-activity. Feel free to re-open if the issue persists.

**Closed by Tabrizian** 2021-12-13 22:26 UTC

**Comment by ahmednofal** [comment] 2023-04-10 16:19
I am having the same issue while exploring the Server API (In-Process C API), via building a client that links against libtritonserver.so in a docker container based off nvcr.io/nvidia/tritonserver:22.11-py3 image.

here is the output I see.

`[libprotobuf FATAL /opt/client/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/stubs/common.cc:83] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.4).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.4).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
Aborted (core dumped)`

thank you.
