### ISSUE TITLE
Memory Leak When Using Python/TensorRT Backend

### ISSUE THREAD

**Issue by chienkan** [triton-inference-server/server#6038] opened 2023-07-09 06:40 UTC
**Description**
Using Triton v23.03 with Python/TensorRT Backend (image from Nvidia Container Registry) and performing the inference with dynamic input size, there seems to be a memory leak: memory usage increases with requests, finally leading to an OOM for the Triton Inference Server instance.

**Triton Information**
What version of Triton are you using? **v23.03**

Are you using the Triton container or did you build it yourself? **I build the server with C API refer to [the official concurrency example](https://github.com/triton-inference-server/server/tree/v2.32.0/docs/examples/jetson/concurrency_and_dynamic_batching) with the Python and TensorRT backends in the official docker image nvcr.io/nvidia/tritonserver:23.03-py3.**

**To Reproduce**
Steps to reproduce the behavior.
1. Start the server to host the **Business Logic Scripting**
2. Send 2000+ inference requests with C API
3. Watch the memory usage of Triton Inference Server to increase

Model configuration file:
```proto
name: "pipeline"
backend: "python"
max_batch_size: 1
input [
  {
    name: "INPUT_0"
    data_type: TYPE_UINT8
    dims: [ -1, -1, 3 ]
  }
]
output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [ -1, 7 ]
  }
]

instance_group [
  { 
    kind: KIND_CPU 
    count: 1
  }
]
```

**Expected behavior**

Nvidia Triton Inference Server should not allow for the OOM. Memory should be freed after the inference request is performed.

How can I fix this issue?

**Comment by chienkan** [comment] 2023-07-12 09:03
I use **tcmalloc** instead of malloc refer to the release notes, then it fixed.

**Comment by chienkan** [comment] 2023-07-24 03:58
It seems that the problem has not been fully solved :(
When using **tcmalloc** the Triton Inference Server instance still comes to an OOM with 10000+ inference request.
This situation occurs sporadically, approximately once in every ten times. The following is the crash log:
```
Operating system: Linux
                  0.0.0 Linux 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64
CPU: amd64
     family 6 model 140 stepping 1
     1 CPU

GPU: UNKNOWN

Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x0
Process uptime: not available

Thread 451 (crashed)
 0  libtcmalloc.so.4 + 0x26fd3
    rax = 0x000000000000001a   rdx = 0x0000000000000000
    rcx = 0x000000000000001b   rbx = 0x0000000000000020
    rsi = 0x000055df90ab3d00   rdi = 0x00007f0e98d24e20
    rbp = 0x000055df73e8a4a0   rsp = 0x00007f0ce6e77470
     r8 = 0x0000000000000003    r9 = 0x000055df73e8a440
    r10 = 0x00000002aefc0000   r11 = 0x000000000000001b
    r12 = 0x000055df73e8a440   r13 = 0x0000000000000400
    r14 = 0x0000000000000020   r15 = 0x00007f0e98d25c60
    rip = 0x00007f0e98b79fd3
    Found by: given as instruction pointer in context
 1  libtcmalloc.so.4 + 0x27350
    rsp = 0x00007f0ce6e774b0   rip = 0x00007f0e98b7a350
    Found by: stack scanning
 2  libtritonserver.so + 0x1de53d
    rsp = 0x00007f0ce6e774d0   rip = 0x00007f0e853f153d
    Found by: stack scanning
 3  libtriton_python.so + 0x78bc9
    rsp = 0x00007f0ce6e77550   rip = 0x00007f0e7423abc9
    Found by: stack scanning
 4  libtritonserver.so + 0x241ccb
    rsp = 0x00007f0ce6e775c0   rip = 0x00007f0e85454ccb
    Found by: stack scanning
 5  libtritonserver.so + 0x25238b
    rsp = 0x00007f0ce6e776a0   rip = 0x00007f0e8546538b
    Found by: stack scanning
 6  libtriton_python.so + 0x76bc1
    rsp = 0x00007f0ce6e776f0   rip = 0x00007f0e74238bc1
    Found by: stack scanning
 7  libtriton_python.so + 0x76b84
    rsp = 0x00007f0ce6e77700   rip = 0x00007f0e74238b84
    Found by: stack scanning
 8  libtriton_python.so + 0x651b1
    rsp = 0x00007f0ce6e77750   rip = 0x00007f0e742271b1
    Found by: stack scanning
 9  libtriton_python.so + 0x7131f
    rsp = 0x00007f0ce6e777b0   rip = 0x00007f0e7423331f
    Found by: stack scanning
10  libtriton_python.so + 0x410d0
    rsp = 0x00007f0ce6e777c8   rip = 0x00007f0e742030d0
    Found by: stack scanning
11  libtcmalloc.so.4 + 0x23020
    rsp = 0x00007f0ce6e777d0   rip = 0x00007f0e98b76020
    Found by: stack scanning
12  libtcmalloc.so.4 + 0x27005
    rsp = 0x00007f0ce6e77800   rip = 0x00007f0e98b7a005
    Found by: stack scanning
13  libtriton_python.so + 0x3a3d9
    rsp = 0x00007f0ce6e77880   rip = 0x00007f0e741fc3d9
    Found by: stack scanning
14  triton_python_backend_shm_region_12 + 0x32d1960
    rsp = 0x00007f0ce6e77898   rip = 0x00007f0c712e9960
    Found by: stack scanning
15  triton_python_backend_shm_region_12 + 0x32cee50
    rsp = 0x00007f0ce6e778a8   rip = 0x00007f0c712e6e50
    Found by: stack scanning
16  triton_python_backend_shm_region_12 + 0x32d1ab0
    rsp = 0x00007f0ce6e778f8   rip = 0x00007f0c712e9ab0
    Found by: stack scanning
17  triton_python_backend_shm_region_12 + 0x32d1b20
    rsp = 0x00007f0ce6e77908   rip = 0x00007f0c712e9b20
    Found by: stack scanning
18  libtriton_python.so + 0x39420
    rsp = 0x00007f0ce6e77948   rip = 0x00007f0e741fb420
    Found by: stack scanning
19  libtriton_python.so + 0x41170
    rsp = 0x00007f0ce6e77998   rip = 0x00007f0e74203170
    Found by: stack scanning
20  libtriton_python.so + 0x5ecc0
    rsp = 0x00007f0ce6e779a0   rip = 0x00007f0e74220cc0
    Found by: stack scanning
21  libtriton_python.so + 0x5eb70
    rsp = 0x00007f0ce6e779f0   rip = 0x00007f0e74220b70
    Found by: stack scanning
22  libtriton_python.so + 0x5ebd8
    rsp = 0x00007f0ce6e77a10   rip = 0x00007f0e74220bd8
    Found by: stack scanning
23  libtriton_python.so + 0x410d0
    rsp = 0x00007f0ce6e77a18   rip = 0x00007f0e742030d0
    Found by: stack scanning
24  libtriton_python.so + 0x5eb70
    rsp = 0x00007f0ce6e77a20   rip = 0x00007f0e74220b70
    Found by: stack scanning
25  triton_python_backend_shm_region_12 + 0x32d1ab0
    rsp = 0x00007f0ce6e77a28   rip = 0x00007f0c712e9ab0
    Found by: stack scanning
26  libtriton_python.so + 0x410d0
    rsp = 0x00007f0ce6e77a48   rip = 0x00007f0e742030d0
    Found by: stack scanning
27  libtriton_python.so + 0x5eb70
    rsp = 0x00007f0ce6e77a50   rip = 0x00007f0e74220b70
    Found by: stack scanning
28  triton_python_backend_shm_region_12 + 0x32d1960
    rsp = 0x00007f0ce6e77a58   rip = 0x00007f0c712e9960
    Found by: stack scanning
29  libtriton_python.so + 0x5eb70
    rsp = 0x00007f0ce6e77a80   rip = 0x00007f0e74220b70
    Found by: stack scanning
30  libtriton_python.so + 0x413f0
    rsp = 0x00007f0ce6e77aa8   rip = 0x00007f0e742033f0
    Found by: stack scanning
31  libtriton_python.so + 0x43e90
    rsp = 0x00007f0ce6e77ab0   rip = 0x00007f0e74205e90
    Found by: stack scanning
32  libtriton_python.so + 0x3b0bf
    rsp = 0x00007f0ce6e77b10   rip = 0x00007f0e741fd0bf
    Found by: stack scanning
33  libtriton_python.so + 0x41cfd
    rsp = 0x00007f0ce6e77b70   rip = 0x00007f0e74203cfd
    Found by: stack scanning
34  libstdc++.so.6 + 0xd5c20
    rsp = 0x00007f0ce6e77b90   rip = 0x00007f0e9812ec20
    Found by: stack scanning
35  libpthread.so.0 + 0x114df
    rsp = 0x00007f0ce6e77ba0   rip = 0x00007f0e9839d4df
    Found by: stack scanning
36  libpthread.so.0 + 0x11530
    rsp = 0x00007f0ce6e77ba8   rip = 0x00007f0e9839d530
    Found by: stack scanning
37  libtriton_python.so + 0x2b447
    rsp = 0x00007f0ce6e77bf0   rip = 0x00007f0e741ed447
    Found by: stack scanning
38  libtriton_python.so + 0x41cd0
    rsp = 0x00007f0ce6e77c28   rip = 0x00007f0e74203cd0
    Found by: stack scanning
39  libtriton_python.so + 0x2a840
    rsp = 0x00007f0ce6e77c68   rip = 0x00007f0e741ec840
    Found by: stack scanning
40  libtriton_python.so + 0x3b050
    rsp = 0x00007f0ce6e77c70   rip = 0x00007f0e741fd050
    Found by: stack scanning
41  libtriton_python.so + 0x4b83c
    rsp = 0x00007f0ce6e77ca0   rip = 0x00007f0e7420d83c
    Found by: stack scanning
42  libpthread.so.0 + 0xf260
    rsp = 0x00007f0ce6e77cc0   rip = 0x00007f0e9839b260
    Found by: stack scanning
43  libpthread.so.0 + 0xf050
    rsp = 0x00007f0ce6e77d08   rip = 0x00007f0e9839b050
    Found by: stack scanning
44  libtriton_python.so + 0x49548
    rsp = 0x00007f0ce6e77d90   rip = 0x00007f0e7420b548
    Found by: stack scanning
```

**Comment by dyastremsky** [comment] 2023-08-10 23:04
@chienkan Is this reproducible in 23.07? If so, can you provide steps for us to reproduce this?

**Comment by chienkan** [comment] 2023-08-11 10:15
It is reproducible in 23.06. I've solved this problem by modifying the code logic:
My program has image processing models on the server, I decoded images on the client side and passed the decoded data (up to 150MB) to the server. Later, I moved the image decoding logic to the server side, and the memory leak issue disappeared.

**Comment by SneakyBerry** [comment] 2023-08-28 06:35
We have the same problem, memory leaking constantly until server stops with shm error. `shm_size` set to 8gb in docker.
<img width="1536" alt="image" src="https://github.com/triton-inference-server/server/assets/49777945/5cf7ce1d-62eb-47bb-aa1a-83493b593b11">

Here is the memory usage graph from prometheus
<img width="729" alt="image" src="https://github.com/triton-inference-server/server/assets/49777945/d7f74fb3-14d9-45da-b43d-a7ad527ba8db">

**Comment by dyastremsky** [comment] 2023-08-28 18:28
Thank you for updating us, @chienkan. Since you have found a way to solve this issue, I will close this ticket.

@SneakyBerry, thank you for sharing. Please open a new issue using the bug report template with full reproduction steps. To root cause your issue, we will need full, clear steps to reproduce the issue including models and configuration files. If you do not want to share your pipeline, feel free to provide a toy model and pipeline that reproduces the issue.

**Closed by dyastremsky** 2023-08-28 18:28 UTC
Labels: bug
