### ISSUE TITLE
Confusion about passing/converting NumPy/PyTorch tensors from and to pb_utils.Tensor for inference request

### ISSUE THREAD

**Issue by jackylu0124** [triton-inference-server/server#5472] opened 2023-03-09 02:59 UTC
**Description**
I am confused about the correct way of passing/converting NumPy/PyTorch tensors from and to pb_utils.Tensor for inference request, especially when inference is done on GPU as this leads to the additional complexity of memory on different devices. And I would also like to gain more insight on the way Triton Inference Server decides on whether to place the returned inference result on GPU or CPU.

In terms of passing/converting NumPy/PyTorch tensors to pb_utils.Tensor for inference request, is something like `input = pb_utils.Tensor("img", img)` sufficient? Or should I always use something like `input = pb_utils.Tensor.from_dlpack( "img", to_dlpack(torch.from_numpy(img)))` to be safe, assuming `img` is a NumPy array in this case? And when converting NumPy/PyTorch tensors to pb_utils.Tensor, should I also specify the device that the tensor is on?

In terms of passing/converting pb_utils.Tensor to NumPy/PyTorch tensors, currently I used the a helper function like the following after looking at this GitHub issue ([https://github.com/triton-inference-server/server/issues/3944](https://github.com/triton-inference-server/server/issues/3944)), is this a good/correct way to do it?
```
def get_response_tensor_by_name(response, name):
    if response.has_error():
        raise pb_utils.TritonModelException(response.error().message())
    else:
        pb_tensor = pb_utils.get_output_tensor_by_name(response, name)
        if pb_tensor.is_cpu():
            return pb_tensor.as_numpy()
        else:
            return from_dlpack(pb_tensor.to_dlpack()).cpu().numpy()
```

One thing I am confused about is that even if I run all the ONNX models with the `kind: KIND_GPU` configuration specified in the configuration file, some ONNX models will return tensors on the CPU branch in the code above and some ONNX models will return tensors on the GPU branch above, and is there any way I could tell or control what's going on behind the scene?

**Triton Information**
I am using the `nvcr.io/nvidia/tritonserver:23.01-py3` Docker container.

Thank you very much for your help and time in advance!

**Comment by jackylu0124** [comment] 2023-03-09 03:33
A related question I have is the use of the function `as_numpy()`. I see that sometimes we use it by calling it with a string passed inside, such as `response.as_numpy("OUTPUT0")` when we call the `as_numpy()` function on a response object. On the other hand, I have also seen its uses inside the Python backend file, such as `pb_utils.get_input_tensor_by_name(request, "img").as_numpy()` when we try to get the NumPy array from a request. Are these two uses of the same function or are they different? Could you also please point me to the documentation for functions like this? Thanks a lot again!

**Comment by GuanLuo** [comment] 2023-03-09 22:11
@Tabrizian on Python backend question.

For ORT output memory type, it is decided through a "handshaking" process between the (ORT) backend and the allocator (Python backend provides for the allocation of the final buffer location). @Tabrizian can provide the complete understanding of the allocator, I think it will respect the preferred memory type by the (ORT) backend, so the final memory type replies on what the backend preferred. In this case, model deployed on GPU, it will be in the same GPU device, except for output with string data type

**Comment by jackylu0124** [comment] 2023-03-10 04:45
@GuanLuo @Tabrizian I see, thanks a lot for the insight and explanation! This is interesting because in my test shown in https://github.com/triton-inference-server/server/issues/5471, both the dynamic batch ONNX model and the single batch ONNX model are configured to run on GPU since I have specified the `instance_group` type to `KIND_GPU`, but the results returned from the dynamic batch ONNX model always ends up on the CPU branch in the code snppet posted above while the results returned from the single batch ONNX model always ends up on the GPU branch in the code snippet posted above. I feel like either it's a bug or my code in https://github.com/triton-inference-server/server/issues/5471 was not correct, is there any chance you could please take a look at my code in that issue (https://github.com/triton-inference-server/server/issues/5471) to see if I made any mistakes that cause the issues I described there? Thanks a lot again!

**Comment by Tabrizian** [comment] 2023-03-14 18:57
> is something like input = pb_utils.Tensor("img", img) sufficient?

This is sufficient only if the `img` is a numpy array. If the tensor is on GPU, numpy doesn't support it and you would have to go the DLPack route.

> And when converting NumPy/PyTorch tensors to pb_utils.Tensor, should I also specify the device that the tensor is on?

The NumPy tensors will be always on CPU. The PyTorch tensors if they use DLPack, they could be on GPU/CPU. The DLPack tensor representation embeds the device information and Triton's tensor representation would use the same device that is mentioned in DLPack. You can't specify the device that the tensor is on.

> response.as_numpy("OUTPUT0") when we call the as_numpy()

The first one is in the Python clients while the second one is in Python backend. In python backend, `as_numpy` doesn't receive any arguments.

The documentation for these functions is something that we are working on. The usage is demonstrated in the Python backend examples: https://github.com/triton-inference-server/python_backend/tree/main/examples


> One thing I am confused about is that even if I run all the ONNX models with the kind: KIND_GPU configuration specified in the configuration file, some ONNX models will return tensors on the CPU branch in the code above and some ONNX models will return tensors on the GPU branch above,

The python backend BLS would return the tensors in the same device that it has received it from the other backend/model. If the backend returns the tensor on GPU, you would receive the tensor on GPU as well. I think it requires a bit more investigation to see whether the issue is in Triton or ORT backend.

**Comment by jackylu0124** [comment] 2023-03-14 19:12
Thank you very much for the detailed explanation! A quick follow-up question I have is that: if I use CUDA onnexruntime to perform inference, would I need to manually specify the device to be GPU using DLPack when constructing and passing in the pb_utils tensor, or will pb_utils tensor handle that for me based on the inference device type I specify in my configuration file even if the tensor I provide is on CPU?

**Comment by Tabrizian** [comment] 2023-03-17 14:59
> will pb_utils tensor handle that for me based on the inference device type I specify in my configuration file even if the tensor I provide is on CPU?

Python backend will fill in the device attribute of DLPack automatically based on the inference result of the ONNX model. The DLPack representation works with both GPUs/CPUs but NumPy only works with CPUs.

**Comment by Tabrizian** [comment] 2023-03-24 15:59
Closing this ticket. Feel free to open a new issue if you have more questions.

**Closed by Tabrizian** 2023-03-24 15:59 UTC
