### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 274435 bytes

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#3524] opened 2021-11-02 09:34 UTC
I'm getting this error while decoding a TYPE_STRING output response from the Triton Server.
Config.pbtxt looks like this:
```
name: "vehicleRec_postprocess"
backend: "python"
max_batch_size: 0
input [
    {
        name: "model_output"
        data_type: TYPE_FP32
        dims: [-1, -1]
    },
    {
        name: "resized_image_shape"
        data_type: TYPE_INT64
        dims: [2]
    },
    {
        name: "original_image_shape"
        data_type: TYPE_INT64
        dims: [2]
    }
]
output [
    {
        name: "final_output"
        data_type: TYPE_STRING
        dims: [-1,-1,-1]
    }
]
```

It's actually is part of an ensemble, but this is the last model of that ensemble.
The sample output I'm getting is:
```
[array([[[b'925', b'369'],
        [b'1013', b'395'],
        [b'bus', b'bus']],

       [[b'515', b'542'],
        [b'571', b'592'],
        [b'rickshaw', b'rickshaw']],

       [[b'458', b'357'],
        [b'508', b'397'],
        [b'bus', b'bus']],

       [[b'868', b'388'],
        [b'900', b'421'],
        [b'car', b'car']],

       [[b'1021', b'412'],
        [b'1113', b'461'],
        [b'bus', b'bus']],

       [[b'593', b'364'],
        [b'639', b'416'],
        [b'van', b'van']],

       [[b'913', b'324'],
        [b'982', b'364'],
        [b'bus', b'bus']],

       [[b'794', b'411'],
        [b'833', b'445'],
        [b'car', b'car']],

       [[b'282', b'460'],
        [b'552', b'641'],
        [b'bus', b'bus']],

       [[b'934', b'403'],
        [b'1104', b'470'],
        [b'bus', b'bus']],

       [[b'813', b'589'],
        [b'851', b'663'],
        [b'motorbike', b'motorbike']],

       [[b'1147', b'399'],
        [b'1280', b'541'],
        [b'bus', b'bus']],

       [[b'717', b'611'],
        [b'765', b'687'],
        [b'motorbike', b'motorbike']],

       [[b'1219', b'559'],
        [b'1280', b'658'],
        [b'rickshaw', b'rickshaw']],

       [[b'591', b'363'],
        [b'640', b'416'],
        [b'bus', b'bus']],

       [[b'505', b'572'],
        [b'571', b'664'],
        [b'rickshaw', b'rickshaw']],

       [[b'701', b'459'],
        [b'805', b'611'],
        [b'bus', b'bus']],

       [[b'592', b'440'],
        [b'700', b'587'],
        [b'bus', b'bus']]], dtype=object)]

```

This output contains bounding boxes and its class label in object type format. I receive around 50-60 outputs perfectly fine, then this error gets thrown
```
File "/home/ericedge/anaconda3/envs/skylark/lib/python3.6/site-packages/tritonclient/http/__init__.py", line 1926, in as_numpy
    self._buffer[start_index:end_index])
  File "/home/ericedge/anaconda3/envs/skylark/lib/python3.6/site-packages/tritonclient/utils/__init__.py", line 268, in deserialize_bytes_tensor
    sb = struct.unpack_from("<{}s".format(l), val_buf, offset)[0]
struct.error: unpack_from requires a buffer of at least 274435 bytes
```

This is the code snippet from where I'm getting the output:
```
inferenceOutputs = [response.as_numpy(output_name) for output_name in output_names]
for i in range(len(inferenceOutputs)):
                    for output in outputs[i]:
                        if output[0][0].decode() != '-1':
                            x1 = int(output[0][0])
                            y1 = int(output[0][1])
                            x2 = int(output[1][0])
                            y2 = int(output[1][1])
                            draw_boxes.add(img, x1, y1, x2, y2, output[2][0].decode())
```
where draw_boxes is a function to draw the bounding boxes alongwith its class label. How to solve this error, and why is it coming?

**Comment by dyastremsky** [comment] 2021-11-02 17:24
@deadeyegoodwin Do you know where the above could be coming from? If not, I can open a bug to investigate.

**Comment by deadeyegoodwin** [comment] 2021-11-02 18:31
Here: https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/utils/__init__.py
Triton serializes strings/bytes as <len><byte0><byte1>... and those must be converted to numpy. Perhaps there is something wrong in that code or the <len> is incorrect for some reason.
We need to be able to reproduce and then you should file a bug.

**Comment by sourabh-burnwal** [comment] 2021-11-02 18:43
@deadeyegoodwin 
I am converting the output to numpy arrays and then decoding it to get the strings. The model is a multi-class object detection model. Initially I wasn't sending out the labels (of the detections), so was using TYPE_FP32 and it was working fine. But when I send a string, I have to use TYPE_STRING. As I said in the issue, it works well for first few requests, then throws this error.

**Comment by dyastremsky** [comment] 2021-11-02 19:20
Thank you both for the extra details.

Sourabh, if you think it's a bug rather than a code issue, feel free to submit a bug via the bug template so that we can reproduce it. Otherwise, it's hard to say what the issue in the code encoding/decoding could be. Based on the error message, it seems like the wrong number of bytes are being read.

**Comment by sourabh-burnwal** [comment] 2021-11-02 19:31
@dyastremsky 
I will try to come up with a python backend model which could reproduce the error and then raise a bug issue. Thanks to both of you for the help.

**Comment by giprime** [comment] 2021-11-08 05:57
I'm struggling with this issue too.
In my case, some trials with fixed input return simillar errors like this topic.

like case of @sourabh-burnwal my model is an ensemble model and error occurs while getting input tensor of last model of the ensemble.
I checked "triton_python_backend_utils.py" and got 
  1) Encoded tensor(bytes. repeat of 4 bytes length bytes and string bytes * length) of output previous model of last model of ensemble.
  2) Transmitted tensor(array of uint8?. same as 1) last model of ensemble received.

I expected tensor 1) and 2) must same in bytes. but, I founded mismatch between two tensors when the error occured.
(I apologize that it is difficult to disclose all data of tensor because it contains sensitive data of my costomer.)

My models(last model in ensemble and previous model of the last model) sent and received a tensor data which contains 87 various length utf-8 encoded bytes strings.(total length 1205 byte, shape is [-1, 1])
1) b'(omitted) ... **\x03\x00\x00\x00** 1/1 _**\x04\x00\x00\x00** \xeb\x9f\xacH'_
                                                           ↓ [ SENT ] ↓
2) b'(omitted) ... **\x03\x00\x00\x00** 1/1 _**\x04\x00\x00\xe0** \x04\x00\x00\x00'_

String in bold means length of next string and string in Italic means error occured at that time. In my case, error occured at decoding time of last string of tensor. so I brought bytes part of last two strings.

At length of last string.  Encoded length of sender indicates last string consists of 4 bytes. But for some unknown reason, some of the length values and thereafter data were passed as invalid values. It indicates there are 3758096388 bytes after length. but there are only 4 bytes left so server raised error.

This error occurred occasionally, but the value of the error that occurred was constant. So I guessing backend under python backend(maybe coded by c++?) has a bug related to it's state.

**Comment by sourabh-burnwal** [comment] 2021-11-08 06:22
@giprime 
Yes, I'm facing the error in a similar situation actually. I tried to create a simple python backend model to reproduce the error, but it didn't work. Can't share the actual code due to confidentiality issues.

**Comment by dyastremsky** [comment] 2021-11-16 00:58
I'll investigate. Be aware that we typically ask you to produce a bug report so that we can reproduce the bug. The additional details are very helpful, but providing steps to reproduce the error makes it more likely we'll be able to debug what you're seeing and fix it. It can be a mock model (not your actual model/data) that results in the same behavior.

**Comment by dyastremsky** [comment] 2021-11-16 19:59
@sourabh-burnwal @giprime Are either of you able to provide inputs and expected outputs of the failure cases?

**Comment by dyastremsky** [comment] 2021-11-22 19:38
I was unable to replicate this bug with a sample ensemble string model and through encoding/decoding the provided inputs. We'll need reproduction steps (sample model, data, or similar) in order to investigate.

**Comment by giprime** [comment] 2021-11-26 02:22
@dyastremsky 
I have investigated this issue for a while. I made a sample model to reproduce the results. but It doesn't produced error.

I guess, the model environments between models in ensemble make the results.
I'm using a custom python backend for portability of some model in ensemble.

@sourabh-burnwal 
Are you using custom python backend for your model?

**Comment by sourabh-burnwal** [comment] 2021-11-26 04:00
> @sourabh-burnwal @giprime Are either of you able to provide inputs and expected outputs of the failure cases?

@dyastremsky 
It was a Yolo multi-object detection model. I have added a sample output above. I didn't get responses in the failure cases.

**Comment by sourabh-burnwal** [comment] 2021-11-26 04:08
@giprime 
The ensemble looks like this:
Python backend pre-process model + YOLO object detection model + Python backend post-process model.

After facing this error, I created a dictionary with 0,1,2,.. as keys and the object class names as the values. Used fp32 format to send the outputs. It didn't throw any error in this case.

**Comment by dyastremsky** [comment] 2021-11-29 19:53
I appreciate the additional information. The sample output encoded/decoded correctly when tested with the encoding/decoding functions. I appreciate the effort you both put into reproducing the results. However, if we cannot reproduce them, we cannot debug this issue. I'm happy you were able to find a workaround.

I am going to close this issue due to it being unreproducible. If that changes, please feel free to provide a way to reproduce the bug and we can look into it.

**Closed by dyastremsky** 2021-11-29 19:53 UTC
Labels: bug

**Comment by geekbeast** [comment] 2023-08-20 09:54
I can reproduce this issue using the Triton Server Stable Diffusion tutorial and binary inference over HTTP 100% of the time on 23.07. Using the regular HTTP inference works fine.

**Comment by dyastremsky** [comment] 2023-08-21 17:19
Thank you for reaching out, Matthew. Please open a new issue using the bug template to show the error you are seeing with full steps for reproducing it.
