### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'StatusCode'

### ISSUE THREAD

**Issue by lyc728** [triton-inference-server/server#6838] opened 2024-01-26 04:32 UTC
Input sequence:  [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264]
Got completed request
Input: Born in north-east France, Soyer trained as a
Output beam 0:  chef at the age of 15. He worked in a number of restaurants in Paris before moving to London in 1987. He has since become one of the most successful and well-known chefs in the UK, with a string of restaurants and cookbooks to his name. Soyer is known for his innovative and creative approach to cooking, and his dishes often feature a combination of traditional French techniques and modern, international influences. He has won numerous awards for his work, including the prestigious
Output sequence:  [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264, 29706, 518, 279, 4231, 315, 220, 16, 20, 13, 1260, 6439, 304, 264, 1372, 315, 15556, 304, 12095, 1573, 7218, 311, 7148, 304, 220, 16, 24, 23, 22, 13, 1260, 702, 2474, 3635, 825, 315, 279, 1429, 6849, 323, 1632, 21309, 59127, 304, 279, 6424, 11, 448, 264, 914, 315, 15556, 323, 4296, 12110, 311, 806, 829, 13, 2055, 26161, 374, 3881, 369, 806, 18199, 323, 11521, 5486, 311, 17233, 11, 323, 806, 25779, 3545, 4565, 264, 10601, 315, 8606, 8585, 12538, 323, 6481, 11, 6489, 33353, 13, 1260, 702, 2765, 12114, 22344, 369, 806, 975, 11, 2670, 279, 40285]
Exception ignored in: <function InferenceServerClient.__del__ at 0x7f6f510fb520>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 257, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 265, in close
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2101, in close
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2082, in _close
AttributeError: 'NoneType' object has no attribute 'StatusCode'

**Comment by jbkyang-nvi** [comment] 2024-01-27 01:28
Can you say a little about what version of Triton, what backend you are using and what model you are using?

**Comment by lyc728** [comment] 2024-01-29 01:25
I use the tensorrt-llm 0.7.0 ,and  
DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .
the model is qwen

**Comment by jbkyang-nvi** [comment] 2024-01-30 00:40
Can you also explain what you are doing with the client? Are you running with the [python client script](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/inflight_batcher_llm_client.py)? Did you try using the generate endpoint, did it work?

**Comment by lyc728** [comment] 2024-01-30 02:00
yes, I run the inflight_batcher_llm_client.py, I use curl -X POST localhost:8000/v2/models/tensorrt_llm_bls/generate -d '{"text_input": "What is machine learning?", "max_tokens": 20, "bad_words": "", "stop_words": ""}' do not error

**Comment by lyc728** [comment] 2024-01-30 02:34
hello, How to solve the inflight_batcher_llm_client.py caused error

**Comment by jbkyang-nvi** [comment] 2024-01-30 19:58
For all of future bug reports, it would be really helpful to get a reproducer. For your case, this means providing:
1. How you compiled the qwen model with the TensorRT-LLM engine?
2. How you are running the `inflight_batcher_llm_client.py` script. What are the inputs you are providing it? Which tutorial are you following?

This seems like there is some problem on destruction on the Triton client, but likely would not effect your client code if you decide to use `inflight_batcher_llm_client.py` as a base to write your own client.
-----------------------------------
I also googled and found the same issue has been filed on the tensorrtllm backend: https://github.com/triton-inference-server/tensorrtllm_backend/issues/317, https://github.com/triton-inference-server/tensorrtllm_backend/issues/285.
From [this comment](https://github.com/triton-inference-server/tensorrtllm_backend/issues/285#issuecomment-1882497867)
it looks like you need to install `pip3 install -r requirements.txt`.

**Comment by lyc728** [comment] 2024-01-31 01:23
I alse try pip3 install -r requirements.txt But also happen the error
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorrt-llm 0.7.0 requires transformers==4.33.1, but you have transformers 4.31.0 which is incompatible.
And the eroor AttributeError: 'NoneType' object has no attribute 'StatusCode' also happen

`python build.py --hf_model_dir /data/LLM/Translation/llms/Qwen-7B-Chat/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4 \
                --enable_context_fmha \
                --use_inflight_batching \
                --output_dir /liuyuanchao/tensorrtllm_backend13/engine_outputs2_inf/
`
python inflight_batcher_llm/client/inflight_batcher_llm_client.py \
--request-output-len 150 \
-S \
--text 写一篇具有现代化诗意的作文

**Comment by jbkyang-nvi** [comment] 2024-01-31 03:22
> I alse try pip3 install -r requirements.txt But also happen the error ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. tensorrt-llm 0.7.0 requires transformers==4.33.1, but you have transformers 4.31.0 which is incompatible. And the eroor AttributeError: 'NoneType' object has no attribute 'StatusCode' also happen
> 
> `python build.py --hf_model_dir /data/LLM/Translation/llms/Qwen-7B-Chat/ \ --dtype float16 \ --remove_input_padding \ --use_gpt_attention_plugin float16 \ --use_gemm_plugin float16 \ --use_weight_only \ --weight_only_precision int4 \ --enable_context_fmha \ --use_inflight_batching \ --output_dir /liuyuanchao/tensorrtllm_backend13/engine_outputs2_inf/ `
> 
> ```
> python inflight_batcher_llm/client/inflight_batcher_llm_client.py \
> --request-output-len 150 \
> -S \
> --text 写一篇具有现代化诗意的作文 
> ```

Have you tried upgrading the transformer version in your container?

**Comment by lyc728** [comment] 2024-01-31 03:25
Initially, transformer version 4.33.1 is an error

**Comment by lyc728** [comment] 2024-01-31 03:29
I am curious why the versions of trt-llm and TRT-LLM-Backend are inconsistent (v0.7.0).
[tensorrtllm_backend](https://github.com/triton-inference-server/tensorrtllm_backend/tree/v0.7.0)
transformers==4.31.0

[TensorRT-LLM](https://github.com/NVIDIA/TensorRT-LLM/tree/v0.7.0)
transformers==4.33.1

**Comment by jbkyang-nvi** [comment] 2024-02-01 20:05
Closing this ticket. I think your problem should be fixed with https://github.com/triton-inference-server/tensorrtllm_backend/issues/285.

**Comment by jbkyang-nvi** [comment] 2024-02-01 20:08
> I am curious why the versions of trt-llm and TRT-LLM-Backend are inconsistent (v0.7.0). [tensorrtllm_backend](https://github.com/triton-inference-server/tensorrtllm_backend/tree/v0.7.0) transformers==4.31.0
> 
> [TensorRT-LLM](https://github.com/NVIDIA/TensorRT-LLM/tree/v0.7.0) transformers==4.33.1

I believe it is related to how TensorRT-LLM python library is not needed to run Triton with tensorrtllm_backend. Please file a ticket with the `tensorrtllm_backend` to confirm!

**Closed by jbkyang-nvi** 2024-02-01 20:08 UTC
Labels: bug, module: clients

**Comment by DZADSL72-00558** [comment] 2024-09-23 17:00
Any update on this thread?

**Comment by jbkyang-nvi** [comment] 2024-09-25 00:23
> Any update on this thread?

please refer to the TRTLLM repo issues linked above
