### ISSUE TITLE
Streaming inference for heavily overlapping data

### ISSUE THREAD

**Issue by alecgunny** [triton-inference-server/server#2442] opened 2021-01-22 18:09 UTC
I have an inference use case where the input data is an infinitely long, continuously streaming timeseries (or, rather, several of them), but the model itself is static: it takes fixed-length snapshots of the timeseries at some fixed interval and then computes inference on them.

If the interval _between_ snapshots is shorter than the length of the snapshot itself, inference using Triton obviously involves streaming duplicate data to the server. As I try to use smaller and smaller intervals between snapshots, the unnecessary network bandwidth is becoming a severe bottleneck in my inference pipeline.

A short-term solution I can imagine would involve basically exposing the model input as a "state", with the model itself becoming essentially a recurrent step on that state, and then leveraging Triton's stateful model API. However, this has the downside that it would preclude scaling to multiple model instances (since every request would need to be routed to the same instance which maintains the state). Since I plan on using intervals which are shorter than the inference time itself (on the scale of hundreds of us), leveraging multiple model instances asynchronously would be hugely advantageous.

The more robust solution I can imagine would involve basically allocating an inference tensor for _all_ model instances which gets updated with each inference request, and then passed to an available model via the usual scheduling policy. This would probably preclude multi-node scaling, but that's a sacrifice I think I can make for now. My question is, since I would like to be able to do this for models leveraging arbitrary backends, would this solution be better (or even possibly) achieved via a custom backend which could call _other_ backends, or would it require a custom build of the server itself?

As an added complication: some of the models I would like to use have outputs which are timeseries themselves of the same length as the input. In this scenario, I imagine the ideal solution would pass each model instance's output to a shared output tensor that does some aggregation between overlapping predictions, streaming back a step in the timeseries after X number of predictions have been made and aggregated on it. While not strictly necessary (I can of course do this aggregation on the client side, it just would involve more unnecessary network bandwidth), I bring it up to see if this would change the answer to my previous question.

**Comment by deadeyegoodwin** [comment] 2021-01-22 22:47
For the input side, have you considered an ensemble which has one instance of a "timeseries" model (implemented with custom backend) that maintains the most-recent timeseries window of the length required by the "snapshot" model.  For each request the timeseries model updates the window, makes an output tensor representing the window, and passes that onto the snapshot model as the window input it needs. In the ensemble you can have as many instances of the snapshot model as you need to get your throughput. As you note this will only work within a single node. The "makes an output tensor" is the potentially problematic part as far as performance. In the triton backend API you need to use the output API to get an empty buffer from Triton that you then fill with a copy of the current window. But I wouldn't pre-judge that it will be a problem and it should be fairly easy to try this solution (but see below for a non-copy alternative).

On the output side I'm less clear on what the issue is. There is an option you can use with your many-instances of snapshot model that will keep the responses in the same order as they are sent by the timeseries model. There is also the "decoupled" capabilities in the backend that allow you to decouple how you send responses from the incoming requests. You would need another "post process" custom model to take advantage of that.

Non-copy alternative: For the custom timeseries model there is another alternative that we don't yet fully support but should work (we don't claim support because we have not yet done enough testing). Your timeseries custom backend can make inferences requests back to the Triton instance using the TRITONSERVER API. In effect, your backend is acting as a client of triton. Why does this help? Because in using the TRITONSERVER API you can provide the input tensors to the snapshot models by just referencing into the timeseries window and not have to copy and data.

**Comment by alecgunny** [comment] 2021-01-24 23:44
Oh wow that is an absolutely excellent idea David, thanks for the suggestion. I really like the idea of the TRITONSERVER API for farther down the line as well, that's a cool functionality. For the ensemble model solution: would this work with single-node multi-GPU (I guess more fundamentally, will the ensemble scheduler ever pipe tensors between model instances on different GPUs)? It shouldn't matter for me: multi-instance on a single GPU should be sufficient for my current use case, but just wondering for posterity.

For the output side, is the suggestion similarly to use another single-instance stateful model in the ensemble that takes care of the requisite functionality, and that the ensemble scheduler will ensure that the tensors that are passed to it from the snapshot  model are kept in the same order in which they were passed to the input "timeseries-to-snapshot" model?

**Comment by deadeyegoodwin** [comment] 2021-01-25 17:04
The ensembler can work with multi-GPU systems. It will move/copy tensors between GPUs as necessary, so you can use instance_group in model configurations to place the models composing the ensemble on different GPUs and it will all work.

On the output side, yes, that is what I am suggesting... based on my understanding of what you were asking. The "preserver order" functionality is here: https://github.com/triton-inference-server/server/blob/master/src/core/model_config.proto#L1011. You would set it on the snapshot model so that even if you have multiple instances of that model the order of responses will match the order of requests.

**Comment by deadeyegoodwin** [comment] 2021-01-26 00:04
@alecgunny  I'm going to close this as your primary question seems to be answered. Feel free to followup with additional questions.

**Closed by deadeyegoodwin** 2021-01-26 00:04 UTC

**Comment by alecgunny** [comment] 2021-01-26 22:30
Yeah absolutely it has, thanks a lot David I appreciate it. This all makes sense and looks like it should support my use case out of the box, which is awesome.

I do have some questions about _constructing_ an "arbitrary" stateful model that I'll pose here, but let me know if you'd like me to open another issue for tracking or googlability reasons.

It's not entirely clear to me how a "state" is created or managed by models. For example, the [simple sequence](https://github.com/triton-inference-server/server/tree/master/docs/examples/model_repository/simple_sequence) model doesn't actually appear as if it maintains state: as far as I can tell, it just adds the `INPUT` tensor to the `START` tensor, conditioned on the corresponding `READY` value being 1 (otherwise it returns 0). What if I wanted to, say, do a cumulative sum across the `INPUT` values for a given sequence, how would I expose that state to the server and update it?

It looks like there are examples of custom models doing something like what I've described ([this one](https://github.com/triton-inference-server/server/tree/master/src/test/custom/sequence), for example), but is it possible to utilize this stateful behavior with a model using one of the standard backends?

**Comment by alecgunny** [comment] 2021-01-27 01:23
I guess to make things more concrete, suppose I had a simple implementation of the type of model we're talking about here (using Torch/ONNX, but just as easily buildable in any framework):
```python
import torch

class Snapshotter(torch.nn.Module):
  def forward(self, streamed_inputs, snapshot):
    snapshot = snapshot[:, streamed_inputs.shape[1]:]
    snapshot = torch.cat([snapshot, streamed_inputs], axis=1)
    return snapshot
```
Where basically the output of the step is the "state" that needs to get passed on to the next step. Does Triton have native support for something like this, or is my best bet a custom model?

**Comment by deadeyegoodwin** [comment] 2021-01-27 17:38
Some of the test models just fake being stateful...
I'm not an expert on the frameworks but they do contain operations (like RNN nodes) that maintain state. I would assume that you could also use something generic like a "variable" that you could read/write but I don't know any details.

I think what you are asking about is a way to be able to use a stateless model in a stateful way by having (one or more) "state" inputs and (one or more) corresponding "next-state" outputs where a "next-state" output feeds back to the corresponding "state" input. And wouldn't it be nice if Triton managed the flow of data from "next-state" to "state" as part of its sequence support.

The answer is yes, that is something we have on our roadmap. Basically we would extend the control concept (https://github.com/triton-inference-server/server/blob/master/src/core/model_config.proto#L1062) in the sequence batcher to let you express the state/next-state pairs in your model and then triton would be responsible for those (and so you would not use/see them from the client).

Is that what you are requesting?

**Comment by alecgunny** [comment] 2021-01-27 22:16
Yes that's it exactly! This would also be consistent with the way that Keras defines [RNNs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN), by taking a static "cell" building block that accepts inputs and states and returns outputs and updated states and then pipes them together on the backend.

FWIW, this appears pretty non-trivial to do in PyTorch/ONNX, you can see my basic attempt [here](https://gist.github.com/alecgunny/9dc6c138032e0b3f2668db5b4a5d302d), but the basic idea is that it doesn't seem like variable assignment works as simply as one might hope (and there don't seem to be any examples out there of how to use it). That said, TensorFlow might be a bit easier since they support building variable "updates" into the graph, and I'll probably try this next. Short of that, it seems like sucking it up and building a custom model might be the path of least resistance until the feature you mentioned above is implemented.

I guess the only other thing I might ask is if you have examples of models that are truly stateful that you use for e.g. testing purposes, particularly any that come from the open source so that I might be able to take a look at how they were constructed in the first place to replicate their behavior?

**Comment by deadeyegoodwin** [comment] 2021-01-27 22:27
I don't recall if any are truly stateful, but the code to generate them is https://github.com/triton-inference-server/server/blob/master/qa/common/gen_qa_sequence_models.py

I believe this TF one is stateful https://github.com/triton-inference-server/server/blob/master/qa/common/gen_qa_sequence_models.py#L173

**Comment by alecgunny** [comment] 2021-01-27 23:09
Ok got it, thanks David that's really helpful. For posterity, I have a working example of this functionality in TF that uses the `.assign` functionality shown in your example [here](https://gist.github.com/alecgunny/44d34db87950e6dfb3b040b442efc1ea). It looks like this should be able to get me going in the shorter term, but curious to keep an eye on when the more general state implementation gets up and running.

Thanks again for all your help here David.

**Comment by alecgunny** [comment] 2021-03-08 21:05
Hey David, quick follow up question here.

The TF implementation I built above works fine for one stream of data, but can only support maintaining and updating state from a single data stream at once (i.e. I can't leverage the CORR_ID at the moment). To support concurrent inference of multiple data streams on a single node, I'll basically need to keep one model instance (and therefore one state) per stream I plan on performing inference on per node.

My question is whether there are any guarantees about how the sequence batcher will distribute streams to instances if some of the instances are occupied (not necessarily currently performing inference, but have a sequence that has not yet timed out).

For example, let's say I have 10 streams I want to send to a single node, and therefore I instantiate 10 instances of my snapshotter model. I begin streaming the first stream to the server, which gets routed to instance 0. I then begin the second stream, which I would assume given the number of available model instances, gets sent to some other instance. As I get up to the 8th or 9th stream, though, can I be sure that the scheduler will not route a new stream back to instance 0 if it just happens to be in between requests from its already ongoing stream? Or will I need to come up with something more clever to accommodate this use case?

**Comment by deadeyegoodwin** [comment] 2021-03-09 23:27
Because your model doesn't understand CORR_ID, you should use the Direct sequence batcher: https://github.com/triton-inference-server/server/blob/master/docs/architecture.md#direct

Take a look at that documentation and let me know if you still have questions.

**Comment by alecgunny** [comment] 2021-03-10 18:07
Got it, I think that does resolve it thank you. Just so I'm totally clear

> Recognizes when an inference request starts a new sequence and allocates a batch slot for that sequence. If no batch slot is available for the new sequence, Triton places the inference request in a backlog.

The availability of a batch slot is _not_ determined by whether or not that sequence currently has some compute going on. Once a sequence has started, its batch slot is not marked as "available" until the sequence either is ended or times out, correct?

**Comment by deadeyegoodwin** [comment] 2021-03-10 18:31
Right, a sequence holds it batch slot reservation even when it has no in-flight requests. I guess you realize this is not very efficient. The Oldest sequence batcher is more efficient in that it doesn't have this slot reservation, but it does require that the model use CORR_ID to understand what state belongs with the request.

**Comment by alecgunny** [comment] 2021-04-01 04:41
Running into a bit of an interesting issue here that I would be curious to get the Triton team's take on, but as always if you would prefer that I file a new bug for visibility/searchability reasons, please let me know.

When running a _single_ client instance against my server, setting some desired request rate, I will sometimes run into a bizarre issue where it seems like requests get throttled on the client side, presumably building up a queue in the `_InferStream._request_queue`, before suddenly being released all at once.

To illustrate my issue, take for example this plot of a "normal" run (one where this throttling issue doesn't occur: it seems to happen at least semi-randomly, but I'll cover that more at the end). On the x-axis is the time since the start of the run; on the y-axis on the left is per-model throughput for my snapshotter model, the downstream model it feeds, as well as the total throughput of the ensemble (as reported at the `:8002/metrics` endpoint and sampled every ~10ms); and on the y-axis on the right is the reported average queue latency over those intervals for the first two models. Everything has some light smoothing applied for the purposes of readability:
![normal-last-two-seconds](https://user-images.githubusercontent.com/14932242/113241950-9c347300-9264-11eb-9515-33250b112af7.PNG)

Everything seems to be working fine: the throughputs all match up so nothing is bottlenecking, and accordingly the queue times remain reasonably low. This aligns with the following graph, which shows the request rate, throughput, and latency as measured on the _client_ side. (The request rate and throughput are averaged over a 1000-sample sliding window. Smoothing is applied to all lines.):
![normal-latency-throughput](https://user-images.githubusercontent.com/14932242/113242127-1533ca80-9265-11eb-98c0-7540fed7f53e.PNG)

As expected, the request rate and throughput align well, and the latency stays reasonably stable and low.

On the other hand, here is the client-side metrics on a run where I observe throttling:
![throttled-latency-throughput](https://user-images.githubusercontent.com/14932242/113242317-883d4100-9265-11eb-8ba4-bce559876864.PNG)

Not only is the request rate much lower, but the throughput can't even keep up with this lower request rate. As such, we see the latency build up steadily until my code terminates based on the violation of a latency threshold. What's interesting about this is if we take a look at the last two seconds of this run on the server side:
![throttled-last-two-seconds](https://user-images.githubusercontent.com/14932242/113242186-33012f80-9265-11eb-8944-1fc8e56de8bd.PNG)

Until the last half second or so, the queue times stay completely within reason, and the model throughputs all seem to be roughly in line with the throughput as measured on the client side: evidently they are having no problem with the load before that point. Then suddenly the snapshotter throughput explodes, overwhelming the downstream model, which can't handle as high a throughput, and building up its queue. But then the request rate to the snapshotter begins to overwhelm _its_ throughput capacity, and so its queue starts to build up as well.

The fact that the queue times remain low _despite_ the disparity between client-side throughput and request rate leads me to believe the pile-up is happening on the client side. It's worth noting that I measure the request rate by clicking my proverbial stopwatch right before I call `InferenceClient.async_stream_infer`, which obviously just measures the rate at which I place objects into the `_request_queue`, not necessarily the rate at which they actually get sent (if there's a way to measure the latter using Triton, that would be good to know).

My suspicion is that Triton's use of threading to enqueue requests and responses is throttling the performance of each of these threads individually (the main thread, the request thread, and the response thread). This would be consistent with the fact that every time I encounter this problem, my measured request rate is _lower_ than the one I attempt to target (likely due to extra latency incurred when building the request in `_get_inference_request`). This would also explain why the snapshotter throughput suddenly explodes at the end of my run: when I stop creating requests in the main thread because my latency threshold has been violated, Triton's request thread is suddenly much more free to fire off the requests in its built-up queue as fast as it can.

This issue happens seemingly independently of what request rate I target (in the example above, the throttled case happened at a _lower_ attempted request rate than the non-throttled case, though I've observed the reverse as well). That said, I have run these tests on GCP VMs (`n1-highcpu-16` machine types) where I have _not_ controlled for or measured the processor model that my VM actually gets assigned. However, 16 vCPUs should be more than sufficient given the simplicity of my data generation (just `np.random.randn`) regardless of processor, so I'm not really considering this as a factor at the moment (though I'm happy to re-run with that information if that would be helpful).

Is the behavior I've described consistent with any behavior observed or heard about by the Triton team? If the threading is actually the culprit, would using processes instead of threads be a workable alternative?

**Comment by tanmayv25** [comment] 2021-04-05 12:56
> if there's a way to measure the latter using Triton, that would be good to know

This function is our closest bet on Triton land: https://github.com/triton-inference-server/server/blob/master/src/clients/python/library/tritonclient/grpc/__init__.py#L1808

With this call the request is plucked out of the `_request_queue` and forwarded to python GRPC streaming API. The python grpc streaming API as little restrictive in this way which requires us to provide a streaming iterator.  The data you shared seemingly points to some weirdness on the client-side (within or outside gRPC call). The experiment will help us in gaining more insights. `_get_inference_request` is a time-taking step as it include marshaling of the request message. 

For performance-critical reason, I would advice to use our C++ gRPC streaming API.

**Comment by alecgunny** [comment] 2021-04-07 20:59
Ok thank you that makes sense, I'll try to build some code to hack into there and click my stopwatch at that point to verify that this is the issue. FWIW, I'm noticing that it's taking a long time to exit the client context, which I take to mean that there are a lot of requests sitting in the `_request_queue` that need to fire off (as an aside, it would be helpful if there was an option to exit without waiting, by using `threading.Event`s and doing a `with _request_queue.mutex: _request_queue.clear()` or something). It also helps explain why that interval above where the queue latency explodes is 0.5 seconds: I'm running the client in a separate process that I try to join for 0.5 seconds before terminating (and thereby ungracefully terminating the request thread and inadvertently failing to close the GRPC channel - I discovered this by accident and have since extended the join time).

You point about `_get_inference_request` is well taken, though it should theoretically have no bearing on my request rate if it's accounted for in my request throttling, since it runs synchronously with the main thread. As a simplified version of what I do, if you took, for example, something like:
```
import argparse
import time
import random
from queue import Empty, Queue

import matplotlib.pyplot as plt
import numpy as np
import tritonclient.grpc as triton


class Callback:
    def __init__(self, q):
        self.q = q
        self.request_times = {}

    def tick(self, request_id):
        tick = time.time()
        self.request_times[request_id] = tick
        return tick

    def __call__(self, result, error):
        tock = time.time()
        request_id = int(result.get_response().id)
        tick = self.request_times.pop(request_id)
        self.q.put((tick, tock))


def dummy_generator(input, n):
    shape = input.shape()
    for i in range(n):
        yield np.random.randn(*shape).astype("float32")


def main(
    url,
    model_name,
    model_version,
    num_requests,
    rate,
    eps=1e-4,
    window_size=500
):
    q = Queue()
    callback = Callback(q)

    with triton.InferenceServerClient(url) as client:
        input = client.get_model_metadata(model_name).inputs[0]
        input = triton.InferInput(
            input.name, input.shape, input.datatype
        )
        data_generator = dummy_generator(input, num_requests)

        client.start_stream(callback=callback)
        start_time = time.time()
        last_time = start_time

        x = next(data_generator)
        sequence_start = True
        sequence_end = False
        while True:
            request_id = random.randint(1, 1e9)
            input.set_data_from_numpy(x)

            try:
                x = next(data_generator)
            except StopIteration:
                sequence_end = True

            if (time.time() - last_time) < (1. / rate - eps):
                time.sleep(1e-6)

            last_time = callback.tick(request_id)
            client.async_stream_infer(
                model_name,
                model_version=str(model_version),
                inputs=[input],
                request_id=str(request_id),
                sequence_id=1001,
                sequence_start=sequence_start,
                sequence_end=sequence_end
            )

            sequence_start = False
            if sequence_end:
                break

    request_sends, request_returns = [], []
    while True:
        try:
            r0, rf = q.get_nowait()
        except Empty:
            break
        request_sends.append(r0 - start_time)
        request_returns.append(rf - start_time)

    rolling_average_request_rate, rolling_average_throughput = [], []
    for i in range(len(request_sends) - window_size):
        request_delta = request_sends[i + window_size] - request_sends[i]
        throughput_delta = request_returns[i + window_size] - request_returns[i]

        rolling_average_request_rate.append(window_size / request_delta)
        rolling_average_throughput.append(window_size / throughput_delta)

    fig, ax = plt.subplots()
    ax.plot(rolling_average_request_rate, color="b", label="Request rate")
    ax.plot(rolling_average_throughput, color="g", label="Throughput")
    ax.legend()
    fig.savefig("rate.png")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", type=str)
    parser.add_argument("--model-name", type=str)
    parser.add_argument("--model-version", type=int, default=1)
    parser.add_argument("--num-requests", type=int, default=10000)
    parser.add_argument("--rate", type=int, default=800)
    parser.add_argument("--eps", type=float, default=1e-4)
    parser.add_argument("--window-size", type=int, default=500)

    flags = parser.parse_args()
    main(**vars(flags))
```
Accounting for this essentially amounts to fine-tuning `eps` to be in the right ballpark (I find that something between 40 and 50 us seems to keep my average right around where I want it when things are working properly)

**Comment by alecgunny** [comment] 2021-04-13 01:12
I ran some tests with an added stopwatch click after the line linked to above (after the `_request_queue.get` in `_InferStream._get_request`) on a single dedicated VM on GCP (same instance type, but bare metal instead of a container), which has removed much of the randomness and inconsistency in my results.

It definitely appears as if this is a pretty straightforward resource issue, and much of the variance seems to be random luck with how your threads get scheduled (though that's a bit of a guess). Either way, I frequently observe that the rate at which I _get_ requests from the queue is much lower than the rate at which I'm putting requests _into_ the queue, and matches up with the observed throughput both on the server-side and from an end-to-end perspective on the client.

Some of this is at least partially due to the other fact that I have a couple other processes running in my script (the client itself is running in a separate process, and I have other ones taking care of things like monitoring and profiling). It's not entirely clear to me why resources in one process should be strongly affecting the request getting/sending thread in another process, running on an entirely different core (though I never rule out any weird behavior with Python threads), but the straightforward solution for me in the short term seems to be to get rid of these extra processes for the purposes of benchmarking and just do a course-grained throughput measurement.

**Comment by alecgunny** [comment] 2021-07-21 19:02
Hey all, I wanted to check in on the status of the stateful control feature David mentioned in [this comment](https://github.com/triton-inference-server/server/issues/2442#issuecomment-768453149). Is there any rough ETA for when this might be available on the roadmap?

The reason I ask is that my TensorFlow implementation of this state update is reasonably slow at the moment (taking anywhere from 1.5-2ms), and bottlenecks some of my online use-cases that can't parallelize over multiple concurrent states. If a faster, native backend feature to handle this sort of thing is somewhere on the horizon, I can live with this for now. Otherwise I may need to invest some time building a custom backend to implement this functionality with a CUDA kernel or something.

Incidentally, being able to batch these updates efficiently would also probably help with the client-side issues I've discussed above as well, because I would be able to achieve the same number of inferences per second with fewer requests made per second.
