### ISSUE TITLE
How to send sequece data while using perf-analyzer ?

### ISSUE THREAD

**Issue by monsterlyg** [triton-inference-server/server#6132] opened 2023-08-02 03:10 UTC
In python client, i am able to send a sequence image data like: 
```
result = self.triton_client.infer(self.model_name,
                                          inputs=inputs,
                                          request_id=real_request_id,
                                          sequence_id = self.camera_id,
                                          sequence_start=start_frame,
                                          sequence_end=stop_frame,
                                          outputs=outputs)
```
I want to use perf-analyzer to do analysis, but i do not know how to prepare the input data, and there exists no clear tutorial.

**Comment by dyastremsky** [comment] 2023-08-02 15:59
You can find perf_analyzer's sequence flags [here](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/cli.md#sequence-model-options). There are examples of provided data for sequence models [here](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/input_data.md#real-input-data).

CC: @matthewkotila

**Comment by matthewkotila** [comment] 2023-08-02 18:29
This is a duplicate of https://github.com/triton-inference-server/model_analyzer/issues/737 and that has been closed, so this can be closed.

**Closed by matthewkotila** 2023-08-02 18:29 UTC
Labels: question
