### ISSUE TITLE
Input to the script for publishing models to mlflow is overly particular with inputs

### ISSUE THREAD

**Issue by rmkraus** [triton-inference-server/server#4089] opened 2022-03-22 14:24 UTC
**Description**
When using the `publish_model_to_mlflow.py` script, if the value given for the `--model_directory` argument has a trailing `/`, the script will bomb in interesting ways.

**Triton Information**
What version of Triton are you using? 2.19.0

Are you using the Triton container or did you build it yourself? container

**To Reproduce**
```
python publish_model_to_mlflow.py \
    --model_name abp-nvsmi-xgb \
    --model_directory /common/models/abp-nvsmi-xgb/ \
    --flavor triton
```

This gives the following error:

```
Traceback (most recent call last):
  File "publish_model_to_mlflow.py", line 71, in <module>
    publish_to_mlflow()
  File "/opt/conda/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "publish_model_to_mlflow.py", line 56, in publish_to_mlflow
    triton_flavor.log_model(
  File "/mlflow/triton-inference-server/server/deploy/mlflow-triton-plugin/scripts/triton_flavor.py", line 100, in log_model
    Model.log(
  File "/opt/conda/envs/mlflow/lib/python3.8/site-packages/mlflow/models/model.py", line 282, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/mlflow/triton-inference-server/server/deploy/mlflow-triton-plugin/scripts/triton_flavor.py", line 73, in save_model
    shutil.copytree(triton_model_path, model_data_path)
  File "/opt/conda/envs/mlflow/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/opt/conda/envs/mlflow/lib/python3.8/shutil.py", line 458, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/opt/conda/envs/mlflow/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/tmpdg2r5f0_/model/'
command terminated with exit code 1
```

The model being used seems to have no effect on the error.

**Expected behavior**
The input provided is syntactically identical to:
```
python publish_model_to_mlflow.py \
    --model_name abp-nvsmi-xgb \
    --model_directory /common/models/abp-nvsmi-xgb \
    --flavor triton
```

and should provide the same outcome.

**Comment by GuanLuo** [comment] 2022-04-07 23:06
It appears that the bug has been fixed by https://github.com/triton-inference-server/server/pull/3828 and I am not able to reproduce it using the model example for the plugin. Can you try the plugin from the latest codebase?
```
python `pwd`/mlflow-triton-plugin/scripts/publish_model_to_mlflow.py \
    --model_name onnx_float32_int32_int32 \
    --model_directory `pwd`/mlflow-triton-plugin/examples/onnx_float32_int32_int32/ \
    --flavor triton
```
returns:
```
Registered model 'onnx_float32_int32_int32' already exists. Creating a new version of this model...
2022/04/07 23:03:53 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: onnx_float32_int32_int32, version 3
Created version '3' of model 'onnx_float32_int32_int32'.
./mlruns/0/945d5c5d6806470d889248cfc7f10b69/artifacts
```

**Comment by Tabrizian** [comment] 2022-04-22 15:58
Closing due to in-activity.

**Closed by Tabrizian** 2022-04-22 15:58 UTC
Labels: bug
