### ISSUE TITLE
HTTP response from server does not include "content-encoding" header even if the response body is encoded

### ISSUE THREAD

**Issue by pkourouklidis** [triton-inference-server/server#5185] opened 2022-12-20 15:56 UTC
**Description**
When sending an HTTP request to the server with the "accept-encoding" header set (e.g accept-encoding: gzip), the server encodes the response body but doesn't set the "content-encoding" header to the appropriate value (e.g content-encoding: gzip). As a result most clients will error out when trying to read the response. 

**Triton Information**
What version of Triton are you using?
2.28.0

Are you using the Triton container or did you build it yourself?
container version 22.11-py3

**To Reproduce**
1. Deploy a model. I used https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet1k_b0/classification/2 . You need to use the folder layout that triton accepts. /path/to/model/modelName/1/model.savedmodel/<everything downloaded from the link above>
2. Send an inference request over HTTP example:
curl -v <server endpoint> -H "Content-Type: application/json" -H "accept-encoding: gzip" -d '{"id": "1","inputs": [{"name": "input_1","shape": [1,2,2,3],"datatype": "FP32","data": [ [[0.5,0.5,0.5], [0.5,0.5,0.5]], [[0.5,0.5,0.5], [0.5,0.5,0.5]] ]}],"outputs": [{"name": "output_1"}]}'
3. curl will error out trying to read the response. If you remove the "accept-encoding" header it will work fine.

**Expected behavior**
The server should set the "content-encoding" header in the response if compression is used for the response body.

Many thanks in advance to the people that will look into this issue!

**Comment by krishung5** [comment] 2022-12-20 20:14
Thanks for reporting the issue. Filed a ticket for the team to investigate.

**Comment by dyastremsky** [comment] 2023-04-14 22:30
Can you add the compressed flag?

Let's assume your command is `curl -v -H "Content-Type: application/json" -H "accept-encoding: gzip" -d '{"id": "1","inputs": [{"name": "input_1","shape": [1,2,2,3],"datatype": "FP32","data": [ [[0.5,0.5,0.5], [0.5,0.5,0.5]], [[0.5,0.5,0.5], [0.5,0.5,0.5]] ]}],"outputs": [{"name": "output_1"}]}' ocalhost:8000/v2/models/savedmodel_zero_1_float32/infer`. You'd just add `--compressed`. This worked in my case.

The header flag was already included. However, when I tried to reproduce this, I received a "Failed writing body" error. The reason is that the content was gzipped and the output stream could not handle binary data. By adding the flag, we let curl handle decompression based on the "Content-Encoding" header. Then, you get readable plain text output.

**Comment by dyastremsky** [comment] 2023-04-19 20:38
Closing due to resolution.

**Closed by dyastremsky** 2023-04-19 20:38 UTC
Labels: bug
