### ISSUE TITLE
No performance gain in models from Tensorflow model zoo

### ISSUE THREAD

**Issue by devloper13** [triton-inference-server/server#3179] opened 2021-07-30 18:44 UTC
Please find my experiment below using the performance analyzer.

To start with, I was able to see a significant performance increase for an example image classification model available in this [https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository](url) But I couldn't replicate this for object detection models from tensorflow model zoo [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md](url) and [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md](url)

Models in Tensorflow 1 model zoo are by default dynamic. But models in Tensorflow 2 are not and requires to be converted explicitly. But there was no performance increase with increase in concurrency even after using dynamic batched models.

**inception_graphdef** (Image classification) from [https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository](url)
| Concurrency | Throughput (infer/sec) | Latency (usec) |
| ----------------- |  ------------------------------ |  ------------------ |
| 1 | 86.4 | 11723 |
| 2 | 93.2 | 21934 |
| 3 | 118.8 | 26034 |
| 4 | 138.8 | 29600 |
| 5 | 151.6 | 34089 |
| 6 | 163.2 | 38072 |
| 7 | 170.4 | 42567 |
| 8 | 179.2 | 46266 |

**Faster-RCNN Resnet101** from [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md](url)
| Concurrency | Throughput (infer/sec) | Latency (usec) |
| ----------------- |  ------------------------------ |  ------------------ |
| 1 | 8.4 | 121353 |
| 2 | 8.6 | 239451 |
| 3 | 8.4 | 371554 |
| 4 | 8 | 504217 |
| 5 | 8 | 629873 |
| 6 | 8.4 | 728557 |
| 7 | 9.2 | 819963 |
| 8 | 9 | 942298 |

**Efficient-Det D0** from [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md](url)
| Concurrency | Throughput (infer/sec) | Latency (usec) |
| ----------------- |  ------------------------------ |  ------------------ |
| 1 | 6.2 | 170510 |
| 2 | 6.2 | 328372 |
| 3 | 6.6 | 459543 |
| 4 | 6.8 | 612650 |
| 5 | 6.6 | 737998 |
| 6 | 6.6 | 866931 |
| 7 | 7 | 1005783 |
| 8 | 6.4 | 1151053 |

**Comment by CoderHam** [comment] 2021-07-30 20:27
@devloper13 did you enable dynamic batching in the model config for these models?

**Comment by devloper13** [comment] 2021-07-30 20:32
> @devloper13 did you enable dynamic batching in the model config for these models?

Yes. An example of my experiment can be found here: https://forums.developer.nvidia.com/t/performance-issue-with-dynamic-batching-on-triton-inference-server/177203

**Comment by tanmayv25** [comment] 2021-08-02 19:55
@devloper13  Can you share complete log of perf analyzer with/without dynamic batching for `EfficientDet-D1`?

> But there was no performance increase with increase in concurrency even after using dynamic batched models.

Increasing concurrency helps pipelining the requests that can hide network latencies. But their contribution will be much smaller for such time taking models (> 100ms). Using dynamic batching with high request concurrency usually helps improving the performance but it is not guaranteed and depends upon model.

For instance, for dynamic batch of 2 requests
Case1(with db):<single model execution with both requests>
Case2(without db): <model execution with first request><model execution with second request>

Usually, case 1 is faster, but an increase in tensor size might make model execution slower than two individual requests with smaller tensor size. A quick experiment would be to run perf analyzer with `-b <batch_size>` without dynamic batching and see if it is improving the performance against `-b 1`. 

Anyways, perf analyzer report will help us in understanding more about the issue.

**Comment by devloper13** [comment] 2021-08-09 08:04
> A quick experiment would be to run perf analyzer with `-b <batch_size>` without dynamic batching and see if it is improving the performance against `-b 1`.

I didn't quite understand. For a non-dynamic batch model I can't give beyond -b 1, correct?

**Comment by tanmayv25** [comment] 2021-08-09 20:41
You can either perform client-side static batching(the request themselves can have N batches) or server-side dynamic batching (N different batch size 1 requests can be merged to run N batches in a single model execution).

As long as you have `max_batch_size` specified as N in the model config, you may provide upto `-b N` without dynamic batching enabled.

**Comment by devloper13** [comment] 2021-08-11 14:15
I have some problem executing effdet1 (not dynamic), will -b = 1 and -b=2 with concurrency=1 will do?

Here is the complete report:


**1. Effdet1 (dynamic) - batch 1 - concurrency 1:5 [Avg GPU Util: 40%]**
```

*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 5 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 23
    Throughput: 4.6 infer/sec
    Avg latency: 211869 usec (standard deviation 3894 usec)
    p50 latency: 210694 usec
    p90 latency: 216763 usec
    p95 latency: 217649 usec
    p99 latency: 219053 usec
    Avg HTTP time: 212235 usec (send/recv 23010 usec + response wait 189225 usec)
  Server: 
    Inference count: 28
    Execution count: 28
    Successful request count: 28
    Avg request latency: 186678 usec (overhead 66 usec + queue 36 usec + compute input 603 usec + compute infer 180017 usec + compute output 5956 usec)

Request concurrency: 2
  Client: 
    Request count: 25
    Throughput: 5 infer/sec
    Avg latency: 394777 usec (standard deviation 7645 usec)
    p50 latency: 392760 usec
    p90 latency: 403535 usec
    p95 latency: 405725 usec
    p99 latency: 413370 usec
    Avg HTTP time: 396371 usec (send/recv 25622 usec + response wait 370749 usec)
  Server: 
    Inference count: 30
    Execution count: 30
    Successful request count: 30
    Avg request latency: 367471 usec (overhead 67 usec + queue 169484 usec + compute input 1109 usec + compute infer 190818 usec + compute output 5993 usec)

Request concurrency: 3
  Client: 
    Request count: 27
    Throughput: 5.4 infer/sec
    Avg latency: 541348 usec (standard deviation 9982 usec)
    p50 latency: 541500 usec
    p90 latency: 555787 usec
    p95 latency: 557149 usec
    p99 latency: 558004 usec
    Avg HTTP time: 540307 usec (send/recv 33306 usec + response wait 507001 usec)
  Server: 
    Inference count: 33
    Execution count: 22
    Successful request count: 22
    Avg request latency: 502174 usec (overhead 353 usec + queue 206794 usec + compute input 1310 usec + compute infer 283773 usec + compute output 9944 usec)

Request concurrency: 4
  Client: 
    Request count: 31
    Throughput: 6.2 infer/sec
    Avg latency: 694450 usec (standard deviation 13955 usec)
    p50 latency: 692152 usec
    p90 latency: 715516 usec
    p95 latency: 717310 usec
    p99 latency: 726499 usec
    Avg HTTP time: 695904 usec (send/recv 47059 usec + response wait 648845 usec)
  Server: 
    Inference count: 35
    Execution count: 17
    Successful request count: 17
    Avg request latency: 640545 usec (overhead 103 usec + queue 212313 usec + compute input 1918 usec + compute infer 402108 usec + compute output 24103 usec)

Request concurrency: 5
  Client: 
    Request count: 30
    Throughput: 6 infer/sec
    Avg latency: 873227 usec (standard deviation 20024 usec)
    p50 latency: 871432 usec
    p90 latency: 899798 usec
    p95 latency: 909048 usec
    p99 latency: 909479 usec
    Avg HTTP time: 873862 usec (send/recv 66178 usec + response wait 807684 usec)
  Server: 
    Inference count: 35
    Execution count: 14
    Successful request count: 14
    Avg request latency: 798621 usec (overhead 123 usec + queue 228641 usec + compute input 2400 usec + compute infer 528910 usec + compute output 38547 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 4.6 infer/sec, latency 211869 usec
Concurrency: 2, throughput: 5 infer/sec, latency 394777 usec
Concurrency: 3, throughput: 5.4 infer/sec, latency 541348 usec
Concurrency: 4, throughput: 6.2 infer/sec, latency 694450 usec
Concurrency: 5, throughput: 6 infer/sec, latency 873227 usec
```

**2. Effdet1 (dynamic) - batch 2 - concurrency 1:5 [Avg GPU Util: 40%]**

```
*** Measurement Settings ***
  Batch size: 2
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 5 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 11
    Throughput: 4.4 infer/sec
    Avg latency: 424424 usec (standard deviation 4613 usec)
    p50 latency: 424762 usec
    p90 latency: 431320 usec
    p95 latency: 431817 usec
    p99 latency: 431817 usec
    Avg HTTP time: 421753 usec (send/recv 51300 usec + response wait 370453 usec)
  Server: 
    Inference count: 28
    Execution count: 14
    Successful request count: 14
    Avg request latency: 365521 usec (overhead 63 usec + queue 38 usec + compute input 1187 usec + compute infer 322538 usec + compute output 41695 usec)

Request concurrency: 2
  Client: 
    Request count: 14
    Throughput: 5.6 infer/sec
    Avg latency: 748771 usec (standard deviation 13973 usec)
    p50 latency: 749394 usec
    p90 latency: 763730 usec
    p95 latency: 763730 usec
    p99 latency: 777840 usec
    Avg HTTP time: 745035 usec (send/recv 63171 usec + response wait 681864 usec)
  Server: 
    Inference count: 32
    Execution count: 16
    Successful request count: 16
    Avg request latency: 676078 usec (overhead 62 usec + queue 302191 usec + compute input 1320 usec + compute infer 330611 usec + compute output 41894 usec)

Request concurrency: 3
  Client: 
    Request count: 13
    Throughput: 5.2 infer/sec
    Avg latency: 1111594 usec (standard deviation 32264 usec)
    p50 latency: 1115049 usec
    p90 latency: 1148643 usec
    p95 latency: 1148643 usec
    p99 latency: 1178986 usec
    Avg HTTP time: 1101148 usec (send/recv 110845 usec + response wait 990303 usec)
  Server: 
    Inference count: 32
    Execution count: 11
    Successful request count: 11
    Avg request latency: 978748 usec (overhead 77 usec + queue 389793 usec + compute input 2261 usec + compute infer 520884 usec + compute output 65733 usec)

Request concurrency: 4
  Client: 
    Request count: 14
    Throughput: 5.6 infer/sec
    Avg latency: 1404407 usec (standard deviation 16519 usec)
    p50 latency: 1408471 usec
    p90 latency: 1425711 usec
    p95 latency: 1425711 usec
    p99 latency: 1432053 usec
    Avg HTTP time: 1398359 usec (send/recv 119393 usec + response wait 1278966 usec)
  Server: 
    Inference count: 36
    Execution count: 9
    Successful request count: 9
    Avg request latency: 1269894 usec (overhead 84 usec + queue 569200 usec + compute input 2986 usec + compute infer 616510 usec + compute output 81114 usec)

Request concurrency: 5
  Client: 
    Request count: 13
    Throughput: 5.2 infer/sec
    Avg latency: 1768746 usec (standard deviation 21414 usec)
    p50 latency: 1767124 usec
    p90 latency: 1800591 usec
    p95 latency: 1800591 usec
    p99 latency: 1805675 usec
    Avg HTTP time: 1768114 usec (send/recv 144378 usec + response wait 1623736 usec)
  Server: 
    Inference count: 30
    Execution count: 6
    Successful request count: 6
    Avg request latency: 1610858 usec (overhead 99 usec + queue 693927 usec + compute input 5548 usec + compute infer 805401 usec + compute output 105883 usec)

Failed to obtain stable measurement within 10 measurement windows for concurrency 5. Please try to increase the --measurement-interval.
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 4.4 infer/sec, latency 424424 usec
Concurrency: 2, throughput: 5.6 infer/sec, latency 748771 usec
Concurrency: 3, throughput: 5.2 infer/sec, latency 1111594 usec
Concurrency: 4, throughput: 5.6 infer/sec, latency 1404407 usec
Concurrency: 5, throughput: 5.2 infer/sec, latency 1768746 usec
```

**Comment by tanmayv25** [comment] 2021-08-11 21:17
@devloper13  My suspicions seems to be right.  Look closely at `Inference count` and `Execution count` being reported under `Server`. The average batch size being delivered to the TF model by Triton is `Inference count`/`Execution count`. This means dynamic batching is indeed working as intended.

Now look at the `compute infer`. This represents the average time taken to execute inference inside tensorflow library. These models in the TF model zoo scale badly with the increased batch size. The model execution doesn't seem to carry enough intra-parallelism as the example model does.

The option to push GPU usage further up would be to use more instances of the model. The will simultaneously execute the inference requests. See more [here](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#instance-groups). Try out `count: 2` or may be `count: 3`.

We have a CLI tool that can automatically derive the model configuration for best performance. See [mode analyzer](https://github.com/triton-inference-server/model_analyzer).

**Comment by devloper13** [comment] 2021-08-12 03:47
Thanks! Will try this out.

**Comment by deadeyegoodwin** [comment] 2021-09-17 20:35
Closing due to inactivity.

**Closed by deadeyegoodwin** 2021-09-17 20:35 UTC
