### ISSUE TITLE
Python backend  (BLS) abnormally consumes large GPU memory

### ISSUE THREAD

**Issue by leemengwei** [triton-inference-server/server#5196] opened 2022-12-26 09:07 UTC
**Description**
Python backend  (BLS) abnormally consumes large GPU memory

**Triton Information**
triton v22.02 from  NGC docker with some pip installs.

**To Reproduce**
I'm deploying a tensorrt model with triton. For users' convience I implemented some preprocess/postprocess to take care of raw model outputs. I'm placing tensorrt model to GPU and specifiying BLS to CPU in their config.pbtxt.

Yet python BLS script does take a lot of GPU in my case. My BLS takes care of output of one Yolov5 tensorrt model. 
Python backend itself shouln't use any GPU memory and I'm not using pytorch backend (just python scripts)...
Here's the config.pbtxt of my bls:
  backend: "python" 
```

backend: "python"

input [
  {
    name: "IMAGE"
    data_type: TYPE_UINT8
    dims: [-1,-1,3]
  },
  {
    name: "CONFIDENCE"
    data_type: TYPE_FP32
    dims: [1]
  },
  {
    name: "NMS"
    data_type: TYPE_FP32
    dims: [1]
  }
]

output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [-1, -1]
  }
]

instance_group:[
	{
    count: 4
		kind:KIND_CPU
	}
]

```
my bls model.py:
```
# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import cv2
import json
import torch
from torchvision.ops import nms
from torchvision.ops import batched_nms
from torch.utils.dlpack import from_dlpack, to_dlpack
import numpy as np
from concurrent.futures import ProcessPoolExecutor
from IPython import embed

# triton_python_backend_utils is available in every Triton Python model. You
# need to use this module to create inference requests and responses. It also
# contains some utility functions for extracting information from model_config
# and converting Triton input/output types to numpy types.
import triton_python_backend_utils as pb_utils


def xywh2xyxy(x):
    # Convert nx4 boxes from [x, y, w, h] to [x1, y1, x2, y2] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[:, 0] = x[:, 0] - x[:, 2] / 2  # top left x
    y[:, 1] = x[:, 1] - x[:, 3] / 2  # top left y
    y[:, 2] = x[:, 0] + x[:, 2] / 2  # bottom right x
    y[:, 3] = x[:, 1] + x[:, 3] / 2  # bottom right y
    return y


def letterbox(im, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleFill=False, scaleup=True, stride=32):
    # Resize and pad image while meeting stride-multiple constraints
    shape = im.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)

    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
    if not scaleup:  # only scale down, do not scale up (for better val mAP)
        r = min(r, 1.0)

    # Compute padding
    ratio = r, r  # width, height ratios
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
    if auto:  # minimum rectangle
        dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding
    elif scaleFill:  # stretch
        dw, dh = 0.0, 0.0
        new_unpad = (new_shape[1], new_shape[0])
        ratio = new_shape[1] / shape[1], new_shape[0] / shape[0]  # width, height ratios

    dw /= 2  # divide padding into 2 sides
    dh /= 2

    if shape[::-1] != new_unpad:  # resize
        im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR).astype(np.float32)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color).astype(np.float32)  # add border
    return im, np.asarray(ratio), np.asarray((left, top)), np.asarray(new_unpad)


def yolov5_preprocess(image):
    image, scale_factor, padding, new_unpad = letterbox(image, auto=False)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = np.transpose(np.asarray(image, dtype=np.float32, order='C'), (2, 0, 1))
    image = np.expand_dims(image, axis=0)
    image /= 255.0
    return image, scale_factor, padding, new_unpad

def yolov5_postprocess(result, scale_factor, padding, new_unpad, confidence_threshold=torch.as_tensor(0.25), nms_threshold=torch.as_tensor(0.5)):
    '''
    x, y, w, h, fg/bg_score, class_score1, class_score2,.....
    '''
    if confidence_threshold > 1 or confidence_threshold < 0:
        print("confidence_threshold before clip", confidence_threshold)
        confidence_threshold = torch.clip(confidence_threshold, 0, 1)
        print("confidence_threshold after clip", confidence_threshold)
    else:
        pass
    if nms_threshold > 1 or nms_threshold < 0:
        print("nms_threshold before clip", nms_threshold)
        nms_threshold = torch.clip(nms_threshold, 0, 1)
        print("nms_threshold after clip", nms_threshold)
    else:
        pass
    img_scale = torch.as_tensor([1 / scale_factor[0], 1 / scale_factor[1]])
    # candidate
    result = result[0]
    candidate_index = (result[:, 4] > confidence_threshold)
    candidate_results = result[candidate_index]
    candidate_results[:, 5:] = candidate_results[:, 4].reshape(-1,1)* candidate_results[:,5:]   # score = fg * class_score
    class_highest_score, class_idx = torch.max(candidate_results[:, 5:], axis=1)
    # real from candidate
    over_confident_index = class_highest_score > confidence_threshold
    selected_results = candidate_results[over_confident_index]
    # prepare and do nms
    class_highest_score, class_idx = torch.max(selected_results[:, 5:], axis=1)
    selected_results[:,:4] = xywh2xyxy(selected_results[:,:4])
    nms_idx = batched_nms(selected_results[:,:4], class_highest_score, class_idx, nms_threshold)

    selected_bboxes_keep = selected_results[nms_idx]
    class_highest_score = class_highest_score[nms_idx]
    class_idx = class_idx[nms_idx]

    box_x1y1 = selected_bboxes_keep[:, :2]
    box_x2y2 = selected_bboxes_keep[:, 2:4]
    min_wh = torch.full_like(box_x1y1, 0)
    max_wh = torch.full_like(box_x1y1, new_unpad[0])
    max_wh[:, 1] = new_unpad[1]
    box_x1y1 = torch.maximum(box_x1y1 - padding.to(box_x1y1.device), min_wh)
    box_x2y2 = torch.minimum(box_x2y2 - padding.to(box_x1y1.device), max_wh)
    box_x1y1 *= img_scale.to(box_x1y1.device)
    box_x2y2 *= img_scale.to(box_x1y1.device)
    detected_objects = torch.cat([box_x1y1[:, 0].unsqueeze(1), box_x1y1[:, 1].unsqueeze(1), box_x2y2[:, 0].unsqueeze(1), box_x2y2[:, 1].unsqueeze(1), class_highest_score.unsqueeze(1), class_idx.unsqueeze(1)], dim=1)
    return detected_objects


class TritonPythonModel:
    """Your Python model must use the same class name. Every Python model
    that is created must have "TritonPythonModel" as the class name.
    """

    def initialize(self, args):
        self.inference_model_name = args['model_name'].split('_', 1)[-1]

    def execute(self, requests):
        responses = []
        for request in requests:
            image = pb_utils.get_input_tensor_by_name(request, "IMAGE").as_numpy()
            confidence = pb_utils.get_input_tensor_by_name(request, "CONFIDENCE").as_numpy()[0]
            nms = pb_utils.get_input_tensor_by_name(request, "NMS").as_numpy()[0]
            image, scale_factor, padding, new_unpad = yolov5_preprocess(image)
            confidence = torch.as_tensor(confidence)
            nms = torch.as_tensor(nms)
            scale_factor = torch.from_numpy(scale_factor)
            padding = torch.from_numpy(padding)
            new_unpad = torch.from_numpy(new_unpad)
            inference_request = pb_utils.InferenceRequest(
                model_name=self.inference_model_name,
                requested_output_names=['output0'],
                inputs=[pb_utils.Tensor("images", image.astype(np.float16))]
            )
            inference_response = inference_request.exec()
            if inference_response.has_error():
                raise pb_utils.TritonModelException(inference_response.error().message())
            else:
                output = from_dlpack(pb_utils.get_output_tensor_by_name(inference_response, 'output0').to_dlpack())
                # from IPython import embed;embed()
                output = yolov5_postprocess(output, scale_factor, padding, new_unpad, confidence, nms)
                # output = pb_utils.Tensor.from_dlpack("OUTPUT", to_dlpack(output.float()))
                output = pb_utils.Tensor("OUTPUT", np.array(output.cpu()).astype(np.float32))
                response = pb_utils.InferenceResponse(output_tensors=[output])
            responses.append(response)
        return responses

    def finalize(self):
        """`finalize` is called only once when the model is being unloaded.
        Implementing `finalize` function is OPTIONAL. This function allows
        the model to perform any necessary clean ups before exit.
        """
        print('Cleaning up...')

```
 ![image](https://user-images.githubusercontent.com/17986725/209527233-bacfe2c8-2060-4dc0-ad79-af7ebdd32217.png) 
As can see above, 'kind' specifies to use 'CPU' (which perhaps is not working as it consumes my GPU mem), with 'count' copies of 4 -----which yields me 4 '975Mib' as shown in nvidia-smi. 
FYI, the script "pb_utils.get_output_tensor_by_name(inference_response, 'output0')" in BLS causes above abnormal. 
Any thought on why's that? Thank you

**Expected behavior**
1, python backend shouldn't use so much memory at any device;
2, python backend should use CPU host memory;

**Comment by leemengwei** [comment] 2022-12-26 09:20
closed as it uses torch to do post process. trying to fix on that

**Comment by leemengwei** [comment] 2023-02-24 10:37
Hi, I'm now using 22.12 version from NGC cloud, yet I still suffered from above issue------ for EACH BLS instance specified in BLS's config file, it will consume another 975MB when python backend trying to handle tensorrt inference output (which located on CUDA memory). 
I'm pretty sure it's caused by how torch's 'from_dlpack' handled trt output. My hope is that by using numpy's np.from_dlpack we can get its data without addressing additional GPU memory issue.  Yet:
`
In [16]: np.from_dlpack(pb_utils.get_output_tensor_by_name(inference_response, 'BatchedNMS').to_dlpack())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[16], line 1
----> 1 np.from_dlpack(pb_utils.get_output_tensor_by_name(inference_response, 'BatchedNMS').to_dlpack())

AttributeError: type object 'PyCapsule' has no attribute '__dlpack__'
`
Any ideas ?  thanks!

**Comment by oandreeva-nv** [comment] 2023-04-25 19:11
@leemengwei  Apologies for the late response. The issue is cause by numpy expecting `__dlpack__` method in Python_Backend Tensor. This is a newer standard of dlpack API, which we currently do not support. This will be addressed in upcoming releases.

Let me know if you have any other questions.

**Comment by dyastremsky** [comment] 2023-05-22 18:43
Closing issue due to inactivity. If you need us to reopen it for follow-up, please let us know.

**Closed by dyastremsky** 2023-05-22 18:43 UTC
