### ISSUE TITLE
python backend is much slower than the same code run in python environment

### ISSUE THREAD

**Issue by DayDayupupupup** [triton-inference-server/server#2958] opened 2021-06-04 03:52 UTC
**Description**
I deploy a python backend model with a piece of image processing code, but the inference speed of triton was much slower than run the same code run in python environment. I set timestamps in model.py's execute() function, it spends 360ms, but in python environment, the same code only spend 46ms.

**Triton Information**
21.05 py3
**Are you using the Triton container or did you build it yourself?**
container
**GPU**
T4

**Python script**
```python
import torch
from itertools import product as product
import numpy as np
from math import ceil
class PriorBox(object):
    def __init__(self, image_size=None):
        super(PriorBox, self).__init__()
        self.min_sizes = [[16, 32], [64, 128], [256, 512]]
        self.steps = [8, 16, 32]
        self.image_size = image_size
        self.feature_maps = [[ceil(self.image_size[0]/step), ceil(self.image_size[1]/step)] for step in self.steps]

    def forward(self):
        anchors = []
        print(self.feature_maps)
        for k, f in enumerate(self.feature_maps):
            print(product(range(f[0]), range(f[1])))
            min_sizes = self.min_sizes[k]
            for i, j in product(range(f[0]), range(f[1])): #every point in featuremap
                for min_size in min_sizes: #two scale anchors
                    s_kx = min_size / self.image_size[1]
                    s_ky = min_size / self.image_size[0]
                    dense_cx = [x * self.steps[k] / self.image_size[1] for x in [j + 0.5]]
                    dense_cy = [y * self.steps[k] / self.image_size[0] for y in [i + 0.5]]
                    for cy, cx in product(dense_cy, dense_cx):
                        anchors += [cx, cy, s_kx, s_ky]
        # back to torch land
        output = torch.Tensor(anchors).view(-1, 4)
        return output
import time
t1 = time.time()
priorbox = PriorBox(image_size=(1000, 750))
priors = priorbox.forward()
print('python script spends {}ms'.format((time.time()-t1)*1000))
```
**python script spends 46.28753662109375ms

**model.py**
```python
import numpy as np
import sys
import json
import torch
from itertools import product as product
from math import ceil
import triton_python_backend_utils as pb_utils

class PriorBox(object):
    def __init__(self, image_size=None):
        super(PriorBox, self).__init__()
        self.min_sizes = [[16, 32], [64, 128], [256, 512]]
        self.steps = [8, 16, 32]
        self.image_size = image_size
        self.feature_maps = [[ceil(self.image_size[0]/step), ceil(self.image_size[1]/step)] for step in self.steps]

    def forward(self):
        anchors = []
        for k, f in enumerate(self.feature_maps):
            min_sizes = self.min_sizes[k]
            for i, j in product(range(f[0]), range(f[1])): #every point in featuremap
                for min_size in min_sizes: #two scale anchors
                    s_kx = min_size / self.image_size[1]
                    s_ky = min_size / self.image_size[0]
                    dense_cx = [x * self.steps[k] / self.image_size[1] for x in [j + 0.5]]
                    dense_cy = [y * self.steps[k] / self.image_size[0] for y in [i + 0.5]]
                    for cy, cx in product(dense_cy, dense_cx):
                        anchors += [cx, cy, s_kx, s_ky]

        # back to torch land
        output = torch.Tensor(anchors).view(-1, 4)
        return output

class TritonPythonModel:

    def initialize(self, args):

        # You must parse model_config. JSON string is not parsed here
        self.model_config = model_config = json.loads(args['model_config'])

        # Get OUTPUT0 configuration
        output0_config = pb_utils.get_output_config_by_name(
            model_config, "prior_data")

        # Convert Triton types to numpy types
        self.output0_dtype = pb_utils.triton_string_to_numpy(
            output0_config['data_type'])


    def execute(self, requests):

        output0_dtype = self.output0_dtype
        responses = []

        for request in requests:

            import time
            hw = pb_utils.get_input_tensor_by_name(request, "hw").as_numpy()
            t1 = time.time()
            priorbox = PriorBox(image_size=hw)
            priors = priorbox.forward()

            print('mid process execute spend= {:.10f} ms'.format((time.time()-t1)*1000))
            prior_data = priors.data
            out_tensor_0 = pb_utils.Tensor("prior_data",
                                           np.array(prior_data.cpu().numpy()).astype(output0_dtype))

            inference_response = pb_utils.InferenceResponse(
                output_tensors=[out_tensor_0])
            responses.append(inference_response)
        return responses

    def finalize(self):
        print('Mid process Cleaning up...')
```
mid process execute spend= 360.0881099701 ms

**config.pbtxt**
```proto
name: "mid_process"
backend: "python"
input {
  name: "hw"
  data_type: TYPE_FP32
  dims: 2
}
output {
  name: "prior_data"
  data_type: TYPE_FP32
  dims: -1
  dims: 4
}
instance_group {
  count: 1
  kind: KIND_GPU
}
```
Why does this phenomenon occur and how to solve this problem？

**Comment by Tabrizian** [comment] 2021-06-04 15:43
Thanks for filing the detailed issue we have filed a ticket.

**Comment by zhaohb** [comment] 2021-06-07 01:48
@Tabrizian  Is there any progress on this issue？

**Comment by tanmayv25** [comment] 2021-11-19 20:12
I was able to reproduce the issue on my machine with Titan RTX. Thanks @DayDayupupupup  for repro steps. 
The first thing I noticed was that python script used list for image size while the model.py stored the image size as numpy array. 

When I modify the python script to use numpy array instead of list, I saw the latency jump from 69.22ms to 251ms.
Next I modified the model.py, to store image_size as list, I saw the latency drop from 359ms to 98ms.

Below are my modifications to the scripts:

### model.py
```diff
*** orig_model.py	Fri Nov 19 19:14:36 2021
--- model_repo_2/mid_process/1/model.py	Fri Nov 19 19:13:15 2021
***************
*** 11,17 ****
          super(PriorBox, self).__init__()
          self.min_sizes = [[16, 32], [64, 128], [256, 512]]
          self.steps = [8, 16, 32]
!         self.image_size = image_size
          self.feature_maps = [[ceil(self.image_size[0]/step), ceil(self.image_size[1]/step)] for step in self.steps]
  
      def forward(self):
--- 11,17 ----
          super(PriorBox, self).__init__()
          self.min_sizes = [[16, 32], [64, 128], [256, 512]]
          self.steps = [8, 16, 32]
!         self.image_size = image_size.tolist()
          self.feature_maps = [[ceil(self.image_size[0]/step), ceil(self.image_size[1]/step)] for step in self.steps]
  
      def forward(self):

```

### python script

```diff
*** orig_python_script.py	Fri Nov 19 19:21:52 2021
--- python_script.py	Fri Nov 19 19:21:24 2021
***************
*** 12,20 ****
  
      def forward(self):
          anchors = []
-         print(self.feature_maps)
          for k, f in enumerate(self.feature_maps):
-             print(product(range(f[0]), range(f[1])))
              min_sizes = self.min_sizes[k]
              for i, j in product(range(f[0]), range(f[1])): #every point in featuremap
                  for min_size in min_sizes: #two scale anchors
--- 12,18 ----
***************
*** 28,34 ****
          output = torch.Tensor(anchors).view(-1, 4)
          return output
  import time
  t1 = time.time()
! priorbox = PriorBox(image_size=(1000, 750))
  priors = priorbox.forward()
  print('python script spends {}ms'.format((time.time()-t1)*1000))
--- 26,33 ----
          output = torch.Tensor(anchors).view(-1, 4)
          return output
  import time
+ np_array = np.array([1000, 750])
  t1 = time.time()
! priorbox = PriorBox(image_size=np_array)
  priors = priorbox.forward()
  print('python script spends {}ms'.format((time.time()-t1)*1000))
```

## Summary

|      | python script with list | model.py with list | python script with np array |  model.py with np array|
| ----------- | ----------- | ----------- | ----------- | ----------- |
| Latency in ms | 69.22 |  98 | 251 |  359 |

## Conclusion

Indexing in numpy array is slower than indexing elements in list and it is being done twice per each iteration. This being said,
There is still the difference of 30ms which must be investigated.. Running some experiments to understand the same.

**Comment by zhaohb** [comment] 2021-11-21 07:01
@tanmayv25 it is great, thank you very much, this is very important to us, we will modify our code and do test.

**Comment by tanmayv25** [comment] 2021-11-25 00:18
Ok.. So, I ran my experiments again collecting numbers for multiple inferences. I am using torch version 1.10.0 and latest 21.11 Triton.

The numbers are almost identical. The small difference may be coming because of the additional CPU activities occurring for Triton.

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

  | Mean Latency | Max Latency | Min Latency | p99 | p95 | p90 | p50
-- | -- | -- | -- | -- | -- | -- | --
Triton | 75.16 | 93.49 | 73.6 | 84.97 | 76.73 | 76.48 | 74.54
Python Script | 69.83 | 86.22 | 68.03 | 72.83 | 72.38 | 70.93 | 69.55


</body>
</html>

Closing the issue for now as the perf difference is not significant.

**Closed by tanmayv25** 2021-11-25 00:18 UTC
Labels: performance, investigating
