### ISSUE TITLE
Python client grpcio==1.42.0 requirement too strict

### ISSUE THREAD

**Issue by zeruniverse** [triton-inference-server/server#5220] opened 2023-01-05 06:01 UTC
**Description**

I have to use tritonclient with other python packages that requires newer grpcio, so currently I have to manually patch them everytime. In the requirements.txt, comment said GRPC has memory leak issue on 1.43.0, but I saw on https://github.com/grpc/grpc/issues/28513 last comment, the gRPC team suggests memory leak is not from grpc. In this case, is it possible to soften the grpc requirement (allow installation of latest versions)?

**Triton Information**
r22.12

**To Reproduce**

`pip install tritonclient[grpc]` will force installation of grpcio==1.42.0

**Expected behavior**

allow any grpcio versions >=1.42.0

**Comment by kthui** [comment] 2023-01-05 22:43
@GuanLuo @jbkyang-nvi Can you comment on this, regarding Python gRPC version and memory leak issue?

**Comment by jbkyang-nvi** [comment] 2023-01-06 22:46
There's a definite leak that is dependent on the grpcio == 1.43.0. We're still looking into the problem. Note we haven't verified if the issue is _not_ related to grpc 1.43.0 or that it's resolved in 1.51.1 for issue https://github.com/grpc/grpc/issues/28513.

**Comment by zeruniverse** [comment] 2023-01-08 07:43
Hi @jbkyang-nvi ,

Thanks for your reply. It would be great if this can be verified and this restriction can be lifted soon.

**Comment by jbkyang-nvi** [comment] 2023-01-17 07:59
https://github.com/triton-inference-server/client/pull/225

**Closed by jbkyang-nvi** 2023-01-17 07:59 UTC
