### ISSUE TITLE
Python backend custom metrics: Unsupported TRITONSERVER_MetricKind

### ISSUE THREAD

**Issue by sandeshan** [triton-inference-server/server#5901] opened 2023-06-06 00:02 UTC
I have a helper method to create a custom metric in my python backend as shown below. This method is called within the model's `execute()` method, and then the metric value is incremented as needed.

Upon running the model, I'm getting the following error:

```sh
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'retrieval', Failed to process the request(s) for model instance '...', 

message: 
TritonModelException: Failed to increment metric value: Failed to process the custom metrics request for model '...', 

message: Unsupported TRITONSERVER_MetricKind
```

As seen in the code block below, I'm using the MetricKind of `COUNTER`, which is supposed to be supported. Any help on how this can be debugged/root caused would be appreciated.

```py
import triton_python_backend_utils as pb_utils

def create_custom_triton_metric(
        metric_name: str,
        description: str,
        model_name: str,
        version="1.0",
):
    metrics_prefix = "custom"
    custom_metric_name = f'{metrics_prefix}_{metric_name}'

    metric_family = pb_utils.MetricFamily(
        name=custom_metric_name,
        description=description,
        kind=pb_utils.MetricFamily.COUNTER
    )

    metric = metric_family.Metric(
        labels={"model": model_name, "version": version}
    )

    return metric
```

```py
# usage in execute():

from custom_metrics_python_lib.metric_utils import create_custom_triton_metric

def execute(self, requests):
    for request in requests:

        request_process_latency_metric_ns = create_custom_triton_metric(
            metric_name="request_process_latency_ns",
            description="Time spent processing request (in nanoseconds)",
            model_name="open_search",
        )

        # Record the start time of processing the requests
        start_ns = time.time_ns()

        # ... processing logic ...

        # Record the end time of processing the requests
        end_ns = time.time_ns()

        # Update metric to track request processing latency.
        request_process_latency_metric_ns.increment(end_ns - start_ns)

```

Triton server version: 23.05
Image source: Official Nvidia image repo

**Comment by Tabrizian** [comment] 2023-06-06 15:29
cc @krishung5

**Comment by krishung5** [comment] 2023-06-07 21:04
Hi @sandeshan, I think the issue is that `metric_family` goes out of scope when returning from the `create_custom_triton_metric` function. Could you return both `metric_family` and `metric` from the `create_custom_triton_metric` function and see if the error still occurs? I will update the document to cover the lifetime of custom metrics object. Also looking into how we can improve the error message to have a better description.

**Comment by sandeshan** [comment] 2023-06-09 22:14
@krishung5 I updated my code to return both `metric_family` and `metric` from the `create_custom_triton_metric` function. With this the error went away, but I don't see the custom metric being published. See my updated code below. 

For each request, I am creating a new metric, and then using `.increment()` to capture the processing time (end - start). Is there a final step I'm missing to actually publish the metric?

```py
import triton_python_backend_utils as pb_utils

def create_custom_triton_metric(
        metric_name: str,
        description: str,
        model_name: str,
        version="1.0",
):
    metrics_prefix = "custom"
    custom_metric_name = f'{metrics_prefix}_{metric_name}'

    metric_family = pb_utils.MetricFamily(
        name=custom_metric_name,
        description=description,
        kind=pb_utils.MetricFamily.COUNTER
    )

    metric = metric_family.Metric(
        labels={"model": model_name, "version": version}
    )

    return metric_family, metric
```

```py
# usage in execute():

from custom_metrics_python_lib.metric_utils import create_custom_triton_metric

def execute(self, requests):
    for request in requests:

        request_process_latency_metric_family, request_process_latency_metric_ns = create_custom_triton_metric(
            metric_name="request_process_latency_ns",
            description="Time spent processing request (in nanoseconds)",
            model_name="open_search",
        )

        # Record the start time of processing the requests
        start_ns = time.time_ns()

        # ... processing logic ...

        # Record the end time of processing the requests
        end_ns = time.time_ns()

        # Update metric to track request processing latency.
        request_process_latency_metric_ns.increment(end_ns - start_ns)

```

**Comment by rmccorm4** [comment] 2023-06-09 22:23
Hi @sandeshan,

You're probably not seeing the metric published because the metric is going out of scope and getting deleted after each execute() returns.

If you add some class member like `self.metrics = []` and `self.metric_families = []` and append each new metric to the class member, it should keep them in scope for the life of the model, so you should see them published while the model is loaded.

**Comment by rmccorm4** [comment] 2023-06-09 22:26
Out of curiosity, why are you adding a new metric for every request? Why not increment or update the existing metric and calculate the difference or the average?

**Closed** 2023-06-12 21:33 UTC

**Comment by sandeshan** [comment] 2023-06-12 22:43
@rmccorm4 @krishung5

Follow-up question: Is there a recommendation on clean up of the metric objects? If I create two lists to hold the metric objects in memory, is there a risk of memory issues as the model is run over a long period of time? 

Does the Triton server backend take care of cleaning up the custom metric objects? If not, and it needs to be done manually, is there a lifecycle event that lets me know when metric objects can be cleaned up or deleted?

**Comment by rmccorm4** [comment] 2023-06-12 22:59
> Follow-up question: Is there a recommendation on clean up of the metric objects? If I create two lists to hold the metric objects in memory, is there a risk of memory issues as the model is run over a long period of time?

I'm not sure how much memory each metric/family is taking up off the top of my head. If you plan to create thousands/millions of them, you may notice significant enough memory usage increases. However, you can manually prune these lists as they reach a certain size if you intend to keep a bunch of them around and only want the N most recent ones. 

When the model is unloaded, the backend would take care of cleaning up any objects associated with the model. For metrics specifically, it would clean them up if your model was holding the last references to them. If other models were accessing the same metrics, then they may stick around until all models referencing the metrics get cleaned up.
