### ISSUE TITLE
Random spikes in RAM while using Triton Inference

### ISSUE THREAD

**Issue by rajsrujan77** [triton-inference-server/server#6143] opened 2023-08-04 11:36 UTC
We are observing spikes in RAM (~40GB) while using Triton Inference server. We have python backend models (CPU and GPU) and TensorRT models. And we also use BLS in the pipeline.

Environment
Trition verison: 22.12 ([nvcr.io/nvidia/tritonserver:22.12-py3](http://nvcr.io/nvidia/tritonserver:22.12-py3))
Python Backend verison: r21.08
TensorRT Version: 8.5.1
GPU Type: GeForce RTX 2080 SUPER
Nvidia Driver Version: 510.108.03
CUDA Version: 11.8
CUDNN Version: 8.7.0 GA
Operating System + Version: Ubuntu 20.04
Python Version (if applicable): 3.7

Relevant Files
![image](https://github.com/triton-inference-server/server/assets/13798104/087ae2ea-0430-4d03-82dd-8f1989325c47)

Steps To Reproduce
We couldn’t find the exact reason for the spikes, so cannot specify the steps to reproduce. This issue happens mostly on long runs (8-12 hrs) of Triton Server.

**Comment by dyastremsky** [comment] 2023-08-04 17:06
This is going to be hard to root cause without a reproduction. Assuming you have gotten rid of other possible causes (e.g. other programs, huge spike in requests, etc.), I'm not sure what could be causing this. Something I am noting is that you are using Triton 22.12 but an old version of Python backend (2 years old). It could be worth upgrading as we have continued to optimize Python backend and remove bugs.

CC: @Tabrizian @krishung5

**Comment by rajsrujan77** [comment] 2023-08-07 05:46
Hey @dyastremsky , We have tried upgrading python version, but we are facing this issue after upgrading, https://github.com/triton-inference-server/server/issues/6137

> This is going to be hard to root cause without a reproduction. Assuming you have gotten rid of other possible causes (e.g. other programs, huge spike in requests, etc.), I'm not sure what could be causing this. Something I am noting is that you are using Triton 22.12 but an old version of Python backend (2 years old). It could be worth upgrading as we have continued to optimize Python backend and remove bugs.
> 
> CC: @Tabrizian @krishung5

**Comment by dyastremsky** [comment] 2023-08-07 18:07
Thanks for trying that. However, I meant the Triton version, not the Python version. For example, upgrading the Triton version to the latest container (23.07) with the latest Python backend (matching, should also be 23.07).

**Comment by rajsrujan77** [comment] 2023-08-08 04:57
> Thanks for trying that. However, I meant the Triton version, not the Python version. For example, upgrading the Triton version to the latest container (23.07) with the latest Python backend (matching, should also be 23.07).

@dyastremsky The main reason for not moving to Triton 23.x is the CUDA version. Our pipelines are currently tested/works on CUDA 11.x and the last version of Triton that supports CUDA 11.x is 22.12, hence, we chose the version.

**Comment by dyastremsky** [comment] 2023-08-08 17:27
Unfortunately, it does not make sense for us to debug an issue in a backend that is 2 years old and does not match the Triton server you are using. Especially given the complexity of this issue.

The very first thing we'd ask is that you'd try to run this in a very recent version of Triton server with a matching backend version. If this is a bug, it is possible it has been fixed in the last couple of years. And any fixes would only be applied going forward.

If you need more hands-on support, I recommend going through [NVIDIA AI Enterprise support (NVAIE)](https://www.nvidia.com/en-us/data-center/products/ai-enterprise/).

**Closed by dyastremsky** 2023-08-08 17:27 UTC
Labels: bug

**Comment by rajsrujan77** [comment] 2023-09-26 06:51
@dyastremsky Thanks. We didn't face this issue again after upgrading Triton to 23.07.

**Comment by dyastremsky** [comment] 2023-09-26 17:24
Wonderful, happy to hear that, Raj! Thank you for updating us.
