### ISSUE TITLE
How to deploy Detectron2 model using pytorch?

### ISSUE THREAD

**Issue by YongTaek** [triton-inference-server/server#2024] opened 2020-09-15 11:45 UTC
I export detectron2 model to torchscript and try to deploy in triton server
*I use detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl  

my config.pbtxt is below

```
name: "testmodel"
platform: "pytorch_libtorch"
max_batch_size: 0
input [
  {
    name: "conv2d__0"
    data_type: TYPE_FP32
    dims: [1056, 1920,3]
  }
]
output [
  {
    name: "bboxex__0"
    data_type: TYPE_FP32
    dims: [-1,4]
  },
  {
    name: "scores__1"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "classes__2"
    data_type: TYPE_INT32
    dims: [-1]
  },
  {
    name: "masks__3"
    data_type: TYPE_BOOL
    dims: [-1]
  }
]
```

I inference to model but I receive an error

```
File "code/__torch__/detectron2/modeling/meta_arch/rcnn.py", line 348, in forward
    _9 = torch.slice(max_size, 0, -2, 9223372036854775807, 1)
    _10 = torch.add(_9, CONSTANTS.c2, alpha=1)
    _11 = torch.floor_divide(_10, CONSTANTS.c3)
          ~~~~~~~~~~~~~~~~~~ <--- HERE
    max_size0 = torch.cat([_8, torch.mul(_11, CONSTANTS.c3)], 0)
    h = ops.prim.NumToTensor(torch.size(t, 1))
Traceback of TorchScript, original code (most recent call last):
/usr/local/lib/python3.6/dist-packages/torch/tensor.py(424): __floordiv__
/usr/local/lib/python3.6/dist-packages/torch/tensor.py(22): wrapped
/usr/local/lib/python3.6/dist-packages/detectron2/structures/image_list.py(98): from_tensors
/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py(222): preprocess_image
/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py(196): inference
/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py(149): forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(704): _slow_forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(720): _call_impl
/root/detectron2/tools/deploy/mymodel.py(70): forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(704): _slow_forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(720): _call_impl
/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py(1109): trace_module
/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py(955): trace
<stdin>(1): 
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

before this error I receive any times same device error and I modify cpu operations to gpu operations like .cuda()

How should I solve this problem? Or is there a way to deploy the detectron2 model?

thank you for reading

**Comment by CoderHam** [comment] 2020-09-16 17:59
When tracing the model did you ensure you used torch.no_grad i.e. model in eval mode?
Could you share your model generation script?

**Comment by YongTaek** [comment] 2020-09-21 00:44
Sorry too late.

This is my model for generation script.
cfg  in PartialModule is detectron2 cfg

```
class PartialModule(torch.nn.Module):
    def __init__(self, cfg):
        super(PartialModule, self).__init__()
        self.cfg = cfg.clone()
        model = build_model(cfg)
        model.eval()
        metadata = MetadataCatalog.get(cfg.DATASETS.TEST[0])
        checkpointer = DetectionCheckpointer(model)
        checkpointer.load(cfg.MODEL.WEIGHTS)
        self.model = model

    def forward(self, x):
        with torch.no_grad():
            image = ImageList.from_tensors([x.permute(2, 0, 1),])
            features = self.model.backbone(image.tensor)
            proposals, _ = self.model.proposal_generator(image, features)
            print(proposals)
            return proposals[0]
```

cfg code is below.

```
cfg = get_cfg()
cfg.DATALOADER.NUM_WORKERS = 0
cfg.MODEL.WEIGHTS = 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'
cfg.MODEL.DEVICE = 'cpu'
cfg = add_export_config(cfg)
cfg.merge_from_file('/root/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml')
cfg.freeze()
```

**Comment by CoderHam** [comment] 2020-09-22 23:48
I don't see the part of your code that converts the model to torchscript. Are you using tracing for the same?

**Comment by whillas** [comment] 2020-10-02 05:08
Hey, we're also trying to deploy a Detectron2 model from pytorch. Did you figure this out?

**Comment by YongTaek** [comment] 2020-10-03 17:24
Sorry. I want to deploy too. But there is cpu operation in nms of torchvision. so I can't.

**Comment by CoderHam** [comment] 2020-10-09 18:23
There will be a fix for the torchvision build in the upcoming release that will allow you to run Detectron 2 successfully.

**Comment by whillas** [comment] 2020-10-11 22:00
@CoderHam is that going to be in the 20.10 image?

**Comment by CoderHam** [comment] 2020-11-30 19:36
This was fixed in 20.11. Please re-open if you are still seeing the torchvision ops not working on GPU.

**Closed by CoderHam** 2020-11-30 19:36 UTC

**Comment by s-rog** [comment] 2021-05-06 02:36
@CoderHam This is still broken on 20.11 and 21.02, will test on 21.04 soon and update.

**Comment by bcvanmeurs** [comment] 2021-05-14 15:23
I have the exact same problem on triton 21.04, I don't fully understand why it doesn't work in triton but the exported torchscript does in Python.

**Comment by CoderHam** [comment] 2021-05-14 16:37
@s-rog 
The error
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
Can be caused by a known multi instance issue. We have an [open issue](https://github.com/pytorch/pytorch/issues/27902) against pytorch for this. Are you running multiple instances of the pytorch model?

On a side note: https://github.com/pytorch/pytorch/issues/43874 is a related issue that confirms that the deprecation error might be correct i.e. the pytorch team is in the work to deprecate the floor_divide function.

@bcvanmeurs Triton's API are designed to pass inputs via tensors i.e. as our API currently stands we cannot specify that a specific input as a tuple. Support for tuples would require re-working our API. This means for now we can only pass inputs as tensors to pytorch.

**Comment by bcvanmeurs** [comment] 2021-05-15 09:56
Thanks for the answer @CoderHam. For clarification, I was referring to the error of @s-rog when running a Detectron2 retinanet model, exported to Torchscript (with tracing) on Triton. 

When I load the traced model in Python with torch.jit.load() it works all fine.

But when I add the same model to the triton model repository I get the same error:

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

I am stuck on how to debug it, I made sure all input tensors and the model itself are on the gpu when tracing, but that didn't help. I can't find a lot of information about this RuntimeError.
Any suggestions? Thanks!

**Comment by s-rog** [comment] 2021-05-15 10:08
@CoderHam we are running a single model instance in triton.

The only way I succeeded in running detectron2 in triton was running it in python backend in eager mode (installing torch and detectron). Neither the python nor pytorch backends can run the torchscript version, despite it working correctly outside triton.

**Comment by mdable2** [comment] 2021-09-10 17:12
Any updates on this? I am facing the same issue.

**Comment by CoderHam** [comment] 2021-09-13 23:59
@mdable2 Are you facing the issue:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
If so I would try to run the TorchScript model in native pytorch first to debug and understand the cause of this error. It originates inside pytorch and is likely caused by some tensor/s being loaded on cpu by the model.

**Comment by CescMessi** [comment] 2021-11-19 13:09
I had the same problem and found the solution. This problem is indeed caused by the tensor `max_size`, which is a tensor in cpu. When I modified the detectron2 code to move the variable to the gpu, Triton worked fine. The code is [here](https://github.com/facebookresearch/detectron2/blob/7801ac3d595a0663d16c0c9a6a339c77b2ddbdfb/detectron2/structures/image_list.py#L83), I just added `.to('cuda')` to make it work. Another solution is to modify the torchscript code. Just unzip torchscript model file and modify the corresponding code. In FasterRCNN model, the code is in `archive/code/__torch__/detectron2/export/flatten.py`, and add a line `max_size = torch.to(max_size, dtype=4, layout=0, device=torch.device("cuda"), pin_memory=None, non_blocking=False, copy=False, memory_format=None)` after `max_size` appear. Then zip the folder, it can also work in Triton.

I don't know if the problem comes from detectron2 or Triton, although the problem was solved by modifying the detectron2 code, the original torchscript model works fine in pytorch. I hope the bug can be fixed soon. @stella-ds @CoderHam

**Comment by stella-ds** [comment] 2021-11-19 14:51
Thank you @CescMessi!  Will try it out!

**Comment by DDyzonepiece** [comment] 2022-01-17 09:22
Thank you@CescMessi  it works!

**Comment by xxxpsyduck** [comment] 2022-03-01 02:30
@stella-ds Can you share the way to get input and output layer names and shapes?
