### ISSUE TITLE
vector length overflow

### ISSUE THREAD

**Issue by hutao568** [triton-inference-server/server#5664] opened 2023-04-20 06:21 UTC
![image](https://user-images.githubusercontent.com/17766186/233275749-4e84761e-e4ac-4b3a-a3d0-9554312604f7.png)

**Comment by dyastremsky** [comment] 2023-04-20 18:47
Thanks for submitting this error, @hutao568. Can you provide reproduction instructions using the bug report template below?

**Description**
A clear and concise description of what the bug is.

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
A clear and concise description of what you expected to happen.

**Comment by hutao568** [comment] 2023-04-21 08:26
When sending a large file to the Triton server, it will cause the service to crash; the Triton server deployed in this way is relatively fragile and easy to be attacked.

In nvcr.io/nvidia/tritonserver:22.10-py3 environment, when a particularly large string is sent to the service, this happens

**Comment by hutao568** [comment] 2023-04-21 08:27
# my server
import json
import numpy as np
import triton_python_backend_utils as pb_utils


class TritonPythonModel:
    """Your Python model must use the same class name. Every Python model
    that is created must have "TritonPythonModel" as the class name.
    """

    def initialize(self, args):
        """`initialize` is called only once when the model is being loaded.
        Implementing `initialize` function is optional. This function allows
        the model to intialize any state associated with this model.
        Parameters
        ----------
        args : dict
          Both keys and values are strings. The dictionary keys and values are:
          * model_config: A JSON string containing the model configuration
          * model_instance_kind: A string containing model instance kind
          * model_instance_device_id: A string containing model instance device ID
          * model_repository: Model repository path
          * model_version: Model version
          * model_name: Model name
        """

        # You must parse model_config. JSON string is not parsed here
        self.model_config = model_config = json.loads(args['model_config'])


    def execute(self, requests):
        """
        requests : list
          A list of pb_utils.InferenceRequest
        Returns
        -------
        list
          A list of pb_utils.InferenceResponse. The length of this list must
          be the same as `requests`
        """


        responses = []

        # Every Python backend must iterate over everyone of the requests
        # and create a pb_utils.InferenceResponse for each of them.
        for request in requests:
            in_0 = pb_utils.get_input_tensor_by_name(request, "input")
            out_tensor_0 = pb_utils.Tensor("output", np.array([1, 2, 3, 4, 5, 6, 7, 8]))
            inference_response = pb_utils.InferenceResponse(output_tensors=[out_tensor_0])
            responses.append(inference_response)
        return responses

    def finalize(self):
        """`finalize` is called only once when the model is being unloaded.
        Implementing `finalize` function is OPTIONAL. This function allows
        the model to perform any necessary clean ups before exit.
        """
        print('Cleaning up...')

**Comment by hutao568** [comment] 2023-04-21 08:27
my config
name: "custom_model"
backend: "python"
input [
  {
    name: "input"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, -1, 4 ]
  }
]

**Comment by hutao568** [comment] 2023-04-21 08:28
# my client
import requests
import numpy as np
import json
if __name__ == "__main__":
    datas = np.ones(shape=(1000000000)).tolist()
    datas = json.dumps(datas)
    request_data = {
    "inputs": [{
        "name": "input",
        "shape": [1],
        "datatype": "BYTES",
        "data": [datas]
    }],
    "outputs": [{"name": "output"}]
}
    res = requests.post(url="http://localhost:8004/v2/models/custom_model/versions/1/infer",json=request_data).json()
    print(res)

~

**Comment by Tabrizian** [comment] 2023-05-01 17:39
@hutao568  I'm not able to reproduce this issue. The client either gets killed because of OOM or the server would just respond normally.

**Comment by Tabrizian** [comment] 2023-05-16 14:51
Closing due to in-activity.

**Closed by Tabrizian** 2023-05-16 14:51 UTC
Labels: bug, investigating
