### ISSUE TITLE
Error when using models with zero-length inputs

### ISSUE THREAD

**Issue by janstrohbeck** [triton-inference-server/server#5972] opened 2023-06-21 12:00 UTC
**Description**
When using a pytorch model with dynamic inputs, e.g. shape [-1] in the model config, and giving the model an input with a total byte size of 0, e.g. inputs of shape [0] or [2, 0], the triton server crashes with an error (see below).

My use case are graph convolutional networks, which can sometimes have empty inputs, for example if a graph is not connected (-> empty list of indices). See also this issue #5899.

```
terminate called after throwing an instance of 'c10::Error'
  what():  The specified pointer resides on host memory and is not registered with any CUDA device.
Exception raised from getDeviceFromPtr at /opt/pytorch/pytorch/aten/src/ATen/cuda/CUDADevice.h:17 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x7fef805c703e in /opt/tritonserver/backends/pytorch/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x7d (0x7fef8058d319 in /opt/tritonserver/backends/pytorch/libc10.so)
frame #2: <unknown function> + 0xd69dff (0x7feef545edff in /opt/tritonserver/backends/pytorch/libtorch_cuda.so)
frame #3: at::TensorMaker::make_tensor() + 0x9b5 (0x7fef2f4f0f95 in /opt/tritonserver/backends/pytorch/libtorch_cpu.so)
frame #4: <unknown function> + 0x20112 (0x7fef806d4112 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #5: <unknown function> + 0x264b5 (0x7fef806da4b5 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #6: TRITONBACKEND_ModelInstanceExecute + 0x52b (0x7fef806dce8b in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #7: <unknown function> + 0x17c114 (0x7fef8d866114 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #8: <unknown function> + 0x17c430 (0x7fef8d866430 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #9: <unknown function> + 0x27c3f1 (0x7fef8d9663f1 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #10: <unknown function> + 0x180504 (0x7fef8d86a504 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #11: <unknown function> + 0xdc2b3 (0x7fef8d1592b3 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #12: <unknown function> + 0x94b43 (0x7fef8cee9b43 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #13: clone + 0x44 (0x7fef8cf7abb4 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Signal (6) received.
 0# 0x0000563A29EDC63D in tritonserver
 1# 0x00007FEF8CE97520 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# pthread_kill in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# raise in /usr/lib/x86_64-linux-gnu/libc.so.6
 4# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 5# 0x00007FEF8D11FBBE in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007FEF8D12B24C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007FEF8D12B2B7 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 8# 0x00007FEF8D12B518 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 9# c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) in /opt/tritonserver/backends/pytorch/libc10.so
10# 0x00007FEEF545EDFF in /opt/tritonserver/backends/pytorch/libtorch_cuda.so
11# at::TensorMaker::make_tensor() in /opt/tritonserver/backends/pytorch/libtorch_cpu.so
12# 0x00007FEF806D4112 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
13# 0x00007FEF806DA4B5 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
14# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
15# 0x00007FEF8D866114 in /opt/tritonserver/bin/../lib/libtritonserver.so
16# 0x00007FEF8D866430 in /opt/tritonserver/bin/../lib/libtritonserver.so
17# 0x00007FEF8D9663F1 in /opt/tritonserver/bin/../lib/libtritonserver.so
18# 0x00007FEF8D86A504 in /opt/tritonserver/bin/../lib/libtritonserver.so
19# 0x00007FEF8D1592B3 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
20# 0x00007FEF8CEE9B43 in /usr/lib/x86_64-linux-gnu/libc.so.6
21# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

Signal (11) received.
 0# 0x0000563A29EDC63D in tritonserver
 1# 0x00007FEF8CE97520 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# 0x00007FEF8D11FBBE in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 4# 0x00007FEF8D12B24C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007FEF8D12B2B7 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007FEF8D12B518 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) in /opt/tritonserver/backends/pytorch/libc10.so
 8# 0x00007FEEF545EDFF in /opt/tritonserver/backends/pytorch/libtorch_cuda.so
 9# at::TensorMaker::make_tensor() in /opt/tritonserver/backends/pytorch/libtorch_cpu.so
10# 0x00007FEF806D4112 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
11# 0x00007FEF806DA4B5 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
12# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
13# 0x00007FEF8D866114 in /opt/tritonserver/bin/../lib/libtritonserver.so
14# 0x00007FEF8D866430 in /opt/tritonserver/bin/../lib/libtritonserver.so
15# 0x00007FEF8D9663F1 in /opt/tritonserver/bin/../lib/libtritonserver.so
16# 0x00007FEF8D86A504 in /opt/tritonserver/bin/../lib/libtritonserver.so
17# 0x00007FEF8D1592B3 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
18# 0x00007FEF8CEE9B43 in /usr/lib/x86_64-linux-gnu/libc.so.6
19# clone in /usr/lib/x86_64-linux-gnu/libc.so.6
```

**Triton Information**
What version of Triton are you using? 23.05

Are you using the Triton container or did you build it yourself? Official docker images, both for server and client

**To Reproduce**

See [this minimal reproducible example](https://github.com/janstrohbeck/mre_triton_issue_emtpy_tensors). The following snippets are copied from there.

Simple Pytorch model which supports empty tensors at the input, as well as non-empty tensors:
```py
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        # Handle empty tensor (this is just a toy example)
        tmp = [0, 0] if x.shape[0] > 0 else [1, 1]
        return torch.tensor(tmp, dtype=torch.long)

model = Model()
scripted_model = torch.jit.script(model)

inputs = [
    torch.empty((0,), dtype=torch.long),
    torch.zeros((1,), dtype=torch.long),
]
# In Pytorch, both inputs can be used successfully:
for x in inputs:
    print(model(x), scripted_model(x))

# Save the model for Triton
torch.jit.save(scripted_model, 'model_repository/test_model/1/model.pt')
```

config.pbtxt:
```
name: "test_model"
backend: "pytorch"
max_batch_size: 0
input [
  {
    name: "x"
    data_type: TYPE_FP32
    dims:  [-1]
  }
]
output [
  {
    name: "result"
    data_type: TYPE_INT64
    dims:  [2]
  }
]
...
```

Client:
```py
import grpc
from tritonclient.grpc import service_pb2
from tritonclient.grpc import service_pb2_grpc

if __name__ == '__main__':
    model_name = "test_model"
    model_version = "1"

    # Create gRPC stub for communicating with the server
    channel = grpc.insecure_channel("localhost:8001")
    grpc_stub = service_pb2_grpc.GRPCInferenceServiceStub(channel)

    inputs = [[0], []]

    for x in inputs:
        print("Input:", x)
        request = service_pb2.ModelInferRequest()
        request.model_name = model_name
        request.model_version = model_version
        # request.id = "my request id"

        input = service_pb2.ModelInferRequest().InferInputTensor()
        input.name = "x"
        input.datatype = "FP32"
        input.shape.extend([len(x)])
        request.inputs.extend([input])

        output = service_pb2.ModelInferRequest().InferRequestedOutputTensor()
        output.name = "result"
        request.outputs.extend([output])

        request.raw_input_contents.extend([bytes(x)])

        response = grpc_stub.ModelInfer(request)
        print("model infer:\n{}".format(response))
```

I want to note that I also get this error using my original C++ code with a more complex model and using CUDA shared memory. There, for empty tensors, I allocate 1 byte for each input using cudaMalloc, which means that the CUDA pointers are definitively valid (but the shapes still include zeros). The error message `pointer resides on host memory and is not registered with any CUDA device` might, thus, be a bit misleading, since it occurs with both CPU and CUDA inputs. I suspect that empty shapes might internally always lead to a nullpointer being passed to the libtorch backend, irregardless of the original pointer that was passed by the Triton client?

**Expected behavior**
The model should be executed successfully, since the original pytorch model can also be successfully executed with empty tensors at the input (see minimal example).

**Comment by kthui** [comment] 2023-06-22 01:29
Thanks for reporting the issue. I have created a ticket for us to investigate further. DLIS-5056

**Comment by kthui** [comment] 2023-08-03 17:46
It is under triage.
cc @Tabrizian

**Comment by janstrohbeck** [comment] 2023-09-01 07:39
I reproduced the error in the new release 2.37.0 and updated the instructions to reproduce the bug in my [sample repo](https://github.com/janstrohbeck/mre_triton_issue_emtpy_tensors).

**Comment by Tabrizian** [comment] 2023-09-01 15:12
I should be able to fix this issue soon. Will let you know as soon as I have an update. Sorry about the delay.

**Comment by janstrohbeck** [comment] 2023-11-08 14:46
@Tabrizian do you have an idea what piece of code could be the issue? I would have a look at it myself, if I knew where to start looking for the issue. From a first look, it was not immediately obvious which part of the code could be the problem.

**Comment by yongbinfeng** [comment] 2023-12-06 19:18
in case it might be helpful, we also run into simiar crashings on GPUs with zero-size inputs. 

In our case the crashing is caused by `torch::from_blob` function here https://github.com/triton-inference-server/pytorch_backend/blob/main/src/libtorch.cc#L2194-L2196
and we have a quick fix https://github.com/yongbinfeng/pytorch_backend/commit/e80ff030c66a2ca50b5acc4e9cbf1fceb343a2f2 which avoids calling `torch::from_blob` but creating a torch tensor directly for zero-size inputs.

**Comment by Tabrizian** [comment] 2023-12-07 16:23
Sorry for the delay I was OOTO for the past few weeks. @yongbinfeng Thanks for identifying the fix. Could you please create a PR so that we can review/merge this change? You also need to fill in the CLA instructions as instructed here: https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md

**Comment by janstrohbeck** [comment] 2023-12-12 13:00
@yongbinfeng Thank you very much for your proposed fix. I have tested it and it does indeed solve the issue!

**Comment by yongbinfeng** [comment] 2023-12-12 22:38
> Sorry for the delay I was OOTO for the past few weeks. @yongbinfeng Thanks for identifying the fix. Could you please create a PR so that we can review/merge this change? You also need to fill in the CLA instructions as instructed here: https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md

Thanks! Done here is the PR: https://github.com/triton-inference-server/pytorch_backend/pull/120

(For the CLA instructions I think I've done that in April 2021 via Fermilab.)

**Comment by Tabrizian** [comment] 2024-01-04 15:59
Closing the issue as the PR has been merged! Thanks @yongbinfeng for the contribution and @janstrohbeck for raising this issue.

**Closed by Tabrizian** 2024-01-04 15:59 UTC
Labels: bug
