### ISSUE TITLE
 How to set request id in Generate？

### ISSUE THREAD

**Issue by Missmiaom** [triton-inference-server/server#6962] opened 2024-03-08 07:08 UTC
This doesn't seem to work

/v2/models/ensemble/generate
```
{
    "text_input": "...",
    "parameters": {
        "id": "123",
    },
    "sequence_id": "456"
}
```

verbose log:

![image](https://github.com/triton-inference-server/server/assets/10678668/cd186b4b-96b6-4d98-93a8-c14ea99629fc)

**Comment by yinggeh** [comment] 2024-03-08 21:14
Hi @Missmiaom,

Can you please provide full reproduction steps (all commands run) and fill out the bug template below? Thank you!
Description
A clear and concise description of what the bug is.

Triton Information
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

To Reproduce
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Expected behavior
A clear and concise description of what you expected to happen.

**Comment by yinggeh** [comment] 2024-04-10 22:37
Hi @Missmiaom . Thanks for waiting. I have opened the ticket DLIS-6456 for our engineers to investigate.

**Comment by dafu-wu** [comment] 2024-07-08 11:35
@yinggeh This feature already done?

**Comment by yinggeh** [comment] 2024-07-09 18:46
@dafu-wu PR https://github.com/triton-inference-server/server/pull/7392 is currently under review. Thanks for your patience.

**Comment by yinggeh** [comment] 2024-07-15 21:38
PR https://github.com/triton-inference-server/server/pull/7392 merged. Reopen for further questions.

**Closed by yinggeh** 2024-07-15 21:38 UTC
Labels: investigating

**Comment by dafu-wu** [comment] 2024-08-15 06:56
@yinggeh Thanks your updated, I use the latest trition server image 24.07 to build the tensorrtllm backend, but the log still has some problem:
![Screenshot2024_08_15_145514](https://github.com/user-attachments/assets/0ac13462-fffa-4f57-bfcd-664dda3fb938)

request body:
`'{"id": "11111",  "sequence_id": "456", "text_input": "What is machine learning?", "max_tokens": 20, "bad_words": "", "stop_words": "", "pad_id": 2, "end_id": 2, "top_p":1, "top_k":1, "temperature":0.7}'`

Is there something wrong with the way I use it?
CC

**Comment by yinggeh** [comment] 2024-08-15 09:16
@dafu-wu Looks like PR https://github.com/triton-inference-server/server/pull/7392 missed the deadline of 24.07 release. Could you try building the latest or wait for the 24.08 image?

**Comment by yinggeh** [comment] 2024-08-18 05:40
@dafu-wu Thanks for your patience. Are you referring to `Dockerfile.*` in [server](https://github.com/triton-inference-server/server/tree/main) repo?
