### ISSUE TITLE
openvino_backend has much lower performance than tensorFlow_backend

### ISSUE THREAD

**Issue by zhaohb** [triton-inference-server/server#3194] opened 2021-08-04 07:13 UTC
**Description**
I have a recommended model, which can be loaded normally using TensorFlow backend, but when using OV loading, it indicates that the operator is not supported, so I implemented the operator that OV does not support and encapsulated the custom operator into a shared library.
now OV can also load the model normally. However, in the performance test, it was found that the performance of OV was much lower than that of TensorFlow. The results are as follows:
tensorflow_backend:
```shell
root@test:/data/xxxx# ./perf_client -a -b 600 -u localhost:8001 -i gRPC -m lat_tf --concurrency-range 1
*** Measurement Settings ***
  Batch size: 600
  Measurement window: 5000 msec
  Using asynchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client:
    Request count: 157
    Throughput: 18840 infer/sec
    Avg latency: 31705 usec (standard deviation 2264 usec)
    p50 latency: 31287 usec
    p90 latency: 34560 usec
    p95 latency: 36016 usec
    p99 latency: 37818 usec
    Avg gRPC time: 31804 usec ((un)marshal request/response 2205 usec + response wait 29599 usec)
  Server:
    Inference count: 113400
    Execution count: 189
    Successful request count: 189
    Avg request latency: 27745 usec (overhead 218 usec + queue 180 usec + compute input 647 usec + compute infer 26637 usec + compute output 63 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 18840 infer/sec, latency 31705 usec
```
ov backend:
```shell
root@test:/data/xxxxx# ./perf_client -a -b 600 -u localhost:8001 -i gRPC -m lat_openvino --concurrency-range 1
*** Measurement Settings ***
  Batch size: 600
  Measurement window: 5000 msec
  Using asynchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client:
    Request count: 35
    Throughput: 4200 infer/sec
    Avg latency: 142570 usec (standard deviation 11775 usec)
    p50 latency: 141110 usec
    p90 latency: 157490 usec
    p95 latency: 158868 usec
    p99 latency: 171043 usec
    Avg gRPC time: 142093 usec ((un)marshal request/response 992 usec + response wait 141101 usec)
  Server:
    Inference count: 25200
    Execution count: 42
    Successful request count: 42
    Avg request latency: 140174 usec (overhead 138 usec + queue 35 usec + compute input 683 usec + compute infer 138491 usec + compute output 827 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 4200 infer/sec, latency 142570 usec
```

**Triton Information**
What version of Triton are you using?  21.06

Are you using the Triton container or did you build it yourself? yes

I recompile ov backend with openvino_backend r21.06, openvino 2021.3. this my command:
```shell
cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_BUILD_OPENVINO_VERSION=2021.3.394
 -DTRITON_BUILD_CONTAINER_VERSION=21.06 ..
```

**To Reproduce**
my code: [https://drive.google.com/file/d/1WObxsMidRSEnkSr97P2bHUytX5UKoym_/view?usp=sharing](https://drive.google.com/file/d/1WObxsMidRSEnkSr97P2bHUytX5UKoym_/view?usp=sharing)
it include repo(ov and tf) and custom op share lib.
you can use Triton to load the repo, and the shared library is placed somewhere, and the shared library path in the OV model's configuration file needs to be changed accordingly.

**Expected behavior**
ov backend better than tf, who can help me? thank you very much.

**Comment by zhaohb** [comment] 2021-08-04 07:17
now , ov can not load model with share lib, please refer to this link to recompile ov bakcend. [https://github.com/triton-inference-server/openvino_backend/pull/27](https://github.com/triton-inference-server/openvino_backend/pull/27)

**Comment by tanmayv25** [comment] 2021-08-04 22:41
Compute Infer Times:
```
TensorFlow-CPU : 26637 ms
openVINO: 138491 ms
```

The model inference on openVINO is taking too long time compared to TF model. Looks like this has to do with model itself than the Triton. We will still take a look at the performance degradation. May be OV 2021.4 with correct settings might help bridhing the gap.

Just to confirm, did you create the OV IR model (model.xml and model.bin) with the same TF savedmodel in your repo?

**Comment by zhaohb** [comment] 2021-08-04 23:45
yes，model.xml model.bin had created from tf savedmodel in my repo


Get Outlook for Android

**Comment by zhaohb** [comment] 2021-08-04 23:49
you can test direct, I want to know the result with 2021.4 ,when will do this test？


Get Outlook for Android

**Comment by tanmayv25** [comment] 2021-08-05 02:03
> another question, can I test on 21.04? 

@zhaohb You can use patch from my PR: https://github.com/triton-inference-server/openvino_backend/pull/25/files

Then follow these steps:

```
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_BUILD_OPENVINO_VERSION=2021.4 -DTRITON_BUILD_CONTAINER_VERSION=21.07 ..
$ make install
```

I believe this should work. Just replace the `backend/openvino` contents with this newly built backend library,

**Comment by zhaohb** [comment] 2021-08-05 02:08
openvino_backend which branch i should use?

**Comment by zhaohb** [comment] 2021-08-05 13:09
@tanmayv25 bad news, I have compiled ov backend of 2021.4 using openvino_backend 21.07 branch and the compilation steps you mentioned, it successed , and I get ov with openmp, but when I test my model,I found MNIST model that can be loaded normally, but if there is a shared library of custom op, an error is reported when loading. I had add my patch for custom op lib.
I wonder where the problem is.
```shell
root@374db5a9e8bf:/opt/tritonserver/backends/openvino# ls
LICENSE.openvino  libMKLDNNPlugin.so  libinference_engine.so  libinference_engine_ir_reader.so  libinference_engine_legacy.so  libinference_engine_lp_transformations.so  libinference_engine_transformations.so  libiomp5.so  libngraph.so  libtriton_openvino.so  plugins.xml
```
the error:
```shell
I0805 13:05:24.679497 1220 server.cc:586]
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Model        | Version  | Status                                                                                                                                                                                                            |
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| lat_openvino | 20210803 | UNAVAILABLE: Internal: ModelState::Create InferenceEngine::Exception: Cannot load library '/work/custom_layer/build/libextension.so': /work/custom_layer/build/libextension.so: undefined symbol: _ZTIN3tbb4taskE |
| lat_tf       | 20210803 | READY                                                                                                                                                                                                             |
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
in my code I do not use tbb::task, I compile so lib with openvino 21.04 that support openmp, I compile it myself, the compile command same with compile openvino_backend.

**Comment by zhaohb** [comment] 2021-08-05 14:39
in my custom op I use InferenceEngine::parallel_for, I do not know whether this has an effect. can you test my model in your ov 2021.4? if you test I can share my custom op code to you, I am eager to know the performance difference between TF and OV in ov 2021.4 with openmp.

**Comment by zhaohb** [comment] 2021-08-06 07:02
@tanmayv25 I find that OV backend does not support the Inference Engine Async API. do we have any plans to support it.

**Comment by zhaohb** [comment] 2021-08-06 07:48
```shell
   THROW_IF_BACKEND_INSTANCE_ERROR(model_state_->ParseParameters(device_));
    // enable dynamic batching in the network
    std::map<std::string, std::string> network_config;
    if ((model_state_->MaxBatchSize() != 0) &&
        (!model_state_->SkipDynamicBatchSize())) {
      network_config
          [InferenceEngine::PluginConfigParams::KEY_DYN_BATCH_ENABLED] =
              InferenceEngine::PluginConfigParams::YES;
    }
    network_config
          [InferenceEngine::PluginConfigParams::KEY_EXCLUSIVE_ASYNC_REQUESTS] =
            InferenceEngine::PluginConfigParams::YES;
    THROW_IF_BACKEND_INSTANCE_ERROR(model_state_->ConfigureInferenceEngine());
    THROW_IF_BACKEND_INSTANCE_ERROR(
        model_state_->LoadNetwork(device_, network_config));
  }

  THROW_IF_BACKEND_INSTANCE_ERROR(
      model_state_->CreateInferRequest(device_, &infer_request_));
}
```
I add KEY_EXCLUSIVE_ASYNC_REQUESTS, but the performance is lower than before

**Comment by tanmayv25** [comment] 2021-08-06 18:18
> I find that OV backend does not support the Inference Engine Async API. do we have any plans to support it.

It is not in our roadmap yet. But we may add support for it if we find any indication of that providing a performance boost.

**Comment by zhaohb** [comment] 2021-08-11 02:06
@tanmayv25  _The _ZTIN3tbb4taskE error is mainly due to the parallel_for api I used in the custom operator

**Comment by tanmayv25** [comment] 2021-12-22 00:31
The performance degradation is coming from OpenVINO library. 
```
TensorFlow-CPU : 26637 ms
openVINO: 138491 ms
```
This does not look like an issue with Triton, but with the openVINO and the model. Closing the ticket for now. Please open a new issue if you identify something wrong with Triton.

**Comment by zhaohb** [comment] 2021-12-22 02:39
@tanmayv25 I don't think so, because I use the same version of OpenVino with Intel's Model Server and the performance is much better, so I still think OpenVino Backend may need to be improved. 
Another question, does OpenVino Backend support 2021.4 now？

**Comment by tanmayv25** [comment] 2022-01-07 18:04
We don't officially support openVINO 2021.4 and onnxruntime_backend is still at 2021.2. But you can use our build.py script to build openvino backends for multiple versions.
https://github.com/triton-inference-server/server/blob/main/build.py#L62-L83

Also, this ticket compares the performance of OV backend with TF backend for the model. Just so that we can better track the issue, can you create a new issue which describes the how to reproduce the perf regression between triton and intel's model server? I think that would be an interesting take. Please make sure you are using same library versions.

**Closed** 2022-01-07 18:13 UTC
Labels: performance, investigating
