### ISSUE TITLE
Requests are processed in an unordered way in BLS model

### ISSUE THREAD

**Issue by saraRaris** [triton-inference-server/server#6121] opened 2023-07-28 14:21 UTC
**Description**
I'm working on an application that needs to process requests in a sequential and ordered way, more concretely I'm dealing with image data coming from a camera (frames). I have built a BLS model that processed each of the frames and has to rely on the frames to be order to be able to send back an accurate response. Everything looked good at the beginning until I realized that some (not all) of the frames are processed in an unordered way. It appears that some of these get ahead of others messing up with the processing pipeline. This does not happen very often but it still produces errors.

**Triton Information**
Version of Triton is 22.10-py3 and using the Triton container.

**To Reproduce**
I'm using python back as seen below. I have checked for the possibility of concurrent threads running but [ the documentation suggests otherwise](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#cpu-model-instance).
The model is running in Model Control Mode EXPLICIT.

```
name: "model"
backend: "python"
max_batch_size: 1

input [
  {
    name: "INPUT_IMAGESTR"
    data_type: TYPE_STRING
    dims: [-1]
  }
]
input [
  {
    name: "UUID"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
input [
  {
    name: "LABELS"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "FINAL_OUTPUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_CPU }]
```

**Expected behavior**
I would expect the frames to be processed in the same order they are sent and arrive to the server unless there's some threading going on or more than one instance of the model running at the same time.

**Comment by jbkyang-nvi** [comment] 2023-07-29 00:06
It seems like you would need to use sequence ids for this case [sequence id documentation](https://github.com/triton-inference-server/client#client-api-for-stateful-models) and https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_sequence.md What does your client look like?

**Comment by saraRaris** [comment] 2023-07-31 06:59
I'm using uuids already internally to separate the sequences coming from different cameras but I'm not using that functionality as described in the documentation. I will give it a shot and integrate this into the client an server. Will update with the results or any further questions. Thank you!

My client looks like this right now:

```
def client(model_input, host, port, cert, model_name, camera_uuid):

    # Define inputs and output
    inputs = []
    outputs = []
    input_name_0 = "INPUT_IMAGESTR"
    input_name_1 = "UUID"
    output_name = "FINAL_OUTPUT"

    # Define and init triton client
    triton_client = tritongrpcclient.InferenceServerClient(
        url=f"{host}:{port}",
        verbose=False,
        ssl=False,
        root_certificates=f"{cert}/ca.pem",
        private_key=f"{cert}/server-key.pem",
        certificate_chain=f"{cert}/server.pem",
    )

    # Format inputs
    jpg_original = base64.b64decode(model_input)
    img_data = np.array([jpg_original], dtype=bytes)
    img_data = np.stack([img_data], axis=0)

    uuid = np.array([camera_uuid]).astype(bytes)
    uuid = np.stack([uuid], axis=0)

    # Add inputs and outputs
    inputs.append(tritongrpcclient.InferInput(input_name_0, img_data.shape, "BYTES"))
    inputs.append(tritongrpcclient.InferInput(input_name_1, uuid.shape, "BYTES"))

    inputs[0].set_data_from_numpy(img_data)
    inputs[1].set_data_from_numpy(uuid)

    outputs.append(tritongrpcclient.InferRequestedOutput(output_name))

    # Infer model
    results = triton_client.infer(model_name=model_name, inputs=inputs, outputs=outputs)
 
```

Anyhow, I'm curious to know what's the reason why the requests are not being processed in order. Are there multiple threads running for any server that does not expect a sequence? I haven't been able to find that information in the documentation.

**Comment by saraRaris** [comment] 2023-07-31 09:57
I have tried to include the sequence_id, sequence_start and sequence_end flags in the client:

```
  # Infer model
  results = triton_client.infer(model_name=model_name,
                                inputs=inputs,
                                outputs=outputs,
                                sequence_id=camera_uuid,
                                sequence_start=sequence_start,
                                sequence_end=False
                                )
```
I'm able to infer the server if the `camera_uuid` is an int type. However, when I try to use a string type such as  `camera_uuid = "e333c95a-07fc-42d2-ab16-033b1a566ed5"`  (as [the example](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_sequence.md#httprest) in the documentation) I get the following error:
`[StatusCode.INVALID_ARGUMENT] [request id: <id_unknown>] correlation ID in request is not an unsigned int`

Anything that I'm missing here?

Also, I have set `sequence_end` to `False` as cameras are continuously streaming once connected and the server is not really expect an end to the sequence. Let me know if you think there could be any issues with this.

**Comment by jbkyang-nvi** [comment] 2023-08-01 18:30
@GuanLuo and @Tabrizian for comments. It looks like it requests the correlation id to be an unsigned int. Since camera uuid seems to be fixed, can you create a mapping in the client of uuid to unsigned int?

**Comment by Tabrizian** [comment] 2023-08-03 22:16
The problem is that string sequence IDs are not supported in Python backend yet. We do have a ticket for this but it has not been scheduled yet.

**Comment by saraRaris** [comment] 2023-08-04 06:54
Thank you. Would be great if you could let me know once that ticket has been finalized and integrated.

**Comment by Tabrizian** [comment] 2024-10-24 16:53
https://github.com/triton-inference-server/python_backend/pull/344

Support has been added here. Closing.

**Closed by Tabrizian** 2024-10-24 16:53 UTC
Labels: enhancement
