### ISSUE TITLE
[Question] [Model storage] Is there a way to download a model from cloud repo and store it to disk?

### ISSUE THREAD

**Issue by 0x4d6f6c666172** [triton-inference-server/server#2887] opened 2021-05-19 12:53 UTC
**Is your feature request related to a problem? Please describe.**
First of all - this is a question regarding an existing functionality, and not a request itself. I would like to provide a bit of context before proceeding further.

At our current project we use a "fat" Triton image with all our models bundled inside (~12 Gb). While this is an acceptable solution for a relatively small scale, we also have to deploy experimental models from time to time, which means that we have to put these inside an image. Obviously it creates difficulties for us in terms of increasing repository size and increasing download sizes for updated images. Thus, we began to investigate possible approaches in solving this problem.

From what we discovered, Triton is able to use models from cloud storage and serve only one model requested via `--model-control-mode=explicit`, which looks like what we need except it does download requested model every time on start. And this is where the question starts. I am wondering if there exist any way to "tell" Triton to download a model from cloud repository, say from S3, and persist it to disk for a further usage? A possible approach requires to re-download a model from S3, which is not always a best solution, especially in our case since we can deploy models multiple times a day.

**Describe the solution you'd like**
It would be great to have a way to inform Triton to use a model repository and persist this model on disk for further usage. However, it will almost certainly create an implication in case an updated model with the same name was uploaded to cloud, since Triton would not be aware of this. 

**Describe alternatives you've considered**
In case a functionality described above is not present or is hard to implement, we are considering to move model downloading to a separate job or service instead of Triton.

**Additional context**
-

Please, feel free to ask me any question and let me know in case I can provide you with any details or clarifications regarding this question. Thank you!

**Comment by deadeyegoodwin** [comment] 2021-05-19 20:40
First of all, you can cut down on the size of the Triton container using steps described here: https://github.com/triton-inference-server/server/blob/main/docs/compose.md

In general, if you want to have a cached model repo you will need to manage that yourself. For example, you can pull down models from S3 or other cloud providers or from other areas and collect them together in a locally accessible filesystem directory. Then when you launch triton container you just need to map that directory into the container. Have you considered this solution?

**Comment by bryanmcgrane** [comment] 2021-05-24 20:33
I have a similar question / issue. In my scenario I have a server that runs alongside Triton. This server fetches models from an S3 bucket and persists the models to a volume. When my server boots up I compare the hash of the model in S3 vs the hash of the locally stored model - this prevents unnecessary downloads on subsequent boots.

The problem is, all my models live on my side-car server. Is there a way for me to call `RepositoryModelLoad` and somehow push the file bytes to Triton so Triton can persist locally?

**Comment by tanmayv25** [comment] 2021-06-08 17:37
@bryanmcgrane Triton needs the model onto a filesystem. There is no API to explicitly push the file bytes to Triton.

**Comment by tanmayv25** [comment] 2021-06-08 17:39
Closing the issue for now. Please re-open in case of any other question or file a new issue with the enhancement request.

**Closed by tanmayv25** 2021-06-08 17:39 UTC
Labels: question
