### ISSUE TITLE
python_backend should not set name_ property

### ISSUE THREAD

**Issue by zjjott** [triton-inference-server/server#2457] opened 2021-01-26 12:04 UTC
python.cc:

```c++
class ModelInstanceState : public BackendModelInstance {
   ....
private:
  TRITONBACKEND_ModelInstance* triton_model_instance_;
  const std::string name_;
// ModelInstanceState::CreatePythonInterpreter()
  subinterpreter_commandline[7] = name_.c_str(); // this will always be empty string
}
```
this is wrong,because in  `BackendModelInstance`,there have two protected property
```c++
class BackendModelInstance {
 protected:
  TRITONBACKEND_ModelInstance* triton_model_instance_;
  std::string name_;

```
constructor  will set protected proproty,but will not set privated `name_`;
You can Reproduce with little c++ program:
```c++
#include <string>
#include <iostream>
using namespace std;
class A
{
protected:
    std::string name_;
    /* data */
public:
    A(std::string name)
    {
        name_ = name + " yes";
    }
    void sayHi()
    {
        cout << "hello:" << name_ << endl;
    }
    ~A();
};

A::~A()
{
}
class B : public A
{
private:
    std::string name_;
    int version_;

public:
    B(std::string name, int version) : A(name), version_(version)
    {
    }
    void sayHi2()
    {
        cout << "hello:" << name_ << " " << version_ << endl;
    }
};
int main(int argc, char const *argv[])
{
    auto hh = A(std::string("hello"));
    hh.sayHi();
    auto b = B(std::string("world"), 123);
    b.sayHi2();
    return 0;
}

```

**Triton Information**
What version of Triton are you using?
python backend: https://github.com/triton-inference-server/python_backend/commit/2cc255f219e2b91eb0b2a6abdd57029e2695eabf will cause this error

**To Reproduce**
Use python backend, and start python progress, there will be error:`--instance-name is required`

BTW: you can add some CI in those repo

**Comment by Tabrizian** [comment] 2021-01-27 23:29
Thanks for reporting this. For some reason, the string was not empty and the Python backend started successfully in our CI tests. The issue is addressed in #33.

**Closed by Tabrizian** 2021-01-27 23:29 UTC
