### ISSUE TITLE
Ensemble model using BLS: stub unhealthy

### ISSUE THREAD

**Issue by WadoodAbdul** [triton-inference-server/server#4026] opened 2022-03-09 07:51 UTC
**Description**
I am trying to run tokenizer+encoder for a model in triton. This is implemented using triton BLS and adding in the encoder inference call in model.py. However, this is the error message upon inferencing the ensemble model through triton python client,
`Stub process is unhealthy and it will be restarted.`

**Triton Information**
22.01

Command to run docker triton:
```
sudo docker run -it --rm --gpus all -p9000:8000 -p9001:8001 -p9002:8002 --shm-size 4g \
-v $PWD/triton_mbart:/models [nvcr.io/nvidia/tritonserver:22.01-py3](http://nvcr.io/nvidia/tritonserver:22.01-py3) \
bash -c "pip install transformers torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html && \
tritonserver --model-repository=/models"
```

**To Reproduce**
The model repo consists of two models:
- encoder (mbart_onnx_encoder)
- tokenizer+encoder (mbart_tokenizer_encoder)

##### Encoder
config.pbtxt:
```
name: "mbart_onnx_encoder"
platform: "onnxruntime_onnx"
max_batch_size : 0
default_model_filename: "mbart_encoder.onnx"

input [
  {
    name: "input"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, -1, 1024 ]
  }
]

instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]

```

##### Tokenizer+Encoder
config.pbtxt:
```
ame: "mbart_tokenizer_encoder"
max_batch_size: 0
backend: "python"

input [
{
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ -1 ]
}
]

output [
{
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, -1, 1024 ]
}
]

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]
parameters: {
  key: "FORCE_CPU_ONLY_INPUT_TENSORS"
  value: {
    string_value:"no"
  }
}

```

model.py
```
import os
from typing import Dict, List

import torch
import numpy as np


try:
    # noinspection PyUnresolvedReferences
    import triton_python_backend_utils as pb_utils
except ImportError:
    pass  # triton_python_backend_utils exists only inside Triton Python backend.

from transformers import AutoTokenizer, PreTrainedTokenizer, TensorType


class TritonPythonModel:
    tokenizer: PreTrainedTokenizer

    def initialize(self, args: Dict[str, str]) -> None:
        """
        Initialize the tokenization process
        :param args: arguments from Triton config file
        """
        # more variables in https://github.com/triton-inference-server/python_backend/blob/main/src/python.cc
        path: str = os.path.join(args["model_repository"], args["model_version"])
        self.tokenizer = AutoTokenizer.from_pretrained(path)
        encoder_model = args["model_name"].replace("_tokenizer_encoder", "_onnx_encoder")

        def encoder_inference(input_ids):
            inputs = input_ids
            inference_request = pb_utils.InferenceRequest(
                model_name=encoder_model, requested_output_names=["output"], inputs=inputs
            )
            inference_response = inference_request.exec()
            return [pb_utils.get_output_tensor_by_name(inference_response, "output")]

        self.encoder_inference = encoder_inference

    def execute(self, requests) -> "List[List[pb_utils.Tensor]]":
        """
        Parse and tokenize each request
        :param requests: 1 or more requests received by Triton server.
        :return: text as input tensors
        """
        responses = []
        # for loop for batch requests (disabled in our case)
        for request in requests:
            # binary data typed back to string
            query = [t.decode("UTF-8") for t in pb_utils.get_input_tensor_by_name(request, "TEXT").as_numpy().tolist()]
            tokens: Dict[str, np.ndarray] = self.tokenizer(text=query, return_tensors=TensorType.NUMPY, return_attention_mask=False)
            # tensorrt uses int32 as input type, ort uses int64
            tokens = {k: v.astype(np.int64) for k, v in tokens.items()}
            # communicate the tokenization results to Triton server
            outputs = list()
            for input_name in self.tokenizer.model_input_names:
                tensor_input = pb_utils.Tensor(input_name, tokens[input_name])
                outputs.append(tensor_input)
                break # onnx encoder is not expecting attention masks
            tokenizer_response = pb_utils.InferenceResponse(output_tensors=outputs)
            input_ids = [pb_utils.Tensor.from_dlpack("input_ids", pb_utils.get_output_tensor_by_name(tokenizer_response, "input_ids").to_dlpack())]
            encoder_outputs = self.encoder_inference(input_ids)
            inference_response = pb_utils.InferenceResponse(output_tensors=encoder_outputs)

            responses.append(inference_response)

        return responses
```
**Expected behavior**

I have run separate inferencing for encoder and tokenizer using triton python client successfully. However, this issue is faced when calling the ensemble model,

```
tritonclient.utils.InferenceServerException: Failed to process the request(s) for model instance 'mbart_tokenizer_encoder_0', message: Stub process is not healthy.
```

Note: I have tried increasing the shm-size and have used 4g.

My end goal is to use encoder-decoder model with beam search in triton. It would be great if you could share share any suggestions/resources for this.

**Comment by Tabrizian** [comment] 2022-03-09 14:07
Thanks for filing the detailed issue. This looks like a bug. I have filed a ticket to look into this. Can you share your ONNX model too so that we can reproduce this issue?

**Comment by WadoodAbdul** [comment] 2022-03-10 19:43
You can download the model from this [link](https://drive.google.com/file/d/1lgzMpXjjtdXSgfcLr-JT8a_yWh5N0peS/view?usp=sharing)
In case you want to see the conversion [script](https://colab.research.google.com/drive/13inuj9l7OSp9gwUtSucIl47xyXHSXnTx?usp=sharing)

Please let me know if you need further details. Thanks.

**Comment by Tabrizian** [comment] 2022-03-14 17:38
Thanks for providing the models. Will update you as soon as more info is available.

**Comment by WadoodAbdul** [comment] 2022-03-17 06:02
Hello, @Tabrizian any updates on this issue?

Also, could you please share any resources/suggestions for inferencing encoder-decoder models in Triton?

Thanks

**Comment by Tabrizian** [comment] 2022-03-23 13:46
Sorry for delay in getting back to you. I tried to reproduce this issue, however, it seems like one piece of the puzzle is still missing:

```
 self.tokenizer = AutoTokenizer.from_pretrained(path)
```

When I run the Python model, I receive the error below:

```
UNAVAILABLE: Internal: OSError: Can't load config for 'models-bug/mbart_tokenizer_encoder/1'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make                    sure 'models-bug/mbart_tokenizer_encoder/1' is the correct path to a directory containing a config.json file                                                                                                                                    
```

Can you share the content of mbart_tokenizer_encoder file? Alternatively, it would be great if you can share your model repository and client file and lead to this error. Thanks.

**Comment by WadoodAbdul** [comment] 2022-03-26 08:39
Sure, 

Here are the contents of mbart_tokenizer_encoder directory;
```
mbart_tokenizer_encoder/
----config.pbtxt
----1/
    ----model.py
    ----sentencepiece.bpe.model  
    ----special_tokens_map.json  
    ----tokenizer.json  
    ----tokenizer_config.json 
```

The contents of the config.pbtxt & model.py have been shared above as "Tokenizer+Encoder".

For the tokenizer files, please use this snippet,

```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('facebook/mbart-large-50-many-to-many-mmt')
tokenizer.save_pretrained("./tokenizer_files")
```
------

### client.py

```
import tritonclient
import tritonclient.http as httpclient
import numpy as np

model_name = f"mbart_tokenizer_encoder"
url = "127.0.0.1:9000"
model_version = "1"
batch_size = 1

triton_client = tritonclient.http.InferenceServerClient(url=url, verbose=False)
assert triton_client.is_model_ready(
        model_name=model_name, model_version=model_version
    ), f"model {model_name} not yet ready"


model_metadata = triton_client.get_model_metadata(model_name=model_name, model_version=model_version)
model_config = triton_client.get_model_config(model_name=model_name, model_version=model_version)

query = tritonclient.http.InferInput(name="TEXT", shape=(batch_size,), datatype="BYTES")
model_score = tritonclient.http.InferRequestedOutput(name="output", binary_data=False)

text = "hi therer"
query.set_data_from_numpy(np.asarray([text] * batch_size, dtype=object))

response = triton_client.infer(model_name=model_name, model_version=model_version, inputs=[query], outputs=[model_score] ).as_numpy("input_ids")
```

Please let me know if you need further details.

**Comment by Tabrizian** [comment] 2022-04-01 21:53
Thanks for providing further details. You need to check the inference response of the BLS request to make sure that it doesn't have any error in this line:

```
inference_response = inference_request.exec()
```

I received the error below:

```
"unexpected inference input 'input_ids' for model 'mbart_onnx_encoder'"
```

**Comment by Tabrizian** [comment] 2022-04-22 15:59
Closing the issue due to in-activity.

**Closed by Tabrizian** 2022-04-22 15:59 UTC
Labels: bug

**Comment by lbjcom** [comment] 2022-12-07 07:21
I wonder whether this issues is resolved or just closed due to inactivity. I also have similar problem with this.

- tritonserver:22.03
- model1: python backend, KIND_CPU
- model2: python backend, KIND_GPU
- These models communicate through BLS.

**Comment by Tabrizian** [comment] 2022-12-12 16:25
There was a problem with dlpack support in Python backend which has been fixed in this commit: https://github.com/triton-inference-server/python_backend/pull/198

Can you try again with this commit included to see if you can still replicate the issue? Alternatively, please downgrade the PyTorch version used to 1.12.0.

**Comment by MhdKAT** [comment] 2022-12-12 17:20
> There was a problem with dlpack support in Python backend which has been fixed in this commit: [triton-inference-server/python_backend#198](https://github.com/triton-inference-server/python_backend/pull/198)
> 
> Can you try again with this commit included to see if you can still replicate the issue? Alternatively, please downgrade the PyTorch version used to 1.12.0.

Thank you ! I am using Nvidia NGC container so I downgraded torch version as you sais to 1.12.0 and it worked. Any update on doing the conversion from GPU tensor to numpy without having to use Torch ?

**Comment by Tabrizian** [comment] 2022-12-20 15:36
> Any update on doing the conversion from GPU tensor to numpy without having to use Torch ?

You don't have to use PyTorch. You can use any framework that supports dlpack for the conversion (such as CuPy). If you are talking about the ability to transfer a tensor from GPU to CPU in Python BE, this has not been implemented yet.
