### ISSUE TITLE
Allow loading/unloading of specific version for a given model

### ISSUE THREAD

**Issue by mmischitelli** [triton-inference-server/server#4416] opened 2022-05-20 14:38 UTC
**Is your feature request related to a problem? Please describe.**
I find the model control mode "explicit" to be very interesting. Although, for my usecase, it pretty much useless as we have few models consisting of tens or even hundred of versions. Each model is basically updated weekly and previous versions must be kept available.

**Describe the solution you'd like**
A new overload to the LoadModel method, accepting not only the model name, but also the version.

**Describe alternatives you've considered**
An additional API, such as LoadVersion, which still sports two arguments: model name and version.

**Additional context**
My aim here is basically keeping the memory usage under control. I don't want to load all the versions of a given model in memory as it would clog to death my client, as well as requiring my server to have terabytes of Ram.

**Comment by dyastremsky** [comment] 2022-05-23 21:27
I've filed a ticket for this feature request.

I don't know your specific use case, but you may also be able to use model names in the meantime (e.g. model100_2022_05_23 or whatever makes sense for you). Another option is leveraging the [specific version policy](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#version-policy). We've added this to our queue to review.

**Comment by mmischitelli** [comment] 2022-05-24 10:21
Thanks!

Unfortunately we cannot "flatten" the model/version hierarchy as we have some strict requirements that would make things way too complicated. For instance, we plot the inference results on a chart: if the function's name is the same we can esily do comparisons, as the version is just a parameter.

The specific version policy instead is kinda "static". Our solution provides users with the backend to run simulations on their own, eventually comparing data from different years. Since we produce model versions weekly, it would result in way too much memory being occupied for no real reason (except for being able to serve all the versions available).

If there was support for an on-demand load/unload of versions, we would then be able to implement some kind of LRU policy for managing the available resources.

**Comment by Lingkar** [comment] 2022-05-24 14:08
@mmischitelli combining the specific version policy with the control mode POLL is quite fast in updating the available models, right?

@dyastremsky My specific use-case will be controlling the model versioning through the API within the KServe modelmesh environment. I will have to find out if either workaround will work. Where can I keep an eye on the progress of the feature request ticket? Would you happen to have an indication of the timeline for such a feature? Thanks for the information!

**Comment by dyastremsky** [comment] 2022-05-24 14:21
@Lingkar The ticket was filed internally. There is no timeline yet for this feature request. Your best bet is to keep an eye on this GitHub issue, as I'm leaving it open as we look into this feature request.

**Comment by mmischitelli** [comment] 2022-05-25 14:47
> @mmischitelli combining the specific version policy with the control mode POLL is quite fast in updating the available models, right?

yes, it's just the time needed to load any new version that is added to the local repo. Usually it's quite fast.

**Comment by GuanLuo** [comment] 2022-09-03 00:50
Now that in model load API, you can [specify a string representation of the config file](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#load) as part of the request, which may address your use case, in the override config, you can specify different version policy based on the circumstances to control which subset of the versions that should be loaded. Do you think it could be helpful?

**Comment by Lingkar** [comment] 2022-09-07 13:24
@GuanLuo Sounds excellent for my use case! I will give it a try, thanks! :+1:

**Comment by mmischitelli** [comment] 2022-09-07 15:09
Hi,
not particularly in my scenario. I need to be able to specify which version to load, not the policy.

In particular, I need to be able to ask the server for version "3" or version "27" for any given model.

> Now that in model load API, you can [specify a string representation of the config file](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#load) as part of the request, which may address your use case, in the override config, you can specify different version policy based on the circumstances to control which subset of the versions that should be loaded. Do you think it could be helpful?

**Comment by GuanLuo** [comment] 2022-09-08 19:09
I believe you can send the request like the following to load the specified version (take "3" as example):
```
POST /v2/repository/models/mymodel/load HTTP/1.1
Host: localhost:8000
{
  "parameters": {
    "config": "{
        ... # other config fields
        "version_policy": {"specific" : { "versions" : [ 3 ] }}
    }"
  }
}
```

**Comment by bangpc** [comment] 2022-09-27 10:22
@GuanLuo your solution does not work even with latest triton image 22.08

**Comment by bangpc** [comment] 2022-09-28 01:46
my `cfg` that I send to Triton 
```json 
{
    "parameters": {
        "config": {
            "name": "fisheye",              
            "platform": "onnxruntime_onnx", 
            "default_model_filename": "model.onnx",
            "input": [
                {
                    "name": "input",                
                    "data_type": "FP32",            
                    "dims": [1, 3, 608, 608]    
                }
            ],
            "output": [
                {
                    "name": "output",               
                    "data_type": "FP32",            
                    "dims": [1, 22743, 6]       
                }
            ],
            "version_policy": {"specific": {"versions": [1]}}
        }
    }
}
```
I load model using the following function
`triton_client.load_model(model_name, config=json.dumps(cfg))`

Result: Triton does not change anything, it will unload and reload the latest version in model directory

**Comment by dyastremsky** [comment] 2022-09-28 17:26
Are you using [EXPLICIT model control mode](https://github.com/triton-inference-server/server/blob/3589c2c72d249392809fe9ae3de8057fe0437135/docs/user_guide/model_management.md#model-control-mode-explicit)?

**Comment by bangpc** [comment] 2022-09-29 01:40
@dyastremsky yep, I use explicit model control mode

**Comment by dyastremsky** [comment] 2022-10-03 18:13
Ah, you're using the model config override. We're currently working through a bug whereby if you override the model config but not the model, the model config override is not recognized. We're working on this and aiming to get a fix in soon.

We try to keep issues focused on the original poster's question. If you have other questions or issues, please open a new issue. (Unload API documentation [here](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#unload).)

CC: @krishung5

**Comment by dyastremsky** [comment] 2022-10-04 22:55
@bangpc It looks like the config you provided isn't correct. The `parameters` and `config` fields shouldn't be part of the config. I think @GuanLuo added those for a POST request, but you're sending it via the client API's `load_model`.

If you send the correct config, it should work. If not, please open a separate issue and we'll investigate.

Closing issue due to the original issue being resolved. Please feel free to follow up and ask us to reopen if there are further questions about the loading/unloading of specific model versions.

**Closed by dyastremsky** 2022-10-04 22:55 UTC
Labels: enhancement

**Comment by Lingkar** [comment] 2023-01-17 11:41
@dyastremsky I have been trying to get the ModelWarmup config to work for a day now in combination with the specific version loading of models. I am sending my request via the python library tritonclient.grpc.  
InferenceServerClient.load_model

This regards the latest server version 2.29.0 and python tritonclient 2.29.0.

Without the model warmup, the following config string works like a charm:
`{version_policy: {specific: {versions: [ 3 ]}}, max_batch_size: 1}`

However adding the model warmup (I believe fully complying with the [ModelWarmup protobuf](https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto))
`{version_policy: {specific: {versions: [ 3 ]}}, max_batch_size: 1, model_warmup: [{ name: "warmup", batch_size: 1, count: 1, inputs: { "INPUT0": { data_type: 11, dims: [3, 32, 32], random_data: true } } }]}`

Results in the following failure of the model load (verbose logging triton server):

```
I0117 11:30:47.434567 1 grpc_server.cc:270] Process for RepositoryModelLoad, rpc_ok=1, 21 step START
I0117 11:30:47.434740 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelLoad', 22
I0117 11:30:47.439573 1 model_config_utils.cc:646] Server side auto-completed config: name: "CIFAR10"
platform: "onnxruntime_onnx"
version_policy {
  specific {
    versions: 3
  }
}
max_batch_size: 1
default_model_filename: "model.onnx"
model_warmup {
  name: "warmup"
  batch_size: 1
  inputs {
    key: "INPUT0"
    value {
      data_type: TYPE_FP32
      dims: 3
      dims: 32
      dims: 32
      random_data: true
    }
  }
  count: 1
}
backend: "onnxruntime"

I0117 11:30:47.439920 1 model_lifecycle.cc:428] AsyncLoad() 'CIFAR10'
I0117 11:30:47.440402 1 model_lifecycle.cc:459] loading: CIFAR10:3
I0117 11:30:47.441071 1 model_lifecycle.cc:509] CreateModel() 'CIFAR10' version 3
I0117 11:30:47.441532 1 backend_model.cc:296] Found overwritten default setting: default-max-batch-size,0
I0117 11:30:47.441684 1 onnxruntime.cc:2563] TRITONBACKEND_ModelInitialize: CIFAR10 (version 3)
2023-01-17 11:30:47.444414203 [I:onnxruntime:, inference_session.cc:271 ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2023-01-17 11:30:47.444534294 [I:onnxruntime:, inference_session.cc:292 ConstructorCommon] Dynamic block base set to 0
2023-01-17 11:30:47.566200458 [I:onnxruntime:, inference_session.cc:1222 Initialize] Initializing session.
2023-01-17 11:30:47.566266587 [I:onnxruntime:, inference_session.cc:1259 Initialize] Adding default CPU execution provider.
2023-01-17 11:30:47.566329919 [I:onnxruntime:log, bfc_arena.cc:26 BFCArena] Creating BFCArena for Cpu with following configs: initial_chunk_size_bytes: 1048576 max_dead_bytes_per_chunk: 134217728 initial_growth_chunk_size_bytes: 2097152 memory limit: 18446744073709551615 arena_extend_strategy: 0
2023-01-17 11:30:47.566353493 [V:onnxruntime:log, bfc_arena.cc:62 BFCArena] Creating 21 bins of max chunk size 256 to 268435456
2023-01-17 11:30:47.567146947 [I:onnxruntime:, reshape_fusion.cc:42 ApplyImpl] Total fused reshape node count: 0
2023-01-17 11:30:47.568536469 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.568659431 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.568720467 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.568773633 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.568822855 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.568870336 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.568919261 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.568966964 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.569015353 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.576678102 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.576812786 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.576872637 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.576928932 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.576980987 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.577032542 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.577085505 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.577139097 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.578556618 [V:onnxruntime:, session_state.cc:1010 VerifyEachNodeIsAssignedToAnEp] Node placements
2023-01-17 11:30:47.578616136 [V:onnxruntime:, session_state.cc:1013 VerifyEachNodeIsAssignedToAnEp]  All nodes placed on [CPUExecutionProvider]. Number of nodes: 25
2023-01-17 11:30:47.578984188 [V:onnxruntime:, session_state.cc:66 CreateGraphInfo] SaveMLValueNameIndexMapping
2023-01-17 11:30:47.579079538 [V:onnxruntime:, session_state.cc:112 CreateGraphInfo] Done saving OrtValue mappings.
2023-01-17 11:30:47.579460571 [I:onnxruntime:, session_state_utils.cc:199 SaveInitializedTensors] Saving initialized tensors.
2023-01-17 11:30:47.579542293 [I:onnxruntime:log, bfc_arena.cc:317 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:1 (requested) num_bytes: 512 (actual) rounded_bytes:512
2023-01-17 11:30:47.579573959 [I:onnxruntime:log, bfc_arena.cc:197 Extend] Extended allocation by 1048576 bytes.
2023-01-17 11:30:47.579596125 [I:onnxruntime:log, bfc_arena.cc:200 Extend] Total allocated bytes: 1048576
2023-01-17 11:30:47.579615996 [I:onnxruntime:log, bfc_arena.cc:203 Extend] Allocated memory at 0x7f04c16e40 to 0x7f04d16e40
2023-01-17 11:30:47.579722587 [I:onnxruntime:log, bfc_arena.cc:317 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:15 (requested) num_bytes: 9437184 (actual) rounded_bytes:9437184
2023-01-17 11:30:47.579749679 [I:onnxruntime:log, bfc_arena.cc:197 Extend] Extended allocation by 16777216 bytes.
2023-01-17 11:30:47.579768272 [I:onnxruntime:log, bfc_arena.cc:200 Extend] Total allocated bytes: 17825792
2023-01-17 11:30:47.579786457 [I:onnxruntime:log, bfc_arena.cc:203 Extend] Allocated memory at 0x7efdddb1c0 to 0x7efeddb1c0
2023-01-17 11:30:47.584066113 [I:onnxruntime:log, bfc_arena.cc:317 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:15 (requested) num_bytes: 9437184 (actual) rounded_bytes:9437184
2023-01-17 11:30:47.584144464 [I:onnxruntime:log, bfc_arena.cc:197 Extend] Extended allocation by 16777216 bytes.
2023-01-17 11:30:47.584164797 [I:onnxruntime:log, bfc_arena.cc:200 Extend] Total allocated bytes: 34603008
2023-01-17 11:30:47.584184519 [I:onnxruntime:log, bfc_arena.cc:203 Extend] Allocated memory at 0x7f06d5dc40 to 0x7f07d5dc40
2023-01-17 11:30:47.588298419 [I:onnxruntime:log, bfc_arena.cc:317 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:14 (requested) num_bytes: 4718592 (actual) rounded_bytes:4718592
2023-01-17 11:30:47.588450899 [I:onnxruntime:log, bfc_arena.cc:197 Extend] Extended allocation by 33554432 bytes.
2023-01-17 11:30:47.588477232 [I:onnxruntime:log, bfc_arena.cc:200 Extend] Total allocated bytes: 68157440
2023-01-17 11:30:47.588497694 [I:onnxruntime:log, bfc_arena.cc:203 Extend] Allocated memory at 0x7f51fff040 to 0x7f53fff040
2023-01-17 11:30:47.642722654 [I:onnxruntime:, session_state_utils.cc:342 SaveInitializedTensors] Done saving initialized tensors
2023-01-17 11:30:47.643228852 [I:onnxruntime:, inference_session.cc:1488 Initialize] Session successfully initialized.
I0117 11:30:47.643371 1 onnxruntime.cc:734] post auto-complete:
{
    "name": "CIFAR10",
    "platform": "onnxruntime_onnx",
    "backend": "onnxruntime",
    "version_policy": {
        "specific": {
            "versions": [
                3
            ]
        }
    },
    "max_batch_size": 1,
    "input": [
        {
            "name": "input",
            "data_type": "TYPE_FP32",
            "dims": [
                3,
                32,
                32
            ]
        }
    ],
    "output": [
        {
            "name": "output",
            "data_type": "TYPE_FP32",
            "dims": [
                10
            ]
        }
    ],
    "batch_input": [],
    "batch_output": [],
    "optimization": {
        "priority": "PRIORITY_DEFAULT",
        "input_pinned_memory": {
            "enable": true
        },
        "output_pinned_memory": {
            "enable": true
        },
        "gather_kernel_buffer_threshold": 0,
        "eager_batching": false
    },
    "instance_group": [
        {
            "name": "CIFAR10",
            "kind": "KIND_CPU",
            "count": 2,
            "gpus": [],
            "secondary_devices": [],
            "profile": [],
            "passive": false,
            "host_policy": ""
        }
    ],
    "default_model_filename": "model.onnx",
    "cc_model_filenames": {},
    "metric_tags": {},
    "parameters": {},
    "model_warmup": [
        {
            "name": "warmup",
            "batch_size": 1,
            "inputs": {
                "INPUT0": {
                    "data_type": "TYPE_FP32",
                    "dims": [
                        3,
                        32,
                        32
                    ],
                    "random_data": true
                }
            },
            "count": 1
        }
    ]
}
I0117 11:30:47.655099 1 onnxruntime.cc:2606] TRITONBACKEND_ModelInstanceInitialize: CIFAR10_0 (CPU device 0)
I0117 11:30:47.655184 1 backend_model_instance.cc:68] Creating instance CIFAR10_0 on CPU using artifact 'model.onnx'
2023-01-17 11:30:47.655324831 [I:onnxruntime:, inference_session.cc:271 ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2023-01-17 11:30:47.655373034 [I:onnxruntime:, inference_session.cc:292 ConstructorCommon] Dynamic block base set to 0
2023-01-17 11:30:47.706854487 [I:onnxruntime:, inference_session.cc:1222 Initialize] Initializing session.
2023-01-17 11:30:47.706917801 [I:onnxruntime:, inference_session.cc:1259 Initialize] Adding default CPU execution provider.
2023-01-17 11:30:47.706982060 [I:onnxruntime:log, bfc_arena.cc:26 BFCArena] Creating BFCArena for Cpu with following configs: initial_chunk_size_bytes: 1048576 max_dead_bytes_per_chunk: 134217728 initial_growth_chunk_size_bytes: 2097152 memory limit: 18446744073709551615 arena_extend_strategy: 0
2023-01-17 11:30:47.707004856 [V:onnxruntime:log, bfc_arena.cc:62 BFCArena] Creating 21 bins of max chunk size 256 to 268435456
2023-01-17 11:30:47.707772718 [I:onnxruntime:, reshape_fusion.cc:42 ApplyImpl] Total fused reshape node count: 0
2023-01-17 11:30:47.709145795 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.709264960 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.709325349 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.709381292 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.709433347 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.709485199 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.709536217 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.709587068 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.709637104 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.717214558 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.717347372 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.717406390 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.717461741 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.717516055 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.717569147 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.717624554 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.717678720 [V:onnxruntime:, selector_action_transformer.cc:129 MatchAndProcess] Matched Conv
2023-01-17 11:30:47.719076779 [V:onnxruntime:, session_state.cc:1010 VerifyEachNodeIsAssignedToAnEp] Node placements
2023-01-17 11:30:47.719131704 [V:onnxruntime:, session_state.cc:1013 VerifyEachNodeIsAssignedToAnEp]  All nodes placed on [CPUExecutionProvider]. Number of nodes: 25
2023-01-17 11:30:47.719432867 [V:onnxruntime:, session_state.cc:66 CreateGraphInfo] SaveMLValueNameIndexMapping
2023-01-17 11:30:47.719518589 [V:onnxruntime:, session_state.cc:112 CreateGraphInfo] Done saving OrtValue mappings.
2023-01-17 11:30:47.719883918 [I:onnxruntime:, session_state_utils.cc:199 SaveInitializedTensors] Saving initialized tensors.
2023-01-17 11:30:47.719960991 [I:onnxruntime:log, bfc_arena.cc:317 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:15 (requested) num_bytes: 9437184 (actual) rounded_bytes:9437184
2023-01-17 11:30:47.719991972 [I:onnxruntime:log, bfc_arena.cc:197 Extend] Extended allocation by 16777216 bytes.
2023-01-17 11:30:47.720011842 [I:onnxruntime:log, bfc_arena.cc:200 Extend] Total allocated bytes: 16777216
2023-01-17 11:30:47.720032305 [I:onnxruntime:log, bfc_arena.cc:203 Extend] Allocated memory at 0x7efdddb1c0 to 0x7efeddb1c0
2023-01-17 11:30:47.724409720 [I:onnxruntime:log, bfc_arena.cc:317 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:4 (requested) num_bytes: 6912 (actual) rounded_bytes:6912
2023-01-17 11:30:47.724520256 [I:onnxruntime:log, bfc_arena.cc:197 Extend] Extended allocation by 16777216 bytes.
2023-01-17 11:30:47.724543793 [I:onnxruntime:log, bfc_arena.cc:200 Extend] Total allocated bytes: 33554432
2023-01-17 11:30:47.724566515 [I:onnxruntime:log, bfc_arena.cc:203 Extend] Allocated memory at 0x7efeddb200 to 0x7effddb200
2023-01-17 11:30:47.769970516 [I:onnxruntime:log, bfc_arena.cc:317 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:15 (requested) num_bytes: 9437184 (actual) rounded_bytes:9437184
2023-01-17 11:30:47.770112885 [I:onnxruntime:log, bfc_arena.cc:197 Extend] Extended allocation by 33554432 bytes.
2023-01-17 11:30:47.770136662 [I:onnxruntime:log, bfc_arena.cc:200 Extend] Total allocated bytes: 67108864
2023-01-17 11:30:47.770156440 [I:onnxruntime:log, bfc_arena.cc:203 Extend] Allocated memory at 0x7f51fff040 to 0x7f53fff040
2023-01-17 11:30:47.819614267 [I:onnxruntime:, session_state_utils.cc:342 SaveInitializedTensors] Done saving initialized tensors
2023-01-17 11:30:47.820060262 [I:onnxruntime:, inference_session.cc:1488 Initialize] Session successfully initialized.
I0117 11:30:47.820191 1 backend_model_instance.cc:391] Generating warmup sample data for 'warmup'
I0117 11:30:47.820244 1 pinned_memory_manager.cc:161] non-pinned memory allocation: size 12288, addr 0x7f04232a20
I0117 11:30:47.821042 1 infer_request.cc:631] [request id: <id_unknown>] adding input override for INPUT0: [0x0x7f047931c0] request id: , model: CIFAR10, requested version: 3, actual version: 3, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
override inputs:
inputs:
original requested outputs:
requested outputs:

I0117 11:30:47.821098 1 infer_request.cc:646] [request id: <id_unknown>] added input override for INPUT0: [0x0x7f047931c0] request id: , model: CIFAR10, requested version: 3, actual version: 3, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
override inputs:
[0x0x7f04317880] input: INPUT0, type: FP32, original shape: [3,32,32], batch + shape: [1,3,32,32], shape: [3,32,32]
inputs:
[0x0x7f04317880] input: INPUT0, type: FP32, original shape: [3,32,32], batch + shape: [1,3,32,32], shape: [3,32,32]
original requested outputs:
requested outputs:

I0117 11:30:47.821176 1 onnxruntime.cc:2640] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0117 11:30:47.826262 1 pinned_memory_manager.cc:190] non-pinned memory deallocation: addr 0x7f04232a20
I0117 11:30:47.826558 1 onnxruntime.cc:2586] TRITONBACKEND_ModelFinalize: delete model state
E0117 11:30:47.826640 1 model_lifecycle.cc:597] failed to load 'CIFAR10' version 3: Invalid argument: [request id: <id_unknown>] expected 1 inputs but got 0 inputs for model 'CIFAR10'
I0117 11:30:47.826733 1 model_lifecycle.cc:285] VersionStates() 'CIFAR10'
I0117 11:30:47.827914 1 grpc_server.cc:270] Process for RepositoryModelLoad, rpc_ok=1, 21 step WRITEREADY
I0117 11:30:47.828321 1 grpc_server.cc:270] Process for RepositoryModelLoad, rpc_ok=1, 21 step COMPLETE
I0117 11:30:47.828366 1 grpc_server.cc:411] Done for RepositoryModelLoad, 21
```



It looks like the problem is with a unknown request id and not having the generated inputs, but I have not found anything about it in the proto configs.

`E0117 11:30:47.826640 1 model_lifecycle.cc:597] failed to load 'CIFAR10' version 3: Invalid argument: [request id: <id_unknown>] expected 1 inputs but got 0 inputs for model 'CIFAR10'`

The working generated configs of the model loaded without warmup from the triton server are:
```
{"name":"CIFAR10","platform":"onnxruntime_onnx","backend":"onnxruntime","version_policy":{"specific":{"versions":[3]}},"max_batch_size":1,"input":[{"name":"input","data_type":"TYPE_FP32","format":"FORMAT_NONE","dims":[3,32,32],"is_shape_tensor":false,"allow_ragged_batch":false,"optional":false}],"output":[{"name":"output","data_type":"TYPE_FP32","dims":[10],"label_filename":"","is_shape_tensor":false}],"batch_input":[],"batch_output":[],"optimization":{"priority":"PRIORITY_DEFAULT","input_pinned_memory":{"enable":true},"output_pinned_memory":{"enable":true},"gather_kernel_buffer_threshold":0,"eager_batching":false},"instance_group":[{"name":"CIFAR10","kind":"KIND_CPU","count":2,"gpus":[],"secondary_devices":[],"profile":[],"passive":false,"host_policy":""}],"default_model_filename":"model.onnx","cc_model_filenames":{},"metric_tags":{},"parameters":{},"model_warmup":[]}
```

**Comment by ozancaglayan** [comment] 2024-10-15 10:36
Hi,

Coming from the other ticket https://github.com/triton-inference-server/server/issues/4638 where the OP actually suggested a way to determine the model version from CLI args, e.g. `--load-model=foo:2` or `--load-model=foo/2`. I understand that running the server in EXPLICIT mode and then subsequently interacting with it with the model loading API is possible but is far from being convenient in deployment settings with liveness/readiness checks etc.

It's also not very clear because from what I understand, one should pass at least the `backend` parameter to `load_model()` as it does not read the `config.pbtxt` and update it from the `load_model()` args but rather completely overrides it. So one should design some HTTP/GRPC calls to prepare a quote-escaped string just to pass this version information which could have been done in CLI args to `tritonserver`.

Or maybe this is already possible but I'm missing it.

Thanks!
