### ISSUE TITLE
Triton Inference Server(23.03 container)  fails to load all models.

### ISSUE THREAD

**Issue by ManoharMarri** [triton-inference-server/server#5786] opened 2023-05-15 04:25 UTC
**Description**
**I have few TensorRT & python-backend models in the model repository that I feed to the triton inference server . While running the tritonserver command, it shows all the models as READY status, but it automatically unloads all the models immediately and returns the output : failed to load all models.**

**Triton Information**
23.03 docker container from NGC

Are you using the Triton container or did you build it yourself?

Using the container from NGC.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

All the ML models are from PyTorch framework.

**Expected behavior**
Ideally, since all the models are in READY state, it should respond with the inference endpoints link, where I can test the deployment.

**Comment by krishung5** [comment] 2023-05-16 19:15
Could you provide the complete server log with the verbose flag(`--log-verbose=1`) enabled? From the error message `failed to load all models`, it appears that one of the models may not have been loaded successfully. Consequently, the server unloads all the models, including the ones that were successfully loaded. The server log should provide more information that can help identify the issue.

**Comment by ac-bay** [comment] 2023-05-23 03:51
The problem I've met. The container version is 22.05. `--log-verbose=1` is enabled. The latest log entries show that some models have successful load message like `successful load <model name>' version 1`. It seems to stop loading at one model because there is Creating instance <a model name> on CPU using artifact, but no `successful load <a model name>' version 1` return. No more log, and the container doesn't restart even the triton doesn't work.

**Comment by wyzhangyuhan** [comment] 2023-06-12 12:02
@krishung5  I would like to ask if triton_repository contains other folders that are not model repositories, will this case make triton's startup fail.

For example, my file strutuct :
```
-triton_repository
  -FolderDoesntMatter
  -myInfer
    -1
    -config.pbtxt
```
`FolderDoesntMatter` consider as an empty folder

**Comment by dyastremsky** [comment] 2023-07-07 22:52
Yes, you should not have empty directories in your Triton model repository. Triton has no way of knowing that's not a model directory, so it assumes it is a model and will fail. When I reproduce locally, the logs show that the Triton tries to load the extra model directory as a model and fails.

I'm going to close this out because it sounds like the issue with the empty directory should now be clear and I don't see logs for the other two failures. If any of you still have issues, please upload your full, unabridged logs. Ideally regular and verbose.

**Closed by dyastremsky** 2023-07-07 22:52 UTC

**Comment by jayachandrakalakutagar** [comment] 2024-02-14 12:54
> @krishung5 I would like to ask if triton_repository contains other folders that are not model repositories, will this case make triton's startup fail.
> 
> For example, my file strutuct :
> 
> ```
> -triton_repository
>   -FolderDoesntMatter
>   -myInfer
>     -1
>     -config.pbtxt
> ```
> 
> `FolderDoesntMatter` consider as an empty folder

I have a folder directory
--triton_repo
    -ensemble
    -preprocessing
    -postprocessing
    -tensorrt-llm
tensorrt-llm folder has the engine all others have pbxt file. Still the same error is seen

**Comment by bkchang** [comment] 2024-05-29 16:47
I am having the same issue with 24.03-trtllm-python-py3 as described by @jayachandrakalakutagar
