### ISSUE TITLE
Not able to fully utilize A16 GPUs with Triton.

### ISSUE THREAD

**Issue by BasharMahasen** [triton-inference-server/server#5725] opened 2023-05-02 12:02 UTC
**Description**
We have issue with GPUs utilization with Triton. After a certain number of requests, Triton starts to buffer incoming requests, and grow the memory even though it has sufficient GPUs resources, CPU, and RAM. Following describes our setup, the issue.

**Triton Information**
nvcr.io/nvidia/tritonserver   23.02-py3

Are you using the Triton container or did you build it yourself?
NGC Container

**To Reproduce**
**Setup**
We run 3 models on a Triton server. The physical server has the following specs: 
-	GPU: A16, 4x 16 GB GDDR6. Each is virtualized into 3 GPUs
-	Server CPU: 96 cores, 
-	Server RAM: 128GB.

Models 1&2 run on GPUs [0..5]. These models process ~80 request per second.  Each has a python front end. Model 1 backend is ONNX while Model 2 backend is Tensor RT model.

Model 3 runs on GPUs [6..11]. This model processes ~30 frames per second. The model has a python front-end model with Tensor RT backend model.

**Case 1:** If we send frames to Model 3 ONLY, we are able to utilize the GPUs, and the utilization grows to 70%+. For this case, Triton is able to distribute and handle all the incoming load without buffering incoming requests. 

**Case 2**: If we start sending frames to Model 1 & 2 (which run their own GPUs), The GPUs' [6-11] utilization drops to 50% (or less); Triton starts to buffer incoming requests (mainly from Model 3), reserved RAM (by Triton) grows gradually until the server runs out of memory, and breaks.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Mode 1 - Python backend
-------------------------
name: "model_1"
backend: "python"
max_batch_size: 0

input [
  {
    name: "camera_id"
    data_type: TYPE_STRING
    dims: [1]
  }
]

input [
  {
    name: "images"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

input [
  {
    name: "timestamp"
    data_type: TYPE_FP64
    dims: [1]
  }
]

output [
  {
    name: "result",
    data_type: TYPE_STRING,
    dims: [1]
  }
]

instance_group: [
        {
            name: "model_1_instance0",
            kind: KIND_CPU,
            count: 10
        }
]

Mode 1 - ONNX backend
--------------------------
name: "model_1_onnx"
platform: "onnxruntime_onnx"

input [
  {
    name: "input.1",
    data_type: TYPE_FP32,
    dims: [-1, 3,112,112]
  }
  ]

output [
{
    name: "683",
    data_type: TYPE_FP32,
    dims: [1, 512]
}
]

instance_group: [
{
            name: "model_1_onnx_0",
            kind: KIND_GPU,
            count: 3
			gpus: [0, 1 ,2 ,3 ,4, 5]
}
]

Model 2 - Python backend
-------------------------
name: "model_2"
backend: "python"
max_batch_size: 0

input [
  {
    name: "camera_id"
    data_type: TYPE_STRING
    dims: [1]
  }
]

input [
  {
    name: "images"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

input [
  {
    name: "timestamp"
    data_type: TYPE_FP64
    dims: [1]
  }
]

output [
  {
    name: "result",
    data_type: TYPE_STRING,
    dims: [1]
  }
]

instance_group: [
        {
            name: "model_2_instance_0",
            kind: KIND_CPU,
            count: 5
        }
]

Model 2 - TRT backend
-------------------------
name: "model_2_fp16"
platform: "tensorrt_plan"
max_batch_size: 10

instance_group: [
{
            name: "model_2_fp16_0",
            kind: KIND_GPU,
            count: 2,
            gpus: [6,7,8,9,10,11]
}
]

Mode 3 - Python backend
-------------------------
name: "model_3"
backend: "python"
max_batch_size: 0

input [
  {
    name: "camera_id"
    data_type: TYPE_STRING
    dims: [1]
  }
]

input [
  {
    name: "images"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

input [
  {
    name: "timestamp"
    data_type: TYPE_FP64
    dims: [1]
  }
]

output [
  {
    name: "result",
    data_type: TYPE_STRING,
    dims: [1]
  }
]

instance_group: [
        {
            name: "model_3_instance0",
            kind: KIND_CPU,
            count: 10
        }
]

Model 3 - TRT backend
-------------------------
name: "model_3_fp16"
platform: "tensorrt_plan"
max_batch_size: 10

instance_group: [
{
            name: "model_3_fp16_0",
            kind: KIND_GPU,
            count: 2,
            gpus: [6,7,8,9,10,11]
}
]

optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }
    }]
}}

**Expected behavior**

We highly appreciate your feedback / inputs on the followings:

-	Why does Triton buffers the requests even though it has plenty of GPU resources to utilize?
-	What causes this bottleneck, and what configurations we’re missing to fully utilize the server’s GPUs?
-	How to control Triton buffering and avoid out of memory as a proactive measure?
-	Which resource do you suggest for Triton performance monitoring, and fine-tuning.

**Comment by GuanLuo** [comment] 2023-05-02 17:22
How does the Python backend and the other framework model being linked together? Are you using Python BLS or ensemble?

I suspect the CPU has become the bottleneck because each Python model instance is running in a separate process (total of 25 processes in your case), I wonder if you can run [perf_analyzer](https://github.com/triton-inference-server/client/tree/main/src/c%2B%2B/perf_analyzer#triton-performance-analyzer) to generate load for the model 3 in case 1 and case 2, which will show you the latency breakdown on the time spent in different section. You may get some idea on what becomes the bottleneck in case 2.

PA should support profiling with ensemble model, @matthewkotila on whether PA currently supports composing model profiling on Python BLS.

**Comment by BasharMahasen** [comment] 2023-05-03 11:59
@GuanLuo @matthewkotila 

Here are the requested details:

We are using BLS for Model 3. It is actually 2 modes (Python + TRT). We send raw frames to a python backend model which does pre-processing, call the TRT model, and forward the result to a Kafka server.
Currently, we use gRPC to call the TRT backend as we had issues with C APIs.

I am not sure the CPU can be a bottleneck. The server has 96 cores. CPU utilization while running Case 1 was around 45-50%, and ~15% while running case 2.

I hope this helps answering our above questions.

** Case 1 : Running Model 3 on GPUs [6-11] while Models 1&2 are running on GPUs[0-5]

root@acb895a2933c:/workspace# perf_analyzer -m model_3 -u tanbeeh-server:8001 -i grpc --input-data data1.json --request-rate-range=20:25  --percentile=99 --measurement-interval 15000 -v
 Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 15000 msec
  Latency limit: 0 msec
  Request Rate limit: 25 requests per seconds
  Using uniform distribution on request generation
  Using synchronous calls for inference
  Stabilizing using p99 latency

Request Rate: 20 inference requests per seconds
  Pass [1] throughput: 10.9996 infer/sec. p99 latency: 487911 usec
  Pass [2] throughput: 11.3845 infer/sec. p99 latency: 477118 usec
  Pass [3] throughput: 11.3883 infer/sec. p99 latency: 462657 usec
  Client:
    Request count: 608
    Delayed Request Count: 604
    Throughput: 11.2575 infer/sec
    Avg client overhead: 0.01%
    Avg send request rate: 11.33 infer/sec
    p50 latency: 348764 usec
    p90 latency: 416065 usec
    p95 latency: 437471 usec
    p99 latency: 479883 usec
    Avg gRPC time: 352935 usec (marshal 218 usec + response wait 352711 usec + unmarshal 6 usec)
  Server:
    Inference count: 608
    Execution count: 608
    Successful request count: 608
    Avg request latency: 350341 usec (overhead 70 usec + queue 169 usec + compute input 253 usec + compute infer 349672 usec + compute output 176 usec)

Request Rate: 21 inference requests per seconds
  Pass [1] throughput: 10.8881 infer/sec. p99 latency: 565597 usec
  Pass [2] throughput: 11.1658 infer/sec. p99 latency: 499192 usec
  Pass [3] throughput: 11.2762 infer/sec. p99 latency: 532672 usec
  Pass [4] throughput: 11.7215 infer/sec. p99 latency: 429305 usec
  Pass [5] throughput: 11.277 infer/sec. p99 latency: 491238 usec
  Pass [6] throughput: 11.4404 infer/sec. p99 latency: 458335 usec
  Pass [7] throughput: 11.6661 infer/sec. p99 latency: 449231 usec
  Client:
    Request count: 619
    Delayed Request Count: 619
    Throughput: 11.4612 infer/sec
    Avg client overhead: 0.02%
    Avg send request rate: 11.46 infer/sec
    p50 latency: 345740 usec
    p90 latency: 411864 usec
    p95 latency: 428684 usec
    p99 latency: 470240 usec
    Avg gRPC time: 349093 usec (marshal 210 usec + response wait 348878 usec + unmarshal 5 usec)
  Server:
    Inference count: 619
    Execution count: 619
    Successful request count: 619
    Avg request latency: 346601 usec (overhead 42 usec + queue 199 usec + compute input 241 usec + compute infer 345945 usec + compute output 173 usec)

Request Rate: 22 inference requests per seconds
  Pass [1] throughput: 10.832 infer/sec. p99 latency: 520380 usec
  Pass [2] throughput: 11.1662 infer/sec. p99 latency: 505189 usec
  Pass [3] throughput: 11.3847 infer/sec. p99 latency: 470327 usec
  Pass [4] throughput: 11.2214 infer/sec. p99 latency: 476101 usec
  Client:
    Request count: 608
    Delayed Request Count: 608
    Throughput: 11.2574 infer/sec
    Avg client overhead: 0.02%
    Avg send request rate: 11.26 infer/sec
    p50 latency: 350811 usec
    p90 latency: 418786 usec
    p95 latency: 441898 usec
    p99 latency: 489597 usec
    Avg gRPC time: 355342 usec (marshal 223 usec + response wait 355114 usec + unmarshal 5 usec)
  Server:
    Inference count: 608
    Execution count: 608
    Successful request count: 608
    Avg request latency: 352646 usec (overhead 38 usec + queue 195 usec + compute input 254 usec + compute infer 351980 usec + compute output 179 usec)

Request Rate: 23 inference requests per seconds
  Pass [1] throughput: 11.3328 infer/sec. p99 latency: 464225 usec
  Pass [2] throughput: 11.2126 infer/sec. p99 latency: 537186 usec
  Pass [3] throughput: 11.7214 infer/sec. p99 latency: 448478 usec
  Pass [4] throughput: 11.2764 infer/sec. p99 latency: 497842 usec
  Pass [5] throughput: 11.6657 infer/sec. p99 latency: 464571 usec
  Pass [6] throughput: 11.8884 infer/sec. p99 latency: 467466 usec
  Client:
    Request count: 627
    Delayed Request Count: 627
    Throughput: 11.6102 infer/sec
    Avg client overhead: 0.01%
    Avg send request rate: 11.63 infer/sec
    p50 latency: 341033 usec
    p90 latency: 407067 usec
    p95 latency: 427896 usec
    p99 latency: 494371 usec
    Avg gRPC time: 344077 usec (marshal 210 usec + response wait 343861 usec + unmarshal 6 usec)
  Server:
    Inference count: 628
    Execution count: 628
    Successful request count: 628
    Avg request latency: 341397 usec (overhead 61 usec + queue 207 usec + compute input 252 usec + compute infer 340707 usec + compute output 168 usec)

Request Rate: 24 inference requests per seconds
  Pass [1] throughput: 11.2774 infer/sec. p99 latency: 443417 usec
  Pass [2] throughput: 11.1099 infer/sec. p99 latency: 568785 usec
  Pass [3] throughput: 10.9437 infer/sec. p99 latency: 532298 usec
  Pass [4] throughput: 11.3823 infer/sec. p99 latency: 468413 usec
  Pass [5] throughput: 11.8325 infer/sec. p99 latency: 471159 usec
  Pass [6] throughput: 11.332 infer/sec. p99 latency: 469912 usec
  Client:
    Request count: 622
    Delayed Request Count: 622
    Throughput: 11.5155 infer/sec
    Avg client overhead: 0.03%
    Avg send request rate: 11.52 infer/sec
    p50 latency: 342720 usec
    p90 latency: 413219 usec
    p95 latency: 435901 usec
    p99 latency: 471159 usec
    Avg gRPC time: 347771 usec (marshal 201 usec + response wait 347564 usec + unmarshal 6 usec)
  Server:
    Inference count: 622
    Execution count: 622
    Successful request count: 622
    Avg request latency: 344981 usec (overhead 43 usec + queue 168 usec + compute input 250 usec + compute infer 344348 usec + compute output 172 usec)

Request Rate: 25 inference requests per seconds
  Pass [1] throughput: 11.2215 infer/sec. p99 latency: 477901 usec
  Pass [2] throughput: 11.0534 infer/sec. p99 latency: 503226 usec
  Pass [3] throughput: 11.2736 infer/sec. p99 latency: 512328 usec
  Client:
    Request count: 604
    Delayed Request Count: 600
    Throughput: 11.1829 infer/sec
    Avg client overhead: 0.02%
    Avg send request rate: 11.26 infer/sec
    p50 latency: 350232 usec
    p90 latency: 431120 usec
    p95 latency: 456832 usec
    p99 latency: 512328 usec
    Avg gRPC time: 356312 usec (marshal 196 usec + response wait 356110 usec + unmarshal 6 usec)
  Server:
    Inference count: 604
    Execution count: 604
    Successful request count: 604
    Avg request latency: 353422 usec (overhead 77 usec + queue 221 usec + compute input 251 usec + compute infer 352712 usec + compute output 160 usec)

Inferences/Second vs. Client p99 Batch Latency
Request Rate: 20, throughput: 11.2575 infer/sec, latency 479883 usec
Request Rate: 21, throughput: 11.4612 infer/sec, latency 470240 usec
Request Rate: 22, throughput: 11.2574 infer/sec, latency 489597 usec
Request Rate: 23, throughput: 11.6102 infer/sec, latency 494371 usec
Request Rate: 24, throughput: 11.5155 infer/sec, latency 471159 usec
Request Rate: 25, throughput: 11.1829 infer/sec, latency 512328 usec



** Running Model3 on GPUs [6-11] -- while no other models running on the server ** 
root@acb895a2933c:/workspace# perf_analyzer -m model_3 -u tanbeeh-server:8001 -i grpc --input-data data1.json --request-rate-range=20:25  --percentile=99 --measurement-interval 15000 -v
 Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 15000 msec
  Latency limit: 0 msec
  Request Rate limit: 25 requests per seconds
  Using uniform distribution on request generation
  Using synchronous calls for inference
  Stabilizing using p99 latency

Request Rate: 20 inference requests per seconds
  Pass [1] throughput: 15.2771 infer/sec. p99 latency: 1584791 usec
  Pass [2] throughput: 17.9988 infer/sec. p99 latency: 248607 usec
  Pass [3] throughput: 17.7769 infer/sec. p99 latency: 269760 usec
  Pass [4] throughput: 18.1658 infer/sec. p99 latency: 256392 usec
  Client:
    Request count: 971
    Delayed Request Count: 971
    Throughput: 17.9805 infer/sec
    Avg client overhead: 0.01%
    Avg send request rate: 17.98 infer/sec
    p50 latency: 219997 usec
    p90 latency: 236089 usec
    p95 latency: 243613 usec
    p99 latency: 260560 usec
    Avg gRPC time: 222328 usec (marshal 83 usec + response wait 222244 usec + unmarshal 1 usec)
  Server:
    Inference count: 971
    Execution count: 971
    Successful request count: 971
    Avg request latency: 221392 usec (overhead 26 usec + queue 80 usec + compute input 132 usec + compute infer 221049 usec + compute output 104 usec)

Request Rate: 21 inference requests per seconds
  Pass [1] throughput: 18.166 infer/sec. p99 latency: 239521 usec
  Pass [2] throughput: 18.6103 infer/sec. p99 latency: 230818 usec
  Pass [3] throughput: 18.5546 infer/sec. p99 latency: 231779 usec
  Client:
    Request count: 996
    Delayed Request Count: 992
    Throughput: 18.4436 infer/sec
    Avg client overhead: 0.00%
    Avg send request rate: 18.52 infer/sec
    p50 latency: 215656 usec
    p90 latency: 225922 usec
    p95 latency: 228548 usec
    p99 latency: 234983 usec
    Avg gRPC time: 216103 usec (marshal 88 usec + response wait 216013 usec + unmarshal 2 usec)
  Server:
    Inference count: 996
    Execution count: 996
    Successful request count: 996
    Avg request latency: 215214 usec (overhead 25 usec + queue 85 usec + compute input 127 usec + compute infer 214867 usec + compute output 108 usec)

Request Rate: 22 inference requests per seconds
  Pass [1] throughput: 18.2217 infer/sec. p99 latency: 240826 usec
  Pass [2] throughput: 18.3881 infer/sec. p99 latency: 244328 usec
  Pass [3] throughput: 18.2763 infer/sec. p99 latency: 250268 usec
  Client:
    Request count: 988
    Delayed Request Count: 984
    Throughput: 18.2953 infer/sec
    Avg client overhead: 0.00%
    Avg send request rate: 18.37 infer/sec
    p50 latency: 216680 usec
    p90 latency: 229777 usec
    p95 latency: 235317 usec
    p99 latency: 244448 usec
    Avg gRPC time: 217813 usec (marshal 86 usec + response wait 217726 usec + unmarshal 1 usec)
  Server:
    Inference count: 988
    Execution count: 988
    Successful request count: 988
    Avg request latency: 216891 usec (overhead 26 usec + queue 97 usec + compute input 130 usec + compute infer 216532 usec + compute output 105 usec)

Request Rate: 23 inference requests per seconds
  Pass [1] throughput: 18.3326 infer/sec. p99 latency: 236194 usec
  Pass [2] throughput: 18.6654 infer/sec. p99 latency: 229669 usec
  Pass [3] throughput: 18.3881 infer/sec. p99 latency: 238612 usec
  Client:
    Request count: 997
    Delayed Request Count: 993
    Throughput: 18.462 infer/sec
    Avg client overhead: 0.01%
    Avg send request rate: 18.54 infer/sec
    p50 latency: 215364 usec
    p90 latency: 225740 usec
    p95 latency: 229262 usec
    p99 latency: 236876 usec
    Avg gRPC time: 215672 usec (marshal 82 usec + response wait 215589 usec + unmarshal 1 usec)
  Server:
    Inference count: 997
    Execution count: 997
    Successful request count: 997
    Avg request latency: 214799 usec (overhead 33 usec + queue 102 usec + compute input 117 usec + compute infer 214445 usec + compute output 101 usec)

Request Rate: 24 inference requests per seconds
  Pass [1] throughput: 18.3883 infer/sec. p99 latency: 230471 usec
  Pass [2] throughput: 18.4432 infer/sec. p99 latency: 245381 usec
  Pass [3] throughput: 18.5548 infer/sec. p99 latency: 237750 usec
  Client:
    Request count: 997
    Delayed Request Count: 993
    Throughput: 18.4621 infer/sec
    Avg client overhead: 0.01%
    Avg send request rate: 18.54 infer/sec
    p50 latency: 215175 usec
    p90 latency: 226298 usec
    p95 latency: 229162 usec
    p99 latency: 237750 usec
    Avg gRPC time: 215891 usec (marshal 85 usec + response wait 215805 usec + unmarshal 1 usec)
  Server:
    Inference count: 997
    Execution count: 997
    Successful request count: 997
    Avg request latency: 215041 usec (overhead 34 usec + queue 92 usec + compute input 118 usec + compute infer 214696 usec + compute output 100 usec)

Request Rate: 25 inference requests per seconds
  Pass [1] throughput: 18.4439 infer/sec. p99 latency: 236133 usec
  Pass [2] throughput: 18.7768 infer/sec. p99 latency: 227080 usec
  Pass [3] throughput: 18.6105 infer/sec. p99 latency: 235595 usec
  Client:
    Request count: 1005
    Delayed Request Count: 1001
    Throughput: 18.6104 infer/sec
    Avg client overhead: 0.01%
    Avg send request rate: 18.68 infer/sec
    p50 latency: 213565 usec
    p90 latency: 223184 usec
    p95 latency: 225887 usec
    p99 latency: 234394 usec
    Avg gRPC time: 214112 usec (marshal 90 usec + response wait 214020 usec + unmarshal 2 usec)
  Server:
    Inference count: 1005
    Execution count: 1005
    Successful request count: 1005
    Avg request latency: 213279 usec (overhead 31 usec + queue 105 usec + compute input 118 usec + compute infer 212918 usec + compute output 106 usec)

Inferences/Second vs. Client p99 Batch Latency
Request Rate: 20, throughput: 17.9805 infer/sec, latency 260560 usec
Request Rate: 21, throughput: 18.4436 infer/sec, latency 234983 usec
Request Rate: 22, throughput: 18.2953 infer/sec, latency 244448 usec
Request Rate: 23, throughput: 18.462 infer/sec, latency 236876 usec
Request Rate: 24, throughput: 18.4621 infer/sec, latency 237750 usec
Request Rate: 25, throughput: 18.6104 infer/sec, latency 234394 usec

**Comment by matthewkotila** [comment] 2023-05-03 18:21
Yes, I believe Perf Analyzer support for profiling BLS models was added recently by @tgerdesnv. He can probably comment more on how to get started.

**Comment by tgerdesnv** [comment] 2023-05-03 20:59
Starting in 23.04, Perf Analyzer will report composing model statistics for BLS models as long as the list of all composing models is specified in `--bls-composing-models`.

This functionality is not available in 23.02.

**Comment by BasharMahasen** [comment] 2023-05-04 09:43
Thank you for your reply. We have started working on the optimization, however, our priority is solve the crashing issue. Given the performance of A16 GPUs and the expected load on Triton, the server may eventually receives more requests than it can handle.!!
Currently, Triton accumulates incoming requests indefinitely and continues to buffer incoming requests until it crashes. We want to prevent this from happening! 

Could you please advise on how to configure Triton to stop accepting requests after a certain threshold or to time-out in-flight requests after a certain interval?

**Comment by GuanLuo** [comment] 2023-05-04 16:17
I saw the "compute infer" time is much larger when all models are under load, @Tabrizian for Python BLS, does "compute infer" represent the end-to-end time of the BLS logic? 

> Starting in 23.04, Perf Analyzer will report composing model statistics for BLS models as long as the list of all composing models is specified in --bls-composing-models.

@BasharMahasen is it possible for you to try 23.04 to get the more detailed breakdown? Or you can also try to add some timestamp recording in your Python BLS logic to futher investigate which part contributes to the increased latency.

**Comment by Tabrizian** [comment] 2023-05-04 16:56
> @Tabrizian for Python BLS, does "compute infer" represent the end-to-end time of the BLS logic?

Yes. The Python model compute infer time would represent the end-to-end time including the time required to execute the BLS requests.

**Comment by BasharMahasen** [comment] 2023-05-09 12:48
@GuanLuo For buffer control, we tested the queue policy controls and they worked fine. Thank you.

Regarding the issue of full GPU utilization, we upgraded TRITON to version 23.04 and converted the model from FP32 to FP16 (TRT). As a result, the inference time dropped. However, we are still unable to fully utilize the GPUs. Regardless of the number of requests we put in, the GPUs do not go beyond 50-60% utilization. We tried different permutations of TRT model instances (1-4), but that did not really help. We found that the performance of 1 instance is nearly as good as 4 concurrent TRT instances.

We restricted the TRT model to 1 and then to 2 GPUs. For this case, the GPUs hit 99% utilization at 50 requests per second. However, when we increased the rate to 200 and made the model available on 6 GPUs, GPUs utilization saturated around 50%, and you can see the same from  throughput rate.
 throughput: 21.7771 infer/sec. -- 6 GPUs with 200 request/s
 throughput: 16.0552 infer/sec. -- 2 GPUs with 50 request/s

What bottleneck are we encountering that prevents us from increasing the utilization over all the GPUs?



Model3 BLS analysis (end-to-end Python backend + TRT )
------------------------

6 GPUs - 45% utilization for all the 6 GPUs

root@b478a6ea68ef:/workspace# perf_analyzer -m model_3_bls -u localhost:8001 -i grpc --input-data generic_input_with_shape.json --request-rate-range=200:201 --percentile=99 --measurement-interval 15000 -v
 Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 15000 msec
  Latency limit: 0 msec
  Request Rate limit: 201 requests per seconds
  Using uniform distribution on request generation
  Using synchronous calls for inference
  Stabilizing using p99 latency

Request Rate: 200 inference requests per seconds
  Pass [1] throughput: 21.9989 infer/sec. p99 latency: 202888 usec
  Pass [2] throughput: 22.3324 infer/sec. p99 latency: 194470 usec
  Pass [3] throughput: 22.3879 infer/sec. p99 latency: 198930 usec
  Client:
    Request count: 1201
    Delayed Request Count: 1197
    Throughput: 22.2397 infer/sec
    Avg client overhead: 0.00%
    Avg send request rate: 22.31 infer/sec
    p50 latency: 177640 usec
    p90 latency: 185451 usec
    p95 latency: 190304 usec
    p99 latency: 200283 usec
    Avg gRPC time: 179551 usec (marshal 94 usec + response wait 179455 usec + unmarshal 2 usec)
  Server:
    Inference count: 1201
    Execution count: 1198
    Successful request count: 1201
    Avg request latency: 178699 usec (overhead 29 usec + queue 185 usec + compute input 118 usec + compute infer 178285 usec + compute output 81 usec)

Request Rate: 201 inference requests per seconds
  Pass [1] throughput: 21.9434 infer/sec. p99 latency: 221953 usec
  Pass [2] throughput: 21.721
![Untitled2](https://github.com/triton-inference-server/server/assets/4402789/b37c42a0-f6bd-4801-bc95-ae6d30a0bb53)
![Untitled](https://github.com/triton-inference-server/server/assets/4402789/56042413-71cd-4407-a39a-010fb6846a6b)
1 infer/sec. p99 latency: 349807 usec
  Pass [3] throughput: 22.6098 infer/sec. p99 latency: 194350 usec



Model3 BLS analysis (end-to-end Python backend + TRT )
------------------------
2 GPUs -- each with 99% utilization 

root@b478a6ea68ef:/workspace# perf_analyzer -m model_3_bls -u localhost:8001 -i grpc --input-data generic_input_with_shape.json --request-rate-range=50:51 --percentile=99 --measurement-interval 15000 -v
 Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 15000 msec
  Latency limit: 0 msec
  Request Rate limit: 51 requests per seconds
  Using uniform distribution on request generation
  Using synchronous calls for inference
  Stabilizing using p99 latency

Request Rate: 50 inference requests per seconds
  Pass [1] throughput: 16.0552 infer/sec. p99 latency: 260191 usec
  Pass [2] throughput: 16.1661 infer/sec. p99 latency: 256155 usec
  Pass [3] throughput: 16.1101 infer/sec. p99 latency: 255997 usec
  Client:
    Request count: 870
    Delayed Request Count: 866
    Throughput: 16.1105 infer/sec
    Avg client overhead: 0.00%
    Avg send request rate: 16.18 infer/sec
    p50 latency: 247401 usec
    p90 latency: 251432 usec
    p95 latency: 253077 usec
    p99 latency: 257875 usec
    Avg gRPC time: 247363 usec (marshal 108 usec + response wait 247253 usec + unmarshal 2 usec)
  Server:
    Inference count: 870
    Execution count: 870
    Successful request count: 870
    Avg request latency: 246480 usec (overhead 27 usec + queue 168 usec + compute input 118 usec + compute infer 246079 usec + compute output 87 usec)

**Comment by BasharMahasen** [comment] 2023-05-13 04:39
@GuanLuo , @Tabrizian  would you kindly update on the above?

**Comment by GuanLuo** [comment] 2023-05-16 00:37
@BasharMahasen sorry for missing this reply, can you add `--bls-composing-models` to your perf analyzer experiment to show the per-model breakdown?

I don't see anything obvious here so just throwing out ideas:
- you may try `--backend-config=tensorrt,execution-policy=BLOCKING` to change the TRT backend execution [setting](https://github.com/triton-inference-server/tensorrt_backend#command-line-options) to see if it helps.
- What is your network bandwidth? You can try running perf analyzer with `--shared-memory` to minimize the data transfer over network to make sure it is not network bounded.

**Comment by GuanLuo** [comment] 2023-05-19 22:15
So I am looking for spike in one of the latency breakdown i.e. `(overhead ... + queue x usec + ... + compute infer y usec + ...)`, and interestingly none of the number seems to be increasing, especially the queue time which is usually the indicator of whether the server is under sufficient load. That suggests that the network is the bottleneck. 

You didn't post the result for the experiment w.r.t. network bandwidth, can you try with the mentioned suggested and see if it helps?
>What is your network bandwidth? You can try running perf analyzer with --shared-memory to minimize the data transfer over network to make sure it is not network bounded.

**Comment by BasharMahasen** [comment] 2023-05-24 05:39
Hi @GuanLuo 
Attached the results of perf_analyzer on the following test cases with and without with tesnor rt backend configs : (--backend-config=tensorrt,execution-policy=BLOCKING).
- BLS / Shared Memory 
- BLS / GRPC 
- TRT / Shared Memory 

The network card we use is 10G, and do not think it is a network issue. The communication between the BLS and TRT is IPC. In addition, our issue is that even the BLS's queue is full, it is not picking more requests and keep the GPUs underutilized (around 60-65%).

[perf_analyzer_without_tensorrt_backend_configs.txt](https://github.com/triton-inference-server/server/files/11550798/perf_analyzer_without_tensorrt_backend_configs.txt)

[perf_analyzer_with_tensorrt_backend_configs.txt](https://github.com/triton-inference-server/server/files/11550799/perf_analyzer_with_tensorrt_backend_configs.txt)

**Comment by BasharMahasen** [comment] 2023-05-30 06:13
Hi @GuanLuo, Did you have the chance to look into the log files I provided?

**Comment by GuanLuo** [comment] 2023-05-31 00:19
> even the BLS's queue is full, it is not picking more requests

You may have tried it but just want to double check: did you increase the number of BLS instances accordingly as you are scaling up on number of GPUs?

Also the queue latency seems to be too small if the requests are actually being backlogged in the server side, some simplified calculation suggests that if there are 18 requests being backlogged at any given second, the queue time be at millisecond unit. Just to verify, do you observe increase in queue time if you increase the concurrency while keeping everything else unchanged?
```
Request Rate: 50 inference requests per seconds
Throughput: 32.6096 infer/sec
queue 254 usec
```

Otherwise, I don't have too much insight from the logs you shared. It is hard to analyze without local reproducer for experimentation. You may also try the [tracing feature](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md) to get timestamps reported at request-level to identify any abnormality.

**Comment by Tabrizian** [comment] 2023-06-23 20:07
Closing, due to in in-activity. Feel free to open new issues if you have additional questions.

**Closed by Tabrizian** 2023-06-23 20:07 UTC
