### ISSUE TITLE
Triton server is slower than pytorch model

### ISSUE THREAD

**Issue by guyqaz** [triton-inference-server/server#3334] opened 2021-09-08 08:55 UTC
**Description**
I have converted model with Torchscript format
I call Triton server using Grpc client. The Model has been synthesized successfully.
But the speed of the model in Triton server is very slow, when it only synthesizes 1 short sentence with 4 words, with Pytorch model it takes less than 0.1 seconds, however with Triton server, the calculation time is about 1.5 seconds.

**Triton Information**
What version of Triton are you using?
r21.04, server version 2.7.0 , cuda_11.2, GPU device:RTX 2080 Ti

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

```
name: "FastPitch"
platform: "pytorch_libtorch"
default_model_filename: "model.pt"

max_batch_size: 8

input {
    name: "INPUT__0"
    data_type: TYPE_INT64
    dims: -1
}
input {
    name: "INPUT__1"
    data_type: TYPE_INT64
    dims: 1
}
output {
    name: "OUTPUT__0"
    data_type: TYPE_FP16
    dims: 80
    dims: -1
}
output {
    name: "OUTPUT__1"
    data_type: TYPE_INT64
    dims: 1
    reshape {
    }
}
output {
    name: "OUTPUT__2"
    data_type: TYPE_FP16
    dims: -1
}
output {
    name: "OUTPUT__3"
    data_type: TYPE_FP16
    dims: -1
}

dynamic_batching {
    preferred_batch_size: [ 4, 8 ]
}

instance_group {
    count: 1
    gpus: 0
    kind: KIND_GPU
}
```
Triton server's log verbose:
```
I0908 08:50:40.641507 2516 libtorch.cc:1095] model FastPitch, instance FastPitch_0, executing 1 requests
I0908 08:50:40.641566 2516 libtorch.cc:504] TRITONBACKEND_ModelExecute: Running FastPitch_0 with 1 requests
I0908 08:50:42.023955 2516 infer_response.cc:165] add response output: output: OUTPUT__0, type: FP16, shape: [1,80,81]
```

**Expected behavior**
I have tried many times but can't fix it.

**Comment by dzier** [comment] 2021-09-08 16:53
Are you sure we are seeing an apples to apples comparison. It sounds like you are comparing a Pytorch model converted to Torchscript running on Triton with an unconverted Pytorch model running on Pytorch. Have you tried running on the Pytorch model on the Pytorch backend directly? Does the converted Torchscript model have the same performance as the Pytorch model outside of Triton?

There have also been some performance improvements in the latest Triton. Do you see the same slowdown in the 2.13.0 version of Triton released in 21.08?

**Comment by guyqaz** [comment] 2021-09-12 01:00
I checked with your advice. Yes, that's not slow on the Triton Server side, when I Convert Model via TorchScript, the model is slower than the Pytorch model outside of Triton. I will try using Pytorch Model with Pytorch backend directly and comparing the results. Thanks for your support!

**Comment by CoderHam** [comment] 2021-09-13 17:18
@guyqaz can you quantify the slowdown and confirm you are using the same version of pytorch as in the Triton release container? You can use the pytorch NGC container for the same release to test your model performance.
We want to compare perf between [PyTorch + Torchscript model] and [Triton + Torchscript model] (Use our perf analyzer so you can see the compute breakdown) to ensure we have an apples to apples comparison.

Ideally, since we use the PyTorch C++ API and we would want to compare performance between native PyTorch C++ API but we can use the PyTorch Python API initially.

**Comment by CoderHam** [comment] 2021-09-30 18:57
@guyqaz we are waiting on a quantified slowdown + model and repo code to be able to further help you.

**Comment by CaoTungSt** [comment] 2021-10-13 23:58
Sorry for the late reply, i will recalculate the result.

**Comment by CoderHam** [comment] 2021-11-15 23:01
@guyqaz closing due to inactivity. I can re-open once you provide us with additional reproduction steps for the issue.

**Closed by CoderHam** 2021-11-15 23:01 UTC
