### ISSUE TITLE
GRPC server always return `RawOutputContents` even if the `InferInputTensor::contents` is specified.

### ISSUE THREAD

**Issue by zouyxdut** [triton-inference-server/server#2937] opened 2021-05-29 07:26 UTC
**Description**
GRPC server always return `RawOutputContents` even if the `InferInputTensor::contents` is specified.

**Triton Information**
r21.03 container

**To Reproduce**
In `src/clients/go/grpc_simple_client.go`, change the input from `RawInputContents` to `InferInputTensor::contents` and just run the sample.

**Expected behavior**
`InferOutputTensor::Contents` should be returned.

Is this behavior by design or a bug?

**Comment by CoderHam** [comment] 2021-06-01 19:22
@zouyxdut the go example is minimal and not the best supported way to. While I look into this could you try using the python grpc client examples to test if it works as per your expectations?
Please refer to the proto definition [here](https://github.com/triton-inference-server/common/blob/main/protobuf/grpc_service.proto) and the python grpc client library [here](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritongrpcclient/__init__.py) to ensure you are using it correctly.

**Comment by tanmayv25** [comment] 2021-06-02 19:31
The return by raw output contents is by design for performance consideration. The parsing of data to contents field will be an expensive operation on the upstream. Hence, tritonserver will directly return the output as a raw data blob. Provided the blob,  user can always parse out the data into individual elements.

@zouyxdut  Do you have a specific use case where you require output to be returned as explicit contents field? Or was there any indication that using `InferInputTensor::contents` would return results as `InferOutputTensor::Contents` in triton docs? If latter is true, we can fix the docs to prevent giving the wrong idea.

**Comment by zouyxdut** [comment] 2021-06-03 06:45
@tanmayv25 The doc doesn't mention that only the `RawOutputContents` would be returned, which makes me confused. So is it the same behavior on the HTTP server?  And when will the `InferOutputTensor::Contents` be returned?

**Comment by tanmayv25** [comment] 2021-06-03 11:55
> So is it the same behavior on the HTTP server? 

HTTP uses json based output return format. So, yes by default http returns as explicit tensors. We adhere to standardized API as described here :https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md#response-output

For better performance in http, users and rely on binary tensor data extension described here: https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_binary_data.md

> And when will the InferOutputTensor::Contents be returned?

In case of Triton IS, **never**.  It is just a part of the standardized grpc response message. Other predict services can chose to return data in  InferOutputTensor::Contents but Triton will always return data as `RawOutputContents` for performance reasons.

**Comment by tanmayv25** [comment] 2021-06-07 11:43
Closing the issue.. Please file a new issue if you would like to request for output to be returned as explicit array within InferOutputTensor::Contents.

**Closed by tanmayv25** 2021-06-07 11:43 UTC
Labels: question
