### ISSUE TITLE
Inputs' shape with reshape for batch inference has wired behaviour

### ISSUE THREAD

**Issue by andompesta** [triton-inference-server/server#5035] opened 2022-11-03 10:36 UTC
**Description**
I'm having a "wide" model written in Tensorflow 2.8. This models expect ~100 features as input, all of them being single scalar values. For ease of use, I created a specific signature to consume the model in production that does not uses columnar inputs (i.e. inputs of the shape `[batch_size, 1]`), but rather simple unidimensional vectors (i.e. inputs of shape `[batch_size]`):

```python
feature_name: tf.TensorSpec(
    shape=(None,),
    dtype=feature_spec.dtype,
    name=feature_name,
) for feature_name, feature_spec in feature_descriptions.items()
```

In the [model configuration](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#reshape) documentation this case is well explained. Following this example, I generate a configuration file of the form:

```
input [
{
    name: "input_name"
    data_type: TYPE_INT64
    dims: [ 1 ]
    reshape: { shape: [ ] }
}, ....
```

When I consume the model through sagemaker endpoint, I have generate the payload using the following format:

```
{
  'inputs': [
    {
      'name': 'input_name',
       'data': ['x', 'x', 'x'],
       'datatype': 'BYTES',
       'shape': [3, 1]
  },
```
 
While the prediction are correct and matches the values I get offline. I'm confused by the fact that the data field is provided as a simple list of shape `[batch_size]`, rather than matching input specification `[batch_size, 1]`. Moreover, this does not match the shape parameter as well. So, I'm wondering if I'm getting the right outputs by chance or I'm actually providing the correct format as input and the API is doing some magic for me.

**Triton Information**
aws provided image: `746233611703.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-tritonserver:22.05-py3-cpu`

**To Reproduce**
Model: simple linear regression build with tensorflow 2.8 
Inputs: ~100 inputs. All of them are integers value or string values (all string values are feed into [tf.keras.layers.Hashing](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Hashing) layer)

**Expected behaviour**

I expected to provided inputs in the form:
```
{
  'inputs': [
    {
      'name': 'input_name',
       'data': [['x'], ['x'], ['x']],
       'datatype': 'BYTES',
       'shape': [3, 1]
  },
```

**Comment by tanmayv25** [comment] 2022-11-04 23:28
AFAIK there should not be any issue in providing data [['x'], ['x'], ['x']] for shape [3, 1]. Actually it is more like a requirement for gRPC and HTTP Triton clients.

@GuanLuo  would you know why the sagemaker endpoint would complain when `'data': [['x'], ['x'], ['x']]`.

**Comment by GuanLuo** [comment] 2023-01-28 00:41
Sorry for missing the ping..

SageMaker endpoint reuse many utilities of the HTTP endpoint so the handling will have a lot in common. For the data representation, both the flat layout and nested layout (that matches the shape) are acceptable (see [protocol specification](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#tensor-data)). Given the image version and you are using `BYTES` data type, I think you hit the bug that is [fixed in later version](https://github.com/triton-inference-server/server/pull/4633), can you try a later version (> 22.08) and check if the issue is resolved?

**Comment by krishung5** [comment] 2023-02-23 22:23
Closing issue due to lack of activity. Please re-open the issue if you would like to follow up with this issue.

**Closed by krishung5** 2023-02-23 22:23 UTC
