### ISSUE TITLE
There is a bug when I set the initial_state

### ISSUE THREAD

**Issue by busishengui** [triton-inference-server/server#6023] opened 2023-07-05 02:22 UTC
**Description**
[libprotobuf ERROR /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format inference.ModelConfig: 24:20: Message type "inference.ModelSequenceBatching.State" has no field named "initial_state".

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:21.12-py3
Are you using the Triton container or did you build it yourself?
 Triton container
**To Reproduce**
Steps to reproduce the behavior.
I0705 02:19:10.998465 1 metrics.cc:298] Collecting metrics for GPU 0: NVIDIA GeForce GTX 1080 Ti
I0705 02:19:11.475796 1 libtorch.cc:1206] TRITONBACKEND_Initialize: pytorch
I0705 02:19:11.475827 1 libtorch.cc:1216] Triton TRITONBACKEND API version: 1.7
I0705 02:19:11.475841 1 libtorch.cc:1222] 'pytorch' TRITONBACKEND API version: 1.7
2023-07-05 02:19:11.880104: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0705 02:19:11.925878 1 tensorflow.cc:2170] TRITONBACKEND_Initialize: tensorflow
I0705 02:19:11.925923 1 tensorflow.cc:2180] Triton TRITONBACKEND API version: 1.7
I0705 02:19:11.925935 1 tensorflow.cc:2186] 'tensorflow' TRITONBACKEND API version: 1.7
I0705 02:19:11.925947 1 tensorflow.cc:2210] backend configuration:
{}
I0705 02:19:11.928109 1 onnxruntime.cc:2210] TRITONBACKEND_Initialize: onnxruntime
I0705 02:19:11.928125 1 onnxruntime.cc:2220] Triton TRITONBACKEND API version: 1.7
I0705 02:19:11.928133 1 onnxruntime.cc:2226] 'onnxruntime' TRITONBACKEND API version: 1.7
I0705 02:19:11.928137 1 onnxruntime.cc:2256] backend configuration:
{}
I0705 02:19:11.953422 1 openvino.cc:1193] TRITONBACKEND_Initialize: openvino
I0705 02:19:11.953439 1 openvino.cc:1203] Triton TRITONBACKEND API version: 1.7
I0705 02:19:11.953444 1 openvino.cc:1209] 'openvino' TRITONBACKEND API version: 1.7
I0705 02:19:12.231892 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f2378000000' with size 268435456
I0705 02:19:12.234343 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
[libprotobuf ERROR /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format inference.ModelConfig: 24:20: Message type "inference.ModelSequenceBatching.State" has no field named "initial_state".
[libprotobuf ERROR /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format inference.ModelConfig: 24:20: Message type "inference.ModelSequenceBatching.State" has no field named "initial_state".
E0705 02:19:12.245691 1 model_repository_manager.cc:1844] Poll failed for model directory 'encoder_model': failed to read text proto from /model_repository/encoder_model/config.pbtxt
I0705 02:19:12.249273 1 model_repository_manager.cc:994] loading: nnlm_model:1
I0705 02:19:12.349748 1 onnxruntime.cc:2291] TRITONBACKEND_ModelInitialize: nnlm_model (version 1)
I0705 02:19:12.349979 1 model_repository_manager.cc:994] loading: decoder_model:1
I0705 02:19:12.370416 1 onnxruntime.cc:2334] TRITONBACKEND_ModelInstanceInitialize: nnlm_model_0_0 (GPU device 0)
I0705 02:19:12.450748 1 model_repository_manager.cc:994] loading: additional_encoder_model:1
I0705 02:19:16.856816 1 onnxruntime.cc:2291] TRITONBACKEND_ModelInitialize: decoder_model (version 1)
I0705 02:19:16.857930 1 onnxruntime.cc:2291] TRITONBACKEND_ModelInitialize: additional_encoder_model (version 1)
I0705 02:19:16.862609 1 onnxruntime.cc:2334] TRITONBACKEND_ModelInstanceInitialize: nnlm_model_0_1 (GPU device 0)
I0705 02:19:17.681908 1 onnxruntime.cc:2334] TRITONBACKEND_ModelInstanceInitialize: decoder_model_0_0 (GPU device 0)
I0705 02:19:17.682242 1 model_repository_manager.cc:1149] successfully loaded 'nnlm_model' version 1
I0705 02:19:18.151967 1 onnxruntime.cc:2334] TRITONBACKEND_ModelInstanceInitialize: additional_encoder_model_0_0 (GPU device 0)
I0705 02:19:18.442790 1 onnxruntime.cc:2334] TRITONBACKEND_ModelInstanceInitialize: decoder_model_0_1 (GPU device 0)
I0705 02:19:18.798384 1 onnxruntime.cc:2334] TRITONBACKEND_ModelInstanceInitialize: additional_encoder_model_0_1 (GPU device 0)
I0705 02:19:18.798661 1 model_repository_manager.cc:1149] successfully loaded 'decoder_model' version 1
I0705 02:19:19.057040 1 model_repository_manager.cc:1149] successfully loaded 'additional_encoder_model' version 1
I0705 02:19:19.057288 1 server.cc:519] 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
name: "encoder_model"
platform: "onnxruntime_onnx"
max_batch_size:1000
instance_group [
    {
      count:2
      kind: KIND_GPU
    }
]
sequence_batching {
    max_sequence_idle_microseconds: 5000000
    oldest {
      max_candidate_sequences: 102400
      max_queue_delay_microseconds: 5000
    }
    control_input [
    ]
    state [
    {
      input_name: "offset"
      output_name:"r_offset"
      data_type: TYPE_INT64
      dims: [1]
      initial_state: {
       data_type: TYPE_INT64
       dims: [1]
       zero_data: true
       name: "initial state"
      }
    },
    {
      input_name: "subsampling_cache"
      output_name:"r_subsampling_cache"
      data_type: TYPE_FP32
      dims: [50, 512]
      initial_state: {
       data_type: TYPE_FP32
       dims: [ 50, 512 ]
       zero_data: true
       name: "initial state"
      }
    },
    {
      input_name: "elayers_output_cache"
      output_name:"r_elayers_output_cache"
      data_type: TYPE_FP32
      dims: [12, 50, 512]
      initial_state: {
       data_type: TYPE_FP32
       dims: [12, 50, 512 ]
       zero_data: true
       name: "initial state"
      }
    },
    {
      input_name: "conformer_cnn_cache"
      output_name:"r_conformer_cnn_cache"
      data_type: TYPE_FP32
      dims: [12, 512, 30]
      initial_state: {
       data_type: TYPE_FP32
       dims: [12, 512, 30 ]
       zero_data: true
       name: "initial state"
      }
    },
    {
      input_name: "cache_mask"
      output_name:"r_cache_mask"
      data_type: TYPE_FP32
      dims: [1,50]
      initial_state: {
       data_type: TYPE_FP32
       dims: [1, 50]
       zero_data: true
       name: "initial state"
      }
    }
  ]
}
input [
  {
    name: "inputs"
    data_type: TYPE_FP32
    dims: [36, 80 ]
  },
  {
    name: "chunk_lens"
    data_type: TYPE_INT64
    dims: [1]
  },
  {
    name: "required_cache_size"
    data_type: TYPE_INT64
    dims: [1]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, -1]
  },
  {
    name: "chunk_out_lens"
    data_type: TYPE_INT64
    dims: [1]
  }
]
**Expected behavior**

**Comment by nnshah1** [comment] 2023-07-05 20:08
The `initial_state` functionality is only available in triton server versions > 21.12

Can you try with the latest or a later version from 22.01 onwards?

`nvcr.io/nvidia/tritonserver:23.06-py3`

**Comment by nnshah1** [comment] 2023-07-10 20:18
Will close this - please reopen if the issue is still present in versions >= 22.01

**Closed by nnshah1** 2023-07-10 20:18 UTC
Labels: invalid
