### ISSUE TITLE
Tensorflow Object Detection Prediction

### ISSUE THREAD

**Issue by ManivannanMurugavel** [triton-inference-server/server#3528] opened 2021-11-03 04:42 UTC
**Triton Information**
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 21.09 (build 27443074)

I deployed my object detection model into triton server. I am using faster-rcnn-inceptionv2 architecture to build my model in tensorflow.

Question:
Can anyone please tell me how can I predict my object detection model using triton client or any other source.

I am refering this issue [#217](https://github.com/triton-inference-server/server/issues/217) and I used tritonserver python library but I am getting error mentioned below.

```
import tensorrtserver.api as triton
url = 'localhost:8000'
protocol = triton.ProtocolType.from_str('HTTP')
triton.InferContext(url, protocol, 'faster_rcnn_inception_v2')
```

ERROR:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/oph/env/tf_yolo/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 1128, in __init__
    streaming, verbose)))
  File "/home/ubuntu/oph/env/tf_yolo/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 259, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [ 0] status request did not return status

Please tell me the solution....

**Comment by dyastremsky** [comment] 2021-11-03 18:09
Is the server running? Are you able to access it at localhost:8000 from wherever you are running your Python script? It looks like the status wasn't returned, so you may want to make sure your client and server are able to communicate.

**Comment by ManivannanMurugavel** [comment] 2021-11-05 09:07
Hi @dyastremsky ,

Ya, the triton server is running and I verifed the server using below command

```
$ curl -v localhost:8000/v2/health/ready
...
< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: text/plain

```


Also I tried the ```tensorrtserver.api``` in triton client docker but I am getting same error.

When I tried the image_client for my own classification model, it's worked and I am getting correct output.
image_client -m my_classification_model -s INCEPTION images/table-image.jpg
Request 0, batch size 1
Image 'qa/images/mug.jpg':
    0.854200 (1) = TABLE

Please suggest me to how can I get the output for my Object Detection Model..

Thanks,

**Comment by dyastremsky** [comment] 2021-11-05 18:22
Thank you for verifying. Did you perform the curl from within the client container?

Can you provide the commands used and output received for running your server, client, and model? Similar to a bug report. That will help with understanding what's going on.

**Comment by ManivannanMurugavel** [comment] 2021-11-06 06:27
Hi @dyastremsky 

Yes, I tried in client container and the logs below.

```
root@ip-172-31-25-233:/workspace# curl -v localhost:8000/v2/health/ready
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/health/ready HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```


This is my docker images:
```
ubuntu@ip-172-31-25-233:~/triton-server-installation$ sudo docker images
REPOSITORY                    TAG             IMAGE ID       CREATED       SIZE
nvcr.io/nvidia/tritonserver   21.09-py3       63e21e0cb5df   6 weeks ago   13.6GB
nvcr.io/nvidia/tritonserver   21.09-py3-sdk   031587eaf930   6 weeks ago   11.4GB
```
Triton server running docker cmd:
```
docker run -itd --gpus=1 -p8000:8000 -p8001:8001 -p8002:8002 -v /home/ubuntu/triton-server-installation/model_repository:/models --name triton-docker-server 63e21e0cb5df tritonserver --model-repository=/models
```

Triton server logs:
```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 21.09 (build 27443074)

Copyright (c) 2018-2021, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

ERROR: This container was built for NVIDIA Driver Release 470.57 or later, but
       version 460.27.04 was detected and compatibility mode is UNAVAILABLE.

       [[]]

I1106 06:20:07.989859 1 metrics.cc:290] Collecting metrics for GPU 0: Tesla T4
I1106 06:20:09.734042 1 libtorch.cc:1030] TRITONBACKEND_Initialize: pytorch
I1106 06:20:09.734072 1 libtorch.cc:1040] Triton TRITONBACKEND API version: 1.5
I1106 06:20:09.734084 1 libtorch.cc:1046] 'pytorch' TRITONBACKEND API version: 1.5
2021-11-06 06:20:10.332239: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I1106 06:20:10.895100 1 tensorflow.cc:2170] TRITONBACKEND_Initialize: tensorflow
I1106 06:20:10.895134 1 tensorflow.cc:2180] Triton TRITONBACKEND API version: 1.5
I1106 06:20:10.896474 1 tensorflow.cc:2186] 'tensorflow' TRITONBACKEND API version: 1.5
I1106 06:20:10.896493 1 tensorflow.cc:2210] backend configuration:
{}
I1106 06:20:10.975671 1 onnxruntime.cc:1997] TRITONBACKEND_Initialize: onnxruntime
I1106 06:20:10.975695 1 onnxruntime.cc:2007] Triton TRITONBACKEND API version: 1.5
I1106 06:20:10.977080 1 onnxruntime.cc:2013] 'onnxruntime' TRITONBACKEND API version: 1.5
I1106 06:20:11.190711 1 openvino.cc:1193] TRITONBACKEND_Initialize: openvino
I1106 06:20:11.190735 1 openvino.cc:1203] Triton TRITONBACKEND API version: 1.5
I1106 06:20:11.190744 1 openvino.cc:1209] 'openvino' TRITONBACKEND API version: 1.5
I1106 06:20:11.442485 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f3a64000000' with size 268435456
I1106 06:20:11.444304 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I1106 06:20:11.463134 1 model_repository_manager.cc:1022] loading: faster_rcnn_inception_v2:1
I1106 06:20:11.563329 1 model_repository_manager.cc:1022] loading: densenet_onnx:1
I1106 06:20:11.565790 1 tensorflow.cc:2270] TRITONBACKEND_ModelInitialize: faster_rcnn_inception_v2 (version 1)
I1106 06:20:11.577665 1 tensorflow.cc:2319] TRITONBACKEND_ModelInstanceInitialize: faster_rcnn_inception_v2_0 (GPU device 0)
2021-11-06 06:20:11.589882: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-11-06 06:20:11.590069: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:11.590638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:1e.0
2021-11-06 06:20:11.590673: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-11-06 06:20:11.590725: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-11-06 06:20:11.590755: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-11-06 06:20:11.590784: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-11-06 06:20:11.590824: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2021-11-06 06:20:11.590853: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-11-06 06:20:11.590885: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-11-06 06:20:11.591016: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:11.591626: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:11.592147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0
I1106 06:20:11.663509 1 model_repository_manager.cc:1022] loading: inception_graphdef:1
2021-11-06 06:20:23.993558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-06 06:20:23.993605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0 
2021-11-06 06:20:23.993621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N 
2021-11-06 06:20:23.993843: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:23.994518: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:23.995162: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:23.995760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13187 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5)
2021-11-06 06:20:24.045284: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f39b8000860 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-11-06 06:20:24.045317: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2021-11-06 06:20:24.085437: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2021-11-06 06:20:24.085773: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f399c73a4c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-11-06 06:20:24.085802: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
I1106 06:20:24.703826 1 onnxruntime.cc:2056] TRITONBACKEND_ModelInitialize: densenet_onnx (version 1)
I1106 06:20:24.705637 1 tensorflow.cc:2270] TRITONBACKEND_ModelInitialize: inception_graphdef (version 1)
I1106 06:20:24.705822 1 model_repository_manager.cc:1183] successfully loaded 'faster_rcnn_inception_v2' version 1
I1106 06:20:24.707486 1 onnxruntime.cc:2099] TRITONBACKEND_ModelInstanceInitialize: densenet_onnx (GPU device 0)
I1106 06:20:31.479864 1 tensorflow.cc:2319] TRITONBACKEND_ModelInstanceInitialize: inception_graphdef (GPU device 0)
I1106 06:20:31.480058 1 model_repository_manager.cc:1183] successfully loaded 'densenet_onnx' version 1
2021-11-06 06:20:31.480350: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:31.480893: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:1e.0
2021-11-06 06:20:31.480930: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-11-06 06:20:31.480954: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-11-06 06:20:31.480973: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-11-06 06:20:31.481008: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-11-06 06:20:31.481036: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2021-11-06 06:20:31.481053: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-11-06 06:20:31.481070: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-11-06 06:20:31.481191: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:31.481796: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:31.482296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0
2021-11-06 06:20:31.482324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-06 06:20:31.482339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0 
2021-11-06 06:20:31.482352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N 
2021-11-06 06:20:31.482486: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:31.483057: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-06 06:20:31.483558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13187 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5)
I1106 06:20:32.118168 1 model_repository_manager.cc:1183] successfully loaded 'inception_graphdef' version 1
I1106 06:20:32.118275 1 server.cc:519] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1106 06:20:32.118348 1 server.cc:546] 
+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
+-------------+-----------------------------------------------------------------+--------+

I1106 06:20:32.118487 1 server.cc:589] 
+--------------------------+---------+--------+
| Model                    | Version | Status |
+--------------------------+---------+--------+
| densenet_onnx            | 1       | READY  |
| faster_rcnn_inception_v2 | 1       | READY  |
| inception_graphdef       | 1       | READY  |
+--------------------------+---------+--------+

I1106 06:20:32.118620 1 tritonserver.cc:1836] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                 |
| server_version                   | 2.14.0                                                                                                                                                                                 |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /models                                                                                                                                                                                |
| model_control_mode               | MODE_NONE                                                                                                                                                                              |
| strict_model_config              | 1                                                                                                                                                                                      |
| rate_limit                       | OFF                                                                                                                                                                                    |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                              |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                               |
| min_supported_compute_capability | 6.0                                                                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1106 06:20:32.138827 1 grpc_server.cc:4111] Started GRPCInferenceService at 0.0.0.0:8001
I1106 06:20:32.141283 1 http_server.cc:2803] Started HTTPService at 0.0.0.0:8000
I1106 06:20:32.183520 1 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002
```

Triton client cmd:
```
sudo docker run -it --rm --net=host 031587eaf930
```

Tree structure of models:
```
model_repository
├── densenet_onnx
│   ├── 1
│   │   └── model.onnx
│   ├── config.pbtxt
│   └── densenet_labels.txt
├── faster_rcnn_inception_v2
│   ├── 1
│   │   └── model.graphdef
│   ├── config.pbtxt
│   └── labels.txt
└── inception_graphdef
    ├── 1
    │   └── model.graphdef
    ├── config.pbtxt
    └── inception_labels.txt
```

The above command only I used to run the triton. My problem is when I run the image_client command it's worked but I don't know what is the command to use to run the object detection model.


Thanks,

**Comment by ManivannanMurugavel** [comment] 2021-11-12 03:43
Any advise @dyastremsky

**Comment by dyastremsky** [comment] 2021-11-12 19:46
Thanks for following up. I filed a ticket for us to investigate further. If you are able to provide the model (or another model that returns this error), that'd help for reproducing the error.

**Comment by ManivannanMurugavel** [comment] 2021-11-13 05:58
Hi @dyastremsky 

I don't have any model, because i have only one model which is my custom model. Can you tell me any other way to solve this error.

Thanks,

**Comment by dyastremsky** [comment] 2021-11-15 18:38
We'll look into it and update you. Being unable to reproduce the error will make it less likely that it gets resolved. You're also welcome to submit a simpler model that returns the same error.

**Comment by dyastremsky** [comment] 2021-11-30 22:39
Hi @ManivannanMurugavel. I'm going to have to close this, as we need reproduction steps. If you can create a way to replicate the error (e.g. steps with a sample model), feel free to file a bug report or reopen the ticket.

**Closed by dyastremsky** 2021-11-30 22:39 UTC
Labels: bug, question
