### ISSUE TITLE
Cannot warmup with python backend with batch_size

### ISSUE THREAD

**Issue by kimdwkimdw** [triton-inference-server/server#4412] opened 2022-05-20 08:48 UTC
**Description**

For example config in below.

```
name: "postprocess"
backend: "python"
max_batch_size: 0
input [
{
    name: "postprocess_in"
    data_type: TYPE_FP32
    dims: [ -1, 581, 2 ]
}
]

output [
{
    name: "postprocess_out"
    data_type: TYPE_FP32
    dims: [ -1 ]
}
]

instance_group [{ kind: KIND_CPU, count: 2 }]

# warmup 2 requests
model_warmup {
  name: "RandomSampleInput"
  batch_size: 256
  inputs [{
      key: "postprocess_in"
      value: {
        data_type: TYPE_FP32
        dims: [1, 581, 2 ]
        random_data: true
      }
   }]
}
```

Input's first dim is different with output's first dim.
However I tried to warmup multiple times with batch_size. 
There is no way to duplicate warmup request.

Error messages

```
E0520 12:38:18.786236 1 triton_model_instance.cc:86] warmup error: Internal - batch size 256 for 'postprocess', max allowed is 0
E0520 12:38:18.786243 1 triton_model_instance.cc:86] warmup error: Internal - batch size 256 for 'postprocess', max allowed is 0
E0520 12:38:18.786250 1 triton_model_instance.cc:86] warmup error: Internal - batch size 256 for 'postprocess', max allowed is 0
E0520 12:38:18.786257 1 triton_model_instance.cc:86] warmup error: Internal - batch size 256 for 'postprocess', max allowed is 0
E0520 12:38:18.786264 1 triton_model_instance.cc:86] warmup error: Internal - batch size 256 for 'postprocess', max allowed is 0
E0520 12:38:18.786274 1 triton_model_instance.cc:86] warmup error: Internal - batch size 256 for 'postprocess', max allowed is 0
```

**Triton Information**

22.01 ~ 22.04

**To Reproduce**

Load model with warmup. `max_batch_size` in model, `batch_size` in model_warmup

**Expected behavior**

Model should accept dynamic shape input.

**Comment by krishung5** [comment] 2022-05-20 17:10
Hi @kimdwkimdw, based on the error messages you provided, it looks like the batch_size for warmup is larger than the max_batch_size being set for the model. Could you try with a different batch_size which doesn't exceed max_batch_size?

@tanmayv25 Could you confirm this?

**Comment by tanmayv25** [comment] 2022-05-21 00:57
@kimdwkimdw  Take a look [here](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#inputs-and-outputs) on how to specify input/output config for a batching model.
We need to skip the batch dimension in i/o config for batching models.

Second, to specify a batching model, the max_batch_size in config.pbtxt should be set > 0. However, you set max_batch_size=0 and then try to warmup using batch_size=256 hence you are seeing this error. See here for more information about [max_batch_size](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#maximum-batch-size) field. 

Looking at what you want, the following should work:

```
name: "postprocess"
backend: "python"
max_batch_size: 256
input [
{
    name: "postprocess_in"
    data_type: TYPE_FP32
    dims: [ 581, 2 ]
}
]

output [
{
    name: "postprocess_out"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
}
]

instance_group [{ kind: KIND_CPU, count: 2 }]

# warmup 2 requests
model_warmup {
  name: "RandomSampleInput"
  batch_size: 256
  inputs [{
      key: "postprocess_in"
      value: {
        data_type: TYPE_FP32
        dims: [ 581, 2 ]
        random_data: true
      }
   }]
}
```

The warmup will run the request with `postprocess_in` as `[256, 581, 2]`.

**Comment by kimdwkimdw** [comment] 2022-05-21 02:31
## How to send [256,581,2] x 256 requests?

@tanmayv25 
> The warmup will run the request with postprocess_in as [256, 581, 2].

https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1657-L1660

really weird part is request is not with [256, 581, 2]. 
This will generate small batchsize request [1, 581, 2] with 256 times.

```
I0521 02:19:52.181746 1 triton_model_instance.cc:668] Starting backend thread for postprocess_0_1 at nice 0 on device 0...
I0521 02:19:52.181793 1 triton_model_instance.cc:532] model 'postprocess' instance postprocess_0_1 is running warmup sample 'RandomSampleInput'
I0521 02:19:52.182015 1 python.cc:616] model postprocess, instance postprocess_0_1, executing 256 requests
```





## Different size of shape in first dim between input and output of python backend.

In my case, I wrote the shape config like below because this is python backend. Input of dynamic shape is range between 1~256, but Output of dynamic shape is range between (batch_size * 2 - 5), it is kind of business logic.

```
max_batch_size: 0
input [
{
    name: "postprocess_in"
    data_type: TYPE_FP32
    dims: [ -1, 581, 2 ]
}
]

output [
{
    name: "postprocess_out"
    data_type: TYPE_FP32
    dims: [ -1 ]
}
```


When I wrote your suggestion, 

```
max_batch_size: 256
input [
{
    name: "postprocess_in"
    data_type: TYPE_FP32
    dims: [ 581, 2 ]
}
]

output [
{
    name: "postprocess_out"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
}
]
```

When output's dims is not same order with input, is it ok to use `max_batch_size` ?

**Comment by tanmayv25** [comment] 2022-05-23 22:13
> When output's dims is not same order with input, is it ok to use max_batch_size ?

This might be a problem in other backends(TF, pyTorch, TensorRT etc.) where the backend itself tries to scatter the output tensors into individual responses. But for python backend, I think your BLS would be creating responses for each request I guess. 
Actually, it looks like you are not interested in Triton's Dynamic Batcher. So, you want a single inference request and not a batch of 256 inference requests.

If that is the case, then I would suggest the following:

```
max_batch_size: 0
input [
{
    name: "postprocess_in"
    data_type: TYPE_FP32
    dims: [ -1, 581, 2 ]
}
]

output [
{
    name: "postprocess_out"
    data_type: TYPE_FP32
    dims: [ -1 ]
}

instance_group [{ kind: KIND_CPU, count: 2 }]

# warmup 2 requests
model_warmup {
  name: "RandomSampleInput"
  batch_size: 1
  inputs [{
      key: "postprocess_in"
      value: {
        data_type: TYPE_FP32
        dims: [ 256, 581, 2 ]
        random_data: true
      }
   }]
}

```

The above config tells Triton that the model is non-batching and Triton's dynamic batching should not be used. Because the model is non batching with respect to Triton, you can not specify `batch_size` > 1 for warmup. This is documented here: https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1653-L1660

> really weird part is request is not with [256, 581, 2].
> This will generate small batchsize request [1, 581, 2] with 256 times.

This is not weird. It is by design and how dynamic batching works in Triton. The `batch_size` is the number of requests send to a single ModelExecute as a batch.

**Comment by Tabrizian** [comment] 2022-05-24 15:34
> really weird part is request is not with [256, 581, 2].
This will generate small batchsize request [1, 581, 2] with 256 times.

Python backend doesn't batch multiple requests to the same request. If Triton's dynamic batcher, batches multiple requests, the length of the `requests` list will reflect the size of the batch created by Triton. Having said that, there is a ticket for this enhancement: https://github.com/triton-inference-server/server/issues/3286

**Comment by kimdwkimdw** [comment] 2022-05-24 15:54
> But for python backend, I think your BLS would be creating responses for each request I guess.

I had misunderstood about python backend. Thanks for giving an example.
However, there is still no way to do `warmup 2 times`. 


With `max_batch_size = 0` , I cannot specify `batch_size: 2` on model_warmup. 
Or, I thought that `inputs` can accept multiple inputs like below, but it's not.

```
model_warmup {
  name: "RandomSampleInput"
  batch_size: 1
  inputs [{
      key: "postprocess_in"
      value: {
        data_type: TYPE_FP32
        dims: [ 256, 581, 2 ]
        random_data: true
      }
   },{
      key: "postprocess_in"
      value: {
        data_type: TYPE_FP32
        dims: [ 256, 581, 2 ]
        random_data: true
      }
   }]
}
```

**Comment by tanmayv25** [comment] 2022-06-01 23:17
> With max_batch_size = 0 , I cannot specify batch_size: 2 on model_warmup.

That is by design. For `max_batch_size = 0` you cannot have batch_size anything other than 1. Even during inference Triton core will ensure that the backends are delivered exactly one request at a time. 
See here for more documentation: https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1653-L1660

**Comment by tanmayv25** [comment] 2022-06-01 23:24
model_warmup is a repeated field. If you want to run multiple requests in warmup, just replicate them in your model config.

https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1927-L1935

@GuanLuo  Will it make sense to add a repeat_count field in model_warmup? The sample will be repeated for that many times before going to the next execution.
I believe the @kimdwkimdw  here is getting confused between batch_size and repeat_count functionality I described.

**Comment by GuanLuo** [comment] 2022-06-15 00:19
Please take a look at https://github.com/triton-inference-server/server/pull/4501 for usage of the new "count" field

**Comment by Tabrizian** [comment] 2022-07-08 19:02
Closing due to in-activity.

**Closed by Tabrizian** 2022-07-08 19:02 UTC
