### ISSUE TITLE
Not able to run custom PyTorch model using Triton Inference Server & Seldon Core

### ISSUE THREAD

**Issue by altruistcoder** [triton-inference-server/server#2637] opened 2021-03-17 20:26 UTC
Hey, 

I am trying to deploy a ML model trained on **CIFAR10** dataset using **PyTorch** as a Rest API on my Openshift cluster using **Seldon** Operator provided in the OperatorHub of my cluster which itself is using the **Triton Inference Server** at the bottom, but I am facing some errors when trying to deploy it.

I have **attached the output of the logs of my Pod** which shows the error which I am facing.

First, I tried to deploy a sample Pytorch model using a sample Seldon Deployment Definition file provided by Seldon in this [triton examples notebook](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/triton_examples.ipynb) and it worked fine and I was able to take predictions from the deployed model successfully.

The Seldon Definition File used in this sample is as follows:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: cifar10
  namespace: seldon
spec:
  annotations:
    seldon.io/engine-seldon-log-messages-externally: "true"
  name: resnet32
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: gs://seldon-models/triton/pytorch_cifar10
      serviceAccountName: s3-sa
      name: cifar10
      type: MODEL
    name: default
    replicas: 1
  protocol: kfserving
```

This sample definition is referring to an already trained model on CIFAR10 dataset which is stored in the google bucket and accessible publicly.

But, in my case I have trained my own model on the CIFAR10 dataset only and stored the trained model in my `Rook-Ceph bucket` which is an **S3-compatible storage solution** in my Openshift cluster. Hence, the only difference in the above definition file comes that instead of writing value of ***modelUri*** as `gs://seldon-models/triton/pytorch_cifar10`, I am writing the value of ***modelUri*** as `s3://<bucket_name_here>/pytorch_cifar10`. And, this is causing the above issue to happen.

The model repository structure for my model (stored in my S3 bucket) is as follows:

![image](https://user-images.githubusercontent.com/31319270/111533162-7dc27800-878c-11eb-8935-08dbc7a7c614.png)

The contents of the *config.pbtxt file* are present below for reference:
```
name: "cifar10"
platform: "pytorch_libtorch"
max_batch_size: 8
input [
    {
      name: "input__0"
      data_type: TYPE_FP32
      dims: [ 3, 32, 32 ]
    }
]
output [
 {
   name: "output__0"
   data_type: TYPE_FP32
   dims: [ 10 ]
 }
]
```

I confirmed that I am using the right model repository structure from the information given by Triton [here](https://github.com/triton-inference-server/server/blob/r21.02/docs/model_repository.md)
But, I am not able to find the reason why my model is not getting deployed when the only difference is in the location where the model is stored.

Can anyone please help me in resolving this issue as I am not able to proceed in my task and stuck on this from quite some time now?

[cifar10_pod_logs.txt](https://github.com/triton-inference-server/server/files/6159458/cifar10_pod_logs.txt)

**Comment by CoderHam** [comment] 2021-03-18 04:24
Have you tried to run the model outside Tritonserver i.e. directly via the PyTorch API? The error from the log indicates that the model might not be a valid torchscript model. 
Did you use tracing or scripting to produce the model?

**Comment by altruistcoder** [comment] 2021-03-18 05:51
Hey @CoderHam,

Thanks for responding. Actually, I followed the code present in this [blog](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html) for training my model and while saving it I gave the name of the model as **mode.pt** as follows:

```
PATH = './model.pt'
torch.save(net.state_dict(), PATH)
```

**Comment by CoderHam** [comment] 2021-03-18 17:44
Ah there is the problem. Like I mentioned, the PyTorch backend requires a [TorchScript](https://pytorch.org/docs/stable/jit.html) model. Please use either scripting or tracing to convert your model to a TorchScript model.

**Comment by altruistcoder** [comment] 2021-03-19 17:18
Hello @CoderHam, 

I tried converting my model using the ***tracing*** method following the instructions described in this [documentation](https://pytorch.org/tutorials/advanced/cpp_export.html#converting-to-torch-script-via-tracing) but now I am facing a new error.
I have attached a file containing the new logs of the pod below:

[cifar10_pod_new_logs.txt](https://github.com/triton-inference-server/server/files/6172985/cifar10_pod_new_logs.txt)

Is there still the problem in converting the model properly into a TorchScript model or there is something else which is causing the error?

**Comment by CoderHam** [comment] 2021-03-19 17:26
@altruistcoder This looks like a forward-compatibility issue, i.e. the version of PyTorch you use to save your model is newer than the libtorch version from the corresponding Triton container. Can you check if this works if these versions match?
Have a look at: https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

**Comment by altruistcoder** [comment] 2021-03-19 18:01
@CoderHam, thanks a lot for responding so quickly, Can you please tell me how can I check the version of libtorch as the container doesn't come into the running state so I cannot access its terminal.

**Comment by CoderHam** [comment] 2021-03-19 18:04
You should use the corresponding NGC Pytorch container to create the TorchScript model. If you are using NGC Triton 21.02, you should use NGC Pytorch 21.02

**Comment by altruistcoder** [comment] 2021-03-24 21:09
Hello @CoderHam,

Actually, this issue isn't solved yet and I am having a little trouble in understanding the last point you mentioned (maybe because of my limited knowledge). I am not able to understand how can I use NGC Triton 21.02 and NGC PyTorch container to create the TorchScript model. 

I am currently using the [Prepackaged Triton Inference Server](https://docs.seldon.io/projects/seldon-core/en/latest/servers/triton.html) provided by Seldon. The image which it is using is `nvcr.io/nvidia/tritonserver:20.08-py3`

Can you please tell me whether it is the right image to be used? or  if not then what is the right image to used for the Inference Server?

**Comment by CoderHam** [comment] 2021-03-24 21:22
@altruistcoder The 20.08 Triton release is quite old. Not sure why Seldon still uses that old release. 
Nonetheless if you are using the `nvcr.io/nvidia/tritonserver:20.08-py3` container you should be using the `nvcr.io/nvidia/pytorch:20.08-py3` release to produce the corresponding Pytorch model. You can find the container [here](https://ngc.nvidia.com/catalog/containers/nvidia:pytorch/tags).  
You can find more about tracing a pytorch model [here](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html).

I am keeping this ticket open for now but the issue is likely not in Triton but the version of Pytorch being used.

**Comment by deadeyegoodwin** [comment] 2021-03-31 16:35
Closing. Reopen with additional information if issue is not resolved.

**Closed by deadeyegoodwin** 2021-03-31 16:35 UTC
